### ISSUE TITLE
如何模拟鼠标滚动向下拉取加载数据？

### ISSUE THREAD

**Issue by Zyn0423** [go-rod/rod#1004]
page.Mouse.MustScroll(0, 0)  尝试了该方法并没有下拉，文档也没有详细介绍
是否有其他的方法能做到该功能？

**Comment by ysmood** [comment]
`page.Mouse.MustScroll(0, 10000)`

**Comment by Zyn0423** [comment]
> `page.Mouse.MustScroll(0, 10000)`


![binance](https://github.com/go-rod/rod/assets/39515741/3759e153-ed0e-4838-ac32-ed2ad8598fa7)

使用该方法还是拿不到滚动后加载新标签的数据，只能获取到前20条 你遇到该问题吗？

**Comment by ysmood** [comment]
没有，这一般都是因为你没有反向工程页面的加载机制导致的，每个网站都不同，我觉得这不是 rod 的问题，除非你能给出最小复现代码，我再 reopen 这个 issue

**Comment by Zyn0423** [comment]
> 没有，这一般都是因为你没有反向工程页面的加载机制导致的，每个网站都不同，我觉得这不是 rod 的问题，除非你能给出最小复现代码，我再 reopen 这个 issue

`func Test_main(t *testing.T) {
	url := "ws://0.0.0.0:9222/devtools/page/00077C805CB673FB8C1977615B61E664"
	page := rod.New().ControlURL(url).MustConnect().MustPage("https://www.binance.com/zh-CN/feed/profile/binance_news")
	page.MustWaitLoad()
	for i := 0; i < 1; i++ {
		wholeDataDiv := page.MustElement("#__APP > div.style_NewLayoutV2__BKM9c > div.feed-layout-main > div > div.css-1l0uqdm > div")
		childDivElements := wholeDataDiv.MustElements("div > *")
		dataMap := make(map[string]string)
		for _, el := range childDivElements {
			subChildElements := el.MustElements("div > div > div.card-content-box > div.card__bd.trading-pairs-first")
			for _, subEl := range subChildElements {
				subTextContent1 := subEl.MustElement("div > div.card__title.css-1iqe90x > h3").MustText()
				subTextContent2 := subEl.MustElement("div > div.rich-text-wrap.card__description_line-clamp.has-title > div").MustText()
				strWithoutNewlines := strings.ReplaceAll(subTextContent2, "\n", "")
				if dataMap[subTextContent1] == strWithoutNewlines {
					continue
				} else {
					dataMap[subTextContent1] = strWithoutNewlines
				}
			}
		}
		var count = 0
		for s, s2 := range dataMap {
			count++
			fmt.Printf("\n%d: ● %s\n\n", count, s)
			fmt.Printf("%s\n", s2)
		}

	}

}` 

> 这是本地测试代码，麻烦你看一下谢谢了

**Comment by Zyn0423** [comment]
`package test

import (
	"fmt"
	"github.com/go-rod/rod"
	"strings"
	"testing"
)

func Test_6main(t *testing.T) {
	url := "ws://0.0.0.0:9222/devtools/page/00077C805CB673FB8C1977615B61E664"
	page := rod.New().ControlURL(url).MustConnect().MustPage("https://www.binance.com/zh-CN/feed/profile/binance_news")
	page.MustWaitLoad()
	for i := 0; i < 1; i++ {
		wholeDataDiv := page.MustElement("#__APP > div.style_NewLayoutV2__BKM9c > div.feed-layout-main > div > div.css-1l0uqdm > div")
		childDivElements := wholeDataDiv.MustElements("div > *")
		dataMap := make(map[string]string)
		for _, el := range childDivElements {
			subChildElements := el.MustElements("div > div > div.card-content-box > div.card__bd.trading-pairs-first")
			for _, subEl := range subChildElements {
				subTextContent1 := subEl.MustElement("div > div.card__title.css-1iqe90x > h3").MustText()
				subTextContent2 := subEl.MustElement("div > div.rich-text-wrap.card__description_line-clamp.has-title > div").MustText()
				strWithoutNewlines := strings.ReplaceAll(subTextContent2, "\n", "")
				if dataMap[subTextContent1] == strWithoutNewlines {
					continue
				} else {
					dataMap[subTextContent1] = strWithoutNewlines
				}
			}
		}
		var count = 0
		for s, s2 := range dataMap {
			count++
			fmt.Printf("\n%d: ● %s\n\n", count, s)
			fmt.Printf("%s\n", s2)
		}
	}
}`

**Comment by ysmood** [comment]
你这个没有 scroll， scroll 完了也没有给页面加载的时间

**Comment by Zyn0423** [comment]
> 你这个没有 scroll， scroll 完了也没有给页面加载的时间

> 这是没加的，加过 比如 page.Mouse.MustScroll(0, 10000) 效果和没加是一样的

**Comment by Zyn0423** [comment]
> > 你这个没有 scroll， scroll 完了也没有给页面加载的时间
> 
> > 这是没加的，加过 比如 page.Mouse.MustScroll(0, 10000) 效果和没加是一样的

> 	假设我现在这样设置结果还是一样
page := rod.New().ControlURL(url).MustConnect().MustPage("https://www.binance.com/zh-CN/feed/profile/binance_news")
	page.MustWaitLoad()
	page.Mouse.MustScroll(0, 10000) 
	page.MustWaitLoad()
运行结果只能获取20条div 标签 ，并没有增加

**Comment by ysmood** [comment]
看看文档，你这个等待用法不对
