### ISSUE TITLE
Is it possible to improve Screenshot's fullPage implementation?

### ISSUE THREAD

**Issue by zbysir** [go-rod/rod#1008]
Rod Version: v0.114.6

## What you got

I saw that the implementation of fullpage is to set the viewpoint to a very large size and then take a screenshot, but in fact this may lead to one problem: if some elements in the page use a unit like 1vh as the height, if the height of the viewpoint is set to a very large size In this case, the final screenshot will result in only this one element in the entire page. For example, https://www.lixiang.com/about.html this website.

```go
if fullPage {
		metrics, err := proto.PageGetLayoutMetrics{}.Call(p)
		if err != nil {
			return nil, err
		}

		if metrics.CSSContentSize == nil {
			return nil, errors.New("failed to get css content size")
		}

		oldView := proto.EmulationSetDeviceMetricsOverride{}
		set := p.LoadState(&oldView)
		view := oldView
		view.Width = int(metrics.CSSContentSize.Width)
		view.Height = int(metrics.CSSContentSize.Height)

		err = p.SetViewport(&view)
		if err != nil {
			return nil, err
		}

		defer func() { // try to recover the viewport
			if !set {
				_ = proto.EmulationClearDeviceMetricsOverride{}.Call(p)
				return
			}

			_ = p.SetViewport(&oldView)
		}()
	}
```

## What you expect to see

Maybe it would be better to use circular scrolling to achieve full-screen screenshots, but this code is too difficult for me to implement. Have you considered improving this logic?

**Comment by ysmood** [comment]
Yes, hope someone can help to make a PR to support scroll screenshot.
