### ISSUE TITLE
中文系统 launcher.NewUserMode().Launch() 会报错

### ISSUE THREAD

**Issue by 914795561** [go-rod/rod#101]
url := launcher.NewUserMode().Launch()

	browser := rod.New().ControlURL(url).Connect()

	browser.Page("https://github.com")

	fmt.Println("done")

报错：
     panic: [launcher] Failed to get the debug url: 正在现有的浏览器会话中打开。

goroutine 1 [running]:
github.com/ysmood/kit/pkg/utils.E(0xc000020fc0, 0x1, 0x1, 0x1c979e0, 0xc000020fb0, 0x100e6c8)
        /Users/xuyang/Documents/project/go/pkg/mod/github.com/ysmood/kit@v0.24.4/pkg/utils/utils.go:33 +0xab
github.com/go-rod/rod/lib/launcher.(*Launcher).Launch(0xc0003260c0, 0xc0003260c0, 0xc0002da120)
        /Users/xuyang/Documents/project/go_github/rod/lib/launcher/launcher.go:230 +0xb1
main.main()
        /Users/xuyang/Documents/project/go_github/rod/lib/examples/compare-chromedp/test/wx.go:28 +0x17e

**Comment by NormalPunch** [comment]
因为没有指定 user data dir，被占用状态无法创建

```go
    url := launcher.NewUserMode().UserDataDir("./chrome-temp").Launch()
```

**Comment by NormalPunch** [comment]
@ysmood  Do we need to pass a default flag to prevent welcome page of `NewUserMode` ?

**Comment by ysmood** [comment]
我稍微解释下，NewUserMode 的说明其实已经很透彻了，只是由于用法比较新颖导致有误解，尤其是对于使用过 puppeteer 和 chromedp 的人。

相比于 `launcher.New`，`launcher.NewUserMode` 是用来启动用户本地的 chrome 并使用本地的用户数据。比如你平时用 chrome 看网页登陆了很多网站，想用 rod 来自动化这些网站，一个个登陆不会很麻烦吗，用它就直接使用你现存的用户数据了，无需再登陆了，rod 用起来就像浏览器插件了，只是更强大。

对于这个人的问题，其实解决方法很简单，就是把已经启动的 chrome 全部关掉就好了，注意是全部，这是 chrome 自身的限制，它只能是单例的。

**Comment by ysmood** [comment]
不过这也是个bug，我其实本来是有友好提示关闭其他 chrome 的，但是我判定的依据是英文的 “Opening in existing browser session”，然而这个朋友的报错信息竟然是中文的，所以才有这个疑惑，我去修正下对多国语言的支持。

**Comment by ysmood** [comment]
另外要注意的是，只需要用 rod 启动一次就够了，只要是 rod 启动的，不关闭也可以再次让 rod 连上。

**Comment by 914795561** [comment]
请问可以像油猴那样在浏览器中使用吗

**Comment by ysmood** [comment]
是的，比油猴子更好用

**Comment by 914795561** [comment]
油猴可以直接嵌入到浏览器中使用，您这个貌似不行

**Comment by ysmood** [comment]
不是很理解你要干什么，显然golang不可在在浏览器运行，这是常识，我以为你知道，所以你会理解我说的是可以用rod 办到油猴子能实现的所有功能而不需要安装任何插件

**Comment by ysmood** [comment]
推荐你看看这个：[如何获得更好的回答](https://github.com/aptx4869yuyang2017/How-To-Ask-Questions-The-Smart-Way)

> 清楚明确的表达你的问题以及需求

不好的问法：rod 能向油猴子一样在浏览器里用吗？
好的问法：我想自动在某某网站里点击下一页，我用油猴子能能搬到，rod 也可以吗？
