### ISSUE TITLE
Why doesn't it remember the window size now?

### ISSUE THREAD

**Issue by moxcomic** [go-rod/rod#1011]
Rod Version: v0.114.7
---

I remember that in previous versions, when using the same code, if you manually dragged the window to change its size, the size would be maintained the next time you started it. But now it seems to revert to a fixed size. Is it necessary now to use MustSetWindow to maintain the window size?

## Code
```
rod.
  New().
  ControlURL(
      launcher.New().
      Headless(false).
      Bin("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome").
      UserDataDir("./data").
      MustLaunch(),
  ).
  MustConnect().
  NoDefaultDevice().
  MustPage("")
```

**Comment by ysmood** [comment]
I haven't changed any related logic. I think every time you launch the browser, you will open a new tab, because different tabs can have the same url, how could you know it's the same one as the last launch?

**Comment by moxcomic** [comment]
> I haven't changed any related logic. I think every time you launch the browser, you will open a new tab, because different tabs can have the same url, how could you know it's the same one as the last launch?

I remember that in previous versions of Chrome, the browser would remember the window size changed by dragging the mouse, but after a certain update of the Chrome browser, it no longer remembers the window size. It might be due to the Chrome update.

**Comment by ysmood** [comment]
could you try without rod? I might be a chromium issue.

**Comment by moxcomic** [comment]
> could you try without rod? I might be a chromium issue.

When I try launching with `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --user-data-dir=/path/to/data`, it can remember the window size normally.

**Comment by ysmood** [comment]
How about use the `Launcher.NewUserMode`

**Comment by moxcomic** [comment]
> How about use the `Launcher.NewUserMode`

It cannot record either; only when opened using the command can it normally record the window size.

**Comment by ysmood** [comment]
The fix will be released in the next version.

**Comment by ysmood** [comment]
Please check v0.114.8

**Comment by moxcomic** [comment]
> Please check v0.114.8

Thanks, the issue has been fixed after testing.
