### ISSUE TITLE
Bug element's pointer-events is none

### ISSUE THREAD

**Issue by rgunindi** [go-rod/rod#1013]
This is work:
```javascript
page.Eval(`document.querySelector('.g0 a').click()`)
```

This doesn't work:

```go
els, _ := page.Elements(".g0 a")
els[0].MustClick() //=> panic: element's pointer-events is none
// OR
el, _ := page.Element(".g0 a")
el.MustClick()
```

why this is happened in rod but work in js  ?

`Rod Version:  v0.114.7`

**Comment by ysmood** [comment]
pointer-events is none means not clickable, please google it first.

**Comment by rgunindi** [comment]
Why js code is work ?

**Comment by ysmood** [comment]
because js code does not control mouse, check the doc of `Page.Click`
