### ISSUE TITLE
Download in headless mode is failing, but works fine otherwise

### ISSUE THREAD

**Issue by sunaynat** [go-rod/rod#1014]
Rod Version: v0.114.7

## The code to demonstrate your question

using below line of code

launchedPage.MustElement(core.LocatorReference["documentPage"]["downloadButton"]).MustClick()

Expected to download file to downloads directory 

Is there a way to confirm is the download began or completed or may be downloaded to other directory ?

**Comment by ysmood** [comment]
https://pkg.go.dev/github.com/go-rod/rod#Browser.WaitDownload

**Comment by sunaynat** [comment]
wait download changes the file name of the download, otherwise the file is getting downloaded using that, is there a way to keep the file name original ?

**Comment by ysmood** [comment]
You can get the name by `SuggestedFilename` field.

**Comment by sunaynat** [comment]
Actually I don't want to manipulate the file name, the application's default file name validation is my test case.

**Comment by ysmood** [comment]
Chromium doesn't have this kind of api, it will always download the file to a tmp location.

You can contact the chromium team to fix it.
