### ISSUE TITLE
Add a JS script to browser

### ISSUE THREAD

**Issue by dunaevv** [go-rod/rod#1017]
Rod Version: v0.114.7

How can I add a JS script which would be evaluated in Chrome?
Can I do it like it in Playwright:
```
context.add_init_script(path_to_file)  
```
Thanks!

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/c35d2abd99a193ef49e21e02591cb6572269291f/page_eval_test.go#L14-L30

**Comment by dunaevv** [comment]
> https://github.com/go-rod/rod/blob/c35d2abd99a193ef49e21e02591cb6572269291f/page_eval_test.go#L14-L30

Thanks! I will try
