### ISSUE TITLE
Missing Request Body When Loading "https://www.booking.com" Using go-rod

### ISSUE THREAD

**Issue by sensensen404** [go-rod/rod#1018]
Rod Version: v0.114.7

I've encountered an issue when using go-rod to load "https://www.booking.com/" and hijack requests. Specifically, the problem arises with requests to the GraphQL API ("https://www.booking.com/dml/graphql"). While the browser's developer console shows that these requests include a request body, the intercepted request in go-rod appears to have a missing body, leading to request failure.

I'm not entirely sure if this issue is directly related to go-rod or if it's an underlying issue with the way requests are intercepted or processed. Any insights or suggestions on how to address this issue would be greatly appreciated.

## The code to demonstrate your question

1. Clone Rod to your local and cd to the repository:

   ```bash
   git clone https://github.com/go-rod/rod
   cd rod
   ```

1. Replace the content of function `Example_hijack_requests` in file `examples_test.go`.

1. Replace ALL THE CONTENT under `Example_hijack_requests` function, like below:

```go
func Example_hijack_requests() {

	browser := rod.New().MustConnect()
	defer browser.MustClose()

	router := browser.HijackRequests()
	defer router.MustStop()

	router.MustAdd("*/graphql*", func(ctx *rod.Hijack) {
		url := ctx.Request.Req().URL.String()
		fmt.Println("ctx test:" + url)
		fmt.Println("ctx test body:" + ctx.Request.Body())

		_ = ctx.LoadResponse(http.DefaultClient, true)

		fmt.Println("ctx test response status:" + ctx.Response.RawResponse.Status)
	})

	go router.Run()

	browser.MustPage("https://www.booking.com").MustWaitDOMStable()

	fmt.Println("done")
	// Output: done
}
```

## What you got

The output logs show the request URL but indicate an empty body for requests that definitely contain a body when inspected directly via the browser's developer console.

## What you expect to see

The request body for GraphQL requests to "https://www.booking.com/dml/graphql" should have a body.

## What have you tried to solve the question

- Inspecting the request directly in the browser to confirm that the body exists for the requests in question.
- Reviewing go-rod's documentation and source code to ensure correct usage of the request hijacking feature.

<img src="https://github.com/go-rod/rod/assets/3976133/b0d459d8-3339-4482-a03a-1f3871ddbcf2">
<img src="https://github.com/go-rod/rod/assets/3976133/78a97f7a-bd40-41f7-9755-07532238b96a">

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/0243a30b10871506324281942f9b16eeb45fdc12/hijack_test.go#L87
