### ISSUE TITLE
goroutine multiple WaitVisible/WaitVisibleE

### ISSUE THREAD

**Issue by kavimaluskam** [go-rod/rod#102]
I am trying to do a form submission (login) with go-rod, and try to do error handling with different element wait.

I am trying to use goroutine to do so:

```go
func Login() error {
        // login implementation
        var err error
	select {
	case err = <-WaitSuccess(page):
		return nil
        case err = <-WaitError(page):
                return err
        }
}

func WaitSuccess(page *rod.Page) <-chan error {
	e := make(chan error)
	go func() {
		defer close(e)
		page.Element("#success-resp").WaitVisible()
		e <- nil
	}()
	return e
}

func WaitError(page *rod.Page) <-chan error {
	e := make(chan error)
	go func() {
		defer close(e)
		page.Element("#error-resp").WaitVisible()
		e <- fmt.Errorf("fail login")
	}()
	return e
}
```

Yet i find i keep falling to same unhandled excpetion: `panic: context canceled`

I would like to ask if my approach is correct, or how to do it more elegantly?

**Comment by kavimaluskam** [comment]
@ysmood Thanks for this nice project. I am quite new to `go` and hope my question is helpful to your project.

**Comment by ysmood** [comment]
Can you provide reproducible code for us to test?

**Comment by kavimaluskam** [comment]
I further tested and it should be reproduced by using `go-rod` and `cobra` together.
When i am trying to race 2 `WaitVisible`.

Not sure if issue case is generic for you, but attached a demo application for you to reproduce the issue.

https://github.com/kavimaluskam/demo

simply: `go run main.go test` should give the issue.

**Comment by ysmood** [comment]
Yes, it's a race condition. See if I can add some locks to make this kind of use easier.

**Comment by ysmood** [comment]
If you remove the `defer browser.Close()` it will work as expected. The reason is because when one `<-goWaitVisible` is resolved, the other is still waiting, if you check the doc of `Element`, you will understand it's still retrying. During the retrying, if you close the browser, it will cause the context to cancel, the retrying will stop and return "context canceled" error.

Another way to fix it is to use try-catch:

```go
kit.Try(func () {
   page.Element(selector).WaitVisible()
})
```

Since one will definitely fail, you have to handle the error yourself.

**Comment by kavimaluskam** [comment]
You are right @ysmood . Thanks you for your support, and looking forward to the update of the related issue :)
