### ISSUE TITLE
but cannot check the element nodes on go-rod.

### ISSUE THREAD

**Issue by cplasfwst** [go-rod/rod#1020]
Rod Version: v0.114.7

Hello, dear author of go-rod, thank you very much for developing go-rod. It is very helpful and supportive to me.

Please tell me why the elements of this page cannot be detected, but I can manually detect them in the browser, but cannot check the element nodes on go-rod.
![QQ图片20240304174806](https://github.com/go-rod/rod/assets/34654697/174c1ed1-4c52-4382-95fc-427dc33506ac)

You can see the element in the developer tools:
![100866](https://github.com/go-rod/rod/assets/34654697/a7090833-776f-49e3-b639-ff80222513fd)

url:https://www.douyin.com

But i use :
`html, err := page.HTML()
				if err != nil {
					fmt.Println(err)
				}
				fmt.Println("Source code:", html)`

The obtained html file has no relevant elements：
[test.html.zip](https://github.com/go-rod/rod/files/14479822/test.html.zip)

How can I get the elements better? Or if you have any other plans or suggestions, please help me. Thank you very much.

**Comment by ysmood** [comment]
You might want to use DOM snapshot:

https://github.com/go-rod/rod/blob/0243a30b10871506324281942f9b16eeb45fdc12/lib/proto/dom_snapshot.go#L9

**Comment by cplasfwst** [comment]
> You might want to use DOM snapshot:
> 
> https://github.com/go-rod/rod/blob/0243a30b10871506324281942f9b16eeb45fdc12/lib/proto/dom_snapshot.go#L9

Please tell me how to operate the elements of proto.DOMSnapshotDOMNode? I mainly want to get the sliding verification box, and then slide to automate the verification

**Comment by cplasfwst** [comment]
> You might want to use DOM snapshot:
> 
> https://github.com/go-rod/rod/blob/0243a30b10871506324281942f9b16eeb45fdc12/lib/proto/dom_snapshot.go#L9

The main reason is that I have no way to get the verification money on the page. I want to operate this verification money page.MustElementX(`//canvas[@id="captcha_verify_image"]`)

**Comment by cplasfwst** [comment]
I saw the source code and wondered if it was because of the frame that I couldn't get the element? How does go-rod use frame?

**Comment by ysmood** [comment]
https://go-rod.github.io/#/selectors/README?id=get-elements-from-iframes

Please search other issues.
