### ISSUE TITLE
Does rod support separate  sessions or incognito  mode? 

### ISSUE THREAD

**Issue by BeyondIM** [go-rod/rod#1031]
Rod Version:v0.114.8

chromedp.WithNewBrowserContext is used to create a new browser context with chromedp. This allows you to operate in a separate session or incognito mode, where the state (cookies, local storage, etc.) is not shared with other browser contexts.  

Does rod have a similar solution? tks.

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/0340433eab4e6551f075eaf1875035469a777480/browser.go#L84-L85
