### ISSUE TITLE
测试时如何获取当前网页

### ISSUE THREAD

**Issue by pqj325** [go-rod/rod#1052]
您好，开发时需要直接获取当前网页，请问如何写？当前版本是 v0.115.0

**Comment by ysmood** [comment]
什么意思？

**Comment by pqj325** [comment]
场景是这样：手工打开一个网页，希望写一段代码实现获取当前网页，并执行代码种的操作，比如点击等。
https://go-rod.github.io/i18n/zh-CN/#/custom-launch?id=%e8%bf%9e%e6%8e%a5%e5%88%b0%e6%ad%a3%e5%9c%a8%e8%bf%90%e8%a1%8c%e7%9a%84%e6%b5%8f%e8%a7%88%e5%99%a8，这里的案例中：
`package main

import (
    "github.com/go-rod/rod"
)

func main() {
    u := "ws://127.0.0.1:9222/devtools/browser/4dcf09f2-ba2b-463a-8ff5-90d27c6cc913"
    rod.New().ControlURL(u).MustConnect().MustPage("**https://example.com**")
}`
需要配置加粗部分，能否不需要配置这个url就能执行代码，从而获取到当前网页？

**Comment by ysmood** [comment]
我不懂

**Comment by pqj325** [comment]
好吧，我先看看文档
