### ISSUE TITLE
Element存在，但Element.MustHas却为false，检测不到Element

### ISSUE THREAD

**Issue by hHZy3nWtn2** [go-rod/rod#1058]
Rod Version:0.116.0
页面URL：https://pub.alimama.com
`
//先进入iframe
loginIframe := tb.page.MustElement("iframe").MustFrame()
//切换到扫码登录方式
if loginIframe.MustHas("#login>.view-type-qrcode") {
	loginIframe.MustElement("#login>.view-type-qrcode>.icon-qrcode").MustEval(`()=>{let e = document.createEvent("MouseEvents");e.initEvent("click", true, true);this.dispatchEvent(e);}`)
}
`
问题1：loginIframe.MustHas始终返回false，但是loginIframe.MustElement("#login>.view-type-qrcode>.icon-qrcode")却可以正确取得Element。
问题2：loginIframe.MustElement("#login>.view-type-qrcode>.icon-qrcode").MustEval(`()=>{let e = document.createEvent("MouseEvents");e.initEvent("click", true, true);this.dispatchEvent(e);}`)如果换成loginIframe.MustElement("#login>.view-type-qrcode>.icon-qrcode").MustClick()，偶尔会出现点击无效（有发送点击事件，但实际按钮事件未被触发）

**Comment by ysmood** [comment]
#322
