### ISSUE TITLE
How to open a new Chrome window while using remote control

### ISSUE THREAD

**Issue by J404J** [go-rod/rod#1059]
Rod Version: v0.116.0

# Question
How can I control Chrome to open a new window or detach an open tab into a separate window while using remote control?

# Why
The reason for this requirement is: 
The target website needs to be displayed in the foreground to run. Even if multiple tabs are open, only the current tab's page will run.

# Ps
Additionally, if there are any other methods to operate pages that need to be kept in the foreground to run?

**Comment by ysmood** [comment]
The `NewWindow` option:

```
page, err := browser.Page(proto.TargetCreateTarget{
		URL: "http://example.com",
		NewWindow: true,
	})
```

**Comment by ysmood** [comment]
Read this example if you want better control:

https://github.com/go-rod/rod/blob/2d3e61f379eaddca6cf029c4060c34271064e641/lib/examples/use-rod-like-chrome-extension/main.go

**Comment by J404J** [comment]
> The `NewWindow` option:
> 
> ```go
> page, err := browser.Page(proto.TargetCreateTarget{
> 		URL: "http://example.com",
> 		NewWindow: true,
> 	})
> ```

Thank you very much, it‘s helpful to me.
