### ISSUE TITLE
How to Set or replace response headers

### ISSUE THREAD

**Issue by Qedr1** [go-rod/rod#1062]
Hi
First of all, this is amazing product ang great job! Thx!

How to Set or Replace **_response_** headers. For  example, I need to set cache headers for disable page caching
Can you help me pls?

Rod Version: v0.116.0

**Comment by ysmood** [comment]
Hijack?

**Comment by Qedr1** [comment]
Yes, hijack
For request headers I got it. But I cant find method for **response** headers.

**Comment by Qedr1** [comment]
OMG. I find it. Sorry
