### ISSUE TITLE
How to Log CDP Logs to a File or Use slog

### ISSUE THREAD

**Issue by thuongtin** [go-rod/rod#1066]
I’m currently working on a project using the go-rod/rod library and I need some assistance with logging CDP logs. Specifically, I want to achieve one of the following:

	1.	Log CDP logs to a file.
	2.	Use slog for logging CDP logs.

Could anyone provide guidance or examples on how to implement either of these logging methods with go-rod/rod? Any help or pointers to relevant documentation would be greatly appreciated.

**Comment by ysmood** [comment]
All the unit test of rod will output files, check the unit test code as example:

https://github.com/go-rod/rod/blob/0340433eab4e6551f075eaf1875035469a777480/setup_test.go#L253-L259
