### ISSUE TITLE
How to wait for all data on the page to load

### ISSUE THREAD

**Issue by duolaAOA** [go-rod/rod#107]
Because I will request many urls, how should I wait for each url to load, including javascript.

Because I don’t know what tag each url has, so I can’t use the following way
```go
// WaitRequestIdle will wait for all possible ajax calls to complete before
// continuing on with further execution calls.
wait := page.WaitRequestIdle()
page.Element("#search_form_input_homepage").Click().Input("test")
time.Sleep(300 * time.Millisecond) // Wait for js debounce.
wait()
```

**Comment by ysmood** [comment]
Can you provide code for us to reproduce your issue?

**Comment by duolaAOA** [comment]
Sorry, my bad.  I wrote the wrong html-label,rod is no problem.
