### ISSUE TITLE
NewUserMode 无法关闭浏览器

### ISSUE THREAD

**Issue by zhengjianyang** [go-rod/rod#1074]
Rod Version: v0.116.1

u:=launcher.NewUserMode().Bin().MustLaunch()

rod.New().ControlURL(u).MustConnect().NoDefaultDevice()

这样启动的浏览器关闭后chrome进程无法关闭、cmd+Q也退出不了、只能强制退出进程，请问这是为什么

**Comment by ysmood** [comment]
这是 chrome 的 bug。你可以使用 leakless 或者 `Browser.Close` 方法来关闭浏览器
