### ISSUE TITLE
missing source files

### ISSUE THREAD

**Issue by gshields** [go-rod/rod#108]
windows 10 version 2004
go version go1.15beta1 windows/amd64

go get -u -fix github.com/go-rod/rod
cannot find package "github.com/pierrec/lz4/v3" in any of:
        C:\go\src\github.com\pierrec\lz4\v3 (from $GOROOT)
        E:\p-tools\go_src\src\github.com\pierrec\lz4\v3 (from $GOPATH)

**Comment by ysmood** [comment]
[Don't rush to claim that you have found a bug.](http://www.catb.org/~esr/faqs/smart-questions.html#idm368)

Please learn how Golang module works. There are a lot of articles you can learn from.

**Comment by gshields** [comment]
I am sorry your page did not reference any install instructions,
maybe you can add that for newcomers.

Thanks

**Comment by gshields** [comment]
I think that there is more to this problem
I have  window 10 version 2004
go version go1.15beta1
and I have these environment set
set GOPATH=E:\p-tools\go_src
set GOBIN=E:\p-tools\go_bin
set GOROOT=C:\go

I have installed 30 other packages with no problem, this is the first one
that fails which leads me to believe it is a configuration issue of the
respository

**Comment by gshields** [comment]
I just install chromedp just fine,

**Comment by ysmood** [comment]
Do you know how to use google? If you use Google to search your error message `cannot find package "github.com/pierrec/lz4/v3"`, the first couple of results are: 

https://github.com/pierrec/lz4/issues/62

and

https://github.com/mholt/archiver/issues/195

The problem is you don't understand how `go module` works.

<img width="495" alt="Screen Shot 2020-07-12 at 16 02 09" src="https://user-images.githubusercontent.com/1415488/87240956-19128900-c459-11ea-87b5-aaca288f5b6a.png">

Just set the same flag on windows then use `go get`:

```
set GO111MODULE=on
go get github.com/go-rod/rod
```

**Comment by gshields** [comment]
This is the correct answer is that go 1.15 does not have GO111MODULE=on

Go from version 1.13 has this variable on by default
https://github.com/golang/go/issues/30750

Go ver 1.15 has GO111MODULE,  but the value is blank
Adding it into the window environment as  '=on'
Fixed the the problem

So in reality it is problem with the beta version of GO in a clean
environment!

**Comment by ysmood** [comment]
> So in reality it is problem with the beta version of GO in a clean

No, it's not. If you try 1.13 or 1.14, it has the same problem. You have to explicitly set `GO111MODULE=on`.

**Comment by gshields** [comment]
From what I have read go from version 1.13 has set to auto
Since there is a go.mod file in the repository it should have worked
https://insujang.github.io/2020-04-04/go-modules/
[image: image.png]

**Comment by ysmood** [comment]
Now, you know your description is wrong. What matters is the go module, not the beta version. If you have set up the go.mod properly, 1.15 beta will work fine.

**Comment by ysmood** [comment]
It's a very common problem for go module. If you google before you ask, we don't have to waste time on this issue.
