### ISSUE TITLE
找不到元素,点击按钮超时等问题

### ISSUE THREAD

**Issue by stevenyangecho** [go-rod/rod#1082]
Rod Version: v0.116.1

## The code to demonstrate your question

 

```
 
f := e.Page()
f.MustWaitStable()
f1 := f.MustElementR("button.t-dialog__confirm", "确定")
f1.MustWaitStable()
f1.MustClick()
```
这个按钮是之前点击后,弹出的一个对话框,
但是日志,却会出现  rod.ElementNotFoundError 的错误
```
[rod] 2024/06/27 17:18:32 [query] rod.elementR("button.t-dialog__confirm","确定")  <page:83C154CF>
[rod] 2024/06/27 17:18:32 [wait] visible <button.t-dialog__confirm>
2024-06-27T17:18:32 [ERRO] {34f2706fe5714baa2a76207bb606ab0a} [UserId:1] error value: &rod.ElementNotFoundError{}
```
同时在 打开的chrome里面,console 里输入

`$("button.t-dialog__confirm")`
能找到元素
![image](https://github.com/go-rod/rod/assets/5569554/5ab2b9d2-28bc-44aa-a553-68832a6f4cc7)

第二个问题

页面上确认选择没问题,也能正常看到按钮,但是MustClick点击的时候,有时候会出现 [wait] stable RAF  一直等待,直到超时...多重复几次,运行有很大失败概率,有时候又可以成功

`[rod] 2024/06/27 17:18:27 [wait] stable RAF <button.`

**Comment by ysmood** [comment]
有办法让我复现这个问题吗？

**Comment by stevenyangecho** [comment]
没事了,大概知道原因,原来是网站魔幻操作,同一个页面弹出框有N个隐藏同样属性的....
