### ISSUE TITLE
discord chat is full or disabled

### ISSUE THREAD

**Issue by gshields** [go-rod/rod#109]
Trying to join discord and get this message

![image](https://user-images.githubusercontent.com/3464355/87231782-f0ae6000-c36e-11ea-9267-701316332567.png)

**Comment by ysmood** [comment]
Just tried the link, it works fine to me, can you provide the error link to us?

**Comment by ysmood** [comment]
Please use the link on the root readme page.

**Comment by gshields** [comment]
on this url https://github.com/go-rod/rod
under examples is this sentance
If you have questions, please raise an issue or join the chat room.
which links to 
https://discord.gg/CpevuvY

This was the I link used to discord.

The button overview  of the same page is labeled as 'chat' which also linked to 
https://discord.gg/CpevuvY

both resolve to a discord page that has this message saying invite invalid

**Comment by ysmood** [comment]
Watch the screen recording, it works fine:

https://drive.google.com/file/d/1yBdG6CPQ6wJlAxZgBhKt4CRabOpw7X4h/view?usp=sharing

**Comment by NormalPunch** [comment]
Works fine for me in a chrome incognito, maybe you can check your network/plugins which may modify the url?

**Comment by gshields** [comment]
Using firefox 78.0.2 with https://everwhere.
I turned it off and the link worked
Then turn it back on and it still worked
must be a bug somewhere in FF, https://everwhere or discord
