### ISSUE TITLE
Sir, I want to get the html system of the whole webpage. What should I do?

### ISSUE THREAD

**Issue by dollarkillerx** [go-rod/rod#110]
Sir, I want to get the html system of the whole webpage. What should I do?
```go
func main() {
	client := launcher.NewRemote("ws://localhost:9222").Client()

	browser := rod.New().Client(client).Connect()

	text,err := browser.Timeout(time.Second * 3).Page("https://www.baidu.com").Element("html").TextE()
	if err != nil {
		log.Fatalln(err)
	}
	log.Println(text)
}
```

I want to get the html of the entire webpage，this operation text is empty

**Comment by Hamzantal** [comment]
Please check out the [HTMLE](https://pkg.go.dev/github.com/go-rod/rod?tab=doc#Element.HTMLE) method

**Comment by dollarkillerx** [comment]
Thank you very much for your answers
