### ISSUE TITLE
Hijack 没有正确的设置和返回数据

### ISSUE THREAD

**Issue by zhanxiaox** [go-rod/rod#1115]
Rod Version: v0.116.2

## The code to demonstrate your question

```go
	router.MustAdd("https://www.baidu.com/*", func(h *rod.Hijack) {
		h.Request.URL().Query().Set("count", "1")
		h.Response.SetBody(`{"status_code": 996}`)
		h.MustLoadResponse()
		resp = h.Response.Body()
		c <- 1
	})
```

## What you got

可以接收到正常（未修改过）的请求的 response，但不能正确设置请求的 url query 和 response body

## What you expect to see

希望能在拦截请求的时候加上自定义的 query 和自定义的 response

## What have you tried to solve the question

参照官方文档中指引的测试单元，代码没有预期的效果

**Comment by ysmood** [comment]
你并没有按照测试代码来写，请仔细对比你的代码和测试代码的区别：

https://github.com/go-rod/rod/blob/c42b414fffbd412dddac4903e5bc9355c6bb786c/hijack_test.go#L45-L49

**Comment by zhanxiaox** [comment]
这个 g 是从 test 出来的，在正常使用用中怎么来得到 g.Context()，后续需要在哪里注入这个 context 吗

**Comment by zhanxiaox** [comment]
> 你并没有按照测试代码来写，请仔细对比你的代码和测试代码的区别，代码的执行顺序不一样：
> 
> https://github.com/go-rod/rod/blob/c42b414fffbd412dddac4903e5bc9355c6bb786c/hijack_test.go#L45-L49

这个 g 是从 test 出来的，在正常使用用中怎么来得到 g.Context()，后续需要在哪里注入这个 context 吗

**Comment by ysmood** [comment]
任意的 context 就行，可以先学习下 golang 的 context 的基本概念，这个和 rod 无关。

**Comment by zhanxiaox** [comment]
好的谢谢。
