### ISSUE TITLE
linux auto install chromium were killed

### ISSUE THREAD

**Issue by twolao** [go-rod/rod#1122]
Rod Version: v0.116.2

## The code to demonstrate your question

1. Clone Rod to your local and cd to the repository:

   ```bash
   git clone https://github.com/go-rod/rod
   cd rod
   ```

1. Use your code to replace the content of function `TestRod` in file `rod_test.go`.

1. Test your code with: `go test -run TestRod`, make sure it fails as expected.

1. Replace ALL THE CONTENT under "The code to demonstrate your question" with your `TestRod` function, like below:

```go
package main

import (
    "github.com/go-rod/rod"
    "log"
)

func main() {
    page := rod.New().MustConnect().MustPage("https://google.com")
    page.MustWaitLoad()
    page.MustWaitStable().MustScreenshot("a.png")
    select {} 
}
```

## What you got

[launcher.Browser]2024/10/12 11:02:09 Download: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1321438/chrome-linux.zip
[launcher.Browser]2024/10/12 11:02:10 Progress: 00%
[launcher.Browser]2024/10/12 11:02:11 Progress: 24%
Killed

## What you expect to see

ubuntu 22

install chromium and get a screenshot

**Comment by ysmood** [comment]
It might be not enough memory or disk space for your system.

**Comment by twolao** [comment]
> It might be not enough memory or disk space for your system.

**Comment by twolao** [comment]
thanx
