### ISSUE TITLE
如何处理异常？

### ISSUE THREAD

**Issue by goodway2016** [go-rod/rod#113]
如题

**Comment by ysmood** [comment]
朋友你这我有点不懂啊，不用强求用英文的，就用你会的，把问题说出来，或许能帮到其他人。

**Comment by ysmood** [comment]
关于异常处理，文档常见问题里说的很清楚了：https://github.com/go-rod/rod#q-why-functions-dont-return-error-values

初学者可以用 `kit.Try` 来捕获一段代码的异常，比如这样：

```go
err := kit.Try(func() {
    page.Element("button").Click()
})
```
