### ISSUE TITLE
Why is user mode downloading new browser?

### ISSUE THREAD

**Issue by rew1nter** [go-rod/rod#1130]
Rod Version: v0.116.2

## The code to demonstrate your question

I'm trying to launch my browser with session with the following code:
```go
func main() {

	path := "/usr/bin/chromium"
	wsURL := launcher.NewUserMode().Bin(path).Headless(false).MustLaunch()
	browser := rod.New().ControlURL(wsURL).MustConnect().NoDefaultDevice()
}
```

## What you got

Upon running, rod starts downloading a browser. When I already have chromium

## What you expect to see

The system chromium browser start with my session

**Comment by ysmood** [comment]
The code works fine for me.

**Comment by rew1nter** [comment]
I'm on Arch linux. Is there anything I can provide you with to troubleshoot the issue?

**Comment by ysmood** [comment]
If you run `launcher.NewUserMode().Bin(path).Headless(false).MustLaunch()` alone, will it download the browser?

**Comment by rew1nter** [comment]
Hello, 
I don't know what happened but the same code is working all of a sudden :/
Thanks
