### ISSUE TITLE
Why does headless mode have no effect

### ISSUE THREAD

**Issue by rew1nter** [go-rod/rod#1132]
Rod Version: v0.116.2
## The code to demonstrate your question
`Headless(true|false)` has no effect on the browser here. The browser is always shown

```go
package main

import (
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
)

func main() {
	// make sure target browser is closed
	path := "/usr/bin/chromium"
	// launch installed browser
	wsURL := launcher.NewUserMode().Bin(path).Headless(true).MustLaunch()
	// connect to the browser
	browser := rod.New().ControlURL(wsURL).MustConnect().NoDefaultDevice()

	browser.MustPage("http://127.0.0.1:80/#")
}

```

## What you got

The browser always shown

## What you expect to see

The browser shown or hidden based on the flag

## What have you tried to solve the question

Such as after modifying some source code of Rod you are able to get rid of the problem.

**Comment by ysmood** [comment]
UserMode is a raw mode, you literally have to manage everything, if you don't close the browser, it will remain open. In this mode, rod will not help you to close the browser.

**Comment by rew1nter** [comment]
You are right!
