### ISSUE TITLE
如何设置浏览器不显示地址栏和菜单栏

### ISSUE THREAD

**Issue by zk3151463** [go-rod/rod#1135]
版本：v0.116.2
如何设置浏览器不显示地址栏和菜单栏，使用
<img width="491" alt="image" src="https://github.com/user-attachments/assets/c217b13f-caf1-46c5-8159-60c0e759e1f0">
这么设置不起作用

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/0096e531a49c82f272f5661eabe755d2e7c1eb61/lib/launcher/launcher.go#L146-L148

**Comment by zk3151463** [comment]
使用NewAppMode 这个后如何跳转页面使用MustNavigate、MustPage 打开两个页面，是否可以提供个 demo，还有设置代理
