### ISSUE TITLE
Doc how to debug rod itself

### ISSUE THREAD

**Issue by ysmood** [go-rod/rod#114]
Devtools is not perfect, it has bugs. Rod provides ways to debug it.

Such as doc how to use env `rod=cdp`, so that people can help us to debug low-level issues.

- vscode tips: CMD+T, CMD+SHIFT+O
- lint code
- go generate
- run, skip, filter tests
- dump values, colorful output
- check log files
- check coverage
- check github actions' log
- use stub
- use breakpoint
- debug goroutine leak

**Comment by thuongtin** [comment]
How can I log to a file instead of printing to the console?
`browser.Logger(utils.Log(func(msg ...interface{}) { fmt.Sprintln(msg...) }))`

**Comment by ysmood** [comment]
@thuongtin https://github.com/go-rod/rod/issues/1066#issuecomment-2143466691
