### ISSUE TITLE
Can't finish benchmark testing

### ISSUE THREAD

**Issue by botsphp** [go-rod/rod#115]
```
func BenchmarkElement(b *testing.B) {
	for i := 0; i < b.N; i++ {
		rod.New().Connect().Page(srcFile("fixtures/open-page.html"))
	}
}
```

will cause goroutine chan error.

**Comment by ysmood** [comment]
[Don't rush to claim that you have found a bug.](http://www.catb.org/~esr/faqs/smart-questions.html#idm368)

**Comment by ysmood** [comment]
The code you showed is like running this kind of pseudo-code:

```
while(true) {
   launch a new chrome.exe
}
```

Do you think your PC's memory can carry 10k chrome.exe instances? 😂
