### ISSUE TITLE
On linux chrome launch failing

### ISSUE THREAD

**Issue by rajender** [go-rod/rod#116]
**Rod Version:** v0.45.1

> panic: [launcher] Failed to get the debug url: [0715/074020.195948:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/a0664b4b74ad4947fce131ab798fc01efd625194/examples_test.go#L202-L229

Add two flags, `no-sandbox` and `--no-zygote`, may help.

**Comment by rajender** [comment]
It's working fine with no-sandbox option.
