### ISSUE TITLE
Support websocket remote browser

### ISSUE THREAD

**Issue by chaoqing** [go-rod/rod#117]
I am using browserless/chrome as my remote headless chrome. They support wss:// devtool protocol and it seems rod actually replace wss with https. Do you guys have any plan support real websocket protocol?

https://github.com/go-rod/rod/blob/a0664b4b74ad4947fce131ab798fc01efd625194/lib/launcher/proxy.go#L24

**Comment by ysmood** [comment]
rod already supports `browserless/chrome`

https://github.com/go-rod/rod/blob/a0664b4b74ad4947fce131ab798fc01efd625194/examples_test.go#L216-L217

The `url` above is your url from `browserless/chrome`

**Comment by chaoqing** [comment]
Great! Thanks for your help. It works.

**Comment by ysmood** [comment]
@chaoqing you can also use code like this to convert http://127.0.0.1:9222 to the url that `ControlURL` needs:

```go
func main() {
	url, _ := launcher.GetWebSocketDebuggerURL(context.Background(), `http://127.0.0.1:9222`)

	browser := rod.New().ControlURL(url).
		Trace(true).Slowmotion(time.Second).Connect()

	text, err := browser.Timeout(time.Second * 3).Page("https://www.baidu.com").Element("html").TextE()
	if err != nil {
		log.Fatalln(err)
	}
	log.Println(text)
}
```
