### ISSUE TITLE
NewUserMode问题

### ISSUE THREAD

**Issue by yasarluo** [go-rod/rod#118]
https://github.com/go-rod/rod/blob/master/lib/examples/use-rod-like-chrome-extension/main.go

这个例子启动后就会panic：
panic: [launcher] Failed to get the debug url: 正在现有的浏览器会话中打开。

加上Headless(true)就不会报错，但是打开的页面并没有复用已经登录的cookie，还是空状态的。

macOS Mojave 10.14.6
Chrome 83.0.4103.116

**Comment by ysmood** [comment]
朋友，麻烦看下这个 NewUserMode 的文档，手的很清楚了 https://pkg.go.dev/github.com/go-rod/rod@v0.46.4/lib/launcher?tab=doc#NewUserMode

**Comment by yasarluo** [comment]
txs，不过这样感觉不太科学

**Comment by ysmood** [comment]
我也觉得不科学，但是chrome就是没支持判定是否已经有 chrome 启动了。目前唯一的想法是通过判定 user data dir 里是否存在 lock 文件来判定，但是这个跨平台问题比较大，暂时时间去细究，如果你感兴趣可以帮我们提交 PR 来改善这个功能。

**Comment by yasarluo** [comment]
我回头研究研究，如果能搞出来就试试~
