### ISSUE TITLE
不能直接连到cdp么

### ISSUE THREAD

**Issue by chennqqi** [go-rod/rod#124]
这个库的用法类似于selenium
能直接连到已经启动9222的远程浏览器上么？就像[chromedp](https://github.com/chromedp/chromedp)之类的

**Comment by ysmood** [comment]
重复提问 #117

**Comment by chennqqi** [comment]
并不是重复提问，我看他的问题似乎解决了，他还是用的本机chrome。我的意思是使用远程的chrome --remote-debugging-port模式。

1. 在构建launcher.New()最后一步执行Launch()返回URL中会启动chrome进程的。
2. launcher.NewRemote() 远程连接必须是lib/launcher/rod-launcher，我的意思是能否支持直接连接原生动chrome:9222端口。
我的问题是能否支持类似于ferrit/chromedp那样，只要远程启动一个chrome就行了，使用的是chrome的tab标签。

**Comment by ysmood** [comment]
已经支持了，你看那个回答的代码截取，压根就没提到 launcher 啊，根本不需要用 launcher 了，直接 `rod.New().ControlURL(url)`

这也是 rod 架构设计的一个优势，每个部分都是可选的可替代的。

**Comment by ysmood** [comment]
launcher 的 remote 是适配 rodorg/rod 这个 docker image 的，只是提供了更好的安全性，你当然可以不用它。

**Comment by ysmood** [comment]
当然我强烈推荐使用 rodorg/rod 来建设集群，这个在设计上比其他库好很多。你可以根据需求动态改变 chrome 的 flag 和配置，而无需重启 container

**Comment by chennqqi** [comment]
感谢回复。。我测了不可以
```
	browser := rod.New().ControlURL("ws://127.0.0.1:9222").
		Trace(true).Slowmotion(time.Second).Connect()
```
或者是
```
	browser := rod.New().ControlURL("http://127.0.0.1:9222").
		Trace(true).Slowmotion(time.Second).Connect()
```

**Comment by ysmood** [comment]
我可以啊，远程控制服务器的 chrome，chrome 我手动启动的

**Comment by ysmood** [comment]
提问最好是提供可复现的步骤，否则你说了我怎么帮你

**Comment by ysmood** [comment]
关于 ferret 我之前在 reddit 里被人问到过，这里提及下：

https://www.reddit.com/r/golang/comments/gc3gue/a_lib_to_make_web_scraping_and_automation_easy/fpe58ew?utm_source=share&utm_medium=web2x

**Comment by chennqqi** [comment]
好的，我详细描述一下步骤：
1.  我在windows下启动chrome浏览器rdp服务`chrome.exe --remote-debugging-port=9222`来模拟rdp集群
2. 编写代码调用rod
代码如下:
example A:
```GO
func main() {
	url := launcher.New().
		Headless(false).Launch()

	fmt.Println("URL:", url)

	browser := rod.New().ControlURL(url).
		Trace(true).Slowmotion(time.Second).Connect()

	text, err := browser.Timeout(time.Second * 3).Page("https://www.baidu.com").Element("html").TextE()
	if err != nil {
		log.Fatalln(err)
	}
	log.Println(text)
}
```
example A:可以正常运行但是无法指定rdp地址

example B:
```Go
func main() {
	browser := rod.New().ControlURL(`http://127.0.0.1:9222`).
		Trace(true).Slowmotion(time.Second).Connect()

	text, err := browser.Timeout(time.Second * 3).Page("https://www.baidu.com").Element("html").TextE()
	if err != nil {
		log.Fatalln(err)
	}
	log.Println(text)
}
```
example B: 运行报错panic: malformed ws or wss URL

example C:
```Go
func main() {
	browser := rod.New().ControlURL(`http://127.0.0.1:9222`).
		Trace(true).Slowmotion(time.Second).Connect()

	text, err := browser.Timeout(time.Second * 3).Page("https://www.baidu.com").Element("html").TextE()
	if err != nil {
		log.Fatalln(err)
	}
	log.Println(text)
}
```
example C:运行报错： panic: websocket: bad handshake

**Comment by ysmood** [comment]
因为你的 url 不是 `ws://127.0.0.1:9222/....`，你启动chrome应该能看到它打印了一个很长的类似这样的路径：

```
DevTools listening on ws://127.0.0.1:9222/devtools/browser/20688243-60b5-4ebb-9009-53e3f37dc4a8
```

当然如果你像我一样懒可以，加一点代码来把 http 转换成 ws

```go
func main() {
        url, _ := launcher.GetWebSocketDebuggerURL(context.Background(), `http://127.0.0.1:9222`)

	browser := rod.New().ControlURL(url).
		Trace(true).Slowmotion(time.Second).Connect()

	text, err := browser.Timeout(time.Second * 3).Page("https://www.baidu.com").Element("html").TextE()
	if err != nil {
		log.Fatalln(err)
	}
	log.Println(text)
}
```

**Comment by chennqqi** [comment]
感谢！问题解决了。。
其实要的就是GetWebSocketDebuggerURL

**Comment by ysmood** [comment]
GetWebSocketDebuggerURL 这个就2行代码，自己写都可以，觉得 rod 好用请帮助推广，更多人贡献代码你就可以从中受益

**Comment by chennqqi** [comment]
一定一定

**Comment by tpsmr** [comment]
.\main.go:33:12: undefined: launcher.GetWebSocketDebuggerURL
.\main.go:33:45: undefined: context
