### ISSUE TITLE
Redirect http to https on js , how to catch or follow ? 

### ISSUE THREAD

**Issue by 23233** [go-rod/rod#125]
### How do follow or catch this js jump behavior ? 

thanks ~

**Comment by ysmood** [comment]
Can you provide code for us to reproduce your issue?

**Comment by 23233** [comment]
![image](https://user-images.githubusercontent.com/12870070/87745482-960a7d80-c820-11ea-964f-3f2f715c9ddc.png)

### code 
```
        u := launcher.New().
		Headless(false).
		Devtools(true).
		Launch()

	browser := rod.New().
		Timeout(time.Minute).
		ControlURL(u).
		Trace(true).
		Slowmotion(2 * time.Second).
		Connect()
	defer browser.Close()
	// 执行网页操作 超时就关闭
	var page *rod.Page
	page,err := browser.Timeout(15 * time.Second).PageE(url)
	if err != nil {
		page = browser.Timeout(40 * time.Second).Page(strings.Replace(url, "http", "https", -1))
	}
        page.Viewport(1920, 1080, 1, false)
	wait := page.WaitRequestIdle()
	wait()

	d.Url = url

	titleElement := page.Eval("() => document.title").String()

        // run this line throw error
	bodyElement := page.Eval("() => document.body.innerText").String()

```

**Comment by 23233** [comment]
### Just like if you use WaitRequestIdle run url  www.1.com but 1.com use js jump to www.2.com , you WaitRequestIdle wait 1.com idle success,  but 2.com is run loading time or not ready , if you get element target code , this throw error !

**Comment by rajender** [comment]
@23233 

Can you try the following code? Is this what you are trying to achieve?

```go
package main

import (
	"log"

	"github.com/go-rod/rod"
)

func main() {
	page := rod.New().Connect().Page("http://www.023dir.com")

	titleElement := page.Element("title").Text()
	log.Println(titleElement)

	bodyElement := page.Element("body").Text()
	log.Println(bodyElement)
}
```

**Comment by 23233** [comment]
### Yes result is right !

### But why change to element find , result is ok ?  

### Eval and Element runtime different ?  maybe element use lazy find ?

### Problem  fix , thanks @rajender
