### ISSUE TITLE
disable `rod` env programmatically

### ISSUE THREAD

**Issue by NormalPunch** [go-rod/rod#127]
like `rod.DisableRodEnv`

to avoid being debugged by normal users

**Comment by rajender** [comment]
What problem are we trying to solve here?

**Comment by NormalPunch** [comment]
> What problem are we trying to solve here?

https://github.com/go-rod/rod/pull/128/commits/01632fcf107f14dea6ab730c9b4a9750a30adf4f

sometimes developers want to disable the `super debug flags` for normal users
