### ISSUE TITLE
doc: add example to show dismissing all window.alert

### ISSUE THREAD

**Issue by rajender** [go-rod/rod#129]
This should be useful for beginners to get rid of annoying alert messages.

Something along the lines of  

```go
page := rod.New().Connect().Page("https://teslainventory.teslastats.no/")

page.Eval(`window.alert = () => {}`)
```

**Comment by rajender** [comment]
@ysmood can you assign this to me? I will try to prepare PR for this.

**Comment by ysmood** [comment]
I invited you to help us maintain the project: https://github.com/go-rod/rod/invitations
