### ISSUE TITLE
Execution hangs when calling cleanup function

### ISSUE THREAD

**Issue by diegobernardes** [go-rod/rod#131]
I'm having some problems with the snippet bellow:
```golang
cleanup, err := page.Context(pctx, pctxCancel).SetExtraHeadersE(w.genHeaders(endpoint))
if err != nil; err != nil {
  return false, fmt.Errorf("failed to set the headers: %w", err)
}
defer cleanup()
```

When the `cleanup` function is called the execution just hangs forever. Do I need to do anything else to use the cleanup? Do I ever need to clean up if the tab is being closed at the end of this function?

Full code here: https://github.com/Nitro/markdown-link-check/blob/master/internal/service/provider/web.go#L202

**Comment by ysmood** [comment]
After you run `cleanup`, the headers you set won't take effect anymore, the requests the browser sends won't carry the extra headers anymore. Are you sure you really want to do that?

Usually, we set extra headers and never disable it.

As you can see, our unit test works fine: https://github.com/go-rod/rod/blob/dbac996/page_test.go#L65

Can you provide code for us to reproduce your issue?

**Comment by diegobernardes** [comment]
> After you run `cleanup`, the headers you set won't take effect anymore, the requests the browser sends won't carry the extra headers anymore. Are you sure you really want to do that?
> 
> Usually, we set extra headers and never disable it. When you close the page, it will clean up automatically.
> 
> As you can see, our unit test works fine: https://github.com/go-rod/rod/blob/dbac996/page_test.go#L65
> 
> Can you provide minimal code for us to reproduce your issue?

Yea this is the desired behavior. The application is used to find broken links on markdown files. The headers on the requests can vary depending on the endpoint being checked.

> As you can see, our unit test works fine: https://github.com/go-rod/rod/blob/dbac996/page_test.go#L65
> 
> Can you provide minimal code for us to reproduce your issue?

Hmm, strange, the problem just happens on my macOS, at the CI environment that is running Linux everything is working fine.

This is the lines that I've changed: https://github.com/Nitro/markdown-link-check/blob/3ada58686485a40dad30cf21271e8363e4ea91d7/internal/service/provider/web.go#L214-L218
The clear function is being called by a defer, that was the only difference.

**Comment by ysmood** [comment]
We have fixed some chrome issue recently: https://github.com/go-rod/rod/commit/03ab89c9387241f9d75b3578c925c5c25e550396

You rod version is behind this fix, I highly recommend you update rod and retry it again.

**Comment by ysmood** [comment]
The way you close the page will cause leaking: https://github.com/Nitro/markdown-link-check/blob/3ada58686485a40dad30cf21271e8363e4ea91d7/internal/service/provider/web.go#L227

If you should always defer page.Close right after the creation of it.

**Comment by ysmood** [comment]
```go
```

**Comment by ysmood** [comment]
I added an example to debug hanging, might be useful to you: https://github.com/go-rod/rod/blob/master/lib/examples/debug-deadlock/main.go

**Comment by diegobernardes** [comment]
Thanks for the help @ysmood. I had to focus on some other tasks but my app is now running with rod. So far everything is fast and stable.
