### ISSUE TITLE
可以增加一个真实登录成功保存cookie，并后续读取导入到浏览器里的例子吗

### ISSUE THREAD

**Issue by zjlx** [go-rod/rod#134]
请教大家有用json格式cookie进行登录的嘛 我试了可能是构造&proto.NetworkCookieParam的参数或者其他问题，导致FB的账号10个能有1个能登录成功，而用selenium都可以登录成功，这种是怎么回事呢，大家谁能提供下这方面的例子吗，万分感谢。
cookie格式是

```json
{"domain":"facebook.com","expirationDate":1648615149,"hostOnly":false,"httpOnly":false,"name":"datr", "path":"/","sameSite":"no_restriction","secure":false,"session":false,"storeId":"0","value":"tr5y48r94r5410WNz","id":0}
```

相关代码：

```go
cookies := &proto.NetworkCookieParam{
			Name:  name,
			Value: value,
			URL:   “https://www.facebook.com”, 
			Domain:   domain,
			Expires:  &proto.TimeSinceEpoch{Time: gconv.Time(expires)}, 
			HTTPOnly: httpOnly,
			Path:     path,
			SameSite: proto.NetworkCookieSameSite(sameSite),
			Secure:   secure,
		}
page.SetCookies(cookies)
```

我尝试了这种，设置所有NetworkCookieParam参数的方式，也试了只有Name,Value,URL的方式，也试了Name,Value,Domain的方式，效果是一样的，都是极少数能登录成功，我觉得可能是我参数构造的方式有问题，希望能添加这方面的例子，谢谢！

**Comment by ysmood** [comment]
Can you provide code for us to reproduce your issue?

**Comment by NormalPunch** [comment]
You can check the api with `http://httpbin.org/get`, it will return your cookies.

**Comment by zjlx** [comment]
> 能提可复现你问题的完整代码吗？

`package main

import (
	"fmt"
	"github.com/buger/jsonparser"
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/proto"
	"github.com/gogf/gf/text/gstr"
	"github.com/gogf/gf/util/gconv"
	"time"
)

func main() {

	//defer os.RemoveAll(tempData)
	useragent:="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"
	debugUrlPort := launcher.New().
		//Bin("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe").
		UserDataDir("tempData").
		Headless(false).
		Set("user-agent", useragent). // add flag
		Set("lang", "en_US").
		Set("disable-web-security"). // add flag
		Set("no-sandbox").
		Delete("use-mock-keychain"). // delete flag
		Set("safebrowsing-disable-auto-update").
		Set("disable-gpu").
		Set("disable-background-networking").
		Set("disable-background-timer-throttling").
		Set("disable-breakpad").
		Set("disable-client-side-phishing-detection").
		Set("disable-default-apps").
		Set("disable-dev-shm-usage").
		//Set("disable-extensions").
		Set("disable-sync").
		Set("disable-translate").
		Set("disable-prompt-on-repost").
		Set("hide-scrollbars").
		Set("ignore-certificate-errors").
		Set("ignore-certificate-errors-spki-list").
		Set("ignore-ssl-errors").
		Set("metrics-recording-only").
		Set("mute-audio").
		Set("no-first-run").
		Set("disable-popup-blocking").
		Set("disable-infobars"). //关闭Chrome 正受到自动测试软件的控制这个控制条
		Set("enable-automation"). //关闭Chrome 正受到自动测试软件的控制这
		Set("disable-notifications"). //禁止订阅提示弹出
		Set("disable-device-discovery-notifications"). //禁止订阅提示弹出
		Set("disable-web-notification-custom-layouts"). //禁止订阅提示弹出
		Launch()
	fmt.Println(debugUrlPort)
	browser := rod.New().
		ControlURL(debugUrlPort).
		Timeout(4 * time.Minute). //如果不设置程序会卡死
		//DebugCDP(true). // log all cdp traffic //开启这个记录居然会导致proxy不起作用
		Trace(true). // 显示每个输入动作的轨迹,会在网页上标红
		Slowmotion(time.Second / 2). // each input action will take 1 second
		Connect()
	//defer browser.Close()

	page := browser.Page("") //需要用这个 否则上面的hook不生效

	// Doc: https://chromedevtools.github.io/devtools-protocol/tot/Network#method-setCookie
	//下面cookie格式是chrome
	cookies:=`[{"domain": ".facebook.com", "expirationDate": 1598255720,"hostOnly": true,"httpOnly": true, "name": "datr", "path": "/","sameSite": "no_restriction","secure": false,"session": false, "storeId": "0", "value": "eemtxUnhtyhrgtrejTPQZ6", "id": 1},{"domain": ".facebook.com", "expirationDate": 1598255720,"hostOnly": true,"httpOnly": true, "name": "sb", "path": "/","sameSite": "no_restriction","secure": false,"session": false, "storeId": "0", "value": "erthutedgreILVDmyFeLC", "id": 2},{"domain": ".facebook.com", "expirationDate": 1598255720,"hostOnly": true,"httpOnly": true, "name": "m_pixel_ratio", "path": "/","sameSite": "no_restriction","secure": false,"session": false, "storeId": "0", "value": "2", "id": 3},{"domain": ".facebook.com", "expirationDate": 1598255720,"hostOnly": true,"httpOnly": true, "name": "wd", "path": "/","sameSite": "no_restriction","secure": false,"session": false, "storeId": "0", "value": "360x366", "id": 4},{"domain": ".facebook.com", "expirationDate": 1598255720,"hostOnly": true,"httpOnly": true, "name": "fr", "path": "/","sameSite": "no_restriction","secure": false,"session": false, "storeId": "0", "value": "1bwhtoneI478949874AH.AWU0z8aS", "id": 5},{"domain": ".facebook.com", "expirationDate": 1598255720,"hostOnly": true,"httpOnly": true, "name": "c_user", "path": "/","sameSite": "no_restriction","secure": false,"session": false, "storeId": "0", "value": "10005478490000", "id": 6},{"domain": ".facebook.com", "expirationDate": 1598255720,"hostOnly": true,"httpOnly": true, "name": "xs", "path": "/","sameSite": "no_restriction","secure": false,"session": false, "storeId": "0", "value": "tert13:9377:2508", "id": 7}]`
	//Todo 如果之前登录成功,那么不加载cookies也是可以的,直接读取本地的data文件夹
	_, err := jsonparser.ArrayEach([]byte(cookies), func(cookie []byte, dataType jsonparser.ValueType, offset int, err error) {
		domain, _ := jsonparser.GetString(cookie, "domain")
		domain = gstr.Replace(domain, `"facebook.com"`, `".facebook.com"`)
		expires, _ := jsonparser.GetInt(cookie, "expirationDate")
		httpOnly, _ := jsonparser.GetBoolean(cookie, "httpOnly")
		name, _ := jsonparser.GetString(cookie, "name")
		value, _ := jsonparser.GetString(cookie, "value")
		path, _ := jsonparser.GetString(cookie, "path")
		//sameSite, _ := jsonparser.GetString(cookie, "sameSite")
		secure, _ := jsonparser.GetBoolean(cookie, "secure")
		//fmt.Printf("%s",expires)
		//cookie=jsonparser.Delete(cookie,"expirationDate")
		//cookie, _ = jsonparser.Set(cookie, expires,"expires")
		//fmt.Println(string(cookie))
		//与cookie设置相关联的request-URI。此值可能会影响创建的cookie的默认域和路径值。
		//cookie必须包括value and url or domain这三个

		cookies := &proto.NetworkCookieParam{
			Name:  name,
			Value: value,
			URL:   "https://www.facebook.com",
			Domain:   domain,//这种方式大概率登录失败
			Path:     path,
			Secure:   secure,
			HTTPOnly: httpOnly,
			SameSite: proto.NetworkCookieSameSiteLax,
			Expires:  &proto.TimeSinceEpoch{Time: gconv.Time(expires)}, //这里需要替换,
			Priority: "",
		}
		page.SetCookies(cookies)
		//下面的方法跟上面的相同，都有无法登录的现象
		//_, err = proto.NetworkSetCookie{
		//	Name:     name,
		//	Value:    value,
		//	Domain:   domain,
		//	Expires:  &proto.TimeSinceEpoch{Time: gconv.Time(expires)}, //这里需要替换
		//	HTTPOnly: httpOnly,
		//	Path:     path,
		//	SameSite: proto.NetworkCookieSameSite(sameSite),
		//	Secure:   secure,
		//}.Call(page)
		//kit.E(err)

	})
	if err != nil {
		panic(err)
	}
	page.Navigate("https://www.facebook.com/").WaitLoad()
	time.Sleep(10 * time.Second)
}
`

**Comment by zjlx** [comment]
> You can check the api with `http://httpbin.org/get`, it will return your cookies.

I'm going to use cookies to bypass user name and password. It's not about getting cookies

**Comment by ysmood** [comment]
> Can I reduce the unrelated code to make the example minimal?

你提交问题的时候我们已经提示过 “你可以移除不影响你问题的代码吗？”

另外请格式化一下你的代码再上传，请学习下如何使用 markdown 展示代码，为什么这个人的代码有语法高亮呢？

![image](https://user-images.githubusercontent.com/1415488/87870641-04983880-c9e5-11ea-848f-60cbbd8cc790.png)

![image](https://user-images.githubusercontent.com/1415488/87870649-14b01800-c9e5-11ea-8c78-7fdedcf0cac2.png)

看看人家提问是多么认真：https://github.com/go-rod/rod/issues/124#issuecomment-659250833

**Comment by ysmood** [comment]
![image](https://user-images.githubusercontent.com/1415488/87870724-a7e94d80-c9e5-11ea-9647-9efa51a5a24b.png)

你可以使用这个编辑按钮，修改提交过的代码

**Comment by ysmood** [comment]
我之所以提出这些要求是希望未来有人遇到同样问题可以轻松通过阅读你的代码而理解和处理问题。

**Comment by zjlx** [comment]
> 我之所以提出这些要求是希望未来有人遇到同样问题可以轻松通过阅读你的代码而理解和处理问题。

我上面提交了关键代码，你非要完整代码，完整代码你觉得import不重要，但是import我用了第三方库的json解析和类型转换，如果我就说gjson你知道是gjson这个库还是goframe下面的gjson这个库呢。

**Comment by ysmood** [comment]
完整的可复现问题的最小代码，这是基本礼仪。注意“最小”两个字。比如下图这些无关紧要的 Set，去掉很多也不影响结果：

<img width="630" alt="Screen Shot 2020-07-19 at 21 28 46" src="https://user-images.githubusercontent.com/1415488/87874692-d75c8200-ca06-11ea-9fc9-2c3fe024969f.png">

**Comment by ysmood** [comment]
我们已经在问题模版里提及了 ”提问的智慧“ http://www.catb.org/~esr/faqs/smart-questions.html，如果你英文不好可以看中文版本的，网上有很多翻译版本。第一次我就当是你没仔细看，但是这已经不是你第一次来提问了，所以我觉得有必要强调一下，还望谅解。

提交之前你应该尽最大的可能用排除法去掉各种代码来尝试是否依然能复现你的问题，直到你发现多删除任何一行代码都将无法复现你的问题为止。这是基本提问的尝试。

**Comment by ysmood** [comment]
我自己向别人项目提交问题时，我都会反复调试自己的问题直到代码最小化，有时甚至能花上数小时，因为我知道开源不是慈善，作者花了很多宝贵的时间给了我们好用的库，我门应该多消耗自己的时间来让作者更轻松的帮助我们，也算是我们对作者的尊重和感激。

**Comment by ysmood** [comment]
> 完整代码你觉得import不重要

我哪有说这种化？如果你三方库是必要的复现元素那可以留下啊

**Comment by NormalPunch** [comment]
> > You can check the api with `http://httpbin.org/get`, it will return your cookies.
> 
> I'm going to use cookies to bypass user name and password. It's not about getting cookies

I mean you can set cookie to `httpbin.org`, it will tell you your real cookies.

If you do not know how to use mitm or devtools, this will be an easy way for debugging.

**Comment by zjlx** [comment]
> 我们已经在 issue 创建模版里提及了 ”提问的智慧“ http://www.catb.org/~esr/faqs/smart-questions.html ，如果你英文不好可以看中文版本的，网上有很多翻译版本。第一次我就当是你没仔细看，但是这已经不是你第一次来提问了，所以我觉得有必要强调一下，还望谅解。
> 
> 提交之前你应该尽最大的可能用排除法去掉各种代码来尝试是否依然能复现你的问题，直到你发现多删除任何一行代码都将无法复现你的问题为止。这是基本提问的礼节。

我明白了，我的问题。

**Comment by ysmood** [comment]
@zjlx @NormalPunch 为你提交了一个例子，你可以看看：https://github.com/go-rod/rod/blob/master/lib/examples/login-leetcode/main.go

**Comment by zjlx** [comment]
> @zjlx @NormalPunch 为你提交了一个例子，你可以看看：https://github.com/go-rod/rod/blob/master/lib/examples/login-leetcode/main.go

感谢回复，我以后提问会注意的，抱歉了。

**Comment by ysmood** [comment]
鉴于我们已经提供了可工作的例子，我暂时关闭这个问题，如果你还是有问题那就是别的原因了，请修改你的代码以功我们调试。
