### ISSUE TITLE
How to get / set checkbox value(s)?

### ISSUE THREAD

**Issue by AngangGuo** [go-rod/rod#150]
First, I want to thank you for this great project. 

Can you please add some examples on how to get/set checkbox value(s)?
I can't find the checkbox example from the [element testing file](https://github.com/go-rod/rod/blob/master/element_test.go).

thanks

**Comment by ysmood** [comment]
Because for human beings the checkbox is just the same as a normal button, so we don't have a unit test for it. You just click it. Here's some pseudo code might help you:

```go
func example() {
	el := page.Element(`[type="checkbox"]`)

	// check it if not checked
	if !el.Property("checked").Bool() {
		el.Click()
	}
}
```

Pretty straight forward isn't it?

**Comment by AngangGuo** [comment]
I mistakenly used `el.Attribute("checked"))` and it always get "<nil>". 
Your example will clarify it.
Thanks for your great work!

**Comment by ysmood** [comment]
https://stackoverflow.com/questions/6003819/what-is-the-difference-between-properties-and-attributes-in-html

This might help you. It's not the knowledge of rod, actually the old knowledge of DOM 😂

**Comment by ysmood** [comment]
I updated the doc for Property, hope it will reduce confusing for others:

https://github.com/go-rod/rod/blob/18822ff933a224fcfe61cd139de9dbb32a0d55d9/sugar.go#L560-L567

**Comment by AngangGuo** [comment]
You are not only a great programmer, but also a great teacher!
We can learn a lot from you. :-)
Thanks.
