### ISSUE TITLE
Add a helper method to easily hover over elements around the page

### ISSUE THREAD

**Issue by Hamzantal** [go-rod/rod#151]
**Is your feature request related to a problem? Please describe.**
Description of what you want to solve.
This can be important when visiting websites where navbars or sidebars show elements on hover events, and so adding such a feature can be helpful.

**Describe the solution you'd like**
Description of what you want to happen.
```
x, y = el.Box()
page.Mouse.Move(x, y)
```
Something along the lines of this.

**Comment by ysmood** [comment]
If you want to help implement it, you can use this private function to get the center point to hover: https://github.com/go-rod/rod/blob/498d159e3fb428ac9c1a4eedaaf1d7cc2412469f/element.go#L115
