### ISSUE TITLE
Add doc for setting the write buffer size of websocket

### ISSUE THREAD

**Issue by ysmood** [go-rod/rod#153]
Rod allows you to choose whatever WebSocket lib you want to use. Therefore you certainly can set whatever buffer size you want. But we don't have a doc for it yet.

The origin issue is here: https://bugs.chromium.org/p/chromium/issues/detail?id=1069431

Here's the default WebSocket:

https://github.com/go-rod/rod/blob/498d159e3fb428ac9c1a4eedaaf1d7cc2412469f/lib/cdp/websocket.go#L10-L20

@zema1 You might be interested in it.

**Comment by zema1** [comment]
Wow, That's very useful. This saves me great effort!  Thanks.

**Comment by ysmood** [comment]
@zema1 Here's the example code to set it to 10MB:

```go
package main

import (
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/cdp"
	"github.com/go-rod/rod/lib/launcher"
)

func main() {
	u := launcher.New().Launch()
	ws := cdp.NewDefaultWsClient()
	ws.WriteBufferSize = 10 * 1024 * 1024 // 10MB
	client := cdp.New(u).Websocket(ws)

	browser := rod.New().Client(client).Connect()

	browser.Page("")
}
```

**Comment by ysmood** [comment]
Fixed in https://github.com/go-rod/rod/commit/55e9433cad2b4251e706bbb4d062b5a440f4335c
