### ISSUE TITLE
有没有元素获取完整 xpath 或者 csspath 的方法

### ISSUE THREAD

**Issue by botsphp** [go-rod/rod#155]
谢谢

**Comment by ysmood** [comment]
和 #81 重复了

**Comment by ysmood** [comment]
能讲讲你为什么需要这个功能吗？这样有助于我们的设计

**Comment by botsphp** [comment]
目前主要是爬虫方面的运用场景，现在只知道最终元素，比如 H1，或者 id="content"，想知道元素的完整路径，方便查找最近父级下其它元素。

**Comment by ysmood** [comment]
@botsphp 你可以直接获取啊, `el.Parent()`, `el.Parents()`, `el.Previous()` 或者 `el.Next()` 这么多函数你没用过吗？

**Comment by ysmood** [comment]
如果你能提出更好的需求，我们可以从新开启这个issue，我先关闭了。
