### ISSUE TITLE
Get the default User-Agent of headless, and modify `HeadlessChrome` to `Chrome`

### ISSUE THREAD

**Issue by NormalPunch** [go-rod/rod#158]
As @ysmood  said, `page.Eval("() => navigator. userAgent").String()` will failed in the docker. 

Try to find the reason and a way without any request.

[Browser.getVersion](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-getVersion)

**Comment by ysmood** [comment]
Related implementation: https://github.com/berstend/puppeteer-extra/pull/104/files#diff-98975a3d66a1aabaea69849482c9ea4eR57-R60

**Comment by ysmood** [comment]
fixed in https://github.com/go-rod/bypass/pull/9
