### ISSUE TITLE
How to disable image and video medias

### ISSUE THREAD

**Issue by botsphp** [go-rod/rod#160]
How to disable image and video medias (img, mp4) when use Rod as a crawler.

**Comment by ysmood** [comment]
You can use Hijack API to hijack media requests and return whatever you want.

https://github.com/go-rod/rod/blob/498d159e3fb428ac9c1a4eedaaf1d7cc2412469f/examples_test.go#L344-L376

**Comment by botsphp** [comment]
@ysmood Pretty cool, thanks.

**Comment by ysmood** [comment]
For more details, read the unit tests for hijack:

https://github.com/go-rod/rod/blob/master/hijack_test.go
