### ISSUE TITLE
Elements select error

### ISSUE THREAD

**Issue by r6c** [go-rod/rod#163]
**Rod Version:** latest

when i run the selector in chrome console, it works.
![image](https://user-images.githubusercontent.com/45527749/88623564-cc28e680-d0d7-11ea-9187-a50774739b08.png)

but when i try to get it in go-rod, it's return nothing
![image](https://user-images.githubusercontent.com/45527749/88623660-05f9ed00-d0d8-11ea-8ef8-ac4d4c154a76.png)
![image](https://user-images.githubusercontent.com/45527749/88623685-127e4580-d0d8-11ea-935c-31596e16e9ac.png)

**Comment by ysmood** [comment]
Can you provide minimal code for us to reproduce your issue?

**Comment by ysmood** [comment]
`WaitLoad` doesn't guarantee the elements are loaded. Please read the doc of `Elements`, it doesn't do the retry and polling for you.

**Comment by ysmood** [comment]
If you want `Elements` to support auto-retry, you can raise an issue and share it with others, let everyone decide how the API should work.

**Comment by ysmood** [comment]
Also please learn how to ask questions:

[Don't rush to claim that you have found a bug.](http://www.catb.org/~esr/faqs/smart-questions.html#idm368)
