### ISSUE TITLE
请问如何获取一组text

### ISSUE THREAD

**Issue by 914795561** [go-rod/rod#165]
请问如何获取一组text，比如名称列表

**Comment by Abin01** [comment]
例子里有

**Comment by 914795561** [comment]
> 例子里有

哪个例子？在哪个文件？

**Comment by 914795561** [comment]
> 例子里有

我翻了一下，并没有发现有这样的例子

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/tree/master/lib/examples/compare-chromedp

这里有个叫 logic 的例子就是了。

**Comment by 914795561** [comment]
> https://github.com/go-rod/rod/tree/master/lib/examples/compare-chromedp
> 
> 这里有个叫 logic 的例子就是了。

谢谢
