### ISSUE TITLE
Propose a better way to handle errors for function chaining

### ISSUE THREAD

**Issue by ysmood** [go-rod/rod#166]
Currently, we are using panic to break the chain, it's a fail-fast style. The main issue of it is that we have to use `recover` to catch the error.

My draft proposal:

```go
type Chainable interface {
    // Use it to get the current error
    Err() error
    
    // Every method of Chainable should check it at the beginning and return if it's true
    HasErr() bool
}
```

Some pseudo-code to express how it feels like.

Chain version will still feel similar with the panic version:

```go
func main() {
    txt, err := page.Element("p").Click().Text()
    if err != nil {
        // ...
    }

    // we will keep the panic version, but use the same naming convention as std libs
    // https://golang.org/pkg/regexp/#MustCompile
    txt = page.Element("p").Click().MustText()
}
```

But the breakdown version will look like this:

```go
func main() {
    el := page.Element("p")
    if el.HasErr() {
        panic(el.Err()) // handle err, such as panic
    }

    el.Click()
    if el.HasErr() {
        // ...
    }

    txt, err := el.Text()
    if err != nil {
        // ...
    }
}
```

This style is like the Maybe monad in Haskell.

Some questions I want to discuss:

- Is there any popular project using this implementation? [GORM](https://github.com/go-gorm/gorm) (maybe we can learn more tricks about it)
- What're the drawbacks when using it?
- How to handling race condition of the error?

The original idea came from here:

https://www.reddit.com/r/golang/comments/i03nte/rod_a_simpler_way_to_drive_headless_browser/fzpj2bo?utm_source=share&utm_medium=web2x

<img width="660" alt="Screen Shot 2020-07-30 at 18 18 02" src="https://user-images.githubusercontent.com/1415488/88905242-0ab5d100-d291-11ea-82f3-0241f410c246.png">

**Comment by ysmood** [comment]
One main problem of this design is, users can forget to handle the errors, such as forget to check `err := el.Err()`.

Usually, we can use go tools to link our code and statically report unhandled errors: https://github.com/kisielk/errcheck.

The current panic version doesn't have this issue, since it will panic if you don't handle it.

**Comment by ysmood** [comment]
@tmc what do you think?

**Comment by rajender** [comment]
Need to think about this. But we should also look at functional options for this.

https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis
https://www.calhoun.io/using-functional-options-instead-of-method-chaining-in-go/

**Comment by ysmood** [comment]
> https://www.calhoun.io/using-functional-options-instead-of-method-chaining-in-go/
> functional options

This is the main reason I don't want to use chromedp, it will definitely becoming abuse of interface after we adding a lot of options. It's hard to jump into the source code and understand how it works. Also, the leveled IDE type-suggestion will become useless. 

Currently, GORM seems like a good example: http://gorm.io/docs/error_handling.html#content-inner

**Comment by ysmood** [comment]
Another main problem is race condition:

```go
go el.Click()
go el.Click()
```

They will race to read and write the shared err on the `el`.

**Comment by arp242** [comment]
> Solution 2: always return a new chainable with a new err instance.

I wrote a logging library which does this; it's probably easiest to show an example how it works:

	l := zlog.Module("dashboard")
	[..expensive stuff]

	l = l.Since("totals")
	[..expensive stuff]

	l = l.Since("locations")
	[..]

	l.FieldsSince().Print()

The `Since()` records the current time since the last `Since()` call, and it's a
nice/simple way to get some basic performance metrics in your terminal/logs:

	dashboard           17ms  totals
	dashboard          120ms  locations
	dashboard          121ms  toprefs
	dashboard          121ms  systems
	dashboard          121ms  browsers
	dashboard          126ms  totalpages
	dashboard          126ms  max
	dashboard          147ms  sizes
	dashboard          170ms  pages

The problem is that I sometimes do:

	l.Since("foo")

And then wonder why it doesn't work – the reason being that I forgot to re-assign the new log entry. There's a few other methods like this too; I found it all rather error-prone and awkward, and I'll probably change it to modify the log entry *and* return it.

I don't really have any opinions on what the best approach is for this project as I haven't looked at it much; just something to consider maybe.

**Comment by ysmood** [comment]
I think the final design will be somthing like this: https://github.com/ysmood/goc/blob/master/main_test.go

**Comment by ysmood** [comment]
After working on the d79f2915659ff99b9726de9c707b72792bff9a28 branch for several weeks, I find out chainable is not practical for Golang. For example the `Page.Has(string) (bool, error)` function, it's simply hard to make the if-else chainable. If we want to make the chainable thread-safe, we have to always return a clone of the chainable, and it's very easy to forget to reassign the clone, such as the code below is actually wrong:

```go
page.Element(`#a`).Click()

page.Element(`#b`).Click()
```

You have to code it like below:

```go
page = page.Element(`#a`).Click()

page.Element(`#b`).Click()
```

We just leave a hell of error handling then enter another hell. The problem is Golang itself, efforts try to get around it is simply waste of time. So I'm closing this issue for now. As long as users can use the code style they want I think it's OK. Once someone has a better solution, we can reopen it.
