### ISSUE TITLE
Overlay Problem?

### ISSUE THREAD

**Issue by AngangGuo** [go-rod/rod#168]
I'm not sure how to use the overlay function correctly. I have the following program and two questions about the overlay:

1. The following code show the overlay effect, but the text message is under the rectangle box, not above it. Is it correct?
 
2. If I comment out the `time.Sleep(5*time.Second)` under `wait()`. the rectangle box and message doesn't show out. Is this a bug?

```
func main() {
	url := launcher.New().
		Headless(false).
		//Devtools(true).
		Launch()
	browser := rod.New().ControlURL(url).Connect()
	defer browser.Close()
	page:=browser.Page("")

	pageURL := `https://www.github.com`
	wait:=page.WaitRequestIdle()
	page1 := browser.Page(pageURL).WindowNormal()
	wait()
	// Show Overlay
	time.Sleep(5*time.Second)

	cancel:=page1.Overlay(0,0,150,150,"Hello, World!")
	time.Sleep(20*time.Second)
	cancel()

}
```

Thanks.

![Overlay](https://user-images.githubusercontent.com/5448794/88954049-a540f080-d24e-11ea-8292-b24efb7dab9d.PNG)

**Comment by ysmood** [comment]
> The following code show the overlay effect, but the text message is under the rectangle box, not above it. Is it correct?

It's by design, the logic is here so that you can always see the message:

https://github.com/go-rod/rod/blob/bbedc15126890b65017c02395dd88cb61b6aa9ff/lib/assets/helper.js#L134-L139

> If I comment out the time.Sleep(5*time.Second) under wait(). the rectangle box and message doesn't show out. Is this a bug?

![image](https://user-images.githubusercontent.com/1415488/88956555-7b341080-d2d8-11ea-8d9e-6d1b7ace6e32.png)

Not a bug, you name the returned function `cancel`, actually if you look at the doc of it, it's called `remove` which will remove the overlay when you call it. You don't see it because you remove it too quickly, your eyes can't catch it.

**Comment by ysmood** [comment]
Also, you need to make sure the page is rendered before you use it, or you won't be able to see it at all. It's a dev-helper function, it's not designed for production use.

Better to change `page1 := browser.Page(pageURL).WindowNormal()` to `page1 := browser.Page(pageURL).WindowNormal().Element("body")` to wait until the body is rendered.

**Comment by AngangGuo** [comment]
Thanks for your answer. I've updated the code below. 
The layout doesn't show out even if I wait for 60 seconds AFTER creating the overlay.
It only shows out if I wait BEFORE creating the overlay.

Can you give me an example on how to properly use this overlay function?

```
func main() {
	url := launcher.New().
		Headless(false).
		Launch()
	browser := rod.New().ControlURL(url).Connect()
	defer browser.Close()

	pageURL := `https://www.google.com`
	page := browser.Page(pageURL).WindowNormal()

	// Before creating overlay effect
	// time.Sleep(5*time.Second)

	remove:=page.Overlay(0,0,150,150,"Hello, World!")
	time.Sleep(60*time.Second)
	remove()
}
```

**Comment by ysmood** [comment]
[Describe the goal, not the step.](http://www.catb.org/~esr/faqs/smart-questions.html#goal)

Can you tell us what exactly you want to complete in a real project?

```go
page := browser.Page(pageURL).WindowNormal().Element("body").WaitVisible()
```

Normally you show overlay to debug, it's meaningless if there's nothing on the page. For example, you wait for a button to show up then put an overlay above it.

**Comment by ysmood** [comment]
As I showed you in https://github.com/go-rod/rod/issues/168#issuecomment-666561864, the overlay is just some random js code injecting a div into the page, the page has its own js, it can remove it at its will.

**Comment by ysmood** [comment]
You have to wait for the page is stable before manipulating it. A lot of websites' js will remove everything when rendering the html.

**Comment by AngangGuo** [comment]
Understand. Not any practical usage at the moment. 
Just want to try every rod function to see how it works.

I want to use Rod automatic checking data on our production web page. 
If found any data problem I may use overlay to show the area with message explaining the problem and create a screenshot, then email the screenshot to associate for them to fix it.

**Comment by ysmood** [comment]
Cool, it will be great if you can share your feedback when you implementing it. Smoke testing is one thing I want to use to, it will be great if you can open source your project and share it with everyone.
