### ISSUE TITLE
Click dynamic HTML element panic - Node is detached from document

### ISSUE THREAD

**Issue by simicn** [go-rod/rod#170]
**Rod Version:** v0.49.1

## To Reproduce

`page` has some *dynamic* div with class `btn`.

```
<div class="container">
  <div class="btn>btn1</div>
  <div class="btn>btn2</div>
</div> 
```

Click like follow: 
```
page.Element(".btn").WaitVisible().Click()
```
or
```
btns := page.Elements(".btn")
btns[0].Click()
```
panic

## Expected behavior
click the first `.btn` div.

## Actual result

```
panic: {"code":-32000,"message":"Node is detached from document","data":""}
```

**Comment by NormalPunch** [comment]
try `WaitStable`

**Comment by simicn** [comment]
> try `WaitStable`

It doesn't work.

**Comment by ysmood** [comment]
I can't reproduce your issue. Can you provide minimal code for us to reproduce your issue?

**Comment by ysmood** [comment]
Sounds like a logic issue. The Element is just a reference. If others do something like this to your reference:

```
type A struct {
    B int
}

a := &A{10}

a = nil

fmt.Println(a.B)
``` 

It will throw error like `Node is detached from document`, it means some code on the page has removed the element.

**Comment by ysmood** [comment]
You can also check this issue, might help you: https://github.com/puppeteer/puppeteer/issues/3496

**Comment by simicn** [comment]
> I can't reproduce your issue. Can you provide minimal code for us to reproduce your issue?

```
package main

import (
	"flag"
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/go-rod/rod"
        "github.com/go-rod/rod/lib/launcher"
	"github.com/ysmood/kit"
)

var flagPort = flag.Int("port", 8544, "port")

func main() {
	flag.Parse()

	// run server
	go testServer(fmt.Sprintf(":%d", *flagPort))

	url := launcher.New().
		Headless(false).
		Devtools(true).
		Launch()

	browser := rod.New().
		Timeout(time.Minute).
		ControlURL(url).
		Trace(false).
		Slowmotion(2 * time.Second).
		Connect()
	defer browser.Close()

	page := browser.Page("")

	page.Navigate(fmt.Sprintf("http://localhost:%d", *flagPort))

	time.Sleep(time.Second * 3)

	for i := 0; i < 100; i++ {
		// output: panic: {"code":-32000,"message":"Node is detached from document","data":""}
		page.Element(".btn").WaitVisible().Click()
		log.Printf(">>>>>>>>>>>>>>>>>>>> CLICK %v", i)
	}
}

func testServer(addr string) {
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(res http.ResponseWriter, _ *http.Request) {
		kit.E(fmt.Fprint(res, indexHTML))
	})
	kit.E(http.ListenAndServe(addr, mux))
}

const indexHTML = `<!doctype html>
<html>
<head>
  <title>example</title>
  <script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
</head>
<body>
  <div class="btn-container">
    <div class="btn">
      button 1
    </div>
  </div>
  <div class="btn-container">
    <div class="btn">
      button 2
    </div>
  </div>
</body>
<script>
$(document).ready(function(){
    setInterval(function(){ 
		$('.btn-container .btn').detach();
        $('.btn-container').append('<div class="btn"><p>dynamic button</p></div>');
	}, 300)
});
</script>
</html>`
```

**Comment by ysmood** [comment]
You don't need golang, just js can make this issue happen. You are racing a dynamic element. It's exactly the problem I mentioned in https://github.com/go-rod/rod/issues/170#issuecomment-667547940

**Comment by simicn** [comment]
> You don't need golang, just js can make this issue happen. You are racing on a dynamic element. It's exactly the problem I mentioned in [#170 (comment)](https://github.com/go-rod/rod/issues/170#issuecomment-667547940)

Clicking on a dynamic element is my purpose.
Is there any way to achieve it?

**Comment by ysmood** [comment]
You can use the trick below:

```
page.Eval(`$('.btn-container .btn').click()`)
```

Because v8 is single-threaded, so it will work.

**Comment by ysmood** [comment]
Whenever you have to solve this kind of problem it means you are wrongly designing your solution. Better to review what you want to achieve and check if there's another way to do it without data racing.

**Comment by ysmood** [comment]
[Describe the goal, not the step.](http://www.catb.org/~esr/faqs/smart-questions.html#goal)

**Comment by simicn** [comment]
It works. Thanks @ysmood .

**Comment by JavascriptMick** [comment]
for whatever reason, I needed todo this...
```
page.MustEval(`() => {document.getElementById("some_id").click();}`)
```
