### ISSUE TITLE
Does leakless support ARMv6?

### ISSUE THREAD

**Issue by pyed** [go-rod/rod#171]
I have a use case for `Rod` on a RaspberryPi 2, which uses `ARMv6`, when I tried to run my Go binary that has been cross-compiled for `ARMv6`, I got the following error
```
panic: fork/exec /tmp/leakless-v0.5.4/leakless: exec format error

goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.E(...)
        /Users/pyed/go/src/github.com/go-rod/rod/lib/utils/main.go:7
github.com/go-rod/rod.(*Browser).Connect(0x246cff0, 0x198e0)
        /Users/pyed/go/src/github.com/go-rod/rod/sugar.go:18 +0x9c
main.main()
        /Users/pyed/src/proj/main.go:18 +0x54
```
of course, that `leakless` bin is:
```
leakless: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked
```
I was baffled when I saw that `leakless` repo is all Go code, until I noticed that they're just binary files inside `.go` for each operating system, which means `leakless` is probably written in C and is close sourced ?!

**Comment by ysmood** [comment]
sure it's not C, you can understand how it works by reading its CI config: https://github.com/ysmood/leakless/blob/master/.github/workflows/go.yml

**Comment by ysmood** [comment]
You can make a PR to add a binary type by adding a Go build flag. But for ARM, you have to watch out the CPU architecture when you build it.

**Comment by ysmood** [comment]
The source code for the binaries are here: https://github.com/ysmood/leakless/tree/master/cmd/leakless

**Comment by ysmood** [comment]
Also, you can disable leakless on ARM, so you don't have to use it at all, it's just a good to have feature, not a must to have.

**Comment by pyed** [comment]
![image](https://media.giphy.com/media/kaq6GnxDlJaBq/giphy.gif)
Thank you for making Rod.

**Comment by ysmood** [comment]
please try `v0.49.2`

**Comment by pyed** [comment]
Sadly I can't test that, I fried my Pi yesterday and it died  ☹️ all it took was a splash of water.

nevertheless, Thank you for making Rod better 👍

**Comment by ydcool** [comment]
Tried with v.0.59.0, still go this error.

```
panic: fork/exec /tmp/leakless-v0.5.0/leakless: exec format error

goroutine 1 [running]:
github.com/ysmood/kit/pkg/utils.E(0x40004641c0, 0x1, 0x1, 0xbde5a0, 0x400078a150, 0x40003e1410)
	/root/dominic/auto-office/vendor/github.com/ysmood/kit/pkg/utils/utils.go:33 +0xa0
github.com/go-rod/rod/lib/launcher.(*Launcher).Launch(0x40003964e0, 0x40003e1401, 0x40003964e0)
	/root/dominic/auto-office/vendor/github.com/go-rod/rod/lib/launcher/launcher.go:230 +0xa8
```

```
uname -a
Linux master1 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:28:13 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux 
```

**Comment by ysmood** [comment]
It works fine on my android phone: https://github.com/go-rod/rod/issues/203

Can you provide the full steps to reproduce the issue?

**Comment by ysmood** [comment]
> panic: fork/exec /tmp/leakless-v0.5.0/leakless: exec format error

v.0.59.0 is using leakless v0.5.7, your output is v0.5.0. Can you double-check your config?

**Comment by ydcool** [comment]
> > panic: fork/exec /tmp/leakless-v0.5.0/leakless: exec format error
> 
> v.0.59.0 is using leakless v0.5.7, your output is v0.5.0. Can you double-check your config?

Yes I was noticed that mismatched version but have no idea why for now. All I have done is `git checkout v0.59.0` and run docker build. I'll check it again.
