### ISSUE TITLE
How to use cookies of default user

### ISSUE THREAD

**Issue by infixint943** [go-rod/rod#173]
How to configure rod to automatically point to `userDataDir`?

**Comment by ysmood** [comment]
use-rod-like-chrome-extension

https://github.com/go-rod/rod/blob/899b00ac27e25786f0a6820a35164436b24bf21c/lib/examples/use-rod-like-chrome-extension/main.go#L8-L18

**Comment by infixint943** [comment]
How do I run this headless?
Using `.headless(false)` doesn't use the current user session

**Comment by ysmood** [comment]
`url := launcher.NewUserMode().Launch().Headless(false)`

**Comment by ysmood** [comment]
Better to check this doc: https://pkg.go.dev/github.com/go-rod/rod@v0.49.3/lib/launcher?tab=doc#Launcher.UserDataDir

**Comment by ysmood** [comment]
Chrome only allows you to choose `headless` or not when launching. You can't switch from headless to head mode on the fly. So whenever you do it you have to close your browser completely, or it won't take effect. On Windows or Mac you should see the application icon on the taskbar, shutdown it before you switch mode.

**Comment by infixint943** [comment]
> Better to check the doc of `Launcher.UserDataDir`: https://pkg.go.dev/github.com/go-rod/rod@v0.49.3/lib/launcher?tab=doc#Launcher.UserDataDir
> 
> `url := launcher.New().UserDataDir("any-dir-you-like").Launch()`

I tried this. However it doesn't work.
I set the dir path to `/home/<username>/.config/google-chrome/Default` as specified in `chrome://version`. However, it doesn't make use of my current session. I tried taking a screenshot of github, and it shows the login page, instead of my profile.

**Comment by ysmood** [comment]
Are you sure you have closed all chrome instances?

**Comment by ysmood** [comment]
Can you paste the code you use?

**Comment by infixint943** [comment]
Sure
```
package main

import (
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
)

func main() {
	url := launcher.New().UserDataDir("/home/gevacrt/.config/google-chrome/").Launch()
	browser := rod.New().ControlURL(url).Connect()

	browser.Page("https://github.com").WaitLoad().Screenshot("test.png")
}
```

**Comment by ysmood** [comment]
I think it should be `/home/gevacrt/.config/google-chrome`, can you remove the `/Default` and try again?

**Comment by infixint943** [comment]
Nope, I tried removing `/Default`. I still get the same image -
![image](https://user-images.githubusercontent.com/45997896/89516589-40f5d200-d7f6-11ea-809d-fcacadcdbb1c.png)

**Comment by ysmood** [comment]
Can you join our discord chat room? I need more info.

**Comment by infixint943** [comment]
Okay, could you please give me the link?

**Comment by ysmood** [comment]
The root readme has it.

**Comment by ysmood** [comment]
Seems like it's a known issue of Chrome, you can't share things like cookies between headless and head mode even they use the same user-data-dir:

https://github.com/puppeteer/puppeteer/issues/921

**Comment by ysmood** [comment]
```go
func main() {
	url := launcher.New().Headless(false).UserDataDir("tmp/login").Launch()

	browser := rod.New().ControlURL(url).Connect()

	browser.Page("http://www.html-kit.com/tools/cookietester/").WaitLoad().Screenshot("")

        select {}
}
```

This code works fine for me. I can preserve the cookie between head mode and headless mode.

First, run it with `.Headless(false)`, click the button to set a cookie on that website. Then run it with `.Headless(true)`, you will find out the screenshot will show you the one you set before.

I think why you fail to reuse the cookie might because your website is using [session cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie), it will be removed when you close the browser.

**Comment by SantoshSah** [comment]
@ysmood Thank you for go-rod package. `NewUserMode()` works as expected in head mode by setting `Headless(false)`.  Any idea why `NewUserMode()` does not work in headless mode? I am using `NewUserMode()` like you have mentioned in [this comment.](https://github.com/go-rod/rod/issues/173#issuecomment-669788842).

**Comment by ysmood** [comment]
@SantoshSah Yes, it's a limitation of Chromium, it will use another profile for the headless mode, I think it's because headless is not the current system user anything more.xa

**Comment by SantoshSah** [comment]
Thank you for your answer.
