### ISSUE TITLE
some code doas not work on windows.

### ISSUE THREAD

**Issue by bashery** [go-rod/rod#174]
**Rod Version:** v0.49.3

this line  ```page.Element(`#rso > div:nth-child(1) > div > div > div.r > a > h3`).Click()```
works on Linux. But it does not work on Windows.It Cannot select item.

The same problem with:
```page.ElementX(`//*[@id="rso"]/div[1]/div/div/div[1]/a/h3`).Click()```
works on linux. but not windows

**Comment by ysmood** [comment]
[Don't rush to claim that you have found a bug.](http://www.catb.org/~esr/faqs/smart-questions.html#idm368)

Can you provide minimal code for us to reproduce your issue?

**Comment by bashery** [comment]
Yes sir.
Purpose: search for a specific site. And enter it.
func main() {
      url := launcher.New().Headless(false).Launch()
      page := rod.New().ControlURL(url).Connect().Trace(true). 
Timeout(5 * time.Second).Page("https://google.com")  
                                                               
    page.Element(`input[name=q]`).WaitVisible().Input("chromedp").Press(input.Enter) 
     
     page.Element(`#rso > div:nth-child(1) > div > div > div.r > a > h3`).Click()
     time.Sleep(time.Second * 15)
 
}

**Comment by ysmood** [comment]
I copied the css selector from windows:

<img width="1259" alt="Screen Shot 2020-08-07 at 15 01 21" src="https://user-images.githubusercontent.com/1415488/89614187-e1afc480-d8be-11ea-95d3-f6a3de7da1cc.png">

The result is `#rso > div:nth-child(1) > div > div.r > a > h3`

The one you copied from linux is `#rso > div:nth-child(1) > div > div > div.r > a > h3`.

They are different, you can't select something that doesn't exist.

**Comment by ysmood** [comment]
This is a very simple bug because you don't think carefully, hope next time you can find out it by yourself.

**Comment by bashery** [comment]
Thank you so much. Sorry For Disturb. Yes, I will be more attentive next time, and I will stick to your advice.
