### ISSUE TITLE
Method to get the selector of element

### ISSUE THREAD

**Issue by thanhps42** [go-rod/rod#175]
**Is your feature request related to a problem? Please describe.**
Method to get the selector of element. I know we have Matches method, but imaging if we have many cases and we can get the selector of element so we can write go code with "switch case" instead of "if else".

**Describe the solution you'd like**
```go
el := page.Element(
  //case 1
  "#login-failed",

  //case 2
  "#blocked",

  //case 3
  "#logout",
)

switch el.Selector() {
case "#login-failed":
  //handle login failed
case "#blocked":
  //handle login blocked
case "#logout":
  //handle login success
}
```

**Comment by ysmood** [comment]
Now, rod supports this:

```go
el := page.Element(
  //case 1
  "#login-failed",

  //case 2
  "#blocked",

  //case 3
  "#logout",
)

switch el.Eval(`this.classList[0]`) {
case "#login-failed":
  //handle login failed
case "#blocked":
  //handle login blocked
case "#logout":
  //handle login success
}
```

**Comment by thanhps42** [comment]
@ysmood classList just return class attribute, don't return id (and others attribute).

**Comment by ysmood** [comment]
So you mean we cache the previous selector?

We have many ways to select element, `page.Element`, `page.ElementX`, `page.ElementMatches`, `page.Search`, etc.

It's not easy to design. Any ideas?

**Comment by thanhps42** [comment]
Yes, I mean we need cache the selector. But if it break your design then no need, I can use `el.Matches` :D

**Comment by ysmood** [comment]
We can keep it open, I'm ok to refactor all the code of `query.go`, just need some good ideas to do it. Currently, it's hard for me. Maybe someone can give us inspiration in the future.

**Comment by ysmood** [comment]
Check the newly added `Page.Race`:

https://github.com/go-rod/rod/blob/92ecd1fce227a687fabaf3acafcca811323d982b/examples_test.go#L122-L128
