### ISSUE TITLE
UserDataDir doesn't reuse the saved session cookies if "password-store=basic" is enabled

### ISSUE THREAD

**Issue by infixint943** [go-rod/rod#177]
**Rod Version:** v0.49.4

## To Reproduce
- on linux
- Manually open your local chrome, and login to github.
- Run the below code to use local session cookies (with go-rod) in headless mode.
```
func main() {
	url := launcher.New().UserDataDir("/home/<username>/.config/google-chrome").
		Headless(false).Launch()
	bs := rod.New().ControlURL(url).Connect()

	bs.Page("https://github.com")
}
```
## Expected behavior
Current user's profile page should be visible.

## Actual result
Local session cookies have somehow got corrupted, logging me out of github (most other sites too!).

## Workaround
In [launcher.go](https://github.com/go-rod/rod/blob/master/lib/launcher/launcher.go#L79) removing the `password-store=basic` flag does the trick and allows to use the local session. See https://github.com/puppeteer/puppeteer/issues/1316#issuecomment-384813318

**Comment by ysmood** [comment]
Another workaround is to save-load cookies like this example: https://github.com/go-rod/rod/blob/master/lib/examples/login-leetcode/main.go

**Comment by ysmood** [comment]
Currently, we can't do much about it, it's more like a design issue of chrome itself.

**Comment by infixint943** [comment]
But what is the requirement of that flag? Chrome automatically sets the encryption to use if none are provided. Isn't that a better option?

**Comment by infixint943** [comment]
I guess it's somewhat related to https://askubuntu.com/questions/31786/chrome-asks-for-password-to-unlock-keyring-on-startup

**Comment by ysmood** [comment]
Can you help us to research the side effect of launching without "password-store"?

**Comment by ysmood** [comment]
If the side effect is not that big, we can consider remove it.

Can raise a PR to help us remove it? I won't close it without a strong reason.

**Comment by ysmood** [comment]
Also you can use NewUserMode to launch browser without any overhead:

```go
func main() {
	url := launcher.NewUserMode().UserDataDir("/home/<username>/.config/google-chrome").
		Headless(false).Launch()
	bs := rod.New().ControlURL(url).Connect()

	bs.Page("https://github.com")
}
```

**Comment by infixint943** [comment]
> I realise that you can use `NewUserMode` to launch browser without any overhead:
> 
> ```go
> func main() {
> 	url := launcher.NewUserMode().UserDataDir("/home/<username>/.config/google-chrome").
> 		Headless(false).Launch()
> 	bs := rod.New().ControlURL(url).Connect()
> 
> 	bs.Page("https://github.com")
> }
> ```

Yes, it works great! I never knew headless mode was supported by `NewUserMode()`.

What is the difference between `.New()` and `.NewUserMode()`? Seems like not much apart from the flags.
> NewUserMode is a preset to enable reusing current user data. Useful for automation of personal browser. If you see any error, it may because you can't launch debug port for existing browser, the solution is to completely close the running browser. Unfortunately, there's no API for rod to tell it automatically yet.

Is there any obvious speed difference when running both modes in headless?
Also, shouldn't `NewUserMode()` automatically select the user-data-dir?

**Comment by ysmood** [comment]
`NewUserMode` is the same as `New`, just another option initializer, if you check their source code you will understand it immediately. I made the source code easy to read on purpose.

**Comment by infixint943** [comment]
> Is there any obvious speed difference when running both modes in headless?
> Also, shouldn't NewUserMode() automatically select the user-data-dir?

Any idea about this?
If there are are no much benefits, I suppose you can document this feature (bug?) somewhere.

I could add a PR to automatically select the user profile for `NewUserMode()` automatically.

**Comment by infixint943** [comment]
Ah, okay. I understood it. I suggest you rename it to `NewCustomMode()`, as the current name is very misleading and makes the user believe it selectes the current users profile

**Comment by infixint943** [comment]
I read a bit about `password-store` flag, and I suppose it's not required, as chrome automatically selects the password storage method to use. Removing the flag will prevent conflicts with different DE configurations

**Comment by ysmood** [comment]
> I suggest you rename it to NewCustomMode(), as the current name is very misleading and makes the user believe it selectes the current users profile

But it actually does selector the `current users profile` :joy:. If you don't specify the user-data-dir, the chrome will use current user's profile. That's why we have an example named "use-rod-like-chrome-extension", chrome extensions usually need the current user's profile to complete tasks.

> I read a bit about password-store flag, and I suppose it's not required, as chrome automatically selects the password storage method to use. Removing the flag will prevent conflicts with different DE configurations

It will be great if you can make a PR for it because if anyone got an issue from it they will find you from the commit message. You know more info about it than me.

**Comment by ysmood** [comment]
I personally use NewUserMode to automate some websites I visite a lot, such as auto click next page when I read posts.

**Comment by ysmood** [comment]
I used to spend a lot of time to name it, I actually renamed it several times before. It's very hard to name things like this.
If you think your special use case is very common, you can add a new initializer besides `New` and `NewUserMode`, we welcome PR.

**Comment by infixint943** [comment]
> > I suggest you rename it to NewCustomMode(), as the current name is very misleading and makes the user believe it selectes the current users profile
> 
> But it actually does selector the `current users profile` . If you don't specify the user-data-dir, chrome will use the current user's profile. That's why we have an example named "use-rod-like-chrome-extension", chrome extensions usually need the current user's profile to complete tasks.
> 
> > I read a bit about password-store flag, and I suppose it's not required, as chrome automatically selects the password storage method to use. Removing the flag will prevent conflicts with different DE configurations
> 
> It will be great if you can make a PR for it because if anyone got an issue from it they will find you from the commit message. You know more info about it than me.

Yes, that makes sense.
