### ISSUE TITLE
user-data-dir still exists after browser is closed

### ISSUE THREAD

**Issue by lu4p** [go-rod/rod#181]
**Rod Version:** v0.49.5

## To Reproduce

```go
package main

import (
	"fmt"
	"os"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
)

const tempdir = "tempdir"

func main() {
	_, err := os.Stat(tempdir)
	fmt.Println(err)
	demo()

	_, err = os.Stat(tempdir)
	fmt.Println(err)
}

func demo() {
	url := launcher.New().UserDataDir(tempdir).Launch()
	browser := rod.New().ControlURL(url).Connect().Trace(true)
	defer browser.Close()
	page := browser.Page("https://google.com")
	defer page.Close()
	page.WaitLoad()
}

```

Output:
```
stat tempdir: no such file or directory
<nil> # should be the same as above
```

## Expected behavior
Rod claims that it deletes the data dir when the browser is closed:
https://github.com/go-rod/rod/blob/44b9c7239bee6a02a590a1f22453087ee8900856/lib/launcher/proxy.go#L38

I expected the "tempdir" to get deleted after the browser is closed.

## Actual result

The tempdir still exists after calling close.

## How I found this
When using `lib/launcher.New()` to create the new browser the user-data-dir is randomized:
https://github.com/go-rod/rod/blob/37a628f131d417f0b83cc2f42da3b2664113bfeb/lib/launcher/launcher.go#L43
This means a new Directory is created for every created browser, because these are never cleaned up they can use up some significant amount of storage on long running programs (this is after a few days with multiple concurrent browsers, and regular browser restarts).

```
$ du -h rod
... [Redacted] ...
28K	rod/user-data/58a27be17dbf9ee1/Default/Local Storage
65M	rod/user-data/58a27be17dbf9ee1/Default
65M	rod/user-data/58a27be17dbf9ee1
4.1M	rod/user-data/baf0f3170e185ce9/BrowserMetrics
4.1M	rod/user-data/baf0f3170e185ce9
4.1M	rod/user-data/bec95cc2177dd64f/BrowserMetrics
4.1M	rod/user-data/bec95cc2177dd64f
66G	rod/user-data
66G	rod

```
These 66GB of data lead to my disk running out of storage:
```
$ df -h
Filesystem                   Size  Used Avail Use% Mounted on
...
/dev/mapper/server--vg-root  467G  443G     0 100% /
...
```
Which then leads to the program not being able to open any new browser instance:
```
/snap/chromium/1260/bin/desktop-launch: line 373: cannot create temp file for here-document: No spac>
[0810/130517.860904:WARNING:discardable_shared_memory_manager.cc(194)] Less than 64MB of free space >
[0810/130517.864102:FATAL:memory.cc(40)] Out of memory. size=131072
```

**Comment by ysmood** [comment]
[Don't rush to claim that you have found a bug.](http://www.catb.org/~esr/faqs/smart-questions.html#idm368)

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/44b9c7239bee6a02a590a1f22453087ee8900856/lib/launcher/proxy.go#L20-L21

The file you mentioned is `proxy.go`, have you ever thought about why it's called `proxy`?

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/44b9c7239bee6a02a590a1f22453087ee8900856/lib/launcher/proxy.go#L38-L39

The comment says "remote browser". You are not using remote browser mode so it's not removed.

**Comment by ysmood** [comment]
Rod uses the tmp dir of OS. Usually, the OS will remove the tmp dir after you restart your system. If you want to remove the dir, you can specify the dir and remove it by yourself:

```go
func demo() {
	url := launcher.New().UserDataDir(tempdir).Launch()
	defer os.RemoveAll(tempdir)
	...
}
```

**Comment by lu4p** [comment]
Ok, but I still believe that the tempdir should be removed by default, after the browser is closed.

**Comment by ysmood** [comment]
Sure, that's a good idea. Can you help us implement it with a PR?

**Comment by ysmood** [comment]
If you need help, go to the discord chat room, we will help you. I think puppeteer and chromedp don't remove them automatically.

**Comment by ysmood** [comment]
I usually use `docker run -p 9222:9222 rodorg/rod`, it doesn't leak tmpdir. I don't have a problem with it.

**Comment by lu4p** [comment]
> Sure, that's a good idea. Can you help us implement it with a PR?

Sure.

**Comment by roeniss** [comment]
Then `browser.close()` would not be enough to delete all temp data! Now I figure out why my tmp directory is up to 8Gb.

Then Is it Ok to do like this?
```
func myFunc() {
	// ...
    defer myBrowser.Close()
    defer myLauncher.Cleanup()	
    // ...
}
```
I don't have deep understanding about rod architecture, so I'm not sure whether those two action have no priority to each other.

**Comment by lu4p** [comment]
The other way around because defer is "first in last out".

```
​func myFunc() {
    // ..
    defer myLauncher.Cleanup()
    defer myBrowser.Close()
            
    // ...
}
```

**Comment by ysmood** [comment]
@roeniss In golang always try to put defer near the allocation line, that's the reason why it's "first in last out", for example:

```go
l := launcher.New()
u := l.MustLaunch()
defer l.Cleanup()

browser := rod.New().ControlURL(u).MustConnect()
defer browser.MustClose()
```

**Comment by roeniss** [comment]
@ysmood Just before I was stuck by `launcher.close()` because that function not proceed on here:
```golang
// ...in launcher.go

func (l *Launcher) Cleanup() {
	<-l.exit        // <----------- my code stuck at here

	dir, _ := l.Get("user-data-dir")
	_ = os.RemoveAll(dir)
}
```

then I read your comment and realized that my code is written like this (not like above!) :

```golang
//...
    defer myLauncher.Cleanup()
    defer myBrowser.Close()
// ... 
```

by just changing those position, everything works perfectly because [`defer` behaves like stack](https://tour.golang.org/flowcontrol/13). Like you said, `first in last out` is important rule. thanks for reminding me of that :)
