### ISSUE TITLE
How to get a Response/HTTP Status code from Browser

### ISSUE THREAD

**Issue by falnyr** [go-rod/rod#188]
Hi, I'm trying to implement logic around taking screenshots conditionally, only if the response's status is `HTTP 200 OK`.
I'd like to perform that in a single request via browser if possible. I looked into the `Browser.HijackRequests()` from the examples but I don't think I understand it fully to get it working.

Here's the code:
```go
func getScreenshot(url string) ([]byte, error) {
	client := launcher.NewRemote("ws://127.0.0.1:9222").Set("window-size", "1920,1080").Client()
	browser := rod.New().Client(client).Connect()
	defer browser.Close()

	router := browser.HijackRequests()
	defer router.Stop()

	// the execution hangs here
	router.Add("*", func(ctx *rod.Hijack) {
		fmt.Println(ctx.Response.StatusCode())
	})

	browser.DefaultViewport(&proto.EmulationSetDeviceMetricsOverride{
		Width:              1920,
		Height:             1080,
		Scale:              1,
	})

	page := browser.Page(url).Timeout(time.Second * 10)
	err := page.WaitLoadE(); if err != nil {
		return nil, err
	}

	return page.ScreenshotE(false, &proto.PageCaptureScreenshot{
		Format:  proto.PageCaptureScreenshotFormatJpeg,
		Quality: 70,
	})
}
```

Any ideas on how the logic could be implemented with the HTTP Status code? Thanks

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/307752428ef2ae3ca4c38b0a55562e4c72a9bdf9/examples_test.go#L352-L356

https://github.com/go-rod/rod/blob/307752428ef2ae3ca4c38b0a55562e4c72a9bdf9/hijack_test.go#L112-L114

Read the doc, follow the example code. It's pretty easy to know when removing which line will cause the hang.

**Comment by ysmood** [comment]
I think you don't need hijack. Network events will do the job:

```
	go page.EachEvent(func(e *proto.NetworkResponseReceived) {
		kit.Dump(e) // e contains HTTP status code
	})()
```

**Comment by ysmood** [comment]
@falnyr  A better solution may be: https://github.com/go-rod/rod/issues/213
