### ISSUE TITLE
Setting a proxy per page with Hijack API

### ISSUE THREAD

**Issue by SaulGDev** [go-rod/rod#189]
So as in the title, I want to hijack requests on every opened tab with proxy and close when it fails. I tried multiple things already and am stuck with this one for days.
``` golang
router := page.HijackRequests()
defer router.Stop()
router.Add("*", func(ctx *rod.Hijack) {
	px, _ := url.Parse("http://user:pass@1.2.3.4:8000")
	ctx.Request.SetClient(&http.Client{
		Transport: &http.Transport{
		Proxy: http.ProxyURL(px),
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
		Timeout: 30 * time.Second,
	})
	ctx.LoadResponse()
})
go router.Run()

**Comment by ysmood** [comment]
Can you describe a little about the error info?

**Comment by SaulGDev** [comment]
Page opens and instantly closes with this:  Error: [rod] navigation failed: net::ERR_ABORTED
With Set("proxy-server", "http://1.2.3.4:8000"). to launcher it works as intended. The error which I have sent is caused by resources  rejecting to load like: https://jsonip.org/favicon.ico

**Comment by ysmood** [comment]
I just tried the code below, works fine to me, the tool I use to proxy is `mitmproxy --proxyauth user:pass`.

```go
func Example_hijack_requests() {
	browser := rod.New().Timeout(time.Minute).Connect()
	defer browser.Close()

	router := browser.HijackRequests()
	defer router.Stop()

	router.Add("*", func(ctx *rod.Hijack) {
		px, _ := url.Parse("http://user:pass@localhost:8080")
		ctx.Request.SetClient(&http.Client{
			Transport: &http.Transport{
				Proxy:           http.ProxyURL(px),
				TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
			},
			Timeout: 30 * time.Second,
		})
		ctx.LoadResponse()
	})

	go router.Run()

	browser.Page("https://www.wikipedia.org/")

	kit.Pause()

	// Output:
	// Done
}
```

**Comment by ysmood** [comment]
if you call `defer router.Stop()` and still try to use proxy, you will get error like `{"code":-32000,"message":"Fetch domain is not enabled","data":""}`. Usually you never call `defer router.Stop()` before your program exits.

**Comment by SaulGDev** [comment]
Okay I resolved it with resty client like in code above but with "*" to router.Add I get recaptcha errors, when I changed it to "https://site.com/*" it changes ip across Incognito pages but I still get "[rod hijack err] {"code":-32000,"message":"Fetch domain is not enabled","data":""}" with every page

**Comment by bynf** [comment]
Hello,
ctx.Request.SetClient changed, you can get the similar function as like : https://github.com/go-rod/rod/blob/a6a9e89b71c86a5b0e28aa33bac08acfd1dce59a/hijack_test.go#L189
