### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by duolaAOA** [go-rod/rod#205]
**Rod Version:** v0.51.0

OS: MacOs 10.15.4
go version: 1.13.1

```go
page := browser.Timeout(10 * time.Second).MustPage("https://github.com")

time.Sleep(10 * time.Second)

page.MustElement("div")
```

Why I get this error:

```go
panic: context deadline exceeded

```

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/8db745a77c33e16c8f2f1b31c8815f8afbab375b/examples_test.go#L25-L27'

Seems like you misunderstand: 

> Timeout will be passed to all chained function calls.

All subsequent functions called will derive the parent context. In your case remove the `.Timeout(15 * time.Second)` should work.

**Comment by ysmood** [comment]
> Can I reduce the unrelated code to make the example minimal?
