### ISSUE TITLE
How can I add trusted url certificate in rod's docker image

### ISSUE THREAD

**Issue by Abin01** [go-rod/rod#206]
As  title

**Comment by Abin01** [comment]
#192

Rod Version:
github.com/go-rod/bypass v0.0.2
github.com/go-rod/rod v0.49.8

**Comment by ysmood** [comment]
The selected answer should work:

https://stackoverflow.com/questions/42292444/how-do-i-add-a-ca-root-certificate-inside-a-docker-image

**Comment by Abin01** [comment]
thanks
