### ISSUE TITLE
Reconnect to the same browser and use WaitRequestIdle will hang forever

### ISSUE THREAD

**Issue by panyanyany** [go-rod/rod#207]
**Rod Version:** v0.52.0

## To Reproduce

```go
func main() {
	u := launcher.New().Headless(false).RemoteDebuggingPort(8765).MustLaunch()
	b := rod.New().Timeout(30 * time.Second).ControlURL(u).MustConnect()

	page := b.MustPages()[0]
	nav(page)
	fmt.Println("1")
	nav(page)
	fmt.Println("2")
}

func nav(page *rod.Page) {
	wait := page.MustWaitRequestIdle()
	page.MustNavigate("https://www.taobao.com")
	wait()
}
```

```bash
go run ./main.go
go run ./main.go
```

## Expected behavior
```
1
2
1
2
```

What you expected to get.

## Actual result
```
1
2
1
panic: context deadline exceeded
```

**Comment by ysmood** [comment]
[Don't rush to claim that you have found a bug.](http://www.catb.org/~esr/faqs/smart-questions.html#idm368)

**Comment by ysmood** [comment]
你有看这个问题吗？ https://github.com/go-rod/rod/issues/205

**Comment by panyanyany** [comment]
> 你有看这个问题吗？ #205

看了，但没看懂。不过你这么一说，我结合你的意思，又懂了。原来这个 Timeout 跟 puppeteer.Launch 的 timeout 不是同一个意思啊。
那我要如何设置全局的 Timeout 呢

**Comment by panyanyany** [comment]
> 你有看这个问题吗？ #205

不对啊，Timeout 我2次都有设置，为什么第一次运行 OK，第二次就出错呢？

**Comment by ysmood** [comment]
能定义下什么叫全局超时吗？

**Comment by ysmood** [comment]
能说一下你是如何理解我引用的文档的吗？

**Comment by panyanyany** [comment]
> 能定义下什么叫全局超时吗？

即每个 Element/ElementX 等方法的默认的超时时间，超过这个时间，Element/ElementX 不管有没有结果，都会返回

**Comment by panyanyany** [comment]
> 能说一下你是如何理解我引用的文档的吗？

只要设置了一次 Timeout，那么接下来不管调用几个方法，不管调用什么方法，都会计算在这个 Timeout 周期内。如果 Timeout 周期内最后那几个方法有一个没完成，就会 exceed

**Comment by panyanyany** [comment]
> 你有看这个问题吗？ #205

他设置了 10s 的 Timeout 然后休息了 10s，再执行 MustElement 方法，由于这个 context 已经超过 10s 了，所以直接报错了。

但在我的程序中，第一次打开 home 到 第二次打开 home 之间，间隔未达到 Timeout，不应该报错。实际却是我的第二次打开被阻塞了，并报错了。

**Comment by ysmood** [comment]
另外你保存ws 和这个问题有什么关系呢？

**Comment by panyanyany** [comment]
> 另外你保存ws 和这个问题有什么关系呢？

因为我的 exe 可能会多次执行。
而我希望仅第一次执行的时候启动一个 chrome，后续执行全部复用第一次启动的 chrome。

所以第一次启动 chrome 后我会把这个 websocket url 保存一下，第二次执行 exe 的时候会先检查这个 chrome 是否还在，在的话就直接连上去了。

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/8db745a77c33e16c8f2f1b31c8815f8afbab375b/dev_helpers.go#L26

**Comment by panyanyany** [comment]
> https://github.com/go-rod/rod/blob/8db745a77c33e16c8f2f1b31c8815f8afbab375b/dev_helpers.go#L26

这个我知道的，但我这个并不是多个 client 同时连一个 target。只有上一个 client 结束后，才会有新的 client 连接的。

**Comment by ysmood** [comment]
我直接跑了下你的代码，运行完了没报错啊。而且我发现你代码并没有缓存ws文件，这个文件压根就没被复用？

**Comment by panyanyany** [comment]
> 我直接跑了下你的代码，我发现你代码并没有缓存ws文件，这个文件压根就没被复用？

第一次跑会启动一个全新的 chrome 这时不会报错
要第二次跑，这时会复用旧的 chrome，这时就会报错了。我试过2个版本的 chrome 都会这样。

ws 没有缓存，可能是因为你没有创建 storage 文件夹，导致文件写不进去，这是我的错，为了简化代码，没有做太多的错误处理了。

**Comment by panyanyany** [comment]
我把 LoadWs 和 SaveWs 的代码改了下，去掉目录了，现在应该会直接创建个 test.txt 文件保存 ws url

**Comment by ysmood** [comment]
> 可能是因为你没有创建 storage 文件夹

@panyanyany 可以试试我这个库 https://pkg.go.dev/github.com/ysmood/kit@v0.25.2/pkg/os?tab=doc#OutputFile
自动生成目录 `kit.OutputFile("path/to/file", "content", nil)`

**Comment by ysmood** [comment]
去掉 MustWaitRequestIdle 就正常化了，感觉这个引起了某种异常

**Comment by ysmood** [comment]
多谢你花时间报告这个问题。我基本确定是某种 bug 了，你可以先不要使用 MustWaitRequestIdle 来等待页面加载。可以用 MustElement 来等待：

```
page.MustNavigate("https://www.taobao.com").MustElement(`.class-name`)
```

这种等待更加实用。

我有时间会看下怎么修复这个 bug。

**Comment by ysmood** [comment]
@panyanyany 最近有时间看了下发现不是 bug，原因是有个长链接一直没有结束所以才会这样，看地址应该是 taobao 的统计代码，用于长时间收集用户信息：

![image](https://user-images.githubusercontent.com/1415488/92702541-4cf02900-f38c-11ea-93e7-b6fd140f5590.png)

处理这种情况很简单只需要加上一个过滤器就行了 `MustWaitRequestIdle("https://gm.mmstat.com/*")`，下面这个代码我跑了很多次，没有任何问题：

```go
func main() {
	u := launcher.New().Headless(false).RemoteDebuggingPort(8765).MustLaunch()
	b := rod.New().Timeout(30 * time.Second).ControlURL(u).MustConnect()

	page := b.MustPages()[0]
	nav(page)
	fmt.Println("1")
	nav(page)
	fmt.Println("2")
}

func nav(page *rod.Page) {
	wait := page.MustWaitRequestIdle("https://gm.mmstat.com/*")
	page.MustNavigate("https://www.taobao.com")
	wait()
}

```

如果你还有问题可以 reopen 这个 issue，我先关了。
