### ISSUE TITLE
Redesign the Timeout context

### ISSUE THREAD

**Issue by ysmood** [go-rod/rod#209]
To allow more precise control of timeouts. The current inheriting style is not intuitive for beginners.

**Comment by chy373** [comment]
@ysmood Is there an example of control fo timeout? I want to close page when a page is stuck for a long duration.

**Comment by chy373** [comment]
> @ysmood Is there an example of control fo timeout? I want to close page when a page is stuck for a long duration.

@ysmood i figured it out myself. Rod is excellent! Thanks a lot!
