### ISSUE TITLE
Network domain invokes via native cdp call doesn't work

### ISSUE THREAD

**Issue by packman80** [go-rod/rod#212]
Have a some problems to execute this code: 

```go
go page.EachEvent(func(e *proto.NetworkResponseReceived) {
        if e.Response.URL == "https://www.example.com/" {
            ctx, client, sessionID := page.CallContext()
            params, _ := json.Marshal(map[string]string{
                "requestId": e.RequestID,
            })
            res, _ := client.Call(ctx, sessionID, "Network.getResponseBody", params)
            fmt.Println(res)
        }
```
Body is empty in this call. Any idea what's wrong?
go-rod v0.52.0

**Comment by ysmood** [comment]
You can't use `Network.getResponseBody` without `Network.setRequestInterception` it will return empty. They don't have a good doc for it so it might be confusing when using it.

`Network.setRequestInterception` is deprecated from their doc: https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setRequestInterception.

If you want to get the HTML, you can use `page.MustWaitLoad().MustElement("html").MustHTML()`

**Comment by ysmood** [comment]
I think it's ok to close it for now. If you have a problem please leave a message.
