### ISSUE TITLE
How to get the request and response info after page load

### ISSUE THREAD

**Issue by ysmood** [go-rod/rod#213]
Such as the request and response headers, status code, etc.

**Comment by gaoyang-china** [comment]
1.响应头信息，在网页加载完后如何拿到响应头。
2.请求头，在网页加载完后如何拿到请求头，这个需求也可以理解：在请求指定目标时是否发生了跳转。

**Comment by ysmood** [comment]
```go
package main

import (
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/proto"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	browser := rod.New().MustConnect()

	page := browser.MustPage("")

	var e proto.NetworkResponseReceived

	wait := page.WaitEvent(&e)
	page.Navigate("https://google.com")
	wait()

	// Print request headers
	utils.Dump(e.Response.RequestHeaders)

	// The page redirect from google.com to www.gogole.com
	utils.Dump(e.Response.Status, e.Response.URL, e.Response.Headers)
}

```

**Comment by LeoHuang2015** [comment]
@ysmood 

获取请求信息这里存在问题：通过e.Response.RequestHeaders， 的请求头是空；
虽然NetworkRequestWillBeSent可以获取请求头，但这里发现，headers里面没有cookie信息，cookie还得单独通过page.cookie获取....
这里是否可以考虑优化下？

**Comment by ysmood** [comment]
@LeoHuang2015 这是上游的问题，优化会比较容易引发未知问题，可以试着给 chromium 提 issue

**Comment by kylechadha** [comment]
@ysmood The one part that was harder to figure out than using chromedp ;)

Perhaps would be a good example, since presumably you need to know the response status before scraping the page (ie: if you received a 4xx error).

**Comment by ysmood** [comment]
@kylechadha Usually, 404 or 500 will be an error page of an website, you don't need http code to tell it.

**Comment by kylechadha** [comment]
@ysmood Trye, my use case is downloading rendered html across many different sites, so perhaps a bit different than average.

**Comment by rew1nter** [comment]
Why is this printing anything to the terminal?
```go
func main() {
	path, _ := launcher.LookPath()

	u := launcher.New().
		Bin(path).
		Headless(false).
		// Devtools(true).
		MustLaunch()

	browser := rod.New().
		ControlURL(u).
		MustConnect()

	page := browser.MustPage("")

	var e proto.NetworkResponseReceived

	wait := page.WaitEvent(&e)
	page.MustNavigate("https://google.com")
	wait()

	// Print request headers
	utils.Dump(e.Response.RequestHeaders)

	// Print response info. The page redirect from google.com to www.gogole.com
	utils.Dump(e.Response.Status, e.Response.URL, e.Response.Headers)
}
```

**Comment by cristianvnica** [comment]
> Why is this not printing anything to the terminal?
> 
Replacing `utils.Dump` with `fmt.Println` worked for me
