### ISSUE TITLE
Unable to open "chrome://" pages on headless mode

### ISSUE THREAD

**Issue by infixint943** [go-rod/rod#217]
**Rod Version:** v0.52.0

## To Reproduce

- Open page `chrome://version` (or any other `chrome://` page) on headless mode.
- Observe the error/panic `net::ERR_INVALID_URL: navigation failed`.

**Comment by ysmood** [comment]
Related post: https://groups.google.com/a/chromium.org/g/headless-dev/c/0zD4nAyVoCY?pli=1

I guess chrome will pages like "chrome://settings/", `chrome://version/` on headless mode.

**Comment by ysmood** [comment]
You can get the version info by this example code:

```go
	utils.Dump(proto.BrowserGetVersion{}.Call(browser))
	utils.Dump(proto.BrowserGetBrowserCommandLine{}.Call(browser))
```
