### ISSUE TITLE
DOM.scrollInToViewIfNeeded wasn't found 

### ISSUE THREAD

**Issue by wings-xue** [go-rod/rod#218]
**Rod Version:** v0.57.2
**Google Chrome:** 80.0.3987.122 (正式版本) （64 位）

执行文件：fixtures\gen-fonts\main.go
报错：DOM.scrollInToViewIfNeeded wasn't found 

![image](https://user-images.githubusercontent.com/17506839/93194039-36761300-f77a-11ea-921b-eac66b2a31b4.png)

**Comment by wings-xue** [comment]
不是 rod的bug， 由于谷歌稳定版不支持很多功能。 更换浏览器或者浏览器版本。

**Comment by ysmood** [comment]
嗯，升级浏览器比较好
