### ISSUE TITLE
这个地方不用Close吧

### ISSUE THREAD

**Issue by chennqqi** [go-rod/rod#220]
https://github.com/go-rod/rod/blob/785f52cac95855560fcc82d139a69874e7b21450/browser.go#L203
如果page没有创建成功就Close会导致崩溃

**Comment by ysmood** [comment]
我这里考虑的其实是创建成功了但是返回了错误，如果发生了就尽量close page，以尽量避免泄漏。

就好比你请求了 chrome 创建页面，chrome 也确实创建了一个 tab ，但是由于某种 chrome 自己的 bug 它告诉我创建出了问题。

大概率是不会发生这种极端情况的

**Comment by ysmood** [comment]
如果你可以写个 demo 能稳定因为这个而 crash 程序，那我才会考虑修复这个问题。

**Comment by ysmood** [comment]
我仔细想了下，这里或许用 `proto.TargetCloseTarget` 应该会好些

**Comment by ysmood** [comment]
改了下，你看看还有问题吗？

**Comment by chennqqi** [comment]
没问题了
