### ISSUE TITLE
WaitRequestIdle()'s wait() never returns on digitalocean page

### ISSUE THREAD

**Issue by vyskocilm** [go-rod/rod#221]
**Rod Version:** v0.56.0
**Chromium Version:** 85.0.4183.102

## To Reproduce

It looks like excludes is ignored, or there is a bug in `WaitRequestIdle`. The page makes HUNDREDS of API calls to `api.greenhouse.io`.

```go
        url := `https://www.digitalocean.com/careers/position/apply/?jid=2229189&gh_jid=2229189`
        excludes := []string{"https://api.greenhouse.io/v1/.*"}
	wait := page.WaitRequestIdle(10*time.Second, []string{}, excludes)
	time.Sleep(sleep)
	wait()
```

## Expected behavior

`wait()` ends in 10 seconds

## Actual result

`wait()` never finishes

I've checked the code and I'd say that calling timer.Stop is the issue here, but I am not that familiar with a timer API, so can't say more than with this change functions ends :shrug: 

```diff
diff --git a/page.go b/page.go
index 77d1a92..fa7c368 100644
--- a/page.go
+++ b/page.go
@@ -349,7 +349,6 @@ func (p *Page) WaitRequestIdle(d time.Duration, includes, excludes []string) fun
 
        reqList := map[proto.NetworkRequestID]struct{}{}
        timeout := time.NewTimer(d)
-       timeout.Stop()
 
        reset := func(id proto.NetworkRequestID) {
                delete(reqList, id)
@@ -369,10 +368,10 @@ func (p *Page) WaitRequestIdle(d time.Duration, includes, excludes []string) fun
                failed *proto.NetworkLoadingFailed,
        ) {
                if sent != nil {
-                       timeout.Stop()
                        url := sent.Request.URL
                        id := sent.RequestID
                        if matchWithFilter(url, includes, excludes) {
+                               timeout.Reset(d)
                                reqList[id] = struct{}{}
                        }
                } else if finished != nil {
```

**Comment by ysmood** [comment]
I think you misunderstand the doc of `WaitRequestIdle`:

https://github.com/go-rod/rod/blob/785f52cac95855560fcc82d139a69874e7b21450/page.go#L342-L345

> no request for d duration

It can wait forever if a request never stops. `d` is not the max wait time. If you want to set a timeout use `Timeout`:

```go
page.TImeout(10*time.Second).MustWaitRequestIdle()
```

**Comment by ysmood** [comment]
Please try v0.59.0, if you still have problems please leave a message here.
