### ISSUE TITLE
Is it possible to roll back the new API of v50.x to the original one?

### ISSUE THREAD

**Issue by zobx** [go-rod/rod#224]
**Rod Version:** v0.49.8

I want to upgrade to the new version and found that the api has changed. The update record says that v50.x is an experimental version. I would like to ask when will the previous apii be restored or will not be restored afterwards?

thinks

**Comment by ysmood** [comment]
Sure, as long as you can get enough people to support your idea. Such 30 upvotes or strong reasons.

**Comment by ysmood** [comment]
It's very easy to upgrade the API. Usually, just run several global replace string will do the job.

**Comment by Abin01** [comment]
#46 
hello , How should I use box()  in  v0.71.0 ? thinks

**Comment by ysmood** [comment]
> hello , How should I use box() in v0.71.0 ? thinks

https://pkg.go.dev/github.com/go-rod/rod#Element.Shape

**Comment by Abin01** [comment]
thinks

**Comment by infinitepr0** [comment]
Due to inactivity, I'll be closing this issue.
