### ISSUE TITLE
 when anchor wrap display, click  no effect 

### ISSUE THREAD

**Issue by pu369** [go-rod/rod#233]
**Rod Version:** v0.64.1

## To Reproduce
HTML code ： `<td><a href="xxx"> example of click long anchor</a></td>`

when  width was  limited by CSS，the anchor Wrap display on Web page ,like this：

example of click long 
anchor

## Expected behavior
 element := page.MustElement("a")
 element .MustClick() 

## Actual result
Actually clicked the blank position，like this：

example of click long 
anchor      ↖
                       the mouse clicked here,  and no effect

**Comment by ysmood** [comment]
Thanks, can you show us the CSS?

**Comment by ysmood** [comment]
Thank you for your report, it a really great catch 👍.

Published v0.66.0, please upgrade rod and check if it works for you.

**Comment by pu369** [comment]
it works great  !
