### ISSUE TITLE
What is the correct way for waiting network request to be done? 

### ISSUE THREAD

**Issue by alufrew** [go-rod/rod#237]
**Rod Version:** v0.69.1

Hi. 

During testing one web page I need to click button, wait till request will be done in background and get request body for further use in tests. I use RuntimeConsoleAPICalled to get console events and work with it as with string. It looks somewhat like this:

```done := make(chan bool)
  go frame.EachEvent(func(e *proto.RuntimeConsoleAPICalled) {
		event := frame.MustObjectsToJSON(e.Args)

		if strings.Contains(event.String(), "/some/api/path") {
			methodToUnmarshalData(event.String())
			done <- true
		}
	})()
```

The thing is when I want to parse response data from console string I must write additional code to correctly do it. Is there a way to get Networks Requests directly instead of using RuntimeConsoleAPICalled?

**Comment by ysmood** [comment]
Such as:

```go
func main() {
	page := browser.MustPage("")
	wait := page.MustWaitNavigation() // wait until network is almost idle
	page.MustNavigate("http://example.com/")
	wait()
}
```

**Comment by alufrew** [comment]
The thing is I am waiting for one specific request and need to get it's body. 

F.e:
1. Go to https://play.golang.org/
2. Open Network tab of dev tools.
3. Click run button.
4. Observe network tab.

First request made is `POST https://play.golang.org/compile`. 
Response is: `{"Errors":"","Events":[{"Message":"Hello, playground\n","Kind":"stdout","Delay":0}],"Status":0,"IsTest":false,"TestsFailed":0,"VetOK":true}`

If I need to wait for this request and then need to parse response body to my own struct for further use is there a way to do so?

**Comment by ysmood** [comment]
How about this:

https://github.com/go-rod/rod/blob/301e8c10ffb97e9c3440c8abc28c0e345f1cca81/examples_test.go#L463-L499

For more details, check the API doc of hijack.

**Comment by wateroot** [comment]
> How about this:
> 
> https://github.com/go-rod/rod/blob/301e8c10ffb97e9c3440c8abc28c0e345f1cca81/examples_test.go#L463-L499
> 
> For more details, check the API doc of hijack.

It seems that the modified requests will not sent via proxy, which set at browser launch step.
