### ISSUE TITLE
after commit commit 137dada0730d0c747880cf0e07dbfcda3a3ab4f5. can't import/sync with rod 

### ISSUE THREAD

**Issue by andriikotko** [go-rod/rod#238]
**Rod Version:** v0.69.1

appears after commit 137dada0730d0c747880cf0e07dbfcda3a3ab4f5. can't import/sync with rod - I noticed it today

## To Reproduce Steps:
 when I try to sync packages:

Actual result
go: finding module for package github.com/go-rod/rod/lib/launcher
go: finding module for package github.com/go-rod/rod/lib/input
go: finding module for package github.com/go-rod/rod
go: found github.com/go-rod/rod in github.com/go-rod/rod v0.69.1
go: found github.com/go-rod/rod/lib/input in github.com/go-rod/rod v0.69.1
go: found github.com/go-rod/rod/lib/launcher in github.com/go-rod/rod v0.69.1
go: github.com/go-rod/rod@v0.69.1 requires
	github.com/ysmood/got@v0.0.1: reading github.com/ysmood/got/go.mod at revision v0.0.1: unknown revision v0.0.1

OR you can try to do it manually :    go get github.com/go-rod/rod

Actual result: 
go get: github.com/go-rod/rod@v0.69.1 requires
        github.com/ysmood/got@v0.0.1: reading github.com/ysmood/got/go.mod at revision v0.0.1: unknown revision v0.0.1

**Comment by ysmood** [comment]
Please check v0.69.2

**Comment by andriikotko** [comment]
Looks good :) - it works
For first time it not compiles, but I noticed you rename method MustViewPort to MustSetViewPort - and now all works correct
