### ISSUE TITLE
consider reducing the amount of kit.E usage.

### ISSUE THREAD

**Issue by tmc** [go-rod/rod#24]
This package would feel more idiomatic if it didn't use this variadic panicing helper.

**Comment by ysmood** [comment]
I don't understand. This is just an optional helper, you don't have to use it. If you want to handle error directly you can use something like `page.ElementE` other then `page.Element`.

All those `kit.E` helpers are inside the same file `sugar.go`, you don't have to use them.

**Comment by ysmood** [comment]
I think you can guess why it's called `sugar.go` 😂. I like to use them, but even we remove this file directly it won't affect the functions.

**Comment by ysmood** [comment]
The trade-off is we use panic to trade the fluent style of coding:

```go
defer func() {
    err = recover()
}()

page.Element("button").WaitStable().Click()
```

Versus

```go
el, err := page.ElementE("button")
if err != nil {
    return err
}
err := el.WaitStable()
if err != nil {
    return err
}
err = el.Click()
if err != nil {
    return err
}
```
You can do both way, but I think anyone call tell which should be the default option for this project 😂

**Comment by ysmood** [comment]
If you or anyone can find a better solution, I will be glad to upgrade the code. We can keep this ticket open.

**Comment by tmc** [comment]
I think the fluent style is great at the top level, I was referring to the internal implementation.

**Comment by ysmood** [comment]
What do you mean by that? I not sure I understand your idea. What's wrong the kit.E? Or what trouble can it introduce? It just follows the standard way to panic error.

**Comment by ysmood** [comment]
I think I tried my best to avoid using it at all. Currently, the places I use it are here:

![image](https://user-images.githubusercontent.com/1415488/82162629-f6447800-98e0-11ea-816e-1cd4b7383883.png)

Most of them are decoding JSON from chrome, which will be 100% no error if chrome has no fatal bug. If there is an error during decoding it must be some fatal error, I think it's best to use panic.

If you look at the golang source code they also use panic a lot when it's highly possible there will be no error at all.

**Comment by ysmood** [comment]
I tried my best to remove some kit.E for deferred code [here](https://github.com/ysmood/rod/commit/94ad1df1c292e74a0c38b1df8c138b88fcc3acb1).

Another thing I want to mention is that I will never use panic inside an unattached goroutine. There will be panic, but you will always be able to use defer to recover the error. If there's a panic you can't recover that must be a bug, please report it and I will fix it.

**Comment by ysmood** [comment]
For now, let's close it. We can reopen it when necessary.
