### ISSUE TITLE
Input problem in docker

### ISSUE THREAD

**Issue by Abin01** [go-rod/rod#240]
**Rod Version:** v0.49.8

docker image Version v0.49.8 And latest

code
```
page.Timeout(100 * time.Millisecond).Search(`table > tbody > tr:nth-child(3) > td:nth-child(3) > input`).Input('100')
```

Enter 100 normally in the desktop version of chrome

Do not enter 100 in docker （ v0.49.8 And latest）

No error will be reported during operation

**Comment by ysmood** [comment]
Remove the `.Timeout(100 * time.Millisecond)` and try again.

**Comment by ysmood** [comment]
[Don't rush to claim that you have found a bug.](http://www.catb.org/~esr/faqs/smart-questions.html#idm368)

**Comment by Abin01** [comment]
okok  ,  thinks
