### ISSUE TITLE
How to disable or remove defaultFlags

### ISSUE THREAD

**Issue by longjin1991** [go-rod/rod#241]
**Rod Version:** v0.73.0

The community is not charity. We welcome constructive questions, but not without limitation.

Check before you submit:

- Have you learned [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html)?
- Is this issue general enough to benefit others?
- Can I provide code to reproduce the issue?
- Can I reduce the unrelated code to make the example minimal?
- Is the example code standalone?
- What have you tried to solve the problem?

this is code of my:
// Launch a new browser with default options, and connect to it.
	url := launcher.New().Headless(false).MustLaunch()
	browser := rod.New().ControlURL(url).MustConnect()

	// Even you forget to close, rod will close it after main process ends.
	defer browser.MustClose()
page := browser.MustPage("https://github.com/")

- how to remove or disable defaultFlags.
- how to close page about:blank.
thank you so much.

**Comment by ysmood** [comment]
Check `launcher.NewUserMode`

https://github.com/go-rod/rod/blob/master/lib/examples/use-rod-like-chrome-extension/main.go

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/73bb4ce80f66ef9dea3bcffaa9897211fff55994/examples_test.go#L361-L383
