### ISSUE TITLE
about ElementByJS question

### ISSUE THREAD

**Issue by Abin01** [go-rod/rod#247]
**Rod Version:** v0.49.8

#88 
```
p.Element(`#gndkiframe`).Frame().ElementByJS(`() => document.querySelector("#tsxx").destroy()`)
```
[rod] eval error: TypeError: document.querySelector(...).destroy is not a function

I want to use js to delete an element, but the code reports an error. Is there a problem with my usage?

**Comment by Abin01** [comment]
```
p.ElementByJS(`() => document.getElementById('gndkiframe').contentWindow.document.getElementById('tsxx').destroy()`)
```
[rod] eval error: TypeError: Cannot read property 'destroy' of null

in chrome console top  the code ``` document.getElementById('gndkiframe').contentWindow.document.getElementById('tsxx').destroy()``` normal running 

in chrome  (`#gndkiframe`) iframe  the code ```document.querySelector("#tsxx").destroy()``` normal running 

Is there any other way to solve my problem

**Comment by ysmood** [comment]
Are you joking? 😂 

<img width="617" alt="Screen Shot 2020-10-20 at 22 11 56" src="https://user-images.githubusercontent.com/1415488/96590677-46f14e80-1321-11eb-9181-d4857689d30f.png">

**Comment by ysmood** [comment]
https://pkg.go.dev/github.com/go-rod/rod#Element.MustRemove
