### ISSUE TITLE
How to get the background image of an element

### ISSUE THREAD

**Issue by Abin01** [go-rod/rod#264]
**Rod Version:** v0.49.8

```
<div id="container" style="display: block; position: absolute; left: 10px; top: 10px; background-image: url(&quot;wsbs/images/bg4_style2.jpg&quot;); height: 100px; width: 268px;"></div>
```
I want to get the background image and save it
I don’t know how to deal with this situation, any good suggestions, thank you

**Comment by ysmood** [comment]
Released v0.76.6, added `Element.BackgroundImage`

The demo of how to use it:

https://github.com/go-rod/rod/blob/58a746adb758b4455e06c0e02e12abcad1434f21/element_test.go#L488-L497
