### ISSUE TITLE
Better doc for the integration between leakless and rod (if we can remove leakless, that will be even better)

### ISSUE THREAD

**Issue by FrankReh** [go-rod/rod#266]
**Rod Version:** v0.79.0

I've been looking through the code and it looks very nice. But the binary blob that is provided when a leakless binary is not found in the path makes me very nervous. Have you considered that some people would not want a binary installed and run like this? Thank you for providing such an interesting package with such a liberal license but maybe you would find increased adoption if the binaries it relied on would come from a make install step, or a go generate step.

**Comment by ysmood** [comment]
Good point, I actually want to make it optional. But no good idea yet. We welcome PR to improve it.

> But the binary blob that is provided when a leakless binary is not found in the path makes me very nervous.

How can that happen? Currently, I don't see people have problems with it.

**Comment by ysmood** [comment]
BTW, you can disable leakless, no binary will be installed: https://pkg.go.dev/github.com/go-rod/rod@v0.79.0/lib/launcher#Launcher.Leakless

**Comment by ysmood** [comment]
Rod's components are all highly decoupled. `launcher` lib is just a shortcut, senior developers can fully control everything, such as this, the only limit is our imagination:

https://github.com/go-rod/rod/blob/dcb14aa18654e326082d41b9851fa54557638ab3/lib/launcher/example_test.go#L11-L27

**Comment by FrankReh** [comment]
I know not everyone is as paranoid about binary blobs as I. I looked for a build way, or an install way, of being sure the blob wasn't installed. I wasn't sure there weren't any unit tests that wouldn't try to install it (that a lots of negatives used there sorry), and while for now I can build the binary from your leakless/cmd/leakless directory and install it, I could't be sure such a binary would always be in a path when a self test is run in the future.

I appreciate you are helping to solve a complicated problem - there are multiple moving parts - platforms, chrome versions, chrome locations, perhaps even chrome debug protocol versions, and providing a binary can seem like it simplifies things for folks. But it is not standard - many people using go will want to build their own version. And the problem you are solving with the leakless binary is interesting - I was unaware it was an issue. 

I see you comment about senior developers being able to pick and choose the parts they want to use. Totally agree. And I appreciated your comment on the main page about how you are using fewer interfaces than another project, so that the code is more understandable. But still I would caution about trying to provide a solution that is easy for non-senior developers to the point where a binary is pulled from GitHub, being base64 encoded, and then installed on their machine and run, perhaps without their knowledge. It doesn't inspire confidence the same way as providing a solution where someone can build everything they need from the go std library and your own packages, without worrying that a unit test might install a binary that they don't know the providence of.

Anyway, I don't want to belabor the point. If you've thought about it but its what you want, your choice. I would ask that you make it a little more obvious on your main rod readme page that it will install and  run a binary that is coming from one of your other packages.

**Comment by ysmood** [comment]
I think the doc is pretty obvious, what do you think we should add? The steps to find out the extra base64 binary logic is just 1 click away: such as use IDE to jump to the API page of leakless (so many other ways to get to there), the first line of the readme is it 😂 , it that not obvious enough?

If you can help us to make PR to add doc you like, that will be great.

**Comment by ysmood** [comment]
I think a better way to decide what do is to think about the bottleneck or what trouble can leakless bring us in the real world. Then we solve the edge cases one-by-one. I don't see any real-world trouble yet. If you can give me a more specific code example that will help me to understand your idea better.

**Comment by FrankReh** [comment]
Well, the kind of comment I was asking for would be on the go-rod readme. It would say that under certain circumstances, a precompiled binary will be installed and run from the leakless package.

On the leakless readme page, "output a standalone executable" isn't as clear as saying something like "the leakless package will install an embedded binary, "leakless", if it is not found in the environment's path.

For your question about why? There are many people who don't want to run binaries compiled by someone else. There are cases already where a project was started by one person and later someone else took over and had the chance to insert malicious code into a project that people had learned to trust. I haven't heard of this happening with a golang project yet but there has been more than one with nom projects. I also haven't come across golang projects where a missing piece of functionality was solved by decoding a binary.

**Comment by FrankReh** [comment]
I'm happy to close the issue. It's not something I want to make a big point about. If we can't agree, it is totally your call. Again, thanks for the clean code and the modularity and the clear license.

**Comment by ysmood** [comment]
Security concerns shouldn't be a problem. It's not like npm, the binary is controlled by the user, not me. It's totally open-sourced, it's not a binary that you have to use or can't change. Leakless even has an API to specify the location of the binary you want to use.

**Comment by ysmood** [comment]
We can leave it open and see if we can doc it better.

**Comment by ysmood** [comment]
> I'm happy to close the issue. It's not something I want to make a big point about. If we can't agree, it is totally your call. Again, thanks for the clean code and the modularity and the clear license.

😂 I'm just lazy, I just want to borrow others' wisdom so that I can focus on other bottleneck problems.

**Comment by ysmood** [comment]
Released `v0.79.1`. If you think it's still not safe enough we can reopen it.
