### ISSUE TITLE
Why use an extra closure for removeTrace?

### ISSUE THREAD

**Issue by FrankReh** [go-rod/rod#270]
**Rod Version:** v0.79.0

Probably you want 
```
< 	defer func() {
<         removeTrace()
<     }
---
> 	defer removeTrace()
```

``` Go
func (el *Element) Wait(opts *EvalOptions) error {
	removeTrace := func() {}
	defer removeTrace()

	return utils.Retry(el.ctx, el.sleeper(), func() (bool, error) {
		res, err := el.Evaluate(opts.This(el.Object))
		if err != nil {
			return true, err
		}

		remove := el.page.Context(el.ctx).tryTraceEval(opts)
		removeTrace()
		removeTrace = remove

		if res.Value.Bool() {
			return true, nil
		}

		return false, nil
	})
}
```

**Comment by ysmood** [comment]
Thank you for the report. Can you raise an PR to help us fix it?

**Comment by ysmood** [comment]
You should join the development. Actually, I made the same mistake before.

```go
package main

import (
	"fmt"
)

func main() {
	foo := func() {}
	defer foo()
	foo = func () { fmt.Println(1) }
}
```

Run this, you will understand what I mean. A function is just a reference that will be copied to the stack if you read the source code of golang.

Also, please read [Don't rush to claim that you have found a bug.](http://www.catb.org/~esr/faqs/smart-questions.html#idm368)

**Comment by FrankReh** [comment]
Just to be clear, you understand the variable foo is evaluated at the time the defer statement is executed? It is the _invocation_ that is delayed until the enclosing function is returned. So there is nothing surprising about the example above, the foo with a noop body is called later on. Just like the code I pointed out. There is no reason someone would want to defer a noop. That's why the closure is needed and why I thought you would consider it a bug. Also I considered what form to use and I felt there is no harm in calling something a bug when the author can always override and say no - it is working as intended and just close it. Sorry you don't like the bug - I thought I was doing a favor. I will withdraw further comment.

**Comment by ysmood** [comment]
I like your report 👍 , it's a good finding. The question tag is useful for others to filter, I'm not the only developer, others may want to help answer questions too.
