### ISSUE TITLE
how to close tab about first

### ISSUE THREAD

**Issue by longjin1991** [go-rod/rod#273]
**Rod Version:** v0.79.1

The community is not charity. We welcome constructive questions, but not without limitation.

Check before you submit:

- Have you learned [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html)?
- Is this issue general enough to benefit others?
- Can I provide code to reproduce the issue?
- Can I reduce the unrelated code to make the example minimal?
- Is the example code standalone?
- What have you tried to solve the problem?

this is my code:
package main

import (
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
)

func main() {
	u := launcher.New().Headless(false).MustLaunch()

	rod.New().ControlURL(u).MustConnect().MustPage("https://github.com/go-rod/rod")

	time.Sleep(time.Hour)
}

it  will open 2 tab:  tab about:blank and tab content https://github.com/go-rod/rod
i want close tab about:blank 
thank you so much.
![Capture](https://user-images.githubusercontent.com/23453308/98683010-256f0a00-2397-11eb-93c5-c74ca9024f3e.PNG)

**Comment by ysmood** [comment]
Please read the readme's FAQ: https://github.com/go-rod/rod#q-why-there-is-always-an-aboutblank-page

**Comment by ysmood** [comment]
Please learn markdown and reformat your issue: https://guides.github.com/features/mastering-markdown/

**Comment by ysmood** [comment]
Use `browser.MustPages().MustFindByURL("about:blank").MustClose()` to close it.

**Comment by longjin1991** [comment]
> Use `browser.MustPages().MustFindByURL("about:blank").MustClose()` to close it.

thank you help me.
Is there any other way to set Headless = false example:
`rod.New().Headless(false).MustConnect().MustPage("https://github.com/go-rod/rod")`
instead of:
`launcher.New().Headless(false).MustLaunch()`

**Comment by ysmood** [comment]
check the doc of  `lib/defaults`

**Comment by ysmood** [comment]
v0.80.0 fixed it
