### ISSUE TITLE
windows browser chrome open not full size

### ISSUE THREAD

**Issue by longjin1991** [go-rod/rod#274]
**Rod Version:** v0.79.2

The community is not charity. We welcome constructive questions, but not without limitation.

Check before you submit:

- Have you learned [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html)?
- Is this issue general enough to benefit others?
- Can I provide code to reproduce the issue?
- Can I reduce the unrelated code to make the example minimal?
- Is the example code standalone?
- What have you tried to solve the problem?
hi all.
when set start-maximized = true, windows browser chrome open not full size
my code:

```
package main

import (
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"time"
)

func main() {

	url := launcher.New().Headless(false).
		Set("start-maximized", "true"). // set argument start-maximized = true
		MustLaunch()

	browser := rod.New().ControlURL(url).MustConnect()
	browser.MustPage("https://github.com/go-rod/rod")

	time.Sleep(time.Hour)

}

```
error:
![Capture](https://user-images.githubusercontent.com/23453308/98813134-4c404580-2456-11eb-961e-c6e4c599911d.PNG)
thank your help.

**Comment by ysmood** [comment]
`DefaultDevice(devices.Clear, false)`

**Comment by badrelmers** [comment]
@ysmood please can you tell me what problems I may have when using NoDefaultDevice? thank you.

**Comment by ysmood** [comment]
@badrelmers Such as you build a binary and distribute it to customers to use, different people will have different screen size,  user-agent, and language settings, some website will render contents differently on them.
