### ISSUE TITLE
does slow require an argument

### ISSUE THREAD

**Issue by FrankReh** [go-rod/rod#275]
**Rod Version:** v0.79.2

There's a comment in the code, defaults.go:135, showing _slow_ passed as a rod environment variable but the defaults library generates an error and subsequently crashes unless a string like "1s" is passed along with slow. Maybe the example in the comment could be updated or maybe the slow default function can fall back to using a default string or value when the argument is the zero value.

**Comment by ysmood** [comment]
Sure. I think it's better to just optimize the crash info. Actually, it's common in Go, for example, if you run `go test -timeout=1` the program will crash.

**Comment by ysmood** [comment]
released v0.79.3

**Comment by FrankReh** [comment]
Nice fix. The comment at defaults.go:137 is still incorrect. It shows usage as rod="show, trace,slow,monitor". slow requires an argument. Also equally trivial, the new comment in must.go meant for MustInputTime refers to MustInput and Input. The rest of your comments that I've seen so far are so good, I thought you would want to know.

**Comment by ysmood** [comment]
Thank you for the report! Added in 1af8225e15149b499fa8835e754055cb059fc32c

There will be lots of issues like this, it will great if you could raise a PR next time, so that I can directly merge it.
