### ISSUE TITLE
Hijacking request with ContinueRequest

### ISSUE THREAD

**Issue by sosnovski** [go-rod/rod#276]
**Rod Version:** v0.78.3

Hello,
I am trying to use HijackRequests.
In some cases, I need to use the ContinueRequest method that takes a pointer to the proto.FetchContinueRequest structure as arguments.
This structure has a required RequestID parameter, but there is nowhere to get it.

Tell me how to solve this situation?

**Comment by ysmood** [comment]
Why not use this:

https://github.com/go-rod/rod/blob/1af8225e15149b499fa8835e754055cb059fc32c/hijack_test.go#L96-L115

**Comment by ysmood** [comment]
The RequestID will be overridden by the router, you don't have to set it.
