### ISSUE TITLE
Revert to allowing multiple selectors in page Element functions

### ISSUE THREAD

**Issue by infinitepr0** [go-rod/rod#277]
Recent API changes have made it difficult to select multiple elements at once; The previous version allowed:
```
page.MustElement("body", "title", ".new-class")
```

Now, we have to do
```
page.Race().MustElement("body", func(){...}).MustElement("title", func(){...}).MustElement(".new-class", func(){...}).MustDo()
```
which is clearly lengthy and complicates the selectors.

Two options are:
1. Bring back multiple selectors in the `Element` functions.
2. Keep the `(*page) Element*()` functions as it is, and change the `(* RaceContext) Element*()` to
    - Returning the selected element from the chained sequence.
    - Removing the function parameter (as the returned element can be used to check and run corresponding code).

I think 2 is a better option. What do you think?

**Comment by infinitepr0** [comment]
With option 2, the above code now becomes
```
elm := page.Race().MustElement("body").MustElement("title").MustElement(".new-class").MustDo()

// Use elm.Matches() to run code based on selected element
```

**Comment by ysmood** [comment]
No need to use `Must`. I feel `elm := page.Race().Element("body").Element("title").Element(".new-class").MustDo()` is simple enough, so we don't have to revert to the old way. What do you think?

**Comment by ysmood** [comment]
Or you can add a helper like `Race().Elements(".a", ".b")`?

**Comment by infinitepr0** [comment]
> No need to use `Must` if no callback. I feel `elm := page.Race().Element("body").Element("title").Element(".new-class").MustDo()` is simple enough (the ide will do the heavy load), so we don't have to revert to the old way. What do you think?

This is better. It allows for better readability (even tho code becomes slightly longer).
But won't using `Element` as `MustElement` cause confusion between the methods for the two types?

**Comment by infinitepr0** [comment]
> Or you can add a helper like `Race().Elements(".a", ".b")`? I hope we can keep all race-related functionalities are all under the `Race` context.

This won't be necessary, if we use method 2. The second method allows for neater code, and chaining can be reserved exclusively for `RaceContext`.

**Comment by ysmood** [comment]
> But won't using Element as MustElement cause confusion between the methods for the two types?

It won't, if you read the source code and run some test, you will understand.

**Comment by infinitepr0** [comment]
> Or you can add a helper like Race().Elements(".a", ".b")? I hope we can keep all race-related functionalities are all under the Race context.

Thinking about it more, this seems like a good option, especially for cases where the selectors are dynamically specified.
