### ISSUE TITLE
How to use this parameter enable-automation to hide the prompt that  "Chrome is being controlled by automated test software"

### ISSUE THREAD

**Issue by zobx** [go-rod/rod#281]
**Rod Version:** v0.81.1
go-rod:
![image](https://user-images.githubusercontent.com/28089614/99365789-b2174c00-28f2-11eb-9794-0861a3c22e71.png)
python:
![image](https://user-images.githubusercontent.com/28089614/99365887-d2470b00-28f2-11eb-944a-71b8f74dfd56.png)

```go
func main() {
	url, _ := launcher.New().Headless(false).
		Set("enable-automation").
		Launch()
	browser := rod.New().ControlURL(url).
		Trace(true).MustConnect()

	text := browser.MustPage("https://www.baidu.com").MustElement("html").MustText()

	log.Println(text)
	kit.Pause()
}
```
```python
from  selenium import  webdriver
import  time
 
chrome_options = webdriver.ChromeOptions(); 
chrome_options.add_experimental_option("excludeSwitches", ['enable-automation']);
driver = webdriver.Chrome(options=chrome_options);  
#定义url 地址
url = 'http://www.baidu.com'
driver.get(url=url)
# 退出并关闭浏览器
# driver.quit()
```

**Comment by ysmood** [comment]
New chrome removed or renamed this flag, can you help us to investigate it?

**Comment by ysmood** [comment]
Use this to delete flag you don't want:

https://pkg.go.dev/github.com/go-rod/rod@v0.81.1/lib/launcher#Launcher.Delete

**Comment by zobx** [comment]
I observed that Puppeteer can also be implemented, that is, delete the enable-automation parameter. Under windows, add --enable-automation to the startup command, and the control bar will be displayed. If not, it will not be displayed. Use rod, Delete( "enable-automation") will report an error, panic: {-32000 Command line not returned because --enable-automation not set. }, I printed out the startup parameters of launch(), including --enable-automation, why delete Will an error be reported if this parameter is dropped?
![image](https://user-images.githubusercontent.com/28089614/99472308-5052f280-2983-11eb-8948-0643c63ae806.png)

**Comment by ysmood** [comment]
I think it should be the same as puppeteer, can you help us to compare the CLI difference between Rod and Puppeteer?

**Comment by ysmood** [comment]
v0.81.2 should have fixed it, please try it

**Comment by zobx** [comment]
thanks ,it's works
