### ISSUE TITLE
Using Chromedriver as an alternative

### ISSUE THREAD

**Issue by yusufozturk** [go-rod/rod#282]
**Rod Version:** v0.79.0

Hi,

First of all, this is a great library! Well done!

We want to replace our current solution (chromedp/chrome.exe) with rod. But I was wondering if it's possible to use chromedriver instead of full chrome package. We are trying to make a really tiny file so we can easily export to customers. But chrome package for Windows/Linux takes around 300 MB in total. So it makes our setup file really big.

Sadly, our product can also run on Windows server (if customer chooses) and not all enterprises have newer browsers in their servers. So we need to add Chrome package in our setup file. Also due to enterprise security restrictions, most of the servers don't have internet connection. Sometimes we don't even have permission to install something so we use portable stuff.

I see that Selenium requires chromedriver and it will make our package 20 mb in total (Windows + Linux). But I really liked the idea of Rod so we would like to switch to this one. If we can use chromedriver, maybe we can't have full features but at least we would like to do some basic thing like taking screenshot of website and doing some basic synthetic transactions on the web pages.

So is it possible to try chromedriver as an alternative? I saw another issue that we can customize browser path. So if we give "chromedriver" as the path, would it work?

We will put some time today to understand this but I wanted to ask in advance to get some recommendations for our case.

Thanks!

**Comment by ysmood** [comment]
Sure, you should be able to use your own chrome executable and run rod without extra network request. About binary size it's not that huge if you compress it before distributing to customers. Rod is interexchangable with puppeteer, if puppeteer can use chromedrive then rod can. Can you help us to investigate that?

**Comment by yusufozturk** [comment]
@ysmood oh it's my bad! I thought chromedriver is a minimal version of chrome but actually it's just a wrapper for Chrome.

I will close this issue because I will continue to use chrome.exe. Thanks!
