### ISSUE TITLE
Send cdp request to non-exist sessions will cause hang

### ISSUE THREAD

**Issue by FrankReh** [go-rod/rod#283]
**Rod Version:** v0.80.0

## The code to demonstrate your question

```shell
// in the top level rod directory
go test -run 'Test/Hijack'
```

Also two other unit tests reliably hang for me. 'Test/PageWait' and 'Test/Mouse'. The other 160 odd pass.
## What have you tried to solve the question
I've tried up to yesterday's commit, 'make test more stable', and the results are the same.

Performing a git bisect, on my darwin system, with the latest Chrome (version 87), the last commit where they pass is a32cd66. The next one, 39dcf1c, causes each of the three tests listed above to hang.

**Comment by FrankReh** [comment]
The best I can tell so far is that the failure is related to how quickly the test finishes, or some ordering of go routines. When I put some println statements into the Mouse test in page_test.go, I find it passes sometimes. Other times, it still doesn't pass, it hangs, but it always reaches the end of the Mouse unit test each time, so it appears some cleanup is blocked on something.

**Comment by FrankReh** [comment]
It looks like the go test infrastructure itself is hung on something. All the functions in setup_test appear to be completing.

**Comment by FrankReh** [comment]
Give me time, I seem to change my mind. I don't think it is hung in the go test infrastructure. I found more testing Cleanup calls in setup_test.go and one of them seems to be part of the hang. In particular, the call to t.browser.MustPages() in the range statement doesn't always return, it seems. That's promising because this commit was about closing the init page automatically.

It still seems timing or Goroutine scheduling related. I have to run the same test a few times to get it to hang once in a while.

**Comment by FrankReh** [comment]
I've narrowed it down to the page.initSession not always returning. In run already, two calls to page.initSession didn't return.

**Comment by ysmood** [comment]
Yes, I found same issue with the `t.browser.MustPages()`. Not sure what is the cause yet, will check it if I have time.

**Comment by FrankReh** [comment]
Question about the tester T that is created for the TesterPool. Why did the commit I referenced above, 39dcf1c, go from setting the T.page property from a getOnePage() result to a browser.MustPage("")? The same commit also created the notion of a self closing page which the browser launch is using. Something about these is changing what MustPages or initSession is seeing during cleanup but I haven't understood what's happening yet.

**Comment by FrankReh** [comment]
It appears that sometimes the rpc call made with a particular id to the browser is hung because the browser does not response with that id.
Here's an example of a message being sent to the browser as part of an rpc call with an id of 129 that is not returned. But what's interesting is three other messages, events I guess, are received, for the same targetId, and the middle one even has the same sessionId. It seems the browser is saying with its three events that the target is no more, so there should be no response for the rpc send expected. Is this a bug in the browser or perhaps should it be expected? Should the rpc defined by lib/cdp/client.go be resilient against req.Id values not being returned in a response?
```
consumeMsg data being sent to browser: {"id":129,"sessionId":"860493597B4668FD88BA6CBEEFB6B16A","method":"Page.enable","params":{}}
readMsgFromBrowser data {"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"6E128820D979B7B02D1CC013A83352B2","type":"page","title":"self-close.html","url":"file:///private/var/folders/2t/sdgt1zts68s4n9_f1tx670pw0000gn/T/rod/self-close.html","attached":false,"canAccessOpener":false,"browserContextId":"1FF45CB207745BBC752124B957E0F362"}}}
readMsgFromBrowser data {"method":"Target.detachedFromTarget","params":{"sessionId":"860493597B4668FD88BA6CBEEFB6B16A","targetId":"6E128820D979B7B02D1CC013A83352B2"}}
readMsgFromBrowser data {"method":"Target.targetDestroyed","params":{"targetId":"6E128820D979B7B02D1CC013A83352B2"}}
```

With all the print statements I've put into the code, the condition that triggers this hang has become more rare. It's possible on another system, with a faster or slower processor or different threading algorithm in the OS, this is not being hit as often.

**Comment by ysmood** [comment]
yes, so far it's pretty strange. the 39dcf1c is just a legacy issue, I will revert it and see if the problem will go away.

**Comment by FrankReh** [comment]
I am able to track other cases of commands not being responded to either, all related to the page that does a self close. Often the command is a simple Emulation.setDeviceMetricsOverride. So far what's common is the three events that are received shortly thereafter by the same client, the Target.targetInfoChanged, the Target.detachedFromTarget, and the Target.targetDestroyed.

I'm going to pursue the theory it is related to the first of these events, because the event seems to be indicating the target is no longer attached to the session, the session the command was sent with. Will look for some correlation with other cases that don't hang.

**Comment by FrankReh** [comment]
Okay, I feel I'm getting closer. When there is a hang because an rpc command wasn't replied, there is always the target from the self-close page that hasn't actually closed yet, so during the test cleanup, the call to t.browser.MustPages(), to check for leaked pages, ends up calling proto.TargetGetTargets{}.Call(b) for one of the browsers and getting back a list of **two** targets, not just one which is normal and what normally is returned during the cleanup stage when the tests work.

The extra target being returned is for the page that is supposed to close itself, but enough time hasn't elapsed for that to happen, so it is treated as a target to be interrogated. And it is one of those interrogation commands that can end up hanging because the page has just about closed itself and that causes the page's sessionID to be invalided. I don't know why the headless chrome wouldn't return an error in that case. Maybe it's a corner case in the browser that isn't working properly.

**Comment by FrankReh** [comment]
To confirm, putting in a hack to sleep for 100ms when the TargetGetTargets call returns a list with length greater than 1, so that another call to the same method returns 1 before continuing, does solve the problem. It doesn't answer what the software should do if there is an rpc call that is not returned however.

To get some clarity on the state of the browser, when I let the cmd hang and then timeout after 2 seconds, I have the same command with the same sessionId sent again and it also isn't responded to. But if I send the command with a null sessionID the second time,
this is responded to with an error. So the rpc channel isn't broken per se and the browser could continue serving the cdp channel. So it appears the browser is not responding to an old/no-longer-valid sessionID.

**Comment by ysmood** [comment]
Nice finding 👍  I have the same thoughts yesterday. I think it's better to a test case for it and make it clear for everyone, then raise a ticket for the chrome team.

The test case will try to simulate using a closed page's session id. See if we can find another way to resolve the hang other than timeout it. 

Also, I invited you to the org, please check here if you are interested: https://github.com/go-rod.

**Comment by ysmood** [comment]
@FrankReh not only an old id, as long as it doesn't exist.

Code to reproduce:

```go
func (t T) PageCloseNonExistSession() {
	p := t.browser.PageFromSession("nonexist").Timeout(time.Second)
	err := proto.PageClose{}.Call(p)
	t.Is(err, context.DeadlineExceeded)
}
```

**Comment by ysmood** [comment]
@FrankReh the 684d320 should have temporarily solved it. Unfortunately, there's nothing much we can do about it.

**Comment by FrankReh** [comment]
Agreed. I like your test.

I had just found that the DOM.enable method also didn't get back any response when a bogus sessionID was passed, although a JSON object with id and error is returned if the sessionID is left empty. It may not have to do with the page being closed per se, although the page self closing was the trigger that caused the go-rod package to send a sessionID that wasn't going to be recognized. I would think the JSONRPC on the Chrome side would be resilient enough to return an error when the sessionID can't be matched to something but it appears not. Also, I was logging stdout and stderr from the browser but nothing is written about the sessionID not being matched and not about the rpc being dropped either.

I wonder if it's easy for one of us to provide a puppeteer script that shows the problem more succinctly for the upstream bug report?  I've never tried.

**Comment by ysmood** [comment]
👍  Yes, a lot of endpoints will behave strangely for a non-exist session id. 

> I wonder if it's easy for one of us to provide a puppeteer script that shows the problem more succinctly for the upstream bug report? I've never tried.

I think it's fine, the problem is pretty easy to reproduce, they have their own test suite for chromium, no need to use the puppeteer.

**Comment by FrankReh** [comment]
Agreed. They don't seem to have the person power to tackle all their outstanding issues, so their triage is based on what their users have gotten used to and what is considered a regression.

I think your patch for the cleanup is fine for go-rod. That was one path that didn't have a context timeout set while most normal use would want a timeout to help track down where things started to go wrong.
