### ISSUE TITLE
Is it possible to export or generate har file?

### ISSUE THREAD

**Issue by yusufozturk** [go-rod/rod#284]
**Rod Version:** v0.79.0

Is it possible to export har file or getting network requests to generate it? I also can't find if we can see all the network requests.

Thanks.

**Comment by ysmood** [comment]
No, but not hard to implement if you want to help. You can use the event methods to capture all the network events. The domain is Network. Read the doc:

https://go-rod.github.io/#/events/README?id=available-events

**Comment by yusufozturk** [comment]
I solved this by using a js file. I used rod to open browser and then javascript to generate har file.

Thanks.
