### ISSUE TITLE
we should not automatically delete tempDir or only allow in remote lancher mode 

### ISSUE THREAD

**Issue by textproofreading** [go-rod/rod#286]
hi, all

Currently , rod delete tempDir automatically ,  this works fine in most cases . 

Some time we want rod run under use a long-live chrome profile ,  keep UserDataDir is the only way to reach that .

I know there is a option "rod-keep-user-data-dir" , unfortunately it only works under  Lanched in RemoteMode .

BTW , I had read the issue #181  .

UserDataDir  can set to tempDir or NotTempDir , so  we should give a chance to stop automatically action in either Local or Remote mode .

thanks.

**Comment by ysmood** [comment]
Not sure what you mean, tmp dir is not automatically removed as long as you don't call the Launcher.Cleanup

**Comment by ysmood** [comment]
I'll close it for now, if you can provide reproducable code, we can reopen it.
