### ISSUE TITLE
如何更改元素的属性值像 puppeteer 的 setAttribute 方法一样

### ISSUE THREAD

**Issue by kdming** [go-rod/rod#287]
**Rod Version:** v0.80.1

如题，我想修改 a 标签的 href 属性，然后再调用 MustClick() 方法
在Rod里面我没找到像puppeteer setAttribute()一样的方法，想请教一下在Rod里面要怎么做。

**Comment by ysmood** [comment]
```go
page.Element("a").MustEval(`this.href = "a.com"`)
```

**Comment by kdming** [comment]
收到，这反馈速度绝了，感谢

**Comment by ysmood** [comment]
puppeteer 并没有 setAttribute 这个函数，它一样也是需要和 rod 一样通过执行远端 js 来更改元素的属性。
