### ISSUE TITLE
How to get the whole html page in text format

### ISSUE THREAD

**Issue by weidonglian** [go-rod/rod#288]
**Rod Version:** v0.81.3

How to save the page into a html file or the []byte/string of the whole page? Then I could use go-query, since all my other queries have been written using go-query. 

I would like to use `go-rod` to render a html page and the dump it to a .html file or buffer. 

Thanks

**Comment by ysmood** [comment]
`page.Element("html").MustHTML()`

**Comment by weidonglian** [comment]
Thanks so much:)
