### ISSUE TITLE
Cant download file by post form request

### ISSUE THREAD

**Issue by imbaMF** [go-rod/rod#290]
**Rod Version:** v0.81.3

## The code to demonstrate your question

```go
package main

func Run(monit string) (string, error) {
	scMonit := strings.Split(monit, ".")
	if len(scMonit) != 3 {
		return "", fmt.Errorf("incorrect monit: %s", monit)
	}
	year := scMonit[2]

	ln := launcher.New().
		Headless(false)
	defer ln.Cleanup()

	ctl := ln.MustLaunch()

	browser := rod.New().
		ControlURL(ctl).
		Trace(true).
		SlowMotion(1 * time.Second).
		MustConnect()

	defer browser.MustClose()

	page := browser.MustPages().First().MustWindowMaximize().MustNavigate(app.Url)

	page.MustWaitLoad()

	log.Println(page.MustInfo().Title)

	el, err := page.Timeout(15*time.Second).Search(0, 1, "#lataWydania")
	if err != nil {
		return "", errors.New("error page load: lataWydania")
	}

	el.First().MustSelect(year)

	page.MustWaitLoad()

	utils.Sleep(3)

	el, err = page.Timeout(15*time.Second).Search(0, 1, ".body")
	if err != nil {
		return "", errors.New("error page load: body")
	}

	divs, err := el.First().Elements("div")
	if err != nil {
		return "", errors.New("error page load: divs")
	}

	var pFirst *rod.Element
	for _, e := range divs {
		pFirst = e.MustElement("p")
		date := pFirst.MustNext().MustText()
		if date != monit {
			continue
		}
		break
	}

	if pFirst == nil {
		return "", errors.New("monit not found")
	}

	utils.Sleep(1)

	name := pFirst.MustText()
	name = strings.Replace(name, " / ", "_", 1)

	pFirst.MustClick()

	page.MustWaitLoad()

	utils.Sleep(15)

	// time for text captcha !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	el, err = page.Search(0, 1, "#pobierzMonitorKaptchaSubmit")
	if err != nil {
		log.Println("captcha submit: ", err)
		return "", fmt.Errorf("captcha submit: %s", err.Error())
	}

	wait := page.MustGetDownloadFile("*")
	el.First().MustClick()
	source := wait()

	log.Println(source)

        utils.Sleep(5)

	return "", nil
}

type App struct {
	Url string
}

var app *App

func main() {

	app = &App{
		Url: "https://ems.ms.gov.pl/msig/przegladaniemonitorow",
	}

	Run("03.01.2020")
}
```
![1](https://user-images.githubusercontent.com/11431176/100323319-35f5c600-2fce-11eb-8d9f-05e58f01008d.png)

## What have you tried to solve the question
Im trying to download file on form submit, but page pause forever and download not begin...
What im doing wrong?
(example above is working)

**Comment by ysmood** [comment]
The first page will close itself immediately in the recent version of Rod.

This is wrong:

```go
page := browser.MustPages().First().MustWindowMaximize().MustNavigate(app.Url)
```

Change it to:

```go
page := browser.MustPage(app.Url)
```

**Comment by ysmood** [comment]
Released v0.82.0, the new way to download files:

https://github.com/go-rod/rod/blob/6d2822e6b8301076f3d2b09c5d7e2bd6c1dd99c0/examples_test.go#L458-L466

**Comment by ysmood** [comment]
@gregtczap Are you using the latest Rod version?

**Comment by gregtczap** [comment]
@ysmood Yeah I am using the latest version as of a week ago: v0.101.4

**Comment by ysmood** [comment]
@gregtczap But your error is a compiler error: `page.MustWaitDownload undefined (type *rod.Page has no field or method MustWaitDownload)`, maybe some old code cache issue?

**Comment by gregtczap** [comment]
@ysmood Yeah it's a compiler error, but it looks legitimate to me. The module is from a first-time install so nothing is cached. The godocs also do not list a `MustWaitDownload` method to exist on `rod.Page`, only on `rod.Browser`. I have also searched the `go-rod` source code and could not find any instances of a `MustWaitDownload` function being attached to `go.Page`, only to `rod.Browser`.

**Comment by ysmood** [comment]
@gregtczap Ah, I see, yes. We removed ii for page scope: 9eb7916

I remember it's a chromium bug. I'm not sure if it's fixed or not.
