### ISSUE TITLE
What if my program crash without disconnect the connection?

### ISSUE THREAD

**Issue by qiankunxienb** [go-rod/rod#292]
**Rod Version:** v0.81.3
Suppose I connect to the rod server, open a webpage, and then I close my program without disconnect. 

If I do this action for 1000 times, will memory leak occur? 

Are there some actions just like garbage collect---if I disconnect, then what I did will be revert and the resource will be release automatically?

**Comment by ysmood** [comment]
![image](https://user-images.githubusercontent.com/1415488/100330041-c86b8900-3011-11eb-9c6c-27c513b7a541.png)

**Comment by qiankunxienb** [comment]
thanks
