### ISSUE TITLE
How to set up a graceful shutdown

### ISSUE THREAD

**Issue by sosnovski** [go-rod/rod#293]
**Rod Version:** v0.81.3

I found that the luncher exits the browser as soon as the sigterm signal is received.
However, in my implementation I would like to wait for all commands to be executed before closing the browser.

How can this be achieved?

Code to reproduce:
```
package main

import (
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/go-rod/rod/lib/launcher"
)

func main() {
	l := launcher.New().Headless(false)
	defer l.Cleanup()

	l.MustLaunch()
	terminate := make(chan os.Signal, 1)
	signal.Notify(terminate, syscall.SIGINT, syscall.SIGTERM)
	<-terminate // at this moment the browser closes


	time.Sleep(20 * time.Second)
        // I would like the browser to be closed when the main function exits
}
```

**Comment by ysmood** [comment]
`launcher.New().Leakless(false)`

**Comment by sosnovski** [comment]
> launcher.New().Leakless(false)

I tried this first. It does not help

**Comment by ysmood** [comment]
Yes, because of how the OS works. Check this example, don't use os.Signal, use stdin: 

https://github.com/go-rod/rod/blob/master/lib/examples/use-rod-like-chrome-extension/main.go

**Comment by ysmood** [comment]
The os will pass the signal to all subprocesses, if you really want to pass a signal only to the current Go program, you have to detach the chrome process from it. Google detach process in Go.

You can use the `cmd` to detach:

https://github.com/go-rod/rod/blob/684d32090e4bc82a8d0a1aa04c20e3d9330c1822/lib/launcher/example_test.go#L11-L27

**Comment by sosnovski** [comment]
You can actually prevent child processes from being closed:

https://stackoverflow.com/questions/35433741/in-golang-prevent-child-processes-to-receive-signals-from-calling-process

This allows you to add the ability to pass context to the Connect method and terminate the child process by monitoring the context termination and signaling sigterm directly to the child process.

**Comment by ysmood** [comment]
👍  Sure, that's another way. Either way, you will use the `cmd` I answered.

I said use `detach` because I don't know your OS, it's easier and it's cross-platform. Use as few syscalls as possible.

**Comment by tpsmr** [comment]
#550
