### ISSUE TITLE
Google Experiment addition

### ISSUE THREAD

**Issue by beastfy** [go-rod/rod#296]
**Rod Version:** v0.83.0

Hi, 

Chrome has something called experimental preferences/experimental flags/experiments, usually located at chrome://flags/ , Im aware that some frameworks have solutions for it , like selenium ([link](https://www.kite.com/python/docs/selenium.webdriver.ChromeOptions.add_experimental_option)) and puppeteer ([link](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-user-preferences) ).

The goal of this addition would be for example to disable "save password pop up" ([screenshot](https://i.imgur.com/vNGF97i.png)) , on selenium uses something like this to disable it: 
```
options.add_preference("credentials_enable_service", false)
options.add_preference("password_manager_enabled", false)
```

Seems like its similar to the way we pass flags to the browser.

Thanks.

**Comment by ysmood** [comment]
`add_preference` is not defined in https://github.com/berstend/puppeteer-extra/search?q=add_preference

**Comment by ysmood** [comment]
Close because of inactive. Ask us to reopen if you have updates.
