### ISSUE TITLE
Add nil argument check for functions

### ISSUE THREAD

**Issue by dbuteyn** [go-rod/rod#300]
**Rod Version:** v0.83.0

## Steps to reproduce

- What did you do?
Called `page.Screenshot(true, nil)`.

- What have you tried to solve the problem?
Documentation does not say second argument is required:
https://pkg.go.dev/github.com/go-rod/rod#Page.Screenshot

## Expected behavior

What do you expect to get?
A buffer containing a PNG image.

## Actual result

What did you actually get?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x82c619]

goroutine 1 [running]:
github.com/go-rod/rod.(*Page).Screenshot(0xc0001d46c0, 0x99a601, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/go-rod/rod/page.go:325 +0x69
```

**Comment by ysmood** [comment]
Thanks for the report. Can you help us to update the doc of it?

**Comment by dbuteyn** [comment]
> Thanks for the report. Can you help us to update the doc of it? If you find similar issues, it will be great if you can directly make a PR to fix. We will be glad to merge it.

I simply wanted to benchmark my existing tests using this API as I found chromedp being rather slow. Unfortunately, just taking a screenshot turned out to be more complicated than it should have been so I decided to continue using chromedp.

I don't think this is just a documentation issue. Specifying `nil` for pointers should never cause segfaults. A simple `if ptr == nil { return nil, errors.New("Argument X is required") }` would have been much nicer.

**Comment by ysmood** [comment]
> I simply wanted to benchmark my existing tests using this API as I found chromedp being rather slow.

I think screenshot won't make a difference, the performance difference is trivial, seldom developers switch chromedp to rod because of it. If that's the only reason for you, then better to keep using chromedp, it's a great project.

>  I don't think this is just a documentation issue. Specifying nil for pointers should never cause segfaults. A simple if ptr == nil { return nil, errors.New("Argument X is required") } would have been much nicer.

Agree, add input runtime check is always better and more user friendly. I updated the title of this issue, hope it makes sense to you now. But one thing I need to mention, you learn the source code of golang, when a required argument is missing we should always panic it, not return an error, it's usually unrecoverable. Such as:

```go
if ptr == nil { panic("Argument X is required") }
```

If you are super picky, you may even ask us to check if the page is nil or not on all functions because you can do:

```go
var page *rod.Page
page.Screenshot(true, nil)
```

Usually, this kind of issue doesn't need doc, because you can find out and fix it immediately by the panic stack trace. If an error can take you more than 2min to find out then we should either doc it or add some runtime guard for it.

Usually, when the project is mature we will take more time to add friendly error checks to improve UX, we just don't have enough human resources to prioritize it, hope you can understand.

**Comment by dbuteyn** [comment]
> > I simply wanted to benchmark my existing tests using this API as I found chromedp being rather slow.
> 
> I think screenshot won't make a difference, the performance difference is trivial, seldom developers switch from chromedp to rod because of it. If that's the only reason for you, then better to keep using chromedp, it's a great project.

I have existing tests that each take ~20-30 seconds to run, even with animations and transitions disabled. For one test this is fine, but eventually there will be hundreds of tests, causing our build pipeline to take several hours. I guess once we reach that stage I'll have no choice but to parallelize our pipeline further and run chunks of UI tests on multiple nodes concurrently.

The screenshot thing was just to see whether I could get this module working.

> > I don't think this is just a documentation issue. Specifying nil for pointers should never cause segfaults. A simple if ptr == nil { return nil, errors.New("Argument X is required") } would have been much nicer.
> 
> Agree, input runtime check is always better and more user-friendly. I updated the title of this issue, hope it makes sense to you now. But one thing I need to mention, if you learn the source code of golang, when a required argument is missing we usually panic it, not return an error, because it's usually unrecoverable. Such as the below might be better:

Missing arguments have always been considered invalid arguments, no matter which language. Also, a segfault is not a panic. Panic is comparable to an uncaught exception where the runtime has a chance to terminate the program in a nice manner. Segmentation faults are triggered by the CPU (application tried to access a memory page in a manner it is not allowed to) and cause the operating system to forcefully terminate the process.

While the called function itself may not be able to recover, it does not mean that the rest of the program cannot continue. For the case of automation, a segfault means that none of my other tests will run. Most likely none of the cleanup stages of currently running tests will be executed either, resulting in lots of "mess" (leftover files, etc).

If the called function instead returned a plain error, it would result in just this one test case failing and the reason of the failure being logged (invalid argument). Fixing the issue will be somewhat more tedious because unlike other languages, go does not tell you _where_ the error occurred (no stack trace). But, there are lots of existing 3rd-party modules that can help with that.

There are methods to continue execution after a segfault such as installing signal handlers (I have written scanners that search foreign process memory in real-time) but doing so is overkill just to trap missing arguments on a program in my control.

> Usually, when the project is mature we will take more time to add friendly error checks to improve UX, we just don't have enough human resources to prioritize it, hope you can understand. Currently, I only doc arguments that are optional, the doc will usually be "what's the default value".

That is fine. We are all human.

**Comment by ysmood** [comment]
> There are methods to continue execution after a segfault such as installing signal handlers (I have written scanners that search foreign process memory in real-time) but doing so is overkill just to trap missing arguments on a program in my control.

If you know a little about how `runtime` works you wouldn't say something like this.
Just a `recover` will do the job, for example, the code before will print "OK" without any problem:

```go
package main

import (
	"fmt"

	"github.com/go-rod/rod"
)

func main() {
	err := rod.Try(func() {
		rod.New().MustConnect().MustPage("http://github.com").Screenshot(false, nil)
	})
	fmt.Println(err)

	fmt.Println("OK")
}
```

> While the called function itself may not be able to recover, it does not mean that the rest of the program cannot continue. For the case of automation, a segfault means that none of my other tests will run. Most likely none of the cleanup stages of currently running tests will be executed either, resulting in lots of "mess" (leftover files, etc).

I think you misunderstand my point, please think twice.
It's like crash the program to tell the developer you are doing something wrong, please fix your code then run it again. This kind of obvious issues will be super hard to hide as long as you at least tested your code once before you ship it:

1. forget to pass an argument
1. run the code on local
1. crash with error "missing argument", golang will tell you which line you should fix
1. have to add the missing argument so the code will work
1. run the code again, now it works
1. commit the code

**Comment by dbuteyn** [comment]
> > There are methods to continue execution after a segfault such as installing signal handlers (I have written scanners that search foreign process memory in real-time) but doing so is overkill just to trap missing arguments on a program in my control.
> 
> Are you sure you understand how `runtime` works?
> Just a `recover` will do the job, for example, the code below will print "OK" without any problem:

I was talking about catching segfaults in C during linked lists and tree traversal in arbitrary processes while the target process is actively making changes. I had zero control over pointer values and address space so any and all code touching the foreign address space would cause a segfault. My only option was to write defensively and rewind to a known good state when a segfault occurred.

> I think you misunderstand my point, please think twice.
> It's like crash the program to tell the developer you are doing something wrong, please fix your code then run it again. This kind of obvious issues will be super hard to hide as long as you at least tested your code once before you ship it:
....

I agree with you, throwing some kind of exception is often desired (fail early, fail loudly). There is a difference however between _crashing_ and _throwing an exception_. Libraries should never intentionally crash their calling applications. The application may be mission-critical and capable of continuing, regardless of failures. Libraries crashing their caller is the basis for a lot of denial-of-service attacks.

Maybe the Go runtime is capable of `recover()`-ing from a segfault but to me it smells all kinds of wrong.

> Please see how Go team designs their code: https://github.com/golang/go/blob/c15593197453b8bf90fc3a9080ba2afeaf7934ea/src/net/dial.go#L369-L372

That's clearly a panic intended to avoid a segfault. There are lots of examples such as `errMissingAddress` and `UnknownNetworkError` in the same file that specifically deal with invalid arguments.

The only panic in that entire file is thrown when `context` is `nil` which probably has more to do with existing expectations regarding `context.Context` handling than anything else.

In any case, considering that all parameters of `PageCaptureScreenshot` are optional, it makes little sense for `Page.Screenshot` to require parameters. I've made two possible pull requests. Pick your poison.
