### ISSUE TITLE
Calling browser.Pages() never returns

### ISSUE THREAD

**Issue by dbuteyn** [go-rod/rod#301]
**Rod Version:** v0.83.0

## Steps to reproduce

- What did you do?
Called `browser.Pages()`.

- What have you tried to solve the problem?
Used `browser.MustPage()` instead.

## Expected behavior

What do you expect to get?
By default, headless Chromium will have one tab open with a blank page (about:blank). I wanted to navigate using this this page but calling `browser.Pages()` simply hangs and fails to return this one page.

## Actual result

What did you actually get?
Process freezes.

**Comment by ysmood** [comment]
dup of #283

**Comment by ysmood** [comment]
You can disable the self-close page by set a launch flag:

```go
launcher.New().Set("", "about:blank").MustLaunch()
```

**Comment by dbuteyn** [comment]
> You can disable the self-close page by setting a launch flag:
> Read the source code of Launcher.New, you will understand:
> 
> But I don't recommend to using this init page, Chrome usually need some time to create this page, you may not be able to get it on slow machine, your program can be flaky.

The command line arguments and startup options should be documented. Telling users to read source is not a particularly great suggestion...

In my experience with chromedp and using the Chrome DevTools Protocol directly, even on a VM I never ran into the issue of the initial page not existing when calling "Page.navigate". I always found http://localhost:9222/json populated with at least one target, always having the URL set to about:blank.

**Comment by ysmood** [comment]
> The command line arguments and startup options should be documented. Telling users to read source is not a particularly great suggestion...

Agree, thanks for the suggestion, I feel the same. I think you have a really good sense about it, can you help us on it? I think your doc will be much better than me.

> In my experience with chromedp and using the Chrome DevTools Protocol directly, even on a VM I never ran into the issue of the initial page not existing when calling "Page.navigate". I always found http://localhost:9222/json populated with at least one target, always having the URL set to about:blank.

Have you tried it on slow Windows? If you check our history of Github Action CI, Windows triggered this issue many times.

**Comment by dbuteyn** [comment]
> > In my experience with chromedp and using the Chrome DevTools Protocol directly, even on a VM I never ran into the issue of the initial page not existing when calling "Page.navigate". I always found http://localhost:9222/json populated with at least one target, always having the URL set to about:blank.
> 
> Have you tried it on slow Windows? If you check our history of Github Action CI, Windows triggered this issue many times.

Can't say I have, no.  Maybe a Windows-specific problem. We're running everything on Linux.
