### ISSUE TITLE
Add a helper to recover from browser crash?

### ISSUE THREAD

**Issue by milkwine** [go-rod/rod#302]
Sometimes `chrome` will crash, cdp log here:
```
[cdp] 2020/12/06 15:09:09 <- @DCA4F5D7 Inspector.targetCrashed {}
[cdp] 2020/12/06 15:09:09 <- @00000000 Target.targetCrashed {"targetId":"56CFC1D2ACB81528C8356CF4EF358C72","status":"abnormal","errorCode":256}
[cdp] 2020/12/06 15:09:09 EOF
```
It's hardly to reproduce this problem everytime,  I have not go too much deeper in chrome yet.
Cdp client will close when it occurs, after that `context canceled` will returned by every rod(`browser` or `page` obj) operation.

https://github.com/go-rod/rod/blob/5b3ca5dc34f669342a482608e9673aa5a79c72ee/lib/cdp/client.go#L197-L209

I solved this temporarily by relaunch a new browser when get `context canceled` error.

Here is my consideration:
1. Maybe can make the error more clearly, like  `browser crashed` or  something.
2. Maybe can offer some `relaunch` strategies, like: relaunch browser when retry times in same operation less than 3.

(Thanks this library, it makes my work much more easier.)

**Comment by ysmood** [comment]
Definitely we should make the error info more friendly. But auto relaunch is hard to design, because if you are controling a remote browser like browserless, it's hard to distinguish between loss of connection or browser crash, they will both result in loss of websocket connection. Chrome doesn't allow reconnect for lost connection.

Any ideas?

**Comment by ysmood** [comment]
v0.84.3 optimized the error of the lost connection, now you can detect the error type like below:

https://github.com/go-rod/rod/blob/2c53d83d30bf6344e6589ae84e50fb7ae75a2375/browser_test.go#L168-L173

Then you can decide whether to relaunch a browser or not.
