### ISSUE TITLE
How to compare elements with each other

### ISSUE THREAD

**Issue by BoladoDevelopment** [go-rod/rod#307]
**Rod Version:** v0.84.1

## The code to demonstrate your question

```go
func getIndexOfSliceValue(slice []*rod.Element, value *rod.Element) int {
	var index int
	for i := 0; i < len(slice); i++ {
		if value.MustHTML() == slice[i].MustHTML() {
			index = i
			break
		}

	}
	return index
}
```

## What have you tried to solve the question

Currently, I have been using the code above to get the index number of an element from an element list, it works, but I think it must be time and resource consuming to use MustHTML() to compare elements.

**Comment by ysmood** [comment]
Some pseudo-code, you get the idea:

```go
func (a *Element) Equal (b *Element) bool {
     return a.MustEval(`b => this === a`, b).Bool()
}
```

Can you help to raise an PR to add this method to Rod, I think it will be useful.
