### ISSUE TITLE
How to add Chrome parameters?

### ISSUE THREAD

**Issue by smp12345** [go-rod/rod#313]
How should I set Chrome startup parameters such as "--user-data-dir" to specify user directories, "-- Start-Maximized" window to maximize? Any examples of that?

**Comment by smp12345** [comment]
Rod Version：0.85.8，Please help me, thank you

**Comment by ysmood** [comment]
https://pkg.go.dev/github.com/go-rod/rod/lib/launcher#Launcher.Set

**Comment by smp12345** [comment]
Thank you
