### ISSUE TITLE
chrome window is zoomed in for the first time

### ISSUE THREAD

**Issue by smp12345** [go-rod/rod#314]
Rod Version: v0.85.8
OS:win10
Go Version : go1.15.6 windows/amd64
## Steps to reproduce

- What did you do?
- When I first opened Chrome and visited the first TAB, the page was zoomed first and then maximized

## Expected behavior

What do you expect to get?
When I open Chrome, just maximize the display 100% ，without scaling first and then maximizing.

First: Thumbnails
![1](https://user-images.githubusercontent.com/50661521/102710425-2e83bd00-42ed-11eb-9608-511b8d39ad45.png)
Second: Maximize display
![2](https://user-images.githubusercontent.com/50661521/102710430-35123480-42ed-11eb-9cdf-9e3c9309aa11.png)

**Comment by ysmood** [comment]
Please read [Don't rush to claim that you have found a bug.](http://www.catb.org/~esr/faqs/smart-questions.html#idm368)

**Comment by ysmood** [comment]
dup of #274

**Comment by smp12345** [comment]
Add NoDefaultDevice to solve this problem. Thank you
