### ISSUE TITLE
How do you determine if the load is complete for requests like XHR and FETCH?

### ISSUE THREAD

**Issue by smp12345** [go-rod/rod#316]
Some websites are partially refreshed by XHR. The wait function does not seem to work. You can only use time.sleep, but time.sleep does not know how long to sleep, if not sleep, Mustclick will produce panic.
Do you have any good solutions? thank you

**Comment by smp12345** [comment]
**Rod Version:** v0.85.9

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/c6c386454cc28cde15667d26919c96b543991979/examples_test.go#L461-L497

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/c6c386454cc28cde15667d26919c96b543991979/examples_test.go#L293-L314

**Comment by smp12345** [comment]
Let me test that out. Thank you. Can I get back the body of the response that comes back from each request? Such as the json data

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/c6c386454cc28cde15667d26919c96b543991979/examples_test.go#L461-L497

**Comment by smp12345** [comment]
I refer to the above example and add some code, but still pannic
wait := tmall.signUpPage.MustWaitRequestIdle()
tmall.signUpPage.MustElement(`(//button[text()='xx'])[1]`).MustClick()
wait()
fmt.Println(len(tmall.signUpPage.MustElementsX(`(//button[text()='xx'])[1]`)) > 0)

**Comment by smp12345** [comment]
panic: element covered by: <div class="nrs-comp-TMCRealSaleItemList"><div> .....

**Comment by ysmood** [comment]
Read the error, learn some English 😂 , I think you can solve it by yourself. Search the error info in this repo.

**Comment by smp12345** [comment]
Forgive the newbie, what country are you from?

**Comment by ysmood** [comment]
If you want to chat, go to the Chat room, the link is in the readme.

**Comment by smp12345** [comment]
According to your hint, I probably know the reason, but I can't directly mustremove, otherwise the element I need to click will be deleted, I don't know much about the website development front end

**Comment by smp12345** [comment]
Why is it that after I increase sleep for a while, it doesn't go wrong

**Comment by ysmood** [comment]
As long as the website is not a malicious website, there will be a button to close the floating modal.

**Comment by smp12345** [comment]
I want to click on the element wrapped in this div, directly deleted, I want to click on the element has also been deleted

**Comment by smp12345** [comment]
Your chat room I verify email network timeout, I can see you chat, but can't talk

**Comment by ysmood** [comment]
Please learn the link before continue, or sorry I won't spend more time on this issue: https://github.com/go-rod/rod/blob/master/.github/CONTRIBUTING.md

**Comment by smp12345** [comment]
This is the structure of the web page, I want to click the position of the number 2 in the picture, but the position of 2 May be blocked by 1, the system panic, look at the above two pictures
![web structure](https://user-images.githubusercontent.com/50661521/102778975-79293600-43ce-11eb-95e5-66a885d4f3fe.png)
![panic](https://user-images.githubusercontent.com/50661521/102778979-7af2f980-43ce-11eb-9ef2-5172d2cef834.png)

**Comment by smp12345** [comment]
I may have solved it, but I am still testing it for some time to see the stability. Thank you for your help
