### ISSUE TITLE
Cannot hijack requests cached by the service worker.

### ISSUE THREAD

**Issue by turboza** [go-rod/rod#318]
**Rod Version:** v0.82.1

## Steps to reproduce

I tried to hijack the request from the website with the service worker, like `https://twitter.com/home`.

So that I can retrieve the JSON response from the request which is stable than retrieving from HTML. 

Somehow, the requests are all missing from the hijack router.

The full sample code.

```go
func main() {
	l := launcher.New().
		Headless(false).
		Leakless(false)

	browser := rod.New().
		Timeout(time.Second * 15).
		ControlURL(l.MustLaunch()).
		Trace(true).
		MustConnect()

	router := browser.HijackRequests()
	router.MustAdd("*", func(ctx *rod.Hijack) {
		fmt.Println("Hijacked URL:", ctx.Request.URL())
		ctx.MustLoadResponse()
	})
	go router.Run()

	page := browser.MustPage("https://twitter.com/home")
        wait := page.MustWaitRequestIdle()
	wait()
}
```

## Expected behavior

All requests should be hijacked like normal website. But somehow, they are not.

If we directly visited a website, we would see several requests in the network tab, while they are not in the actual result.

![image](https://user-images.githubusercontent.com/761819/102777150-9e17ac00-43c2-11eb-80b6-0505fc7a4f9e.png)

## Actual result

```
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/polyfills.4d8d59c5.js
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/vendors~main.f7f618b5.js
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/main.f51fb665.js
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/i18n/en.fa8270e5.js
```

I guess it is because the web with service work cannot be hijacked, as I found in the puppeteer issue https://github.com/puppeteer/puppeteer/issues/4041#issuecomment-469496322

**Comment by turboza** [comment]
I tried to bypass the service worker as suggested by @ysmood, but the result is still the same. Not sure if I did correctly though. 

Code:
```go
func main() {
	l := launcher.New().
		Headless(false).
		Leakless(false)

	browser := rod.New().
		Timeout(time.Second * 15).
		ControlURL(l.MustLaunch()).
		Trace(true).
		MustConnect()

	router := browser.HijackRequests()
	router.MustAdd("*", func(ctx *rod.Hijack) {
		fmt.Println("Hijacked URL:", ctx.Request.URL())
		ctx.MustLoadResponse()
	})
	go router.Run()

	page, err := browser.Page(proto.TargetCreateTarget{})
	if err != nil {
		panic(err)
	}

	err = proto.NetworkSetBypassServiceWorker{Bypass: true}.Call(page)
	if err != nil {
		panic(err)
	}

	page.MustNavigate("https://twitter.com/login")
	wait := page.MustWaitRequestIdle()
	wait()
}
```

Result:
```
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/polyfills.4d8d59c5.js
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/vendors~main.f7f618b5.js
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/main.f51fb665.js
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/i18n/en.fa8270e5.js
```

**Comment by ysmood** [comment]
Can you give some description about why you have to hijack service work?

**Comment by turboza** [comment]
@ysmood I tried to get the data from the JSON in the request which is more stable than parsing from the HTML. 

Updated the desc 😄 .

**Comment by ysmood** [comment]
How do you confirm the JSON is handled by the service work?

**Comment by turboza** [comment]
@ysmood I checked the network request logging and see the initiator is the `serviceworker`. Also there will be a gear icon on the left of the request. However, I am not 100% sure it is because of the service worker. 

![image](https://user-images.githubusercontent.com/761819/102790844-ac70c280-43d8-11eb-9afc-ea63f9e76180.png)

**Comment by ysmood** [comment]
`err = proto.NetworkSetBypassServiceWorker{Bypass: true}.Call(page)`

Shouldn't the `Bypass` be set to false?

**Comment by ysmood** [comment]
You can also use env `rod=cdp` to enable the debug log to see all the network events from the console, you should be able to find the service worker request there.

**Comment by turboza** [comment]
I guess `Bypass: true` should be correct. However, I tried `Bypass: false` and the result is the same. 

```go
// NetworkSetBypassServiceWorker (experimental) Toggles ignoring of service worker for each request.
type NetworkSetBypassServiceWorker struct {

	// Bypass Bypass service worker and load from network.
	Bypass bool `json:"bypass"`
}
```

**Comment by turboza** [comment]
I am not sure how, did you mean this?

```sh
$ env ROD=cdp
$ go run path_to_sample/main.go
```

**Comment by ysmood** [comment]
https://en.wikipedia.org/wiki/Environment_variable

```bash
rod=cdp go run path_to_sample/main.go
```

https://pkg.go.dev/github.com/go-rod/rod@v0.85.9/lib/defaults

**Comment by turboza** [comment]
So far, I have managed to get all the hijack requests by waiting differently.

It seems the root cause for this case seems to be `MustWaitRequestIdle()` does not wait all the requests, so it terminates early. any idea? 

```go
func main() {
	...
	router := browser.HijackRequests()
	router.MustAdd("*", func(ctx *rod.Hijack) {
		fmt.Println("Hijacked URL:", ctx.Request.URL())
		ctx.MustLoadResponse()
	})
	go router.Run()

	browser.MustPage("https://twitter.com/home")
        
        time.Sleep(10 * time.Second)
}
```

Result:
```sh
Hijacked URL: https://twitter.com/home
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/polyfills.4d8d59c5.js
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/vendors~main.f7f618b5.js
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/i18n/en.fa8270e5.js
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/main.f51fb665.js
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/sharedCore.b008c955.js
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/ondemand.Dropdown.9088a8f5.js
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/loader.AppModules.dfbd7225.js
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/loader.SideNav.911fe7c5.js
Hijacked URL: https://pbs.twimg.com/hashflag/config-2020-12-22-07.json
Hijacked URL: https://api.twitter.com/1.1/guest/activate.json
Hijacked URL: https://abs.twimg.com/responsive-web/client-web/bundle.NetworkInstrument.8cd49fb5.js

# And more
```

**Comment by ysmood** [comment]
Use `sync.WaitGroup` for the request you want to wait.

**Comment by turboza** [comment]
@ysmood I cannot follow here. could you provide more code example? like when to do `wg.Add(1)`?

**Comment by ysmood** [comment]
What do you want to do? Get the content of the JSON?

**Comment by ysmood** [comment]
Close because of no respond.
