### ISSUE TITLE
How do I intercept XHR response data triggered by a button?

### ISSUE THREAD

**Issue by smp12345** [go-rod/rod#320]
**Rod Version:** v0.85.9

I refer to the Example_hijack_requests example, which can intercept all requests for page normally. When the page is loaded, I click on a button on the page, and the asynchronous XHR request will be triggered. HijackRequests seem to have no effect.So what should I do to get the returned JSON data

**Comment by ysmood** [comment]
Can you provide minimal code for us to reproduce your issue?

**Comment by smp12345** [comment]
I wanted to intercept the JSON data after Clicking the query button, but the MustAdd function didn't output it, so it didn't seem to capture it

func main(){
	launch := launcher.NewUserMode()
	wsUrl := launch.MustLaunch()
	browser := rod.New().ControlURL(wsUrl).MustConnect().NoDefaultDevice()

	router := browser.HijackRequests()
	defer router.MustStop()

	router.MustAdd("http://www.kuaidi.com/index-ajaxselectcourierinfo-773058962040428-shentong-UUCAO*", func(ctx *rod.Hijack) {
		fmt.Println("**************")    // The asterisk has no output, indicating that it has not been executed
		ctx.MustLoadResponse()
                fmt.Println(ctx.Response.Body())
	})

	go router.Run()

	page:=browser.MustPage("http://www.kuaidi.com/")
	page.MustElementX(`//*[@id="search"]`).MustInput(`773058962040428`)
	page.MustElementX(`//*[@id="container"]/div/div/div[2]/div[1]/div[1]/a`).MustClick()
	time.Sleep(1*time.Hour)
}

![xhr_request](https://user-images.githubusercontent.com/50661521/103012840-2048d180-4577-11eb-9f84-14c18dd34e46.png)

**Comment by smp12345** [comment]
I want to get the json data back
![Uploading response_json_data.png…]()

**Comment by ysmood** [comment]
Not reproducible, can't help.

**Comment by smp12345** [comment]
You run the above code directly. Is there an asterisk output?My computer system is Win10  @ysmood

**Comment by smp12345** [comment]
![stdout](https://user-images.githubusercontent.com/50661521/103043736-e993ab00-45b8-11eb-95f9-8f4f06be9457.png)

**Comment by ysmood** [comment]
#322
