### ISSUE TITLE
How do I display CDP logs ?

### ISSUE THREAD

**Issue by smp12345** [go-rod/rod#325]
**Rod Version:** v0.85.9

How do I display the CDP log instead of the Rod log? 
Can you give an example for reference？

**Comment by ysmood** [comment]
Learn this first: https://en.wikipedia.org/wiki/Environment_variable

Then on Unix:

```bash
rod=cdp go run main.go
```

On Windows, learn the link above.

**Comment by smp12345** [comment]
可以看到cdp日志了，我昨天点击一个页面的按钮，点击了没有反应，我直接用js点击是可以的，日志如下：
我怀疑可能是因为没有mouseMoved，被识别到了，只有mouseReleased和mousePressed，造成点击失效，我记得selenium是有mouseMoved事件的 @ysmood

[cdp] 2020/12/26 12:37:34 => #130 @201823FA Input.dispatchMouseEvent {"type":"mousePressed","x":909.9344787597656,"y":334.483047485351
56,"button":"left","buttons":1,"clickCount":1}
[cdp] 2020/12/26 12:37:34 <= #130 {}
[cdp] 2020/12/26 12:37:34 <- @201823FA DOM.attributeModified {"nodeId":76,"name":"data-spm-anchor-id","value":"a21xr.12606288.sale.i0.
7eea47a1wU5SEI"}
[cdp] 2020/12/26 12:37:34 => #131 @201823FA Input.dispatchMouseEvent {"type":"mouseReleased","x":909.9344787597656,"y":334.48304748535
156,"button":"left","clickCount":1}

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/95208cfc67f4546ff374145cbea1ff572f3e3570/element.go#L77

**Comment by smp12345** [comment]
你是对的，确实有mouseMoved，前几天这个网站是可以正常点击的，但从昨天开始，MustClick点击就失效了，点了和没点一样，毫无反应，因为这个网站是需要登陆的，所以我不能给出问题复现的测试环境。还有一些什么原因造成点击失效呢，程序也没有报错，正常往下走

**Comment by ysmood** [comment]
你给的信息太少了，可能性太多了。那就得自己 debug 了，rod 源代码很容易读才对

**Comment by smp12345** [comment]
我先自己折腾一下吧，我和selenium对比了一下，dispatchMouseEvent 传的参数比selenium少。我再请教一下，可以支持后台运行吗？比如最小化窗口，不影响正常工作

**Comment by ysmood** [comment]
不用问我的，请自己搜索关键字
