### ISSUE TITLE
Don't use eval in ElementR

### ISSUE THREAD

**Issue by infinitepr0** [go-rod/rod#328]
Thinking about it more, PR #327 has the following disadvantage - Injection attacks are not prevented in `HasR` (and other regex methods using `ElementR`).

I suggest stripping the eval, and instead using regex to extract the flags from the regex. See [this](https://github.com/IonicaBizau/regex-parser.js/blob/master/lib/index.js) module for implementation details.

**Comment by infinitepr0** [comment]
Any downsides to this approach? We can remove `ElementRF` too, with this implementation.

**Comment by ysmood** [comment]
No downsides, good idea!
