### ISSUE TITLE
May stuck when getting NetworkResponseReceived.

### ISSUE THREAD

**Issue by Srar** [go-rod/rod#331]
**Rod Version:** v0.86.2

## Steps to reproduce

Try to get the header of Page such as https://wework.paratera.com/.

首先非常感谢作者做出如此易用的库。在使用过程中爬取某些特殊页面Header时，例如：https://wework.paratera.com/ 会造成卡住的现象。同时经过搜索也没寻找到可以设置超时的地方。

```
package main

import (
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/proto"
	"github.com/go-rod/rod/lib/utils"
	"log"
)

func main() {
	browser := rod.New().MustConnect()

	page := browser.MustPage("")

	var e proto.NetworkResponseReceived

	wait := page.WaitEvent(&e)
	page.MustNavigate("https://wework.paratera.com/")
	wait()

	log.Println(utils.Dump(e.Response.RequestHeaders))
	log.Println(utils.Dump(e.Response.Status, e.Response.URL, e.Response.Headers))
}
```

> The code from #213.

## Expected behavior

Get the header of Page successfully or return an error.

## Actual result

Got stuck on waiting NetworkResponseReceived when navigating to especial page.

**Comment by ysmood** [comment]
add `go page.MustHandleDialog(true, "")()` before `page.MustNavigate("https://wework.paratera.com/")`

**Comment by ysmood** [comment]
请阅读下面的链接，否则下次我不会再回答你的问题，而是直接关闭 issue

Please read [Don't rush to claim that you have found a bug.](http://www.catb.org/~esr/faqs/smart-questions.html#idm368)

**Comment by Srar** [comment]
非常感谢答复，第一次使用模板创建issue错误的选择了`Bug report`非常抱歉。

Thanks for your answer, Sorry for using the template to create the wrong type of issue for the first time.

**Comment by cecobask** [comment]
Hi @ysmood, sorry for reviving an old issue. I'm facing the same problem.
However, when I add `go page.MustHandleDialog()`, the app crashes with:
```
panic: assignment to entry in nil map

goroutine 94 [running]:
github.com/go-rod/rod.(*Page).setHelper(0x14000400000, {0x1400016ca38, 0x17}, {0x102930f94, 0x7}, {0x140003e00a8, 0x17})
        /Users/dtsvetoslav/go/pkg/mod/github.com/go-rod/rod@v0.116.1/page_eval.go:320 +0x104
github.com/go-rod/rod.(*Page).ensureJSHelper(0x14000400000, 0x10329f680)
        /Users/dtsvetoslav/go/pkg/mod/github.com/go-rod/rod@v0.116.1/page_eval.go:292 +0x73c
github.com/go-rod/rod.(*Page).formatArgs(0x14000400000, 0x140000b6700)
        /Users/dtsvetoslav/go/pkg/mod/github.com/go-rod/rod@v0.116.1/page_eval.go:234 +0x2a0
github.com/go-rod/rod.(*Page).evaluate(0x14000400000, 0x140000b6700)
        /Users/dtsvetoslav/go/pkg/mod/github.com/go-rod/rod@v0.116.1/page_eval.go:150 +0x48
github.com/go-rod/rod.(*Page).Evaluate(0x14000400000, 0x140000b6700)
        /Users/dtsvetoslav/go/pkg/mod/github.com/go-rod/rod@v0.116.1/page_eval.go:129 +0x4c
github.com/go-rod/rod.(*Page).Overlay(0x14000400000, 0x0, 0x0, 0x407f400000000000, 0x0, {0x1400002caa0, 0x1d})
        /Users/dtsvetoslav/go/pkg/mod/github.com/go-rod/rod@v0.116.1/dev_helpers.go:117 +0x2e8
github.com/go-rod/rod.(*Page).tryTrace(0x14000400000, {0x10292cd7c, 0x4}, {0x140000b66c0, 0x3, 0x4})
        /Users/dtsvetoslav/go/pkg/mod/github.com/go-rod/rod@v0.116.1/dev_helpers.go:143 +0x314
github.com/go-rod/rod.(*Page).WaitLoad(0x14000400000)
        /Users/dtsvetoslav/go/pkg/mod/github.com/go-rod/rod@v0.116.1/page.go:859 +0xa8
github.com/cecobask/imdb-trakt-sync/pkg/client.navigateAndValidateResponse(0x14000400000, {0x140005481b0, 0x25})
```

Any other ideas on how to check the response status code of a page, after navigating to it?

**Comment by ysmood** [comment]
@cecobask This looks like a bug of rod, could you open a new issue with reproducible code, so that I can help.

**Comment by cecobask** [comment]
> @cecobask This looks like a bug of rod, could you open a new issue with reproducible code, so that I can help.

I tried to create a reproducible sample but didn't manage to. My use case involved spawning multiple tabs into go routines.
What fixed it for me was to move the call to `go tab.MustHandleDialog()` before `tab.WaitEvent(&event)`. Not sure what could've caused this.

**Comment by ysmood** [comment]
Yes, you must wait the event before it happens.
