### ISSUE TITLE
How to determine whether the request is a navigation request in HijackRequests？

### ISSUE THREAD

**Issue by Threezh1** [go-rod/rod#336]
How to determine whether the request is a navigation request in HijackRequests？

The function I want to achieve is:

**Intercept navigation request**: judge the request and intercept it while returning status 204, so that the browser can not only send out the request, but also prevent the page from jumping. But I didn't see the relevant judgment method in HijackRequest.

**Comment by ysmood** [comment]
Can you make a PR to add `HijackRequest.IsNavigation()`?

By using [HijackRequest.Type ](https://pkg.go.dev/github.com/go-rod/rod#HijackRequest.Type) == [proto.NetworkResourceTypeDocument](https://pkg.go.dev/github.com/go-rod/rod@v0.88.10/lib/proto#NetworkResourceType)

**Comment by Threezh1** [comment]
This is the first time I have encountered a problem when writing a go program, so there may be problems with my increased PR. Hope you can fix it for me. Thank you!
