### ISSUE TITLE
ability to hijack fetch/xmlhttprequest with proxy client

### ISSUE THREAD

**Issue by poprer656sad** [go-rod/rod#338]
**Rod Version:** v0.88.10

```go
router.MustAdd("*", func(ctx *rod.Hijack) {
		log.Print(ctx.Response)
		ctx.LoadResponse(&client, true)
	})

	go router.Run()
	page.MustNavigate( some site here )

	page.MustEval(`(endpoint)=>{j = new XMLHttpRequest(); j.open("POST", endpoint); j.send()}`, posturl)
```

when evaluating xmlhttprequest, client is not used. the request is hijacked, and headers, methods can be seen, but the ip is of the main machine's not a proxy (when http.client is through a proxy)

there is an options request preflight, and rod can display that, but that too is not using client to send, rather, main machine's ip

**Comment by ysmood** [comment]
Please fix your issue after reading this: http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by ysmood** [comment]
Close because of inactive

**Comment by zobx** [comment]
l := launcher.New().Headless(false)
l.Set("proxy-server", "http://127.0.0.1:8008")

我也遇到了这个问题, 使用rod.Hijack的时候，里面劫持的请求没有使用代理ip请求，而是使用本地ip请求
请问有解决方案吗

**Comment by ysmood** [comment]
Sorry, we can't reproduce it. Can you provide minimal code and steps for us to reproduce your issue?
