### ISSUE TITLE
got "Could not compute content quads." sometimes when use MustWaitInteractable() with the slow internet.

### ISSUE THREAD

**Issue by KendoJaaa** [go-rod/rod#339]
I'm not sure this is considered a bug. It might be a bug or a question. 

I have to deal with element that visible but not interactable.
In case of MustClick => the error will say something cover the element.
In case of MustInput => it will pass silencely but nothing happen 

I use MustWaitInteractable to wait to deal with the problem but sometimes I got the error.
I guess the problem only occurs when using slow internet.

**Rod Version:** v0.88.10

## Steps to reproduce
```
package main

import (
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"time"
)

func main() {

	l := launcher.New().
		Headless(false)

	browser := rod.New().
		Timeout(time.Second * 60).
		ControlURL(l.MustLaunch()).
		Trace(true).
		SlowMotion(0).
		MustConnect()

	page := browser.MustPage("https://iservice.truecorp.co.th/")
	page.MustElement("#login_text_box_textbox_field").MustWaitInteractable().MustInput("12345")
}
```
- What did you do?
I tried to input some number inside the text input.

- What have you tried to solve the problem?
I upgraded go rod to the latest version to use MustWaitInteractable() which is not available before. 
I did this before and found the same problem
```
interactable := false
for !interactable {
   interactable = page.MustElement("xxx").MustInteractable()
}
```

## Expected behavior

What do you expect to get?
- I expect to always get no error from the code being run. 
- the number should be inserted in the input box

## Actual result

What did you actually get?
```
[rod] 2021/01/19 16:15:38 [query] rod.element("#login_text_box_textbox_field")  page:F78F033E1E05F81D6C3B7A6194006DE7
[rod] 2021/01/19 16:15:38 [query] rod.element("#login_text_box_textbox_field")  page:F78F033E1E05F81D6C3B7A6194006DE7
[rod] 2021/01/19 16:15:38 [query] rod.element("#login_text_box_textbox_field")  page:F78F033E1E05F81D6C3B7A6194006DE7
[rod] 2021/01/19 16:15:39 [query] rod.element("#login_text_box_textbox_field")  page:F78F033E1E05F81D6C3B7A6194006DE7
[rod] 2021/01/19 16:15:41 [query] rod.element("#login_text_box_textbox_field")  page:F78F033E1E05F81D6C3B7A6194006DE7
[rod] 2021/01/19 16:15:42 [query] rod.element("#login_text_box_textbox_field")  page:F78F033E1E05F81D6C3B7A6194006DE7
[rod] 2021/01/19 16:15:42 [wait] interactable input#login_text_box_textbox_field._2vUn1dlNQLx672lJGkeIGs.yB91L4MJDLhA7twfy9bw2
panic: {-32000 Could not compute content quads. }

```

**Comment by ysmood** [comment]
v0.88.11 should have fixed it.
