### ISSUE TITLE
Cannot open page with new Chrome 88

### ISSUE THREAD

**Issue by alufrew** [go-rod/rod#341]
**Rod Version:** v0.81.1

## Steps to reproduce

1. Update new Chrome Version 88.0.4324.96 (Official Build) (x86_64).
2. Try to use MustPage for any site. f.e.:
```
browser := rod.New().MustConnect()
page := browser.MustPage("https://google.com")
```

## Expected behavior
Page should be opened.

## Actual result
Code exits with panic. 
`panic: invalid character '.' after top-level value`

## Investigation notes
Installing previous Chrome version helps. So it seems the problem appears only on lates Chrome.

**Comment by ysmood** [comment]
Please try the latest v0.89.0 of Rod.

**Comment by alufrew** [comment]
Thanks. Sorry. I've thought i updated rod but it seems not.
