### ISSUE TITLE
How to release global the page state after failing to close a page

### ISSUE THREAD

**Issue by Srar** [go-rod/rod#345]
**Rod Version:** v0.88.0

Rod holds `state` variable that Pages state. When closing Page unsuccessful, Rod won't remove it even if closing onnection of Chrome.

Rod内有个变量保存Chrome页面状态，当关闭页面失败时不会将页面状态清除。即使关闭了Chrome链接也会保持该状态信息。

![image](https://user-images.githubusercontent.com/12068066/105940035-53f6aa00-6095-11eb-890d-8291098a16a4.png)

**Comment by Srar** [comment]
Solution:

```
package main

import (
	"github.com/go-rod/rod"
)


func main() {
	browser := rod.New().MustConnect()
	defer browser.MustClose()
	browser.MustIgnoreCertErrors(true)
	// The page may stuck, Can't be closed.
	browser.MustPage("https://www.wikipedia.org/")

	// The solution from Yad
	pages, err := browser.Pages()
	if err != nil {
		panic(err)
	}
	for _, page := range pages {
		browser.RemoveState(page.TargetID)
	}

}

```

**Comment by ysmood** [comment]
Also, you can use [proto.PageCrash](https://pkg.go.dev/github.com/go-rod/rod@v0.89.3/lib/proto#PageCrash) to force kill a frozen page.

**Comment by tpsmr** [comment]
#550
