### ISSUE TITLE
when google recaptcha , how 

### ISSUE THREAD

**Issue by 24** [go-rod/rod#346]
like https://avxhm.se/go/5698859/0/

this page will use  google recaptcha 
and sleep 1 second ,
will auto redict to other url ,

how use rod do this ?

试了几种方式，都失败了，求指点指点。。

**Comment by 24** [comment]
@ysmood  help

**Comment by ysmood** [comment]
https://go-rod.github.io/#/emulation?id=bypass-bot-detection

**Comment by 24** [comment]
@ysmood  thank you ,my friend :)
