### ISSUE TITLE
Does rod support back-end execution?

### ISSUE THREAD

**Issue by smp12345** [go-rod/rod#347]
I use Chrome with GUI mode when automation, please can I minimize the window after doing other work on the computer without being affected?For example, some mouse and keyboard operations

**Comment by smp12345** [comment]
**Rod Version:** v0.89.3

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/4fd9b11510208314d950aae8ef159d3c0476de92/lib/examples/use-rod-like-chrome-extension/main.go#L39
