### ISSUE TITLE
How to use rich text editor？

### ISSUE THREAD

**Issue by ChenSee** [go-rod/rod#348]
**Rod Version:** v0.88.0

## The code to demonstrate your question

```go
// Please make sure your code is minimal and standalone
func main() {
	var c []*proto.NetworkCookieParam
	_ = json.Unmarshal([]byte(cookie), &c)

	browser := rod.New().MustConnect()
	defer browser.MustClose()

	page := browser.MustPage("").MustSetCookies(c...).MustNavigate("https://zhuanlan.zhihu.com/write")
	page.MustWaitLoad()
	page.MustElement("textarea").MustInput(title)

	page.MustElement(".DraftEditor-root").MustInput(text)
	texts := page.MustElement(".DraftEditor-root").MustText()

	fmt.Println(texts)
	page.MustScreenshot("a.png")
}
```

## What have you tried to solve the question
.DraftEditor-root is a rich text editor. It has no input attribute. How can I input it?

**Comment by ysmood** [comment]
```go
page.MustElement(".DraftEditor-root").MustClick().MustInput("test test test")
```

**Comment by ChenSee** [comment]
@ysmood 
Thank you for your reply. I've tried this code before, but it still can't be used. If the drafteditor root is a div tag, the following error will be reported.
···
        panic: reflect.Set: value of type int is not assignable to type proto.InputDispatchMouseEventPointerType [recovered]
···

**Comment by ysmood** [comment]
That's because you are using the latest Chrome, it introduced some breaking change. You can force Rod to use an old version of Chrome: https://go-rod.github.io/#/compatibility?id=browser-and-cdp-protocol-versioning

**Comment by ChenSee** [comment]
> That's because you are using the latest Chrome, it introduced some breaking change 😂 . You can force Rod to use an old version of Chrome: https://go-rod.github.io/#/compatibility?id=browser-and-cdp-protocol-versioning
> 
> I will support the latest Chrome on the next Rod version.

I tried chrome version 82.0.4081.0 and Google Chrome version 87.0.4280.141, both of which reported such errors. Which version is supported?

**Comment by ysmood** [comment]
```go
package main

import (
	"fmt"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	bin, err := launcher.NewBrowser().Get()
	utils.E(err)

	u := launcher.New().Bin(bin).MustLaunch()

	browser := rod.New().ControlURL(u).MustConnect()

	page := browser.MustPage("http://example.com")

	fmt.Println(page.MustInfo().Title)
}
```

**Comment by ChenSee** [comment]
> ```go
> package main
> 
> import (
> 	"fmt"
> 
> 	"github.com/go-rod/rod"
> 	"github.com/go-rod/rod/lib/launcher"
> 	"github.com/go-rod/rod/lib/utils"
> )
> 
> func main() {
> 	b := launcher.NewBrowser()
> 	b.ExecSearchMap = map[string][]string{} // force to download from remote
> 	bin, err := b.Get()
> 	utils.E(err)
> 
> 	u := launcher.New().Bin(bin).MustLaunch()
> 
> 	browser := rod.New().ControlURL(u).MustConnect()
> 
> 	page := browser.MustPage("http://example.com")
> 
> 	fmt.Println(page.MustInfo().Title)
> }
> ```

![image](https://user-images.githubusercontent.com/11918919/106983556-0e2a9780-67a1-11eb-8259-518bdb4d1e57.png)
In this way, the rich text editor without the input tag may not work?

**Comment by ChenSee** [comment]
@ysmood 
I just press 18 tabs. It's a little rough...
![image](https://user-images.githubusercontent.com/11918919/106985351-441d4b00-67a4-11eb-927e-5ec21903e1aa.png)
