### ISSUE TITLE
Windows 10 have leakless cmd window

### ISSUE THREAD

**Issue by ChenSee** [go-rod/rod#349]
**Rod Version:** v0.90.0

## The code to demonstrate your question

```go
// Please make sure your code is minimal and standalone
func main() {
	var c []*proto.NetworkCookieParam
	_ = json.Unmarshal([]byte(cookie), &c)

	browser := rod.New().MustConnect()
	defer browser.MustClose()

	page := browser.MustPage("").MustSetCookies(c...).MustNavigate("https://zhuanlan.zhihu.com/write")
	page.MustWaitLoad()
	page.MustElement("textarea").MustInput(title)

	page.MustElement(".DraftEditor-root").MustInput(text)
	texts := page.MustElement(".DraftEditor-root").MustText()

	fmt.Println(texts)
	page.MustScreenshot("a.png")
}
```

## What have you tried to solve the question
Windows 10 have leakless cmd window,How to deal with it close.

![image](https://user-images.githubusercontent.com/11918919/107144869-0887aa00-6979-11eb-8347-f3bff7166f88.png)

**Comment by ysmood** [comment]
Please read [Describe the goal, not the step.](http://www.catb.org/~esr/faqs/smart-questions.html#goal)

Please fix your issue after reading this: http://www.catb.org/~esr/faqs/smart-questions.html

Ask us to reopen the issue after you have fixed your question.
