### ISSUE TITLE
ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. 

### ISSUE THREAD

**Issue by incafox** [go-rod/rod#352]
panic: [launcher] Failed to get the debug url: [0212/171212.760456:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. 

Im got this problem, I know there is a workaround  using puppeter : 
https://github.com/puppeteer/puppeteer/issues/3698
So the question is how should I fix this with rod ?

This is my solution right now : 
https://youtu.be/tc379GTTgys

**Rod Version:** v0.91.1

**Comment by ysmood** [comment]
https://go-rod.github.io/#/custom-launch
