### ISSUE TITLE
how to transfer a []byte golang value to a arraybuffer js value, when use page.Eval

### ISSUE THREAD

**Issue by y573724537** [go-rod/rod#357]
**Rod Version:** v0.92.0

## The code to demonstrate your question

```go
// Please make sure your code is minimal and standalone
func main() {
        browser := rod.New()
	err := browser.Connect()
        if err != nil {
             panic(err)
        }
       page := browser.MustPage("http://jfkdsjflsjlkfsjl.com")
       _, err := Page.Eval(`(data) => { window.render(data); }`, []byte{})
      if err != nil {
           panic(err)
      }
}
```

## What have you tried to solve the question
I just want to pass a []byte golang value to js code, and js code regard it as a arraybuffer, how can I do this?

**Comment by y573724537** [comment]
Could I use proto.RuntimeRemoteObject? I really need a example, please.

**Comment by y573724537** [comment]
when I just pass a []byte golang value to it, js code got null.

**Comment by ysmood** [comment]
You can only pass valid JSON values between browser and golang: https://www.json.org/json-en.html

Here's an example to pass binary data to page:

https://github.com/go-rod/rod/blob/d97095edc943f5c9ffac35f9462d88badf61e3a1/lib/examples/use-rod-like-chrome-extension/main.go#L56
