### ISSUE TITLE
Translate documentation site into Chinese

### ISSUE THREAD

**Issue by ysmood** [go-rod/rod#358]
If you don't know Chinese you can ignore this issue.

这个 issue 将用于讨论中文文档翻译的工作。

## 任务描述

英文项目地址为 https://github.com/go-rod/go-rod.github.io

翻译的任务可以直接在 crowdin 网站完成 https://crowdin.com/project/go-rod 点击想要翻译的文件就可以开始翻译了。

项目已经在[这里](https://github.com/go-rod/rod-docs-zh)翻译了很多，你可以直接拿来用 ，但是很多都是机翻，可以直接拿来用，只要保证最终整体都是中文且语义通顺就可以了。

## 关于领赏

因为都是公开的，应该不存在你干了我赖账的情况，所以直接微信汇款啥的应该没问题，实在不放心的可以上猪八戒开账户接单，地址是 https://task.zbj.com/327973710956883968?pst=i-mytask-list-zbj-23844463-1-1

500 块嫌少的话可以再讨论，我也是第一次尝试这种想法。如果这个模式可行，以后英文文档更新就可以反复使用。

## 常见问题

你可能会问我为啥不自己翻译呢？主要是文档后期更新需要有更自动化的方式同步，目前没有足够强大的 AI 能替换人这个部件，只能花钱来转换问题？钱可以驱动人来自动化这个步骤，只不过运行的不是程序而是人。

**Comment by Zxilly** [comment]
翻了一遍，如果指的是翻译Github Pages的全部md文件，有意

**Comment by Zxilly** [comment]
不过看起来应该需要一套自动化的系统来保证文档的同步。像fastapi那种一样，原始文本变更后作废翻译，直接显示英文

**Comment by ysmood** [comment]
@Zxilly 根据网友 AGD 的建议，crowdin 是个很不错的翻译管理系统，我建立了个项目打算尝试下 https://crowdin.com/project/go-rod

目前试了下网页翻译的功能相当好用:

![image](https://user-images.githubusercontent.com/1415488/108855730-a4c5d800-762c-11eb-925e-288bd907631e.png)

**Comment by Zxilly** [comment]
这个管理的是翻译，我指的是用于显示的静态网页生成器需要一套这样的管理

**Comment by ysmood** [comment]
没明白你的意思，你指要页面渲染级别的多语言支持吗？

**Comment by Zxilly** [comment]
嗯，不知道 docsify 有没有内置支持

**Comment by shniubobo** [comment]
看了一下 docsify 自己的文档是直接 pr 提交的，也没有保证文档同步的手段。估计是没有内置支持了。

比较理想的情况应该是像 cpython 的文档一样定时从翻译网站拉取同步：https://github.com/python/python-docs-zh-cn/blob/master/.github/workflows/python-39.yml

**Comment by ysmood** [comment]
@shniubobo 

我是想保持贡献过程简单，这样就不会费太多时间在工具上，文档更新的频率应该会很低，所以用上复杂的工具可能会得不偿失。
我也没有太多这些工具的经验，都好的建议我们可以试试，直接提 PR 就行。

**Comment by shniubobo** [comment]
crowdin 有自己的 [github 集成](https://store.crowdin.com/products/github)，也有[手段](https://support.crowdin.com/translation-memory/)能保证翻译过的东西不用再翻译，每次更新时只需要翻译新出现的文本即可。

**Comment by ysmood** [comment]
@shniubobo 是的，挺好的。唯一的问题就是需要付费

**Comment by JeOam** [comment]
@ysmood crowdin 官网好像说对于开源项目可以免费：https://crowdin.com/pricing#annual

**Comment by shniubobo** [comment]
> @ysmood crowdin 官网好像说对于开源项目可以免费：https://crowdin.com/pricing#annual

对的，https://github.com/marketplace/crowdin/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW40MjM=#pricing-and-setup

**Comment by ysmood** [comment]
@shniubobo 多谢提醒，他们的说明在页面最下面 😂  https://crowdin.com/page/open-source-project-setup-request
提交了申请，等审核。

**Comment by ysmood** [comment]
关于翻译内容如何应用到具体项目，我这边会花点时间设计一个 Github Action 自动提交 crowdin 的翻译到 https://github.com/go-rod/rod-docs-zh

这样翻译人员就只需要专注于在 crowdin 上翻译就行了，其他的事情都会被自动化完成。

**Comment by shniubobo** [comment]
文中有很多应该用 `` ` `` 包裹的文字，在 crowdin 中显示为用双引号包裹。这时候是应该用 `<code>` 来模拟 `` ` ``，还是说直接使用双引号？

**Comment by ysmood** [comment]
@shniubobo 我这边没这个问题啊，比如用它提供的这种 `<0>` 就会保留原始的格式：

![image](https://user-images.githubusercontent.com/1415488/108890992-8cb47f80-7651-11eb-9314-4e6fcfe8e3fd.png)

**Comment by shniubobo** [comment]
> @shniubobo 我这边没这个问题啊，比如用它提供的这种 `<0>` 就会保留原始的格式：
> 
> ![image](https://user-images.githubusercontent.com/1415488/108890992-8cb47f80-7651-11eb-9314-4e6fcfe8e3fd.png)

这个问题好像主要出现在 [`get-started/README.md`](https://github.com/go-rod/rod-docs-zh/blob/main/get-started/README.md) 中。比如 [这一段](https://github.com/go-rod/rod-docs-zh/blob/main/get-started/README.md#%E7%AC%AC%E4%B8%80%E4%B8%AA%E7%A8%8B%E5%BA%8F)，Github里的 `main.go` 是等宽字体，crowdin 里面是双引号。

这个设置我有开，`<0>` 是可以保留格式的，但 crowdin 里面的“原格式”就不是等宽字体。

**Comment by ysmood** [comment]
@shniubobo 这个不用但心，我测试过了，编译下载的翻译文件格式没有问题。因为你看的这个是其他网友人工翻译的，所以其实原文就没有用 `` ` ``

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/1415488/108892708-8b845200-7653-11eb-8094-f875758327bf.png)

</details>

**Comment by shniubobo** [comment]
翻译好了，还请麻烦 approve 一下。

**Comment by ysmood** [comment]
@shniubobo 👍🏼  你这效率也太高了吧，我晚上之后才有时间，我会尽快 review

**Comment by ysmood** [comment]
@shniubobo 大致验收没问题，能加个微信吗？可以 discord 私信我
