### ISSUE TITLE
Search Function doesn't return anything in 10 minutes

### ISSUE THREAD

**Issue by putrapurba** [go-rod/rod#361]
**Rod Version:** v0.94.0

## Steps to reproduce
```
page := browser.MustPage("https://somewebsite.com/login?lang=en").MustWaitLoad()
	page.MustElement(`input[name="session[username_or_email]"]`).MustInput(screenName)
	page.MustElement(`input[name="session[password]"]`).MustInput(password)
	page.Keyboard.MustPress(input.Enter)
	time.Sleep(time.Second * 1)
	page.MustReload()
	pageInfo := page.MustInfo()

_, err := page.Search(0, 1, userId)
	if err != nil { return false }
```

- What did you do?
I just want search a simple string containing user id on html page, using page.Search(0, 1, userId), I think this function work on version 0.8x.00

- What have you tried to solve the problem?
`html, _ := page.HTML()
if !strings.Contains(html, userId){ return false }`

## Expected behavior
Returning status if HTML contained desired User ID

## Actual result
Please see this error log
[pagesearch.log](https://github.com/go-rod/rod/files/6057693/pagesearch.log)

**Comment by ysmood** [comment]
Can you provide minimal code for us to reproduce your issue?

Works fine for me:

https://github.com/go-rod/rod/blob/deea7a7dea55e8bc437d2dd78a8e0ae543a5422c/examples_test.go#L196-L208

**Comment by ysmood** [comment]
Close because of https://github.com/go-rod/rod/issues/322

**Comment by putrapurba** [comment]
Hi ysmood, it was Search not MustSearch.

https://pkg.go.dev/github.com/go-rod/rod#Page.Search

**Comment by ysmood** [comment]
> Hi ysmood, it was Search not MustSearch.

https://go-rod.github.io/#/error-handling?id=error-handling

**Comment by putrapurba** [comment]
My bad I will reformat this
