### ISSUE TITLE
The number of open browsers is up to 1000, what is the way to build will be more cost effective

### ISSUE THREAD

**Issue by zplzpl** [go-rod/rod#362]
**This is not a problem of program code.**

## What have you tried to solve the question

The number of open browsers is up to 1000, what is the way to build will be more cost effective?

The login state needs to be isolated under the same domain, so it needs to be isolated by creating a browser instance.

**Comment by ysmood** [comment]
Use PagePool, GetCookies, SetCookies,  [StorageClearCookies](https://pkg.go.dev/github.com/go-rod/rod@v0.94.1/lib/proto#StorageClearCookies)

https://github.com/go-rod/rod/blob/c2daf6b4f8ef4f2f5290d8889ca2a7bcfd11118e/examples_test.go#L532-L573

https://github.com/go-rod/rod/blob/c2daf6b4f8ef4f2f5290d8889ca2a7bcfd11118e/lib/examples/use-rod-like-chrome-extension/main.go#L38

**Comment by zplzpl** [comment]
These 1000 users need to operate simultaneously. The real time requirement for each user is high. It may not be possible to use 30 pages to handle 1000 users cookies real time is not that high.

**Comment by ysmood** [comment]
Then, just opening 1000 incognito pages doesn't work for you? Each page 10MB mem, 1000 is only 10GB of memory.
