### ISSUE TITLE
cant hijack request

### ISSUE THREAD

**Issue by imbaMF** [go-rod/rod#363]
**Rod Version:** v0.94.1
im trying to change request body, but i cant... The minimal example:
## The code to demonstrate your question

```go
package main

import (
	"log"
	"net/url"
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	ln := launcher.New().
		Set("no-sandbox", "true").
		Headless(false).
		Set("disable-notifications")
	defer ln.Cleanup()

	ctl, err := ln.Launch()
	if err != nil {
		log.Println("cannot init launcher", err)
	}

	browser := rod.New().
		ControlURL(ctl).
		Trace(true).
		SlowMotion(250 * time.Millisecond)

	err = browser.Connect()
	if err != nil {
		log.Println("cannot connect to browser", err)
	}
	defer browser.MustClose()

	var page *rod.Page
	err = rod.Try(func() {
		page = browser.
			MustPage("https://www.merchantwords.com/login").
			MustSetViewport(1366, 748, 1, false).
			MustWindowMaximize()
	})

	if err != nil {
		log.Println("cannot open page", err)
	}

	page.MustWaitLoad()

	loginField, err := page.Timeout(30 * time.Second).Element(`input[name="email"]`)
	if err != nil {
		log.Println("cannot find login field", err)
	}
	loginField.MustInput("test lgn")

	passField, err := page.Timeout(5 * time.Second).Element(`input[name="password"]`)
	if err != nil {
		log.Println("cannot find password field", err)
	}
	passField.MustInput("test pwd")

	loginBtn, err := page.Timeout(15 * time.Second).Element(`button#submitButton`)
	if err != nil {
		log.Println("cannot find login button", err)
	}

	router := page.HijackRequests()

	router.MustAdd("https://www.merchantwords.com/login*", func(ctx *rod.Hijack) {
		urlValues := url.Values{
			"email":                []string{"bla login"},
			"password":             []string{"bla pwd"},
			"g-recaptcha-response": []string{"captcha"},
		}

		r := ctx.Request.SetContext(page.GetContext())
		values := urlValues.Encode()
		log.Println(values)
		r.SetBody(values)
		ctx.MustLoadResponse()
	})

	go router.Run()

	utils.Sleep(0.1)

	// wait := page.MustWaitRequestIdle()
	loginBtn.MustEval(`() => {this.disabled = false; this.click();}`)
	// wait()

	utils.Sleep(1)
	router.MustStop()

	utils.Pause()

}

```

why i cant hijack request?
im trying change 
![2](https://user-images.githubusercontent.com/11431176/110053595-63d36f00-7d62-11eb-91b3-11736473886b.png)
but result is not changed
![1](https://user-images.githubusercontent.com/11431176/110053639-78b00280-7d62-11eb-849b-db75dcc40458.png)

What im did wrong? thx u.

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/issues/322

**Comment by imbaMF** [comment]
@go-rod/everyone

**Comment by imbaMF** [comment]
@go-rod/everyone

**Comment by ysmood** [comment]
Because the data is modified after you use the Devtools UI, not before it, you should use a proxy to confirm if the data is intercepted, not the  Devtools.

**Comment by ysmood** [comment]
Rod is a Devtools' driver, you can't use Devtools to debug Devtools 😂

**Comment by imbaMF** [comment]
did not know, ok, i will try debug it via fiddler, ty

**Comment by imbaMF** [comment]
i was debug it via fiddler and result the some, body not changed

![1](https://user-images.githubusercontent.com/11431176/110098365-c51e3100-7da8-11eb-831e-8950b6739053.png)

**Comment by ysmood** [comment]
@imbaMF Same code works fine for me:

<img width="1593" alt="Screen Shot 2021-03-08 at 4 33 48" src="https://user-images.githubusercontent.com/1415488/110252234-bf526680-7fc7-11eb-9bd4-cf6acc9f5fc7.png">
 
I don't know how you use fiddler, but I think the way you use it is wrong.

https://github.com/go-rod/rod/blob/085f1353f62c6f9228fb487f48ad190ab813458a/examples_test.go#L459-L464

Do you see the `rod ---> server`, it means we are using Go to send the request, not the browser.

I will close it for now. If you want to reopen, please provide more details.

**Comment by imbaMF** [comment]
ok, maybe ur right! solved it by another way. thx u for ur response!
