### ISSUE TITLE
How to define an event listener for handling all dialogs?

### ISSUE THREAD

**Issue by Evilran** [go-rod/rod#364]
**Rod Version:** v0.92.0

## Background

In puppeteer, there exists a way to handle all pop-up dialogs:

```py

import asyncio
from pyppeteer import dialog

async def close_dialog(dialog_handler: dialog):
    await dialog_handler.accept()

page.on("dialog", lambda dialog_handle: asyncio.ensure_future(close_dialog(dialog_handle)))

```
I wanted to achieve the above way with rod and I found two examples:

```go

// page_test line 128
func (t T) PageCloseCancel() {
	page := t.browser.MustPage(t.srcFile("fixtures/prevent-close.html"))
	page.MustElement("body").MustClick() // only focused page will handle beforeunload event

	w, h := page.MustHandleDialog()
	go func() {
		w()
		h(false, "")
	}()
	t.Eq(page.Close().Error(), "page close canceled")

	page.MustEval(`window.onbeforeunload = null`)
	page.MustClose()
}

// page_test line 410
func (t T) Alert() {
	page := t.page.MustNavigate(t.srcFile("fixtures/alert.html"))

	wait, handle := page.MustHandleDialog()

	go page.MustElement("button").MustClick()

	e := wait()
	t.Eq(e.Message, "clicked")
	handle(true, "")
}

```

## The Question I met

With the two examples above, I tried to implement. However, I found a problem where an exception **`panic: context deadline exceeded`** would be thrown if there were multiple dialogs on the page. When there is no dialog on the page, calling the HandleDialog method will also raise the same exception (timeout).

My goal is to design a generic website crawler, so I used the following code to implement it:

```go

package main

import (
	"fmt"
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/proto"
	"time"
)

const (
	GetOnEvent = `() =>{
		var onevents = [];
		var treeWalker = document.createTreeWalker(
			document.body, 
			NodeFilter.SHOW_ELEMENT,
			{ acceptNode: function(node) { return NodeFilter.FILTER_ACCEPT; }},
		);
		while (treeWalker.nextNode()) {
			var element = treeWalker.currentNode;
			for (k = 0; k < element.attributes.length; k++) {
				attr = element.attributes[k]
				if (attr.nodeName.startsWith('on')) {
					if (onevents.indexOf(attr.nodeValue) < 0) {
						onevents.push(attr.nodeValue);
				 	}
				}
				if (attr.nodeName == "href"){
					javascript_code = attr.nodeValue.match("javascript:(.*)")
					if (javascript_code) {
						if (onevents.indexOf(attr.nodeValue) < 0) {
							onevents.push(attr.nodeValue);
				 		}
					}
				}
			}
		}
		return onevents
}`
)

func main() {
	url := "http://example.com"
	l := launcher.NewUserMode().Headless(true)
	u := l.MustLaunch()
	browser := rod.New().ControlURL(u).Timeout(10 * time.Second).MustConnect()
	_ = proto.SecuritySetIgnoreCertificateErrors{
		Ignore: true,
	}.Call(browser)
	page := browser.MustIncognito().MustPage(url).Timeout(10 * time.Second).MustWaitIdle().MustWaitLoad()
	fmt.Println(page.MustInfo().Title)
	onEvents := page.MustEval(GetOnEvent).Arr()
	for _, el := range onEvents {
		wait, handle := page.MustHandleDialog()
		go page.MustEval(el.String())
		wait()
		handle(true, "")
	}
	els := page.MustElementsByJS("document.querySelectorAll('[src]')")
	for _, el := range els {
		urlElement := el.MustEval(`this.getAttribute("src")`).Str()
		fmt.Println(urlElement)

	}

	defer l.Kill()
	defer l.Cleanup()
	defer browser.MustClose()
	return
}

```

## The Solution I Tried

I tried to detect if a dialog had occurred on the page by following:

```go

for msg := range page.Event() {
	e := proto.PageJavascriptDialogOpening{}
	if msg.Load(&e) {
		break
	}
}

```

But because the pop-up occurs in a concurrent process( `go page.MustEval(el.String())` ), the **HandleDialog** method must wait for a dialog, The solution I tried didn't work.

The way I currently do it is to determine if there is a statement in my js code that causes a dialog, but I don't think this is a good way to do it, is there a more elegant solution?

**Comment by ysmood** [comment]
https://pkg.go.dev/github.com/go-rod/rod#Page.EachEvent

https://github.com/go-rod/rod/blob/c2daf6b4f8ef4f2f5290d8889ca2a7bcfd11118e/examples_test.go#L409-L413

**Comment by Evilran** [comment]
> Read the doc first: https://go-rod.github.io/#/events/README?id=handle-multiple-events
> 
> https://github.com/go-rod/rod/blob/c2daf6b4f8ef4f2f5290d8889ca2a7bcfd11118e/examples_test.go#L409-L413
> 
> Same works for `proto.PageJavascriptDialogOpening`. Call the `proto.PageHandleJavaScriptDialog` in the callback.

I've read the doc and tried `proto.PageJavascriptDialogClosed`, but it doesn't work.

The problem was solved according to your tips:

```go
go page.EachEvent(func(e *proto.PageJavascriptDialogOpening) {
	restore := page.EnableDomain(&proto.PageEnable{})
	defer restore()
	_ = proto.PageHandleJavaScriptDialog{
		Accept:     true,
		PromptText: "",
	}.Call(page)
})()
```

Thank you very much, it's awesome!

**Comment by ysmood** [comment]
@Evilran Read the doc of `page.EachEvent`, you don't need `restore := page.EnableDomain(&proto.PageEnable{})`

**Comment by Evilran** [comment]
@ysmood You're right, `page.EachEvent` has already done it, thanks.

It's my pleasure to be involved. :thumbsup:

PR: #366
