### ISSUE TITLE
How to handle "Select a Certificate" dialog

### ISSUE THREAD

**Issue by ydcool** [go-rod/rod#367]
**Rod Version:** v0.94.0

I'm using rod to load some intranet page which will ask for selecting a certificate instantly at begining of page load,
and page was blocked for waiting conform of the dialog.

![image](https://user-images.githubusercontent.com/5668295/110192688-7d5fde00-7e6a-11eb-86b5-74b9c257d397.png)

## The code to demonstrate your question

```go
// Please make sure your code is minimal and standalone
func main() {
	l := launcher.New()

	// For more info: https://pkg.go.dev/github.com/go-rod/rod/lib/launcher
	u := l.MustLaunch()

        fmt.Println("starting page...")
	browser := rod.New().ControlURL(u).MustConnect()

	page := browser.MustPage("http://example.com")
        
        # this line and below was blocked by dialog and can never reached 
        fmt.Println("page loading...")
	wait, handle := page.MustHandleDialog()
	wait()
	handle(true, "")
}
```

## What have you tried to solve the question

I  tried to use `HandleDialog` but it seems that the page has already been blocked before wait and handle. How to seperate the page loading into another goroutine?

**Comment by ysmood** [comment]
FYI, https://github.com/puppeteer/puppeteer/issues/540

**Comment by ydcool** [comment]
@ysmood 2nd solulation worked for me, thank you!

/close

**Comment by ydcool** [comment]
Hmmmm...it was worked for chrome but not for the chrome started by rod...how can I handle the [chrome policy list](https://www.chromium.org/administrators/policy-list-3) in rod?

**Comment by ysmood** [comment]
I don't know how to reproduce it. Can you provide minimal code for us to reproduce your issue?

**Comment by ysmood** [comment]
The certificate popup only opens if you have more than one client certificate installed.
You can remove the client certificate to avoid the popup be open, google it I think you can solve it by yourself.

**Comment by ydcool** [comment]
I dont think so..I have only one cert installed, that capture above is just a sample. I'll try build a demo to reproduce this.

**Comment by ysmood** [comment]
But your screenshot has two lines. Your installed one plus the system one it will be two?

**Comment by ydcool** [comment]
Sorry for the misleading, that screenshot is from google not mine. On my computer it shows only one cert in the list. And the dialog never shows up again after I set the policy when I start chrome by hand, but in rod  it comes again. so I think I should set up a minimal site with ssl verification and gen a cert to reproduce this.

**Comment by ydcool** [comment]
I noticed one thing, rod v0.94.0 using a standalone chromium, but no longer  the google chrome nor other browsers using chromium like Edge?

**Comment by ydcool** [comment]
Yes that's why the policy not work for rod.

 All from my googled results include chrome documents says the policy should placed to `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\AutoSelectCertificateForUrls` , but is just work for google chrome , if you using Microsoft Edge, then you should using the path `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\AutoSelectCertificateForUrls` , and for chromium, the path is `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Chromium\AutoSelectCertificateForUrls`.

Now it's work great with all my browsers as well as rod. 💯

**Comment by ysmood** [comment]
FYI You can still easily use the system browser https://go-rod.github.io/#/custom-launch?id=control-every-step
