### ISSUE TITLE
Add support to get the live Dom tree snapshot including Iframes 

### ISSUE THREAD

**Issue by badrelmers** [go-rod/rod#374]
First, thank you very much for your excellent work.

Actually we can use different methods to get the Dom tree but none of them return the expanded Iframes (as we see them in the Devtool).

I hope it is possible to add something like you did with the wonderful `MustSearch` which traverse Iframes and Shadow Dom.

Actually Chrome Devtool Protocol have no way to get that information. I already tested those:
[Network.getResponseBody](https://chromedevtools.github.io/devtools-protocol/tot/Network/)
[DOMSnapshot.captureSnapshot](https://chromedevtools.github.io/devtools-protocol/tot/DOMSnapshot/)
[Page.captureSnapshot](https://chromedevtools.github.io/devtools-protocol/tot/Page/)
Runtime.evaluate: `document.documentElement.innerHTML`
Runtime.evaluate: `XMLSerializer().serializeToString(document)`

I hope we can have an option to get the full Dom tree as in the Devtool here:

![image](https://user-images.githubusercontent.com/40046489/111895424-8aacc900-8a23-11eb-8685-47325e325c7d.png)

Thank you very much.

**Comment by ysmood** [comment]
`proto.DOMGetDocument`
