### ISSUE TITLE
Getting `chrome: no such file or directory` with Alpine

### ISSUE THREAD

**Issue by jurado-dev** [go-rod/rod#377]
**Rod Version:** v0.96.0

I am trying to run a simple test with Alpine and Docker. I am doing a 2 stage  docker build. Build the app with golang:alpine and then I used only alpine as a container for the app.

When the application runs, go-rod downloads chrome correctly, unzip it correctly. But when go-rod want to run the browser it shows this error

```bash
 fork/exec /root/.cache/rod/chromium-856583/chrome-linux/chrome: no such file or directory
```
If you access the container, the Chrome file exists, so I don't understand what the problem is.

## The code to demonstrate your question

```go

func main() {
l := launcher.New().
		Headless(true).
		Devtools(false)

	defer l.Cleanup()

	launcherURL, err := l.Launch()
	if err != nil {
		log.Fatal(err.Error())
	}

	browser := rod.New().
		ControlURL(launcherURL).
		Trace(true).
		SlowMotion(2 * time.Second)

	err = browser.Connect()
	if err != nil {
		log.Fatal(err.Error())
	}
defer browser.Close()

	page := browser.MustPage("https://github.com/go-rod/rod")
       // Use the page
     
}

```

## What have you tried to solve the question

Tried with the ubuntu container, it works fine.

**Comment by ysmood** [comment]
#322
