### ISSUE TITLE
About Proxy

### ISSUE THREAD

**Issue by asyncins** [go-rod/rod#379]
**Rod Version:** v0.95.0

## The code to demonstrate your question

```go
// Please make sure your code is minimal and standalone
func main() {
browser := rod.New().ControlURL(
		launcher.New().Proxy("").Headless(false).MustLaunch()).MustConnect()
}
```

## What have you tried to solve the question

我想问一下，URL 格式的代理应该怎么设置？类似下面这样

```
http://QR50:0j@http-proxy-t1.abc.cn:9980
```

**Comment by ysmood** [comment]
#322

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/eff7c9785ce2ae78231d5fdce51c32a4e76af2b4/examples_test.go#L376
