### ISSUE TITLE
capture console from web worker

### ISSUE THREAD

**Issue by FrankReh** [go-rod/rod#380]
**Rod Version:** v0.94.1

The following page.EachEvent call is great at logging what the page's main thread writes to the console but does not capture what a web worker is writing to the console. I see you created, #145, an issue that web worker's aren't supported yet so probably this is directly related and blocked until that is resolved. But in case it were easy to explain, I thought I'd ask if you see a way to create such a call that would capture either all of the threads' consoles, or a loop for capturing each of the thread's console separately.
## The code to demonstrate your question

```go
		// Listen for all events of console output.
		go page.EachEvent(func(e *proto.RuntimeConsoleAPICalled) {
			fmt.Println(page.MustObjectsToJSON(e.Args))
		})()
```

## What have you tried to solve the question

Looked for some reference to worker in the rod source.

**Comment by ysmood** [comment]
Have you tried `Browser.EachEvent`?

**Comment by FrankReh** [comment]
Thanks for the info. And again, thanks for a great project - sorry I can't help more. As the web worker code is mine in this case, I've decided to post the debugging to the server rather than write to the console and then listen to the console. So I have a work around that this time at least actually makes decoding the debugging information easier.

**Comment by ysmood** [comment]
Cool, let's close it for now.
