### ISSUE TITLE
PointerEvent should dispatch as always when page.Mouse.MustMove()

### ISSUE THREAD

**Issue by HaoweiCh** [go-rod/rod#381]
**Rod Version:** v0.96.1

## Steps to reproduce

- What did you do?

```
document.querySelector("body > div.geetest_fullpage_click.geetest_float.geetest_wind.geetest_slide3 > div.geetest_fullpage_click_wrap > div.geetest_fullpage_click_box > div > div.geetest_wrap > div.geetest_slider.geetest_ready > div.geetest_slider_button").addEventListener('pointermove', function(event) {
  console.log(`pointerType ${event.pointerType}`);
  console.log(event)
}, false);
```

- What have you tried to solve the problem?

dispatch event by js

## Expected behavior

PointerEvent should dispatch by browser

What do you expect to get?

## Actual result

PointerEvent not dispatch

What did you actually get?

none

----

* useful links
  * https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/PointerEvent
  * https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted

**Comment by ysmood** [comment]
#322
