### ISSUE TITLE
About collect all the elements of the page

### ISSUE THREAD

**Issue by evi1ox** [go-rod/rod#388]
**Rod Version:** v0.97.0

## The code to demonstrate your question

```go
body := page.MustHTML()
doc, err := goquery.NewDocumentFromReader(strings.NewReader(body))
```

## What have you tried to solve the question
有没有方法可以获取渲染后的页面html, 而不使用Element提取section节点元素, 然后使用goquery提取关键信息, 非常感谢

**Comment by ysmood** [comment]
你不是自问自答了吗？

**Comment by evi1ox** [comment]
> 你不是自问自答了吗？

我想表达的意思是这样的, rod抓取section节点是能获取到值的, 但是抓取完整的body是未曾渲染过的, 有没有办法可以获取渲染后的所有body

**Comment by ysmood** [comment]
`Page.MustWaitElementsMoreThan`

**Comment by evi1ox** [comment]
感谢, 已解决
