### ISSUE TITLE
user-data-dir doesn't retain the session

### ISSUE THREAD

**Issue by elbek** [go-rod/rod#389]
**Rod Version:** v0.89.3

## The code to demonstrate your question

```go
	l := launcher.New()
	//l.Flags["disable-web-security"] = nil
	//l.Flags["user-data-dir"] = []string{"/opt/chromium"}
	l.UserDataDir("/opt/chromium/data")
	u := l.MustLaunch()
	return rod.New().ControlURL(u).MustConnect()
```

## What have you tried to solve the question
I tried running running user-data-dir with chrome without rod involved and it works as expected.
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --user-data-dir=/opt/chromium
```
But with rod a website asks passowrd all the time. I can see when chrome is launched thru rod it is indeed using the folder, because it creates bunch of new files, but not retaining the session between restarts.

**Comment by ysmood** [comment]
Works fine for me, how can I help?

**Comment by elbek** [comment]
@ysmood, does browser instance clean or do something with the user data dir when it is being shut down? I saw there is a clean method, but it seems needs to be called explicitly?

**Comment by ysmood** [comment]
No auto-clean.

Show your complete code and screen record your problem.

**Comment by elbek** [comment]
I will try to repro the issue with simple web site

**Comment by elbek** [comment]
We can close this, It is working as expected, I was wrong
