### ISSUE TITLE
cant click on button in canvas by mouse click()

### ISSUE THREAD

**Issue by imbaMF** [go-rod/rod#396]
**Rod Version:** v0.97.8
Hi, im trying to click on button Login in canvas element maked by unity (webgl), but nothing happend, its a bug or i did something wrong? 
the minimal example:
when the game is loaded and the button "Login" is on, just type "click" in terminal
```go
package main

import (
	"bufio"
	"log"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/proto"
)

func main() {
	ln := launcher.New().
		Set("no-sandbox", "true").
		Headless(false).
		Set("disable-notifications")
	// defer ln.Cleanup()

	ctl, err := ln.Launch()
	if err != nil {
		log.Printf("%s = %s\n", "cannot init launcher", err)
	}

	browser := rod.New().
		ControlURL(ctl).
		Trace(true).
		SlowMotion(250 * time.Millisecond)
	defer browser.Close()

	err = browser.Connect()
	if err != nil {
		log.Printf("%s = %s\n", "cannot connect to browser", err)
	}

	var page *rod.Page
	err = rod.Try(func() {
		page = browser.
			MustPage("https://play.alienworlds.io/").
			MustSetViewport(800, 600, 1, false).
			MustWindowMaximize()
	})

	if err != nil {
		log.Printf("%s = %s\n", "cannot open page", err)
	}

	page.MustWaitLoad()

	clickChan := make(chan int)

	page.Mouse.Move(0, 110, 1)
	time.Sleep(time.Second)

	go func() {
		<-clickChan
		log.Println("do click")
		page.Mouse.Click(proto.InputMouseButtonLeft) // here is not working
	}()

	scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {
		cmd := scanner.Text()
		// do click
		if cmd == "click" {
			clickChan <- 1
			continue
		}

		// for cursore move (x, y) from terminal "0 100" or "100 100"
		posSlice := strings.Split(cmd, " ")
		x, err := strconv.ParseFloat(posSlice[0], 64)
		if err != nil {
			log.Println(err)
		}
		y, err := strconv.ParseFloat(posSlice[1], 64)
		if err != nil {
			log.Println(err)
		}
		log.Println(x, y)
		page.Mouse.Move(x, y, 1)
	}

	if scanner.Err() != nil {
		log.Fatal(scanner.Err())
	}
}

```

**Comment by ysmood** [comment]
Have you tried to use the slow motion and "mock mouse cursor" to debug?

![image](https://user-images.githubusercontent.com/1415488/116350391-d3c71880-a82c-11eb-8afe-a312a8eb2d3f.png)

**Comment by imbaMF** [comment]
@ysmood thx, if headless works in lates versions https://github.com/go-rod/rod/issues/46#issuecomment-796890241, how can i enable proto.InputSetIgnoreInputEvents ? Can you please provide a min. example?

**Comment by imbaMF** [comment]
i was did 
```go
go func() {
		<-clickChan
		log.Println("do click")
		_ = proto.InputSetIgnoreInputEvents{
			Ignore: true,
		}.Call(page)
		page.Mouse.Click(proto.InputMouseButtonLeft) // here is not working
	}()
```
but still not working

**Comment by ysmood** [comment]
Can you show us the screen record of the slow motion?

**Comment by imbaMF** [comment]
https://www.loom.com/share/0212a908191a44d2afcd717c2c65a8c1

**Comment by ysmood** [comment]
@imbaMF Next time please make sure your code is minimum. Too much garbage code.

```go
package main

import (
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/proto"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	browser := rod.New().MustConnect()

	page := browser.MustPage("https://play.alienworlds.io/").MustWaitLoad()

	wait := true

	go func() {
		for wait {
			page.Mouse.MustMove(638, 579).MustClick(proto.InputMouseButtonLeft)
			utils.Sleep(1)
		}
	}()

	p := page.MustWaitOpen()()
	wait = false

	p.MustWaitOpen()().MustElement("input[name=userName]").MustInput("test@test.com")

	utils.Pause()
}
```

**Comment by imbaMF** [comment]
ок, sorry for long example! why ur coordinates starts from left, top, but when im trying to move mouse its start from center?
![1](https://user-images.githubusercontent.com/11431176/116394305-6b2b6c00-a82b-11eb-9165-775dc9df336b.png)

**Comment by ysmood** [comment]
It's a bug of the tracer, the actual location is not at what it shows, fixed in `v0.97.9`.

search canvas, such as AI?

**Comment by imbaMF** [comment]
> It's a bug of the tracer, the actual location is not at what it shows, fixed in `v0.97.9`.
> 
> search canvas, such as AI?

not AI =), how found button coordinates? I cant understand how do it...

**Comment by imbaMF** [comment]
okey, was updated rod, now it works perfect, so the promles was in coordinates! thx you very much!

**Comment by ysmood** [comment]
Image AI object detection to locate the x and y of the button.
