### ISSUE TITLE
can't connect chrome from command line remote port

### ISSUE THREAD

**Issue by zjlx** [go-rod/rod#397]
**Rod Version:** v0.97.10

## The code to demonstrate your question
I use chrome in linux, the cmd is:
```shell
./chrome --headless  --no-sandbox --disable-gpu --disable-dev-shm-usage --remote-debugging-port=9222
```
go code is:
```go
// Please make sure your code is minimal and standalone
func main() {
        l := launcher.MustNewRemote("ws://127.0.0.1:9222")
        browser := rod.New().Client(l.Client()).MustConnect()
        fmt.Println(
		        browser.MustPage("https://github.com").MustEval("() => document.title"),
	        )

        utils.Pause()
}
```
the error result is:
panic: invalid character '<' looking for beginning of value [recovered]
	panic: invalid character '<' looking for beginning of value

## What have you tried to solve the question
I tried to use ws://127.0.0.1:9377/devtools/browser/ddd09793-0051-4c3b-908b-a8e111a8f203 as remoteUrl, it return error EOF.

**Comment by ysmood** [comment]
@zjlx It's your misuse, read the doc carefully.
