### ISSUE TITLE
Q: Freezing when MustPage(url) with headless chromium

### ISSUE THREAD

**Issue by nea** [go-rod/rod#399]
**Rod Version:** v0.97.11

## What have you tried to solve the question
Hi

I have a headless chromium started, running and go-rod connect to it. The connection looks good, starts normally without any issues.

If I then create a browser.MustConnect() also all goes well until I try to open MustPage(url). No error, no nothing, it just hangs. I tried to Page(url) if an error is returned but nothing.

The headless shell is running with disable-gpu, single-process, no-sandbox on an aws lambda instance.
If I run a dump-dom on the headless shell it runs and prints without issues, but connecting and trying to navigate freezes the call. I also tried to enable logging but havent gotten anything out of it.

Anybody got an idea what I am missing here?

Thanks

**Comment by ysmood** [comment]
Sorry, we can't reproduce it. Can you provide minimal code and steps for us to reproduce your issue?

**Comment by deehidayat** [comment]
Hi, I got same issue on Windows 7. If I run on headless mode it do nothing when MustPage(url) (freezed). I tried to open monitoring server it seems page do nothing, tab title still <about:blank>. If I run headfull mode all went well except if I minimize browser, it like freeze again.
Have try "Run as administrator" but still.

**Comment by ysmood** [comment]
@deehidayat does any website will freeze?

**Comment by nea** [comment]
Ahoi @deehidayat 

I don't know if this fixes your case too, but for me the issue was using `--disable-gpu` in my environment. Removing and providing `swiftshader` as gl fallback worked flawlessly. In my case it was no Windows but a Linux environment, but maybe worth a try.


Best

**Comment by ysmood** [comment]
@nea How about we add `--disable-gpu` as the default?

**Comment by nea** [comment]
Ahoi @ysmood 

In general I would agree to add `--disable-gpu` as default because in most cases this probably is the preferred way.
But for me it was the opposite: I had to remove `--disable-gpu` and replace it with `--use-gl=swiftshader` in my case.

So maybe this should rather be a documented suggestion than a default?


Cheers

**Comment by ysmood** [comment]
@nea So you mean if you don't use `swiftshader`, you still have problems? I thought at least it won't freeze anymore.

**Comment by nea** [comment]
Ahoi @ysmood 

Exactly. I retried it several times, recompiled and tested and it was reproducible:
* Using `--disable-gpu` lead to a freeze when opening the url (MustPage)
* Using `use-gl...` instead of `disable-gpu` worked every time

Environment was a headless Linux container (serverless), why it might be a very specific case in my test, but at least these were my findings.

**Comment by ysmood** [comment]
@nea how about make `swiftshader` the default? Have you tried this docker [image](https://github.com/orgs/go-rod/packages/container/package/rod)? I never use `swiftshader`, it works fine for me.

**Comment by nea** [comment]
Ahoi @ysmood 

Didn't even know about that Docker image ^^' As I used it in a Lambda environment, I referred back to the AWS images and did not compile my own. If this image works, then this could be a solution for serverless environments, too, as most providers allow container-based deployments nowadays. Damn, should have known earlier ^^

**Comment by ysmood** [comment]
@nea about how to use this image https://github.com/go-rod/rod/blob/master/lib/examples/connect-browser/main.go

**Comment by ysmood** [comment]
@nea also check this one https://go-rod.github.io/#/custom-launch?id=remotely-manage-the-launcher

**Comment by egonelbre** [comment]
I had a similar issue with browser hanging, one thing that helped me to debug the issue was to add a logger for the launcher.

For example:

```
l := launcher.New().
		Logger(os.Stderr)
...
```

Then the browser startup errors will be printed to stderr.
