### ISSUE TITLE
Failed to download Chromium zip

### ISSUE THREAD

**Issue by yujiri8** [go-rod/rod#406]
**Rod Version:** v0.97.12

I ran this on a FreeBSD server in a new project after being referred [here](https://github.com/mxschmitt/playwright-go/issues/122#issuecomment-833636781).

On first run, this fails with `panic: zip: not a valid zip file`. I see the downloaded `rod/chromium-869685.zip` is:
```xml
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromium-browser-snapshots//869685/</Details></Error>
```

On subsequent run, fails with `panic: exec: "rod": executable file not found in $PATH`.

## The code to demonstrate your question

As in the docs example:

```go
func main() {
	page := rod.New().MustConnect().MustPage("https://www.wikipedia.org/")

	page.MustElement("#searchInput").MustInput("earth")
	page.MustElement("#search-form > fieldset > button").MustClick()

	el := page.MustElement("#mw-content-text > div.mw-parser-output > p:nth-child(6)")
	fmt.Println(el.MustText())
}
```

## What have you tried to solve the question

Nothing.

**Comment by ysmood** [comment]
https://go-rod.github.io/#/compatibility?id=compatibility

**Comment by ysmood** [comment]
I think for freebsd you should use docker to launch the browser, check this doc:  https://go-rod.github.io/#/custom-launch?id=docker

**Comment by yujiri8** [comment]
I assumed this would work out of the box because of your referral. I see this will not be as simple as I hoped. Feel free to close the issue.

**Comment by ysmood** [comment]
@yujiri8 Sorry about my unclear statement, rod supports FreeBSD doesn't mean Chromium supports it 😂 .

Thanks for you report, I will fix the error message and make it easier for others to know what's going on.
