### ISSUE TITLE
Support to change the browser executable path for launcher.MustNewManaged

### ISSUE THREAD

**Issue by SanFenZuiCom** [go-rod/rod#408]
**Rod Version:** v0.97.12

I can't change the browser executable path on the remote machine.

**Comment by ysmood** [comment]
func main() {
    l := launcher.New()
	l.Bin("/root/Default/chrome")
	browser := rod.New().Client(l.Client()).MustConnect()
}

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/89877d303871d4e9573fbfd8ad59097a2e56d30c/lib/launcher/example_test.go#L12-L17

**Comment by SanFenZuiCom** [comment]
> https://github.com/go-rod/rod/blob/89877d303871d4e9573fbfd8ad59097a2e56d30c/lib/launcher/example_test.go#L12-L17

I known that code,but it is still not working.
I set bin path for a launcher.MustNewRemote() not launcher.New().

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/e5a4037aab4d91c3cff5e1b08cf1d2a5851d1b13/lib/launcher/remote_launcher.go#L26

**Comment by SanFenZuiCom** [comment]
> https://github.com/go-rod/rod/blob/e5a4037aab4d91c3cff5e1b08cf1d2a5851d1b13/lib/launcher/remote_launcher.go#L26
> 
> https://github.com/go-rod/rod/blob/master/lib/examples/connect-browser/main.go
Rod v0.97.13
I'm connected to that service.First running lib/launcher/rod-launcher/main.go server in debug.
And set breakpoint to below code.
```go
func (l *Launcher) Bin(path string) *Launcher {
	l.bin = path //set breakpoint to  this line
	return l
}
```
`Remote control url is ws://[::]:7317`
Then I connect to that server through below code.
```go
//client
func main() {
    l := launcher.MustNewManaged("ws://localhost:7317")
    l.Bin("/root/Default/chrome")
    browser := rod.New().Client(l.Client()).MustConnect()
}
```
But the server breakpoint was not triggered.And the running chrome is not my set bin `/root/Default/chrome`.
I think server launcher.NewService() not receive the bin set from client launcher.MustNewManaged().

**Comment by ysmood** [comment]
```go
func main() {
    u := launcher.New().Bin("/root/Default/chrome").MustConnect()
    browser := rod.New().ControlURL(u).MustConnect()
}
```

**Comment by SanFenZuiCom** [comment]
> Why do you need to use `launcher.MustNewManaged`? Use the code below:
> 
> ```go
> func main() {
>     u := launcher.New().Bin("/root/Default/chrome").MustConnect()
>     browser := rod.New().ControlURL(u).MustConnect()
> }
> ```

Because I connect a  lib/launcher/rod-launcher/main.go running server from another machine.So I can't use  the most used launcher.New to create a browser.

**Comment by ysmood** [comment]
Now I get your point. It's far

**Comment by ysmood** [comment]
A temp quick solution is to use a `.rod` file and set its content to:

```txt
bin=/path/to/chrome
```
Then run  `go run ./lib/launcher/rod-launcher`.

If you use Linux you can run without `.rod` file: `rod="bin=/path/to/chrome" go run ./lib/launcher/rod-launcher`
