### ISSUE TITLE
Getting `chrome: no such file or directory` with Alpine

### ISSUE THREAD

**Issue by mazihao66** [go-rod/rod#411]
**Rod Version:** v0.96.1

## The code to demonstrate your question

```go
// Please make sure your code is minimal and standalone
func main() {
 l, err:= launcher.New().
			Set("disable-web-security").
			Set("disable-setuid-sandbox").
			Set("no-sandbox").
			Set("no-first-run", "true").
			Set("disable-gpu").
			Headless(true).
			Launch()
fmt.Println("roderr：", err)
browser := rod.New().ControlURL(l).MustConnect()
}
```

## What have you tried to solve the question
I am trying to run a simple test with Alpine and Docker. I am doing a 2 stage docker build. Build the app with golang:alpine and then I used only alpine as a container for the app.

When the application runs, go-rod downloads chrome correctly, unzip it correctly. But when go-rod want to run the browser it shows this error
fork/exec /root/.cache/rod/chromium-856583/chrome-linux/chrome: no such file or directory

**Comment by ysmood** [comment]
Close because of #404
