### ISSUE TITLE
rod.Browser disconnects from Chromium with the error cdp connection closed: context canceled

### ISSUE THREAD

**Issue by polyma** [go-rod/rod#415]
If I leave the rod.Browser instance connected to the underlying Chromium instance for a day or so, the Websocket will disconnect. This generally happens silently, and I won't realise that the instance is disconnected until I try to issue any commands. This results in a lot of failures.

So either there should be a) an event that is emitted when a disconnect occurs; or b) a configurable retry strategy for the websocket connection.

An alternative is to have an idempotent 'Connect' function on rod.Browser. This will mean that goroutines can separately call `Connect` on the same Browser instance without recreating websocket connections, and in a threadsafe way.

**Comment by ysmood** [comment]
If the connection is lost, chrome will clean up all the references created by the cdp client, such as the page id we use to control the page, so even you reconnect to the same browser again, all the ids will be unusable.

Usually, people will just restart the whole process again.

One thing you might help with is to do some keep-alive actions, such as send heartbeat request once in a while to keep the websocket alive. Such as call `proto.BrowserGetVersion{}.Call(browser)` every hour.

**Comment by polyma** [comment]
Perhaps we can not expose the context.Canceled wrapped error. So we can use errors.Is(err, context.Canceled) without getting false positives. It makes sense that this library should not expose its implementation details (that it uses context to track browser connections). As a developer, I would only ever expect one context to be passed around, and that is my own.

**Comment by DiMiTriFrog** [comment]
Same problem with AWS Lambda.
How could I use it ?

**Comment by samymassoud** [comment]
Maybe if possible u can add some method to check the WS status on the browser level, something like

`rod.IsConnected()`

That way the implementer can put the check, in case if the browser WS was closed, we can re-initiate the process.

**Comment by ysmood** [comment]
@samymassoud 

> If the connection is lost, chrome will clean up all the references created by the cdp client, such as the page id we use to control the page, so even you reconnect to the same browser again, all the ids will be unusable.

Usually, you have to create a brand new cdp client.

**Comment by ysmood** [comment]
Use the [latest version](https://github.com/go-rod/rod/releases/tag/v0.106.3) you can do something like this:

```go
package main

import (
	"fmt"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	l := launcher.New()
	browser := rod.New().ControlURL(l.MustLaunch()).MustConnect()

	connLost := false
	go func() {
		<-browser.Event()
		connLost = true
	}()

	l.Kill()

	utils.Sleep(1)

	fmt.Println(connLost)
}
```

**Comment by aakarim** [comment]
Could you confirm that browser.Event() channel will only ever return an event when browser is disconnected?
