### ISSUE TITLE
Side by side code example between chromedp and rod

### ISSUE THREAD

**Issue by ysmood** [go-rod/rod#42]
To help users who are familiar with chromedp to understand rod better.

Reference: https://github.com/chromedp/examples

**Comment by youshy** [comment]
@ysmood can roll with that if you want

**Comment by ysmood** [comment]
Oh! that will be great! You can add a markdown under the `lib/examples/` to compare the examples, if you need more instructions just let me know.

**Comment by ysmood** [comment]
resolved by #75
