### ISSUE TITLE
incognito page not work

### ISSUE THREAD

**Issue by tingfeng-key** [go-rod/rod#421]
**Rod Version:** v0.99.1

## The code to demonstrate your question

```go
// Please make sure your code is minimal and standalone
func main() {
         url := launcher.New().
		Set("--incognito").
		MustLaunch()

	browser := rod.New().ControlURL(url).MustConnect()
	page := browser.MustPage("https://www.google.com/")
}
```

Incognito Mode does not work

**Comment by ysmood** [comment]
Learn how to search before asking questions.

![image](https://user-images.githubusercontent.com/1415488/119268970-e19f6c00-bc27-11eb-8576-c328cd489cf0.png)

**Comment by tingfeng-key** [comment]
thanks
