### ISSUE TITLE
How would I evaluate a function

### ISSUE THREAD

**Issue by elbek** [go-rod/rod#422]
**Rod Version:** v0.99.0

## The code to demonstrate your question

```go
// Please make sure your code is minimal and standalone
func main() {
		data, err := ioutil.ReadFile("js-file.js")
		if err != nil {
                       //log
			return
		}
		jsContent := string(data)
		_, err = page.Eval(jsContent)



                // then later I would like to call a function inside the .js file above
                result, err := page.Eval("jsFunc(2)")
                result, err = page.Eval("jsFunc(3)")
}
```

## What have you tried to solve the question
Right now when I try it gives `jsFunc` is not defined error.

**Comment by elbek** [comment]
For example this one:
https://github.com/go-rod/rod/blob/443e72df8e1b19fb43e66fe8a14375934c00d351/lib/launcher/load_test.go

I I create `wait()` function using `page.Eval(jsContent)` it is not callable later

**Comment by ysmood** [comment]
https://go-rod.github.io/#/javascript-runtime?id=define-a-global-function

**Comment by elbek** [comment]
Thank you, ysmood!
