### ISSUE TITLE
Easier way to avoid panic with Must helpers.

### ISSUE THREAD

**Issue by egonelbre** [go-rod/rod#424]
Currently all the `Must` helpers call to `utils.E`, which panics the test. One option would be to avoid `Must` methods altogether, however, they are rather convenient.

This is a problem, because with concurrent tests it will stop all the tests rather than just the test that failed.

I propose adding a `browser.OnFail` which accepts `interface { Fatal(args ...interface{}) }` and returns a `rod.Browser`. Instead of calling `utils.E` the browser would then call the on fail func.

The actual method name can be something entirely different.

**Comment by ysmood** [comment]
If you read the tests of Rod, every test is concurrent, one panic will not stop other tests. You can use the `rod.Try` to catch panics.

**Comment by egonelbre** [comment]
So, here's a simple example how panic stops tests:

```
package tests

import (
	"fmt"
	"testing"
)

func TestA(t *testing.T) { panic("x") }
func TestB(t *testing.T) { t.Log("y") }
func TestC(t *testing.T) { t.Log("z") }
```

The tests `TestB` and `TestC` won't run.

`rod.Try` catches all panics rather than rod panics.

**Comment by ysmood** [comment]
> rod.Try catches all panics rather than rod panics.

We already documented the trade-off: 

https://github.com/go-rod/rod/blob/0998fccf111871a7e2168a4e717bd522f31e75b6/examples_test.go#L169

**Comment by ysmood** [comment]
If you want to have full control of errors you can just use the non-must-prefixed API.

I understand your proposal, browser and nodejs use this way, but in practice I never use it, it will catch too many extra errors, even worse than using `rod.Try`, at least `rod.Try` can control which part you want to catch easily, and the execution flow is linear, no hidden stack.

I welcome all kinds of solutions, as long as you can make a PR to demo how it works, I'd like to give it a try. For now, it's hard for me to imagine the value of it.

Also we used to have another proposal, I feel it's more controllable than yours: https://github.com/go-rod/rod/issues/166

**Comment by egonelbre** [comment]
So that's the rough idea on what I mean. Hopefully it makes it clearer.

**Comment by ysmood** [comment]
Write some chained methods and test them with intentional errors, you will find out your design's problem.

**Comment by ysmood** [comment]
Also if you use [got](https://github.com/ysmood/got) as your test framework, you won't have the panic crash problem at all:

```go
@@ -0,0 +1,23 @@
package main_test

import (
	"testing"

	"github.com/ysmood/got"
)

type T struct {
	got.G
}

func Test(t *testing.T) {
	got.Each(t, T{})
}

func (t T) A() {
	panic("err")
}

func (t T) B() {
	t.Log("B will still be tested")
}
```

**Comment by egonelbre** [comment]
> Write some chained methods and test them with intentional errors, you will find out your design's problem.

I don't quite understand the problem you mean?

**Comment by ysmood** [comment]
I mean, nil pointer panics. Just try it in a real project, you will find out, pretty obvious.

**Comment by egonelbre** [comment]
Just to clarify, you mean that the implementation itself is buggy or the idea is problematic? I'm very well aware that the implementation is unfinished with correctness in mind.

**Comment by egonelbre** [comment]
> Besides, if you use got v0.13.1 as your test framework, you won't have the panic crash problem at all:

Replacing the testing framework unfortunately is not a good solution, in my case.

**Comment by ysmood** [comment]
> Just to clarify, you mean that the implementation itself is buggy or the idea is problematic? I'm very well aware that the implementation is unfinished with correctness in mind.

I mean design will cause nil pointer panics a lot, how can you prevent that?

**Comment by egonelbre** [comment]
Note, I'm completely fine if this is not a good fit for the library, but just trying to understand the problem.

If there's a nil pointer panic, this means that there was some earlier code that didn't handle failure scenario properly. i.e. some method returned `nil` result and `nil` error.

> If we fail to create a new page or fail to get the element, what will happen to MustClick?

`MustClick` won't be called.

**Comment by ysmood** [comment]
It's too late tonight. I'll explain why yours has the same fundermental design issue as #166 tomorrow. You can polish your PR before that.

I think if you can solve the problem, I will be happy to accept your PR.

**Comment by ysmood** [comment]
If all you want is to be able to implement your own panic, then we can have a better design. I will create  PR and ask you to review it.
