### ISSUE TITLE
Some missing closes of Response.Body in the library

### ISSUE THREAD

**Issue by egonelbre** [go-rod/rod#427]
**Rod Version: v0.99.1**

While reviewing 0998fccf111871a7e2168a4e717bd522f31e75b6 with some of my usual linters I noticed that there are quite a few cases where req.Body is not being closed.

Per https://golang.org/pkg/net/http/#Client.Get (and similar) the caller should always close `Response.Body`.

https://github.com/timakin/bodyclose found these cases:

```
$ go vet -vettool=$(which bodyclose) ./...

# github.com/go-rod/rod/lib/devices/generate
lib/devices/generate/main.go:78:22: response body must be closed

# github.com/go-rod/rod/lib/launcher/revision
lib/launcher/revision/main.go:23:22: response body must be closed

# github.com/go-rod/rod/lib/utils/check-issue
lib/utils/check-issue/main.go:62:36: response body must be closed
lib/utils/check-issue/main.go:77:35: response body must be closed

# github.com/go-rod/rod/lib/cdp
lib/cdp/websocket.go:199:31: response body must be closed

# github.com/go-rod/rod/lib/launcher
lib/launcher/manager.go:49:22: response body must be closed
lib/launcher/url_parser.go:104:22: response body must be closed

# github.com/go-rod/rod/lib/proto/generate
lib/proto/generate/utils.go:25:22: response body must be closed

# github.com/go-rod/rod/lib/examples/stripe
lib/examples/stripe/main.go:41:33: response body must be closed

# github.com/go-rod/rod/lib/examples/use-rod-like-chrome-extension
lib/examples/use-rod-like-chrome-extension/main.go:84:22: response body must be closed
```

I was looking into fixing these and some are an obvious fix to add `defer res.Body.Close()`. However, some of these use `gson.New(res.Body)` and which may delay the reading of body in the first place.

My idea was to use `io.ReadAll` in all of these location and then use that as an input to `gson.New`. If that sounds like a good approach, I can send a PR.

PS: I think most of them are in a place where a leak doesn't cause problems.

**Comment by ysmood** [comment]
> My idea was to use io.ReadAll in all of these location and then use that as an input to gson.New. If that sounds like a good approach, I can send a PR.

Yes, sounds good. Also please update the lint config: https://github.com/ysmood/golangci-lint

The reason why we use https://github.com/ysmood/golangci-lint is here: https://github.com/golangci/golangci-lint/issues/1657

**Comment by ysmood** [comment]
Close in favor of #431
