### ISSUE TITLE
Pages.Find, .FindByURL, .MustFind and .MustFindByURL may return nil without error

### ISSUE THREAD

**Issue by egonelbre** [go-rod/rod#430]
**Rod Version:** v0.99.1

Currently when `Pages` does not contain the appropriate page it returns `err == nil` from `.Find`, `.FindByURL`, `.MustFind` and `.MustFindByURL`.

I would expect to get some sort of `ErrPageNotFound` (and failure from `Must` methods), alternatively, if that is the intended behavior, then it should be documented.

This is important for `Must` methods, because they are chained and the implementation may end up with a call to nil `*Page`.

**Comment by ysmood** [comment]
Agree.
