### ISSUE TITLE
How to get the page information after clicking

### ISSUE THREAD

**Issue by tingfeng-key** [go-rod/rod#438]
Click the link in the page to open a new page. How to get the information of the new page

**Comment by ysmood** [comment]
Already answered in other issues.

**Comment by tingfeng-key** [comment]
Before and after your reply, I searched issue and documents, but I didn't find any answers to my questions. Please give me your advice. The keywords I searched are click and tab

**Comment by ysmood** [comment]
You are violating 5 in #322: no mention about what keywords you have searched.

**Comment by tingfeng-key** [comment]
`click` and `tab`，I've already explained that

**Comment by ysmood** [comment]
![image](https://user-images.githubusercontent.com/1415488/121125729-a02ed380-c859-11eb-83fe-8d97fd19a7c2.png)

**Comment by tingfeng-key** [comment]
Thanks

**Comment by ysmood** [comment]
Before asking a question we should search at least multiple types of keywords. Only `click` and `tab` are too lazy and not respectful to the contributors.

**Comment by tingfeng-key** [comment]
I'm sorry that I didn't think of these words. If it's inconvenient and bothering you, I'm sorry to you

**Comment by ysmood** [comment]
I'm not blaming you, no need to say sorry, just want you to know that you already has the keywords, if you search the keywords in you first comment you will get the same result as me:

![image](https://user-images.githubusercontent.com/1415488/121130703-5ba73600-c861-11eb-8463-4645cd9823f7.png)
