### ISSUE TITLE
Failed to overrite request headers using MustSetExtraHeaders.

### ISSUE THREAD

**Issue by shuiRong** [go-rod/rod#443]
**Rod Version:** v0.100.0

## The code to demonstrate your question

```go
// Please make sure your code is minimal and standalone
func main() {
	page := browser.MustPage("")

	page.MustSetExtraHeaders("User-Agent", "Mozilla/5.0(compatible;Baiduspiderrender/2.0;+http://www.baidu.com/search/spider.html)","asd123","asdasd")

	page.MustNavigate("https://weibo.com/1768473917/KikMXnlbi").MustWaitElementsMoreThan("div", 10)
}
```

## What have you tried to solve the question

给页面设置一个搜索引擎专用的UA，但发现由于请求自带UA，所以设置没有生效。
作为对照，设置"asd123"生效了。

![image](https://user-images.githubusercontent.com/16076993/123056693-bc299c00-d439-11eb-8337-343a02f97808.png)

1. `MustSetExtraHeaders`只能设置原请求不存在的 Header 吗？
2. 除了`MustSetExtraHeaders`，还有其他设置请求 Header 的办法吗？

**Comment by ysmood** [comment]
麻烦先读读文档吧 https://go-rod.github.io/#/emulation?id=user-agent
有中文版，自己点几下吧

**Comment by ysmood** [comment]
另外能帮忙创建一个 PR， 给 SetExtraHeaders 加点文档吗？ Extra 的意思是除了 浏览器自动会设置的头以外的头，UA 就不在 extra 里。

**Comment by shuiRong** [comment]
通过给微博爬虫设置 百度搜索引擎 的UA，可以拿到微博页面内容了（不过只有html本身）
```
page.MustSetUserAgent(&proto.NetworkSetUserAgentOverride{
		UserAgent: "Mozilla/5.0(compatible;Baiduspiderrender/2.0;+http://www.baidu.com/search/spider.html)",
	})
```
