### ISSUE TITLE
Possible to use use rod.Race() in a background context?

### ISSUE THREAD

**Issue by BoladoLimited** [go-rod/rod#446]
**Rod Version:** v0.100.0

## The code to demonstrate your question

```go
// Please make sure your code is minimal and standalone
go func() {
	for {

		page.Race().ElementX("//video[@class='ad']").MustHandle(func(e *rod.Element) {
	            videoAdPlaying = true
		    gifAdPlaying = false
		}).ElementX("//div[@class='image-ad-container']").MustHandle(func(e *rod.Element) {
		    gifAdPlaying = true
		    videoAdPlaying = false
		}).MustDo()

	}
}()
```

## What have you tried to solve the question

The code above is just an example, I wanted to leave a race running while I do other actions within the page, but I came across some "concurrent map read and map write" panics.

**Comment by ysmood** [comment]
This is a bug, a temp solution is to use a mutex lock to do it in the background. I will fix it when I have time.

**Comment by ysmood** [comment]
If you want to help to make a PR, just replace below with a `sync.Map` will fix it:

https://github.com/go-rod/rod/blob/5c495a128e0a52c2f53c05cf25ae53a3c79915a7/page.go#L60

**Comment by ysmood** [comment]
Can you try `v0.101.2`, and see if this still happens.

**Comment by BoladoLimited** [comment]
So far haven't noticed the same behavior.  Will update if I see anything.
