### ISSUE TITLE
Manual Browser Close Event

### ISSUE THREAD

**Issue by RambIing** [go-rod/rod#447]
I've looked around the docs and examples and can't find a function to wait for a user-controlled closing of a browser/page. Does this exist in rod yet? Would be similar to waiting for an element, however, I'm just trying to see if the browser is closed manually.

**Comment by BoladoLimited** [comment]
If user close the browser, it will close the cdp connection as well, so I don't think you can do it, I could be wrong tho.

**Comment by ysmood** [comment]
@RambIing If the process is launched by you, you can wait for the process to exit. Look at this example:

https://github.com/go-rod/rod/blob/5c495a128e0a52c2f53c05cf25ae53a3c79915a7/lib/launcher/example_test.go#L34

You can use the `cmd.Wait` to achieve that. It's not a Rod problem, it's just a common Go process API.

**Comment by ysmood** [comment]
If anyone has an idea to achieve this, please feel free to ask to reopen it.

**Comment by ysmood** [comment]
BTW, you can listen to a page close event, search `TargetTargetDestroyed` in this project the learn how to use it.

**Comment by RambIing** [comment]
Did not know that, thank you!

I'll open a PR once I get it down for the example 😄
