### ISSUE TITLE
How do I get the response of a request that is made after clicking a button?

### ISSUE THREAD

**Issue by jj0e** [go-rod/rod#449]
**Rod Version:** v0.4.3

## The code to demonstrate your question

```go
import (
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/devices"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/stealth"
)

func main() {
    path, _ := launcher.LookPath()
    browser := rod.New().ControlURL(launcher.New().Bin(path).Headless(false).MustLaunch)).MustConnect()
    page := stealth.MustPage(browser)
    page.MustEmulate(devices.Pixel2)
    page.MustNavigate("redacted_url")
    page.MustWaitLoad()
    page.MustElement(`input[name="emailAddress"]`).MustInput(task.Email)
    page.MustElement(`input[name="password"]`).MustInput(task.Password)
    // There is an element that should go here to click the button, that sends a request and contains the response body that I'm looking for
    
    time.Sleep(time.Hour * 100)
}
```

## What have you tried to solve the question

I have tried looking into the [HijackRequest](https://go-rod.github.io/#/network?id=hijack-requests) feature as it seems there is a way to accomplish what I need. However, to be quite honest I'm just confused on how exactly it works. I've also looked at the [tests](https://github.com/go-rod/rod/blob/master/hijack_test.go). I am confused about the parts where it a router is created like so:

```go
func (t T) HijackLoadResponseErr() {
	p := t.newPage().Context(t.Context())
	router := p.HijackRequests()
	defer router.MustStop()

	wg := &sync.WaitGroup{}
	wg.Add(1)

	router.MustAdd("http://test.com/a", func(ctx *rod.Hijack) {
		t.Err(ctx.LoadResponse(&http.Client{
			Transport: &MockRoundTripper{err: errors.New("err")},
		}, true))

		t.Err(ctx.LoadResponse(&http.Client{
			Transport: &MockRoundTripper{res: &http.Response{
				StatusCode: 200,
				Body:       ioutil.NopCloser(&MockReader{err: errors.New("err")}),
			}},
		}, true))

		wg.Done()

		ctx.Response.Fail(proto.NetworkErrorReasonAborted)
	})

	go router.Run()

	_ = p.Navigate("http://test.com/a")

	wg.Wait()
}
``` 

with a given url. I didn't really see any examples that extracted the response after a button click. Am I suppose to create a router and then use `.MustAdd()` and pass in the url of the `POST` request that the button executes? How would I also then get the actual response body?

**Comment by ysmood** [comment]
I can create a button that can trigger 100 random requests to 100 urls, I think it's hard to distinguish them. How can you tell if a request is triggered by a random button?

**Comment by jj0e** [comment]
> I can create a button that can trigger 100 random requests to 100 urls, I think it's hard to distinguish them. How can you tell if a request is triggered by a random button with devtools?

I don't think I'm fully understanding what you're asking. When the button is clicked, a login request is sent. I want to track the response of this login request. With that being said, I have done some further research in the meantime and believe that what I'm trying to achieve can be done with go-rod and rather with something like [this](https://betterprogramming.pub/chrome-extension-intercepting-and-reading-the-body-of-http-requests-dd9ebdf2348b). For that reason I will go ahead and close this issue to not waste any more of your time. Thanks

**Comment by ysmood** [comment]
Rod can do almost everything an extension can do, just follow the same logic should solve your problem.
