### ISSUE TITLE
Why does a DOS window appear when the browser is closed?

### ISSUE THREAD

**Issue by smp12345** [go-rod/rod#450]
The following is the sample code. Why does a DOS window flash past after the program ends? Can I cancel the DOS window flash screen?

System: win10
Browser version:89.0.4389.114

```
	path, _ := launcher.LookPath()
	u := launcher.New().Bin(path).MustLaunch()
	rod.New().ControlURL(u).MustConnect().MustPage("https://baidu.com")
```

**Comment by BoladoLimited** [comment]
It's because of leakless, I still uses the 0.6.8 version of leakless cause it still works in my use case, recent versions open this DOS window when closing, and it can be quite heavy when you close 100+ at the same time. 

But yeah, it's leakless making sure everything is being closed.

**Comment by ysmood** [comment]
The new leakless shouldn't have this window, can you try an empty Go program without Rod?

**Comment by smp12345** [comment]
Without using the rod program, no problems have been found.To compile is to simply go build

**Comment by ysmood** [comment]
@smp12345 What version of Rod are you using?

**Comment by smp12345** [comment]
rod@v0.101.1

**Comment by smp12345** [comment]
When I use newUserMode, I don't see this problem, it is normal.
```
wsURL := launcher.NewUserMode().MustLaunch()
browserOpt.browser = rod.New().ControlURL(wsURL).MustConnect().NoDefaultDevice()
```

**Comment by ysmood** [comment]
@smp12345 do you know how to disable leakless?

**Comment by smp12345** [comment]
I don't know how to disable it.

**Comment by BoladoLimited** [comment]
> I don't know how to disable it.

One way is that you can use .Leakless(false) while initializing launcher like this. https://github.com/go-rod/rod/blob/4bdc9bfd4811300521d00983a530bbe542971400/lib/launcher/launcher_test.go#L136

**Comment by smp12345** [comment]
OK, I'll try. Thank you
