### ISSUE TITLE
virus?

### ISSUE THREAD

**Issue by imbaMF** [go-rod/rod#452]
**Rod Version:** v0.101.1

Why when i build a script just with ur package? a windows defender detect it as a virus? and some of antivirus of virustotal detect it to?
![1](https://user-images.githubusercontent.com/11431176/124740729-b9dc3d00-df23-11eb-9378-7b0ecdb36feb.png)

https://www.virustotal.com/gui/file/9a42cabc783d08e6355cd6fa926a58466ccd5fd71382d149023ef74d76831c7f/detection

**Comment by ysmood** [comment]
This should be a false alarm. The binary we use is built by Github, I don't think Github is spreading virus.

Read this doc carefully: https://github.com/ysmood/leakless

**Comment by ysmood** [comment]
I just tried a, works fine to me, the Windows 10 Defender I use is up to date, steps to reproduce:

1.  Build the the exe: `go build ./lib/examples/custom-launch`
2. Use a custom scan to scan this file.
3. 0 threats.

Please ask me to reopen this issue if you can provide more info.
