### ISSUE TITLE
Automatic Viewport resize in Chrome-nonheadless

### ISSUE THREAD

**Issue by andre-rice** [go-rod/rod#453]
Hi,

I really enjoy playing with this project and I love how much you went into detailing many ways to utilize the library.

I have noticed that the viewport get's set and stays set no matter how I change the chrome window size manually. Is there a specific reason for this? Also, is there a simple way to address this in the options?

So far I was able to write an event watcher to look for DOMDocumentUpdated events and refresh the viewport every time the dom is updated. It's not a great solution but it got me into thinking about how to further utilize the library. 

I'm currently using it to automate some manual tasks with the intent to automate more based on feedback. However in the mean time I would be using manual controls alongside automation tasks backed by rod. So I need the non-headless mode to work dynamically as an application almost would. 

Thank you very much for your work on this.

**Comment by andre-rice** [comment]
Ah,

I think I see the reasoning now. With the click functions they must wait for the element to be stable and interactable. If the viewport is too small then the elements can get hidden. 

I just noticed certain functions not working when an element was barely hidden. Still would like to know a way around this if it ever becomes something useful.

**Comment by ysmood** [comment]
Read the doc carefully 😉 https://go-rod.github.io/#/emulation?id=emulation

**Comment by ysmood** [comment]
Also could you help to add it to the FAQ? Too many people are asking this question. https://go-rod.github.io/#/faq/README
