### ISSUE TITLE
 Page blocked after change

### ISSUE THREAD

**Issue by 3490654586** [go-rod/rod#455]
1. I jump from the landing page to the home page, is there any way to get the address of the home page, because the address parameter of the home page is not fixed, I want to get it automatically?
  2. After I finish the operation on the first page, I'm ready to jump to the second page. How to solve the problem of mustelement blocking

**Comment by ysmood** [comment]
Sorry, we can't reproduce it. Can you provide minimal code and steps for us to reproduce your issue?

**Comment by ysmood** [comment]
Please ask us to reopen once you provide more info.
