### ISSUE TITLE
chrome does not start on windows 10 with the Leakless(true) launcher option

### ISSUE THREAD

**Issue by errordnk** [go-rod/rod#457]
**Rod Version:** v0.101.4

```go
package main

import (
  "fmt"
  "time"
  "github.com/go-rod/rod"
  "github.com/go-rod/rod/lib/launcher"
)

func main() {
    path, _ := launcher.LookPath()
    fmt.Println("path: ", path)
    l := launcher.New().Bin(path).Headless(false).Leakless(true).RemoteDebuggingPort(10000)
    fmt.Println("launcher: ", l)
    defer l.Cleanup()
    u,_ := l.Launch()
    fmt.Println("chrome url: ", u)
    b := rod.New().ControlURL(u).MustConnect().Trace(true).Timeout(60 * time.Second)
    fmt.Println("browser: ", b)
    defer b.MustClose()
    p := b.MustPage("https://github.com/")
    fmt.Println("page: ", p)
    p.MustWaitLoad().MustScreenshot("github.png")
}

```
main.exe is hanging on l.Launch() without error

**Comment by ysmood** [comment]
Can you clone the leakless project and run the unit test of it?

**Comment by errordnk** [comment]
Аre you talking about this project https://github.com/ysmood/leakless?
Test does not work on my wi10 installation
C:\Go\leakless-master>go test -- hanging
press Ctrl+C

**Comment by ysmood** [comment]
For leakless repo, can you run `go test -v` and tell us which test will hang?

**Comment by errordnk** [comment]
first TestBasic hanging

C:\Go\leakless-master>go test -v                 
=== RUN   TestBasic                              
^C
exit status 3221225786                           
FAIL    github.com/ysmood/leakless      187.553s

**Comment by ysmood** [comment]
Maybe it's blocked by a firewall or antivirus software?

**Comment by errordnk** [comment]
My antivirus and firewall are always disabled

**Comment by ysmood** [comment]
The github Actions of Rod uses Windows Server 2022, I think it should be similar with Windows 10, I will close it for now.

https://github.com/go-rod/rod/runs/5751126035?check_suite_focus=true
