### ISSUE TITLE
Basic auth make so browser doesn't open new page

### ISSUE THREAD

**Issue by wchretien** [go-rod/rod#458]
Can't seem to be able to use auth handling. When Im trying to use it, only a blank page appears and nothing else happen.
Obviously here I removed my credentials and URL but they're all correct when using inside my code.

**Rod Version:** v0.101.4

## The code to demonstrate your question

```go
package main

import (
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/proto"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	l := launcher.New().
		Headless(false).
		Devtools(true)

	defer l.Cleanup() // remove launcher.FlagUserDataDir

	url := l.MustLaunch()

	// Trace shows verbose debug information for each action executed
	// Slowmotion is a debug related function that waits 2 seconds between
	// each action, making it easier to inspect what your code is doing.
	browser := rod.New().
		ControlURL(url).
		Trace(true).
		SlowMotion(2 * time.Second).
		MustConnect()

	defer browser.MustClose()

	browser.MustIgnoreCertErrors(true)

	browser.HandleAuth("username", "password")
	page := browser.MustPage("url").MustWaitLoad()

	pdf, _ := page.PDF(&proto.PagePrintToPDF{
		PaperWidth:      8.5,
		PaperHeight:     11,
		PrintBackground: true,
	})
	_ = utils.OutputFile("my.pdf", pdf)
}

```

## What have you tried to solve the question
Tried both `MustHandleAuth` and `HandleAuth`, both with `go browser.HandleAuth.. ()`, both before or after `MustPage` but it obvisouly need to be before `MustPage`. So yeah, what am I doing wrong?

**Comment by ysmood** [comment]
Sorry, I cannot reproduce your problem.

**Comment by wchretien** [comment]
Once I `go build` and run `./main` the current code above with proper creds and URL. I get this infinite loading blank page and nothing happens.
![Screenshot from 2021-07-27 10-51-17](https://user-images.githubusercontent.com/1131670/127176396-f78d954b-c677-41e0-834d-61582a07e8a3.png)

**Comment by ysmood** [comment]
Replace `browser.HandleAuth("username", "password")` with `go browser.HandleAuth("username", "password")`

**Comment by andre-rice** [comment]
Yeah, 

I'm able to reproduce the same result. It's also using same default dialog login for my url/cred server. 

Normal:
![image](https://user-images.githubusercontent.com/52677379/128454558-ed267926-916c-4d3b-b62e-b1f0dfbfddf3.png)

Rod:
![image](https://user-images.githubusercontent.com/52677379/128454667-359ae2e9-5207-4a3f-9b49-ad37f6a26a32.png)

**Comment by ysmood** [comment]
The unit test works fine, we run a mock server: https://github.com/go-rod/rod/blob/b75b8ec4f46c1ad2e74e9ccddb93f08115395c7e/hijack_test.go#L272

**Comment by mahmutcetin** [comment]
if you connect website with basic auth you can use url: http://admin:password@192.168.1.1

**Comment by ysmood** [comment]
Close because inactively.
