### ISSUE TITLE
docker 和 rod相关配置的文档

### ISSUE THREAD

**Issue by ysk229** [go-rod/rod#464]
当然是可以的，FAQ 里有提到这个问题，docker 和 rod：

https://github.com/go-rod/rod#q-how-to-use-rod-with-docker

_Originally posted by @ysmood in https://github.com/go-rod/rod/issues/84#issuecomment-653310593_

请问一下，这个链接失效，打不开。我需要这样的配置，要不然在headless 模式下，只能后台截图，这样觉得太麻烦了，请问一下，有没有这相关方面的配置啊？？

**Comment by ysmood** [comment]
https://go-rod.github.io/#/custom-launch?id=remotely-manage-the-launcher
