### ISSUE TITLE
Suggestions for enhancing the Eval function

### ISSUE THREAD

**Issue by Fly-Playgroud** [go-rod/rod#468]
Testing has shown that the Eval function works well for small js code, but is weak for large js code.
Large js code executions are recommended using：

- `EvalExpression(js string) (gson.JSON, error)`
- `EvaluateExpression(js string) (*proto.RuntimeRemoteObject, error)'`

Implement these two functions for executing large chunks of js code.

Eval is designed to facilitate the injection of small pieces of js.

Another implementation idea is: **Enhancing Eval's intelligent recognition**

The recognition algorithm is here：https://github.com/go-rod/rod/blob/8a1a350c4c2a3f0b7dee26e3eed0d82f80baf0da/utils.go#L255

Feel free to get involved and write more unit tests to make it more robust.

**Comment by ysmood** [comment]
No need for this we will always use function definition for eval.
