### ISSUE TITLE
How to throttle the network

### ISSUE THREAD

**Issue by alicazi** [go-rod/rod#470]
**Rod Version:** v0.101.5

I'm wondering how I can throttle the network. I didn't find any reference to throttling in the documents and examples.

**Comment by ysmood** [comment]
```go
	page.EnableDomain(proto.NetworkEnable{})

	proto.NetworkEmulateNetworkConditions{
		Offline:            false,
		Latency:            300,
		DownloadThroughput: 100,
		UploadThroughput:   50,
		ConnectionType:     proto.NetworkConnectionTypeCellular2g,
	}.Call(page)
```

**Comment by ysmood** [comment]
It will be great if you could help to add this to the doc site: https://go-rod.github.io/#/network

**Comment by alicazi** [comment]
@ysmood I adde the code under network/throttling.

**Comment by ysmood** [comment]
@alicazi Looks good, could you make a PR for it?

**Comment by alicazi** [comment]
I just created the pull request but I'm not fully familiar with this process but definitely willing to help. Let me know if I missed to do something.

**Comment by ysmood** [comment]
Merged https://github.com/go-rod/go-rod.github.io/commit/73fdf3157914a656bb8f1eb224ebf0e3da6f3402
