### ISSUE TITLE
What is the best practice to manage tests and have some reporting with rod.

### ISSUE THREAD

**Issue by alicazi** [go-rod/rod#471]
**Rod Version:** v0.101.5

i used to work with webdriverio frame work in Javascript. I migrated most of my test cases to rod. The tests are now running much faster (close to 2X faster) which is excellent. 

I was trying to create some reporting when I running many test cases as go-routines. I did some coding and it works for me but I had to handle the panic,  timeout, retry count, etc. to keep the tests moving even in case of one test failed for any reason and have a summary report at the end. Frankly without a high level test manager I don't see how this can work in real world when someone has 10s to 100a of test cases that want to run as much as possible concurrently.

I'm wondering if there is a best practice, solution or a library to manage test cases and provide reporting.

**Comment by ysmood** [comment]
Have you checked this project? https://go-rod.github.io/#/end-to-end-testing

Also, the unit tests rod uses for itself is also a good example.
