### ISSUE TITLE
请问一下，在.rod文件配置show的参数，使用headless 模式跑，程序一直卡住，加了show参数就可以正常跑

### ISSUE THREAD

**Issue by ysk229** [go-rod/rod#477]
请问一下，在.rod文件配置show的参数，使用headless 模式跑，程序一直卡住，加了show参数就可以正常跑。想部署在linux不想出现浏览器界面，想像脚本一样，一直在命令行跑。不知道要配置什么样的参数，才像能加了show参数一样正常跑呢？？

**Comment by ysmood** [comment]
https://go-rod.github.io/#/custom-launch?id=remotely-manage-the-launcher
