### ISSUE TITLE
Go test --browser-bin not working properly

### ISSUE THREAD

**Issue by gregtczap** [go-rod/rod#481]
**Rod Version:** v0.101.5

## The code to demonstrate your question

The following code should run the tests using the existing browser specified by `--browser-bin`:

```bash
git clone git@github.com:go-rod/rod.git
cd rod
go test -v --browser-bin=/usr/bin/google-chrome
```

But instead the result is an attempt to download a new browser:

```bash
Download: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/901912/chrome-linux.zip
Progress: 00% 03% 07%^Csignal: interrupt
FAIL	github.com/go-rod/rod	2.911s
```

## System specs

* OS: Pop!_OS 20.04 LTS (Essentially Ubuntu 20.04)
* Results of [launcher.LookPath()](https://pkg.go.dev/github.com/go-rod/rod/lib/launcher#LookPath): `/usr/bin/google-chrome`
* go-rod branch: `master` (Aug 30, 2021)

**Comment by ysmood** [comment]
The doc is outdated, you can use the rod env or `.rod` file to set the bin path.

**Comment by gregtczap** [comment]
@ysmood Is the `.rod` file or rod env you mention documented anywhere. Upon searching, I can find them also mentioned but not documented on https://go-rod.github.io

**Comment by ysmood** [comment]
@gregtczap https://pkg.go.dev/github.com/go-rod/rod@v0.101.5/lib/defaults
