### ISSUE TITLE
How to get the source code of the original webpage, not after the second page？

### ISSUE THREAD

**Issue by iiiusky** [go-rod/rod#483]
**Rod Version:** v0.0.0

## The code to demonstrate your question

```go
// Please make sure your code is minimal and standalone
func main() {
                browser := rod.New().MustConnect()
	defer browser.MustClose()
	page := browser.MustPage("https://geektutu.com/feed.xml")
	wait := page.WaitEvent(&proto.PageLoadEventFired{})
	wait()
        time.sleep(3  * time.Second)
	fmt.Println(page.MustHTML())
}
```

## What have you tried to solve the question
I requested that my web page be in xml format. After the request, I used the MustHTML() method to get the source code, but in the returned result, an html node was nested in the outermost layer, and some inexplicable node data was added. The test site is: https://geektutu.com/feed.xml

**Comment by ysmood** [comment]
You don't need to rod for this, use the `http.Request`.

**Comment by iiiusky** [comment]
> You don't need rod for this, use the `http.Get("https://geektutu.com/feed.xml")`.

This is just an example, the actual website needs to be accessed with a headless browser. Please grasp the focus of the problem.

**Comment by ysmood** [comment]
As long as the actual website uses xml it's not a valid html website, headless is not designed for it. Why does it require a browser?

**Comment by ysmood** [comment]
Anyway, you can use this to get the raw content https://go-rod.github.io/#/page-resources/README?id=page-resources
