### ISSUE TITLE
Headless is true还是有浏览弹出来

### ISSUE THREAD

**Issue by ysk229** [go-rod/rod#485]
**Rod Version:** v0.0.0

## The code to demonstrate your question

```go
 url := launcher.
            NewUserMode().
            Headless(true).
            Delete("use-mock-keychain"). // delete flag "--use-mock-keychain"
            Set("disable-extensions").
            Delete("disable-extensions").
            Set("disable-blink-features", "AutomationControlled").
            Set("excludeSwitches", "enable-automation").
            MustLaunch()
        browser = rod.New().ControlURL(url).Timeout(time.Second * viper.GetDuration("timeout")).MustConnect().NoDefaultDevice()
```

## What have you tried to solve the question
这样的运行，还会弹出浏览器出来，不知道那里代码少了什么，导致浏览器出来，我想让它不出来，因为是跑在docker环境的。
在.rod文件是配置trace。我在issues找了各种方式也会弹出浏览器来，比如把所有浏览器的进程杀掉，还是会弹出来的

**Comment by ysmood** [comment]
因为 `NewUserMode` 是单例模式，会试图复用已经启动的 ”用户浏览器“，你浏览器可能已经以 headful 模式启动了。你需要完全关闭浏览器之后再运行你这段代码。你仔细阅读下 NewUserMode 的文档，其实说的比较清楚了。

**Comment by ysk229** [comment]
用Headless模式，好像提交表单，出现403Access Denied，如果用了page := stealth.MustPage(browser)反而更多的网页出来403Access Denied

**Comment by ysmood** [comment]
如果和本问题无关，请开个新的 issue
