### ISSUE TITLE
自动点击Button的时候遇到图片遮挡的问题

### ISSUE THREAD

**Issue by allanpk716** [go-rod/rod#486]
**Rod Version:** v0.97.2

## What have you tried to solve the question

在加载这个[页面](https://subhd.tv/a/522893)的时候，想要自动点击“下载”按钮，首先可以找到对应的“下载”按钮的 element，但是遇到一个问题，就是其实这上面还有一个广告，如果执行“下载”按钮 element 的 MustClick() 就会出错。提示如下错误：
`element covered by: <img>`
意思是理解的。之前在用其他类似的框架的时候，比如 python 的，会让 chrome 加载广告过滤的插件去屏蔽这种广告，从而避免点击出问题。不知道您这个项目有什么的解决方案呢？或者说怎么让 chrome 启动的时候去加载（或者去下载）一个插件呢？

**Comment by allanpk716** [comment]
找了以下相关问[文档](https://github.com/go-rod/rod/blob/a7722e5f40bd66b1119028fd1c7353a28395dc85/element_test.go)，按文档中的代码试了下，代码如下。

![image](https://user-images.githubusercontent.com/1176000/133467937-2979f58e-5412-4ab9-904d-eb60d8a40882.png)

在 Remove 的时候还是会崩溃，提示不在此 node 中。其实想 Hide 这 element 也行，但是没有找到对应的函数。或者说还有什么版本吗？

**Comment by ysmood** [comment]
https://go-rod.github.io/i18n/zh-CN/#/error-handling?id=%e6%a3%80%e6%9f%a5%e5%bc%82%e5%b8%b8%e7%b1%bb%e5%9e%8b

这样打印异常可以看到细节 `gop.P(err)`

**Comment by allanpk716** [comment]
> https://go-rod.github.io/i18n/zh-CN/#/error-handling?id=%e6%a3%80%e6%9f%a5%e5%bc%82%e5%b8%b8%e7%b1%bb%e5%9e%8b
> 
> 这样打印异常可以看到细节 `gop.P(err)`
> 
> https://github.com/go-rod/rod/blob/a7722e5f40bd66b1119028fd1c7353a28395dc85/error.go#L147-L150

感谢给出的思路。暂时的[想法](https://github.com/allanpk716/ChineseSubFinder/tree/dev/internal/pkg/rod_helper)是让 chrome 去加载 adblock 去实现的，刚测试 OK 了。
