### ISSUE TITLE
Implement a way to clear user-data files after execution

### ISSUE THREAD

**Issue by yusufozturk** [go-rod/rod#488]
Hi @ysmood 

We had an issue at client today. His disk was full and it was unable to do monitoring.

When we check the reason, we saw following files:

![image](https://user-images.githubusercontent.com/928600/133569130-5e1b70ae-2846-4389-b3c8-70b82285e2dd.png)

Directory content:

![image](https://user-images.githubusercontent.com/928600/133569228-ebacad21-be7e-49c9-a38b-ed20cd1242f0.png)

Here it says, it should be deleted after server reboot:

![image](https://user-images.githubusercontent.com/928600/133569257-95597c3f-b7a0-4138-b615-00c88ac3b4e0.png)

But client machines are usually up and running like hundreds of days.

Is it possible to clean the logs after execution? We are afraid that disk will be full in 2 days again.

Thanks for help.

**Comment by ysmood** [comment]
Have you read the example?

https://github.com/go-rod/rod/blob/a7722e5f40bd66b1119028fd1c7353a28395dc85/examples_test.go#L71

**Comment by yusufozturk** [comment]
Thanks, I missed this one, sorry!
