### ISSUE TITLE
如何跟踪拦截按钮点击后触发的请求

### ISSUE THREAD

**Issue by xdwangkx** [go-rod/rod#489]
**Rod Version:** v0.101.7

请问如果一个请求是在点击按钮之后触发的, 是否有方法可以拦截到这个请求呢?

## The code to demonstrate your question

```go
// Please make sure your code is minimal and standalone
func main() {
       var Code string
	browser := rod.New().MustConnect()
	defer browser.MustClose()

       //浏览器添加请求拦截器
	router := browser.HijackRequests()
	defer router.MustStop()
	router.MustAdd("https://*", func(ctx *rod.Hijack) {
		ctx.MustLoadResponse()
		if ctx.Request.Method() == http.MethodGet {
			return
		}
                // 这里我希望从这个请求的 Response 中解出Header里面的一个字段
		if Code == "" {
			Code = ctx.Response.Headers().Get("Code")
			fmt.Printf("Code:%s\n", Code)
		}
	})
	go router.Run()

	page := browser.MustPage("https://...")
	// 账号密码
	page.MustElement(".userAccount").MustInput("userName")
	page.MustElement(".input-pwd").MustInput("password").MustPress(input.Enter)
        // 这里输入完账号密码点击确认之后, 触发了一个请求, 但是这个请求的 Initiator 是 Other, 所以我上面创建的拦截器拦截不到这个请求
}
```

## What have you tried to solve the question
我看了[hijack_test](https://github.com/go-rod/rod/blob/master/hijack_test.go)中的用例, 并且尝试了`browser.HijackRequests()` 和 `page.HijackRequests()`都没有成功, 请问这个问题是否有方法解决呢?

**Comment by xdwangkx** [comment]
我看到之前有一个类似的[issue](https://github.com/go-rod/rod/issues/449), 但是其中似乎并没有提到解决方法

**Comment by ysmood** [comment]
比如一个 xhr 用了三方库或者 setTimeout 之类的，那 Initiator 基本就很难被用来判断请求是发起于哪个按钮了。通常是用过滤链接的 url 或者内容来决定要不要 drop 。

**Comment by xdwangkx** [comment]
> 比如一个 xhr 用了三方库或者 setTimeout 之类的，那 Initiator 基本就很难被用来判断请求是发起于哪个按钮了。通常是用过滤链接的 url 或者内容来决定要不要 drop 。

这里的drop指的是拦截器 不会 去拦截这个请求吗? 但是如果是通过过滤的方式选择性drop的话, 前提是他首先可以截获到所有的请求, 再根据 `router.MustAdd`中定义的 pattern 去将不符合要求的请求 drop ? 那我这里的 pattern 定义的是 `https://*`, 理论上是所有的https请求都可以的截获到的, 但是 实际情况是 点击登录之后的这个https请求没有拿到, 所以我想知道这里的判断条件除了pattern还有其他条件吗?

**Comment by ysmood** [comment]
都能拿到的，应该是你写的代码有 bug，这个等价于 devtools 的 network 调试器。
