### ISSUE TITLE
Using rod with browser extensions

### ISSUE THREAD

**Issue by canack** [go-rod/rod#490]
Can we install an ad-blocking plugin in the browser and make it work on every startup?
I installed adblocker on chrome.exe, but the program I wrote on go does not have adblocker installed.
Any ideas??

Thank you.

**Comment by ysmood** [comment]
Read this https://go-rod.github.io/#/custom-launch?id=user-mode

Or read this

https://github.com/go-rod/rod/blob/252b329c9ff8db7873fccf5e0fe4d16df2ded286/examples_test.go#L569-L589
