### ISSUE TITLE
Input and MustInput will always return an error if page navigation occurs shortly after said action

### ISSUE THREAD

**Issue by nightah** [go-rod/rod#497]
**Rod Version:** v0.101.8

## The code to demonstrate your question
This is following a discussion on the Discord channel, I've included code that allows full reproduction:
```bash
git clone https://github.com/authelia/authelia.git --branch gorod-test-reproduction
```

The specific test that results in a failure can be simulated with a couple of steps from the root of the cloned project and utilises Docker to spin up containers for said tests:

1. `source bootstrap.sh`
2.  `authelia-scripts --log-level debug suites test NetworkACL --test TestNetworkACLSuite/TestShouldAccessSecretUpon2FA`

The relevant code being executed can be found [here](https://github.com/authelia/authelia/blob/90fb99496ff14f3eb7720231e1195134a954a63c/internal/suites/suite_network_acl_test.go#L20-L39).
```go
ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	browser, err := StartRod()
	s.Require().NoError(err)

	defer func() {
		err = browser.WebDriver.Close()
		s.Require().NoError(err)
		browser.Launcher.Cleanup()
	}()

	targetURL := fmt.Sprintf("%s/secret.html", SecureBaseURL)
	page := browser.doVisit(s.T(), targetURL).Context(ctx)

	browser.verifyIsFirstFactorPage(s.T(), page)
	browser.doRegisterAndLogin2FA(s.T(), page, "john", "password", false, targetURL)
	browser.verifySecretAuthorized(s.T(), page)
```

The error specifically occurs [here](https://github.com/authelia/authelia/blob/90fb99496ff14f3eb7720231e1195134a954a63c/internal/suites/action_totp.go#L50-L57).
```go
func (rs *RodSession) doEnterOTP(t *testing.T, page *rod.Page, code string) {
	inputs := rs.WaitElementsLocatedByCSSSelector(t, page, "otp-input input")

	for i := 0; i < 6; i++ {
		err := inputs[i].Input(string(code[i]))
		require.NoError(t, err)
	}
}
```

If we attempt to catch the error on the `Input` of each element above, the very last `Input` will always fail, it seems that this occurs because the page navigates away and rod cannot verify the success or failure of said input.

## What have you tried to solve the question
I can work around the issue by discarding the error on the Input:
```go
func (rs *RodSession) doEnterOTP(t *testing.T, page *rod.Page, code string) {
	inputs := rs.WaitElementsLocatedByCSSSelector(t, page, "otp-input input")

	for i := 0; i < 6; i++ {
		_ = inputs[i].Input(string(code[i]))
	}
}
```

However, for obvious reasons, this isn't ideal. Another important note is that `MustInput` instead of `Input`:
```go
func (rs *RodSession) doEnterOTP(t *testing.T, page *rod.Page, code string) {
	inputs := rs.WaitElementsLocatedByCSSSelector(t, page, "otp-input input")

	for i := 0; i < 6; i++ {
		inputs[i].MustInput(string(code[i]))
	}
}
```

Also results in a test failure:
```
[rod] 2021/10/19 14:14:00 [wait] writable <input.makeStyles-otpDigitInput-33>
[rod] 2021/10/19 14:14:00 [input] input 9 <input.makeStyles-otpDigitInput-33>
[rod] 2021/10/19 14:14:00 [input] insert text 9 <page:DE8575BF>
    suite.go:63: test panicked: cannot find object: {"type":"object","subtype":"node","className":"HTMLInputElement","value":null,"description":"input.makeStyles-otpDigitInput-33","objectId":"-9001259992535198516.9.54"}
        goroutine 7 [running]:
        runtime/debug.Stack()
                /home/amir/go/go1.17.1/src/runtime/debug/stack.go:24 +0x65
        github.com/stretchr/testify/suite.failOnPanic(0xc00022e1a0)
                /home/amir/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:63 +0x3e
        panic({0xede3a0, 0xc000010910})
                /home/amir/go/go1.17.1/src/runtime/panic.go:1038 +0x215
        github.com/go-rod/rod/lib/utils.glob..func1({0xede3a0, 0xc000010910})
                /home/amir/go/pkg/mod/github.com/go-rod/rod@v0.101.8/lib/utils/utils.go:64 +0x25
        github.com/go-rod/rod.genE.func1({0xc00042af80, 0xc00038276c, 0x1})
                /home/amir/go/pkg/mod/github.com/go-rod/rod@v0.101.8/must.go:35 +0x5a
        github.com/go-rod/rod.(*Element).MustInput(0xc000475350, {0xc00038276c, 0xc00016b418})
                /home/amir/go/pkg/mod/github.com/go-rod/rod@v0.101.8/must.go:765 +0x8b
        github.com/authelia/authelia/v4/internal/suites.(*RodSession).doEnterOTP(0x1328f00, 0xc00022e1a0, 0x0, {0xc00049e4b0, 0x6})
                /srv/repos/authelia/internal/suites/action_totp.go:54 +0x75
        github.com/authelia/authelia/v4/internal/suites.(*RodSession).doValidateTOTP(0xc0002c40c0, 0x2b, 0xc000413b90, {0xc0000ba176, 0x34})
                /srv/repos/authelia/internal/suites/action_totp.go:70 +0xb0
        github.com/authelia/authelia/v4/internal/suites.(*RodSession).doLoginTwoFactor(0x0, 0xffa9b8, 0xc0003935c0, {0xff8ec5, 0x1331798}, {0xffa9b8, 0xfb10c0}, 0x90, {0xc0000ba176, 0x34}, ...)
                /srv/repos/authelia/internal/suites/action_login.go:68 +0x97
        github.com/authelia/authelia/v4/internal/suites.(*RodSession).doRegisterAndLogin2FA(0xc0002c40c0, 0x1001563, 0x1, {0xff8ec5, 0x4}, {0xffa9b8, 0x8}, 0xe0, {0xc0002c40c0, 0x2b})
                /srv/repos/authelia/internal/suites/action_login.go:110 +0xd2
        github.com/authelia/authelia/v4/internal/suites.(*NetworkACLSuite).TestShouldAccessSecretUpon2FA(0xc00000ecd8)
                /srv/repos/authelia/internal/suites/suite_network_acl_test.go:37 +0x31c
        reflect.Value.call({0xc000252de0, 0xc000010e28, 0x13}, {0xff8c31, 0x4}, {0xc000061e70, 0x1, 0x1})
                /home/amir/go/go1.17.1/src/reflect/value.go:543 +0x814
        reflect.Value.Call({0xc000252de0, 0xc000010e28, 0xc00000ecd8}, {0xc000052670, 0x1, 0x1})
                /home/amir/go/go1.17.1/src/reflect/value.go:339 +0xc5
        github.com/stretchr/testify/suite.Run.func1(0xc00022e1a0)
                /home/amir/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:158 +0x4b6
        testing.tRunner(0xc00022e1a0, 0xc000174bd0)
                /home/amir/go/go1.17.1/src/testing/testing.go:1259 +0x102
        created by testing.(*T).Run
                /home/amir/go/go1.17.1/src/testing/testing.go:1306 +0x35a
--- FAIL: TestNetworkACLSuite (21.00s)
    --- FAIL: TestNetworkACLSuite/TestShouldAccessSecretUpon2FA (21.00s)
FAIL
FAIL    github.com/authelia/authelia/v4/internal/suites 21.001s
FAIL
```

If you need to simulate the test to allow slower observation you can modify the following two areas:
1. https://github.com/authelia/authelia/blob/90fb99496ff14f3eb7720231e1195134a954a63c/internal/suites/webdriver.go#L39
2. https://github.com/authelia/authelia/blob/gorod-test-reproduction/internal/suites/suite_network_acl_test.go#L21

The second one controls the timeout context for the specific test.

**Comment by ysmood** [comment]
Sorry, I missed this issue, have you solved it?

> it seems that this occurs because the page navigates away and rod cannot verify the success or failure of said input.

Seems like a race condition, do you mean this:

```go
go func() {
    page.MustNavigate("somewhere else")
}()

page.MustElement("input").MustInput("test")
```

**Comment by nightah** [comment]
No, I haven't solved this. I have resorted to not validating those specific inputs.

Effectively the inputs are for a TOTP code, and from what I can tell because the React SPA navigates to a different URL as soon as the last input is entered (assuming the TOTP code is correct) it appears rod doesn't have enough time to validate the last input before the navigation away occurs?

**Comment by ysmood** [comment]
If we check the code of `Page.Input`, it will evaluate a js to dispatchEvent the input events:

https://github.com/go-rod/rod/blob/424ac3d95c6f762754a13657f43da298afdb5f1c/element.go#L274

https://github.com/go-rod/rod/blob/dc4a0043fc4c56aabe5e25b32174a363244563ea/lib/js/helper.js#L214-L217

If the page redirects to a new location too fast, after the input the eval will fail because the js context is lost.

I think the fix is simple, just ignore the error for fast redirection:

```go
func (rs *RodSession) doEnterOTP(t *testing.T, page *rod.Page, code string) {
	inputs := rs.WaitElementsLocatedByCSSSelector(t, page, "otp-input input")

	for i := 0; i < 6; i++ {
		err := inputs[i].Input(string(code[i]))
		if !errors.As(err, &rod.ErrEval{}) {
				panic(err)
		}
	}
}
```

Any other solution is to completely simulate the human input process of TOTP, `Page.Input` is actually the simulation of copy & page which is actually not what you want to do here, what you want to do is to simulate keystrokes one by one, so your code can be change to this:

```go
func (rs *RodSession) doEnterOTP(t *testing.T, page *rod.Page, code string) {
	inputs := rs.WaitElementsLocatedByCSSSelector(t, page, "otp-input input")

	for _, char := range code {
		inputs.MustPress(char)
	}
}
``` 

Also, I think it's OK to ignore the last line's eval error of `rod.Input` because it's actually a helper to trigger some unnecessary events. Can you help to make a PR for it?
