### ISSUE TITLE
Provide keyboard modifiers as argument to mouse click.

### ISSUE THREAD

**Issue by kukaki** [go-rod/rod#499]
## Request

While [clicking an element ](https://pkg.go.dev/github.com/go-rod/rod#Element.Click) in Rod please provide an argument to send keyboard modifiers like Alt, Ctrl etc.

## Use case

`Alt + Click` Downloads the target of a link as per the [Google Chrome help center](https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cmouse-shortcuts).

## Similar feature in other libraries

Playwright's [page-click](https://playwright.dev/docs/api/class-page#page-click) takes [modifiers](https://playwright.dev/docs/api/class-page#page-click-option-modifiers) argument using which we can send keyboard modifiers. As its docs say..

`**modifiers** <Array<"Alt"|"Control"|"Meta"|"Shift">> Modifier keys to press. Ensures that only these modifiers are pressed during the operation, and then restores current modifiers back. If not specified, currently pressed modifiers are used.`

**Comment by ysmood** [comment]
#532
