### ISSUE TITLE
Waiting for canvas to render before generating PDF

### ISSUE THREAD

**Issue by wchretien** [go-rod/rod#502]
Even when using a `wait` as follow the generated PDF sometime doesn't have all the dashboards of Grafana:  
```
page.MustWaitLoad()
wait := page.WaitRequestIdle(3000*time.Millisecond, nil, nil)
wait()
```
Here's a screenshot of the dashboard itself:  
![Screenshot from 2021-10-14 13-04-49](https://user-images.githubusercontent.com/1131670/138476344-ec2b672a-06c6-4b22-9507-27d02c75a0de.png)
Here's the generated PDF of the same dashboard:
![Screenshot from 2021-10-14 13-05-04](https://user-images.githubusercontent.com/1131670/138476434-f89deb31-de5d-4d0d-9296-4b824e6165bd.png)

**Comment by ysmood** [comment]
I think there's no easy way to do that, maybe something like `time.Sleep(10 * time.Second)` is the easier solution.
