### ISSUE TITLE
How to disable/enable devtools settings/preferences like 'Enable JavaScript source maps', from the code

### ISSUE THREAD

**Issue by alicazi** [go-rod/rod#507]
**Rod Version:** v1.101.8

How to disable/enable devtools options like 'Enable JavaScript source maps', etc. from the code. These options are accessible in devtools/settings/Preferences

I searched chromium options but there is no option related to these preferences which are accessible from chrome devtools settings

**Comment by ysmood** [comment]
`source maps` is a function of devtools project, it's a standalone Chrome extension. Chrome DevTools Protocol (cdp) itself doesn't support it.

The relationship between them:

```text
chrome <-- cdp <-- devtools
                    ^
                     |
                     |
                   rod
```

**Comment by alicazi** [comment]
Actually I want to find a way to access the devtools and turn off the 'source map' as it slow down chromium and caused errors when I run tests concurrently.

**Comment by ysmood** [comment]
By default, the source map is already disabled.
