### ISSUE TITLE
Is it possible to emulate "save-as" behavior?

### ISSUE THREAD

**Issue by ikorjavin** [go-rod/rod#508]
**Rod Version:** v0.101.0

I use el.HTML() and it returns html.
But this html is different from save-as exported version.

Is there a way to get save-as version?

**Comment by ysmood** [comment]
```go
utils. OutputFile("test.html", page.MustHTML())
```

**Comment by ikorjavin** [comment]
It doesn't look what i want.

I want something like this:
https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureSnapshot

is it possible?

**Comment by ysmood** [comment]
```go
res, _ := proto.PageCaptureSnapshot{ }.Call(page)
utils.OutputFile("test.mhtml", res.Data)
```

**Comment by ysmood** [comment]
@ikorjavin Could you help to add a method to `Page`, let's call it `Page.MHTML` to implement the functionality above?
