### ISSUE TITLE
like puppeteer-extra plugin

### ISSUE THREAD

**Issue by simpleMemory** [go-rod/rod#514]
https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth

I noticed that there are puppeteer-extra plugins in puppeteer, is rod considering adding type extensions as well?

**Comment by ysmood** [comment]
https://github.com/go-rod/stealth

**Comment by simpleMemory** [comment]
Thanks。。。。。
