### ISSUE TITLE
intercepting binary websocket messages

### ISSUE THREAD

**Issue by amlwwalker** [go-rod/rod#518]
**Rod Version:** v0.101.8

## The code to demonstrate your question

```go
// Please make sure your code is minimal and standalone
func main() {
 //...
 //...
	router := browser.HijackRequests()
	router.MustAdd("*/ws/video/", func(ctx *rod.Hijack) {
		_ = ctx.LoadResponse(http.DefaultClient, true)
		log.Println(ctx.Response.Body())
	})
}
```

## What have you tried to solve the question

I have found the video element on a page and I have clicked play, prior to `router := browser.HijackRequests()` above.

My intent is to intercept the websocket that is providing the binary video data to the page over a socket and displays the video. In effect I want to intercept the video stream and write it to file.

I can get all the way, except the `router.MustAdd` doesn't seem to pick up anything at all.

Any tips on intercepting websocket data from a page, much appreciated. Thanks

**Comment by ysmood** [comment]
For the latest `Chrome DevTools Protocol`, you can read the WebSocket data, but you can't modify them.

**Comment by amlwwalker** [comment]
Ahh thanks for the tip,

I have a `browser` a `page` and a iframe called `gFrame` - I tried to do the `.EachEvent` on each of those and I get the error at the same point of the program:

```
panic: interface conversion: *proto.NetworkWebSocketFrame is not proto.Event: missing method ProtoEvent

goroutine 1 [running]:
github.com/go-rod/rod.(*Browser).eachEvent(0xc000150300, 0x0, 0x0, 0xc000131f28, 0x5, 0x5, 0x300000002)
        /Users/username/go/pkg/mod/github.com/go-rod/rod@v0.101.8/browser.go:356 +0x1e9
github.com/go-rod/rod.(*Browser).EachEvent(...)
        /Users/username/go/pkg/mod/github.com/go-rod/rod@v0.101.8/browser.go:315
main.main()
        /Users/username/go/src/username/auto-rod/cmd/main.go:32 +0x290
```

My guess is this isn't quite the interface we are looking for? Unless its about making it wait until a socket connection is created (and it hasn't yet been setup, or something)?

**Comment by ysmood** [comment]
How about use a page, not browser.

**Comment by amlwwalker** [comment]
I have tried it on all three, same crash:

> I have a `browser`a `page` and a `iframe` called gFrame - I tried to do the .EachEvent on each of those and I get the error at the same point of the program:

By the looks of things from this, because `NetworkWebSocketFrame` is not an interface with a method proto.Event which makes sense as the chrome dev hooks documentation shows that to be the case

**Comment by ethanx40** [comment]
hey guys, can you receive `proto.NetworkWebSocketFrameReceived` of iframe `websocket`? I tried to use `browser`, `page` and `frame`, but none of them can work correctly. Can you give me some suggestions?
