### ISSUE TITLE
How launch chrome in arm64 mode on macOS

### ISSUE THREAD

**Issue by alicazi** [go-rod/rod#519]
**Rod Version:** v0.101.8

## The code to I'm using to open url in browser

```go
...
        path, _ := launcher.LookPath()  //This points to chrome in Application folder which I regularly use for browsing
	// path := launcher.NewBrowser().MustGet() // This points to chromium
	l := launcher.New().Bin(path).Headless(false).Devtools(false)
	l.Set("--disable-web-security")
	url := l.MustLaunch()

	browser := rod.New().
		ControlURL(url).
		// Trace(true).
		SlowMotion(0 * time.Millisecond).
		MustConnect()

	// Create a new page
	page := browser.MustPage()
        rp := page.MustNavigate("URL")
...	
```

## The issue and what I tried to resolve it

This code was working fine until recently I noticed the tests is running slower (~2x slower) I verified the browser ver it was showing: 
       Chrome is up to date
       Version 96.0.4664.110 (Official Build) (x86_64 translated)
but when I open the browser manually it's showing the native arm64
      Chrome is up to date
      Version 96.0.4664.110 (Official Build) (arm64)
as the code showing I'm using the same installed chrome and I tried to uninstall and reinstall chrome even revert back to previous versions of chrome. In all scenarios the launcher opening the (x86_64 translated) not the (arm64) version.
The only thing that change before this issue started is me upgrading macOS to Monterey 12.1, Go to 1.17.5 and I noticed that chrome is also updated on 12/12/2021 to above mentioned version. I'm not sure if any of these updates could cause the issue though.
**I'm wondering if there is a way to force the launcher to launch the arm64 or any other solution**. This issues causes many of my tests to fail and I had to double the timeouts and run only one test at a time (I used to run 6 instances simultaneously which saves me a lot of time on running tests concurrently). 
I also tried to use chromium but that haven't help too. I was not able to find a native arm64 version for mac.

**Comment by ysmood** [comment]
I hope they have special launch flags for chrome, but it seems like no.

Have you checked these:

https://github.com/Eloston/ungoogled-chromium/issues/1287

https://github.com/Eloston/ungoogled-chromium

**Comment by alicazi** [comment]
@ysmood 
1- I'm wondering if you have any theory how it was working in arm64 and out of the blue it stopped (I mean after 3 updates that I mentioned)
2- Do you know any where to download chromium for macos arm64. I tried to compile but I had no success, it's beyond my skill I think.

**Comment by ysmood** [comment]
![image](https://user-images.githubusercontent.com/1415488/146626923-e94bf2a4-8b67-4dac-a234-2cea012a92c3.png)

**Comment by alicazi** [comment]
@ysmood Thank you so much for your help.
1. Downloading ungoogled-chromium and using  eloston-chromium **(brew install --cask eloston-chromium)** both resolved the issue. However they may not have the latest version of Chromium available.  I noticed that eloston-chromium has a newer version, still not the latest. 

2. I didn't stop there, and digged down to find the root cause. I pined point the issue to the Leakless option of the launcher. using: launcher.New().Bin(path).Headless(false).Devtools(false).**Leakless(false)** resolved the issue. I thought this may help you find out and fix the issue.

For everyone else who may have the same issue. We have two options:  eloston-chromium vs regular chrome (which is always the latest version and I don't have to worry about the version because chrome keep the app updated to latest version). For now I think Leakless is a very helpful feature so I will stick with eloston-chromium and wait for  the Leakless feature to be fixed and stopped forcing chrome to (x86_64 translated) and then switch to using regular chrome.

@ysmood Let me know if you think I can help with fixing the issue with Leakless.
Thank you again for your help.

**Comment by ysmood** [comment]
Interesting, could you help to rebuild leakless with the latest golang and test it again?

**Comment by alicazi** [comment]
@ysmood I tried to apply go generate per instruction but it's failing with the following messages:

> ❯ go generate
panic: exit status 1

goroutine 1 [running]:
github.com/ysmood/leakless/pkg/utils.E(...)
	/Users/alicazi/Documents/git/go/workspace/pkg/mod/github.com/ysmood/leakless@v0.7.0/pkg/utils/utils.go:17
main.build({0x100620752, 0xb})
	/Users/alicazi/Documents/git/go/workspace/pkg/mod/github.com/ysmood/leakless@v0.7.0/cmd/pack/main.go:97 +0x58c
main.pack({0x100620752, 0xb})
	/Users/alicazi/Documents/git/go/workspace/pkg/mod/github.com/ysmood/leakless@v0.7.0/cmd/pack/main.go:31 +0x5c
main.main()
	/Users/alicazi/Documents/git/go/workspace/pkg/mod/github.com/ysmood/leakless@v0.7.0/cmd/pack/main.go:22 +0xdc
exit status 2
leakless.go:1: running "go": exit status 1

I have no idea how to fix this. I got other permissions error which I was able to fix but this one I don't know how to fix.

**Comment by ysmood** [comment]
I updated the way the launcher works in the latest release, it might work now.
