### ISSUE TITLE
Possible to bypass/spoof ServiceWorker?

### ISSUE THREAD

**Issue by xines** [go-rod/rod#522]
**Rod Version:** v0.101.9-0.20211222104445-2424108c10b5

## Demonstrate your question

Is it possible to bypass/spoof ServiceWorker with rod as sites like:
* https://abrahamjuliot.github.io/creepjs/

are able to detech spoofed user-agent + gpu using ServiceWorker.

## What have you tried to solve the question

I tried using the below without luck.
```
err := proto.NetworkSetBypassServiceWorker{Bypass: true}.Call(page)
if err != nil {
	return
}
```

**Comment by ysmood** [comment]
Related to: https://github.com/go-rod/stealth/issues/15
