### ISSUE TITLE
how to monitor window post message

### ISSUE THREAD

**Issue by mntya** [go-rod/rod#523]
**Rod Version:** v0.101.8

## The code to demonstrate your question
我想要像在chrome的控制台一样，可以监听页面中的post message的消息，使用rod应该怎么处理呢？
```
window.addEventListener("message", function(e) {
    console.log(e);
})
```

## What have you tried to solve the question
I want to monitor postmessage on some specified page, but i got no idea how to by rorod. 
Any advice, thanks.

**Comment by ysmood** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

**Comment by mntya** [comment]
> https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

How should i do it in rod, to get the post message data? I searched repo, and event apis, seems no related solutions

**Comment by ysmood** [comment]
```js
window.addEventListener("message", (event) => {
  if (event.origin !== "http://example.org:8080")
    return;

  // ...
}, false);
```

**Comment by mntya** [comment]
> 



> ```js
> window.addEventListener("message", (event) => {
>   if (event.origin !== "http://example.org:8080")
>     return;
> 
>   // ...
> }, false);
> ```

我没get到你的点？你是让我用eval的方式去添加监听？但是我想要message event内容，go里面有办法获取到吗

**Comment by ysmood** [comment]
`Page.Expose`

**Comment by mntya** [comment]
> 

好的，非常感谢。看到对应的api了.
