### ISSUE TITLE
导航时地址输入到了地址栏但是并没有导航过去

### ISSUE THREAD

**Issue by mntya** [go-rod/rod#528]
**Rod Version:** v0.101.8

## 示例代码释义

代码环境：Windows系统
根据实际代码改编如下demo，每次运行程序时:
  如果存在历史chrome时杀死并开启新的debug的chrome，
  开启协程(blockingMonitorPage)监听当前page对象被关闭事件，
  开启携程(blockingMonitorNewDoc)监听当前页面的DOM文档切换。
 
## 示例代码
```go
import (
	"context"
	"fmt"
       "encoding/json"
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/proto"
        wapi "github.com/iamacarpet/go-win64api"
	"github.com/pkg/errors"
	"log"
	"os"
	"os/exec"
)

func TestNavigate(t *testing.T) {
	ctx, cancel := context.WithCancel(context.TODO())
	defer cancel()

	// 杀死历史chrome
	if err := killChrome(); err != nil {
		t.Fatal(err)
	}
	// 开启新的debug chrome
	err := exec.Command("cmd", "/c", "start chrome --remote-debugging-port=9222").Run()
	if err != nil {
		t.Fatal(err)
	}
	
	time.Sleep(time.Second * 5)
	debugURL, err := GetBrowserDebugURL()
	if err != nil {
		t.Fatal(err)
	}
	browser := rod.New().ControlURL(debugURL).MustConnect().NoDefaultDevice()
	b := &Browser{
		browser:  browser,
		currPage: (browser.MustPages())[0],
	}
	go b.blockingMonitorNewDoc(ctx)
	go b.blockingMonitorPage(ctx)
	
	// 开始导航
	err = b.navigate(ctx, "https://www.baidu.com/?1=1")
	if err != nil {
		t.Fatal(err)
	}
	select {}
}

// 相关实现
type Browser struct {
	browser  *rod.Browser
	currPage *rod.Page
}

func (c *Browser) navigate(ctx context.Context, url string) error {
	if c.currPage == nil {
		return errors.New("want navigate but nil page")
	}
	err := c.currPage.Context(ctx).Navigate(url)
	if err != nil {
		return errors.Wrap(err, "navigate page")
	}
	// 等待页面加载完成
	if err := c.currPage.Context(ctx).Timeout(time.Second * 30).WaitLoad(); err != nil {
		return errors.Wrap(err, "wait page navigated")
	}
	return nil
}

func (c *Browser) blockingMonitorPage(ctx context.Context) {
	defer func() {
		if i := recover(); i != nil {
			log.Printf("[tab monitor] - panic:%v\r\n", i)
		}
		log.Printf("blocking monitor browser tabs stopped...")
	}()
	events := c.browser.Event()
	for {
		select {
		case <-ctx.Done():
		case ev := <-events:
			// 等待目标页面被关闭的事件
			if ev.Method != "Target.targetDestroyed" {
				continue
			}
			var entity proto.TargetTargetDestroyed
			if !ev.Load(&entity) {
				fmt.Println("got Target.targetDestroyed but not loaded")
				continue
			}
			if entity.TargetID != c.currPage.TargetID {
				continue
			}
			// 当前页面被关闭了
			log.Printf("current page closed...\n")
                         // 自定义更多逻辑
		}
	}
}

func (c *Browser) blockingMonitorNewDoc(ctx context.Context) {
	defer func() {
		if i := recover(); i != nil {
			log.Printf("[page monitor] - panic:%v", i)
		}
		log.Println("[page monitor] - browser or current page closed manually!!!")
	}()
	log.Println("[page monitor] - blocking monitor new page...")
	events := c.currPage.Context(ctx).Event()
	for {
		select {
		case <-ctx.Done():
			log.Println("[page monitor] - canceling...")
			return
		case ev, ok := <-events:
			if !ok {
				return
			}
			if ev.Method != "Page.domContentEventFired" {
				continue
			}
			info, err := c.currPage.Context(ctx).Info()
			if err != nil {
				log.Println(err)
				continue
			}
			log.Printf("[page monitor] - new page:%v %v\n", info.URL, info.Title)
		}
	}
}

func GetBrowserDebugURL() (string, error) {
	resp, err := http.Get("http://localhost:9222/json/version")
	if err != nil {
		return "", err
	}
	var result map[string]interface{}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", err
	}
	return result["webSocketDebuggerUrl"].(string), nil
}

func killChrome() error {
	pr, err := wapi.ProcessList()
	if err != nil {
		return err
	}
	for _, p := range pr {
		if p.Executable == "chrome.exe" {
			log.Println("killing history chrome instance...")
			_, err := wapi.ProcessKill(uint32(p.Pid))
			return err
		}
	}
	return nil
}
```

## 问题描述 
  生产环境中，发现某些服务器执行导航www.baidu.com时，www.baidu.com出现在了浏览器导航栏但未导航成功的现象(并未加载对应页面)，同时软件收到了当前页Target.targetDestroyed的事件，此blockingMonitorNewDoc携程也会结束(这个是正常行为吧？)。
  实际情况是，浏览器外部看起来正常，标签页也未关闭，去浏览器的导航栏手动enter，也可以正常导航至www.baidu.com。

**Comment by ysmood** [comment]
抱歉没听懂你的描述，你给的代码也没法复现问题。

**Comment by mntya** [comment]
> 抱歉没听懂你的描述，你给的代码也没法复现问题。

你好，已更新相关描述与代码

**Comment by ysmood** [comment]
能分享下设计这么复杂的逻辑目的是什么吗？说不定有更好的方法解决你的目的。

**Comment by mntya** [comment]
> 



> 能分享下设计这么复杂的逻辑目的是什么吗？说不定有更好的方法解决你的目的。

终极

> 能分享下设计这么复杂的逻辑目的是什么吗？说不定有更好的方法解决你的目的。

最终目标是需要监听当前tab下的页面切换，1.反馈当前页的url和title，2.通过page.Expose暴露函数到最新的document里面去，3.检查当前页面是否出现一些特定的element；

由于出现我提出的问题，现在换了处理思路，每次导航时均新开启tab页(关闭其他tab页)，然后为当前tab页绑定新文档的事件流监听(blockingMonitorNewDoc)

**Comment by ysmood** [comment]
为啥要用 page.Expose 呢？`Page.Element` 不可以吗？

**Comment by mntya** [comment]
> 

场景是需要通过page.Expose暴露函数去监听页面出现的验证，如HCaptcha隐式存在于页面，提交表单时才可能会弹出，这种检查元素是行不通的，存在交互

**Comment by mntya** [comment]
> > 
> 
> 场景是需要通过page.Expose暴露函数去监听页面出现的验证，如HCaptcha隐式存在于页面，提交表单时才可能会弹出，这种检查元素是行不通的，存在交互

检查元素就涉及到一个问题，iframe的可见性问题，这个问题貌似有点复杂，最终选择暴露函数去处理...

**Comment by mntya** [comment]
> 为啥要用 page.Expose 呢？`Page.Element` 不可以吗？

我没有测试过visible方法，这个方法就是表示人类是否可见吗，如果该元素是iframe，那么是否表示iframe是否可见？

**Comment by ysmood** [comment]
`Page.Element` 跟 visible 有啥关系呢？抱歉，我没懂你意思。

**Comment by mntya** [comment]
> `Page.Element` 跟 visible 有啥关系呢？抱歉，我没懂你意思。

还是拿检查页面是否出现验证举例，需求就变为了 1.检查页面是否有验证相关的元素(目前是iframe)，2.验证相关的元素是否人类可见，3.如果验证相关元素均人类不可见，在一定交互后是有可能显示出来的，需要处理。

**Comment by mntya** [comment]
> `Page.Element` 跟 visible 有啥关系呢？抱歉，我没懂你意思。

还是拿检查页面是否出现验证举例，需求就变为了 1.检查页面是否有验证相关的元素(目前是iframe)，2.验证相关的元素是否人类可见，3.如果验证相关元素均人类不可见，在一定交互后是有可能显示出来的，需要处理。

**Comment by ysmood** [comment]
`Page.Search` 支持 iframe

**Comment by mntya** [comment]
> 

非常感谢解答，我看了下api感觉不太适合我目前的场景，这个api应该是阻塞式的，我的场景更偏向于1.`Page.Has` 且可见，2.`Page.Has`但不可见，经过交互后元素变为可见；

并且以上的变化是要维护状态机、与应用逻辑有关系的。

我觉得`Page.EvalOnNewDocument`是满足我当前的需求场景的，但这个函数不能像`Page.Eval`使用`Page.Expose`的函数，你看`Page.EvalOnNewDocument`是否可以添加一个expose的函数？这样就能完美解决我的问题...

**Comment by mntya** [comment]
或者rod是否可以提供一个`Page.EachNewDocument(callback...)`的方法，让使用者能够执行一些初始化操作

**Comment by ysmood** [comment]
用另一个 goroutine 调用 `Page.Search` 不就可以了吗？

**Comment by mntya** [comment]
> 

`Page.Search`如果doc切换仍未搜索到结果会自动停止吗？而且一个doc要检查N种验证的M种呈现方式，总不能开N*M个协程吧...

**Comment by ysmood** [comment]
可以设置超时。抱歉，关于验证这个 M 和 N 没听懂。

**Comment by mntya** [comment]
> 

设置超时不太适合我目前的场景，验证的N*M，是指每到一个新的页面(URL或者title发生了变化)，都需要检查多种captcha是否存在，每种captcha的不同呈现方式是否存在。

而且测试过程中，在同一个页面发现有iframe元素未发生变化，但却由于交互后从隐藏变为可见的现象，这种侦听iframe元素本身不太好解决问题

**Comment by ysmood** [comment]
不用这么麻烦吧，captcha 肯定有个通用容器承载它吧，检测其是否存在不就好了吗，等它出来了就可以测定是哪种 captcha，我觉得不需要 M * N 这么多

**Comment by mntya** [comment]
> 

对，现在是有一个validator链，新页面都会执行一次validator链。

但是问题就在于有些元素不是简单的检查页面是否存在该元素就可以的，比方说现在遇到的难题是有些captcha，他可见(需要解决)和不可见(不需要解决)状态下，他的iframe元素本身未发生任何变化，而且他是否需要验证具有随机性，导致我这边最终只好通过监听他的postmessage来判断他最终是否显示出来....

**Comment by ysmood** [comment]
大致了解你的问题了，关于你的代码，能否简化下呢？


> 如果存在历史chrome时杀死并开启新的debug的chrome，

这个问题和杀不杀chrome 有关联吗，去掉了就不回复现了吗？

一定要写这么复杂的代码才可以复现你的问题吗？

**Comment by mntya** [comment]
> 大致了解你的问题了，关于你的代码，能否简化下呢？
> 
> > 如果存在历史chrome时杀死并开启新的debug的chrome，
> 
> 这个问题和杀不杀chrome 有关联吗，去掉了就不会复现了吗？
> 
> 一定要写这么复杂的代码才可以复现你的问题吗？

因为我不确定我提的问题出现在哪里，所以按现有代码提了个demo，我个人觉得杀不杀都不影响的，有这部分代码是基于历史原因，目前在修改为如果chrome存在但是不能建立debug环境，就杀死重新打开。

测试过程中，有两种现象：第一种，刚开始navigate(浏览器未加载页面)，就收到了target destroy事件;第二种，navigate成功了，跳转了几次后，收到了target destroy事件;

我觉得要复现我出现的问题，应该是开启一个带远端debug 端口的浏览器，程序通过ws连接browser，程序获取浏览器的默认tab作为当前页(只使用`page.Navigate`、不使用`browser.Page`)，一直在当前页进行操作，最终会概率收到当前tab关闭的事件

**Comment by ysmood** [comment]
所以能再简化下复现代码吗？
