### ISSUE TITLE
interact with elements on multiple pages at the same time

### ISSUE THREAD

**Issue by alimsk** [go-rod/rod#529]
**Rod Version:** v0.101.8

## The code to demonstrate your question
is it possible to interact with elements on multiple pages at the same time?
for example:
```go
for i := 0; i < 3; i++ {
	i := i
	go func() {
		page := browser.MustPage("https://google.com").MustWaitLoad()
		page.MustElement("body > div.L3eUgb > div.o3j99.ikrT4e.om7nvf > form > div:nth-child(1) > div.A8SBwf > div.RNNXgb > div > div.a4bIc > input").
			MustInput("hello")
		fmt.Println("input page", i, "done")
	}()
}
utils.Pause()
```
it doesn't input until you open the page, which means I have to call `page.MustActivate()` for it to run.

btw, chromedp can do it, I'm using it now and I'm planning to migrate to rod. thanks

**Comment by ysmood** [comment]
Yes, you should be able to do that, try another website, it might be some site-specific feature, such as the website uses js to check if the window is activated or not.

**Comment by alimsk** [comment]
Hi thanks for the response.

I don't think that's the reason, try below code:
```go
package main

import (
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/utils"
	"github.com/go-rod/rod/lib/launcher"
	"fmt"
)

func main() {
	path, _ := launcher.LookPath()
	browser := rod.New().ControlURL(launcher.New().
			Bin(path).
			Headless(false).
			MustLaunch()).
		MustConnect().
		NoDefaultDevice()

	for i := 0; i < 3; i++ {
		i := i
		go func() {
			page := browser.MustPage("https://google.com").MustWaitLoad()
			page.MustElement("body > div.L3eUgb > div.o3j99.ikrT4e.om7nvf > form > div:nth-child(1) > div.A8SBwf > div.RNNXgb > div > div.a4bIc > input").
				MustInput("hello")
			fmt.Println("input page", i, "done")
		}()
	}

	utils.Pause()
}
```
it only prints the text "input page n done" once, whereas this code:
```go
package main

import (
	"github.com/chromedp/chromedp"
	"context"
	"fmt"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
	)
	allocCtx, cancelAlloc := chromedp.NewExecAllocator(context.Background(), opts...)
	ctx, cancelCtx := chromedp.NewContext(allocCtx)
	defer cancelAlloc()
	defer cancelCtx()
	chromedp.Run(ctx)

	for i := 0; i < 3; i++ {
		i := i
		go func() {
			newCtx, _ := chromedp.NewContext(ctx)
			if err := chromedp.Run(newCtx,
				chromedp.Navigate("https://google.com"),
				chromedp.SendKeys(
					"body > div.L3eUgb > div.o3j99.ikrT4e.om7nvf > form > div:nth-child(1) > div.A8SBwf > div.RNNXgb > div > div.a4bIc > input",
					"hello",
					chromedp.ByQuery,
				),
			); err != nil {
				panic(err)
			}
			fmt.Println("input page", i, "done")
		}()
	}

	<-(chan int)(nil)
}
```
it prints three times.

**Comment by alimsk** [comment]
looks like rod can do it in headless mode, when I set headless to false, it doesn't work.
sorry for the less detailed question.

is there any setting/configuration to make rod able to interact with elements in the background (without activating the page)?

**Comment by ysmood** [comment]
I think this is a chromium issue, chromedp will have an issue if you open lots of tabs, check the issue here, it's still open after years: https://github.com/puppeteer/puppeteer/issues/3339

**Comment by alimsk** [comment]
yes i've tried it, interacting with 20 tabs at the same time using chromedp, i launched a new goroutine for each tab, and everything seems to be fine, i see no error.

**Comment by ysmood** [comment]
I think the reason why rod doesn't work is because rod is using `Element.WaitStableRAF` inside the `Element.Input` method.  The [RAF](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) will be frozen if the page is inavtive.

**Comment by ysmood** [comment]
If you try to use high-level features like screenshots on chromedp, I think it won't work anymore. It's an accident that chromedp works.

I think we can close this for now since the headful mode is not intended to be used for background pages. If you have more info about it, we can reopen this.
