### ISSUE TITLE
Bypassing CSP

### ISSUE THREAD

**Issue by gigabitwize** [go-rod/rod#531]
**Rod Version:** v0.101.8

With Pupeteer, all one had to do was call page#setBypassCSP(true); I was wondering if there's a similar way to do it with go-rod?

Thanks.

**Comment by 456478** [comment]
BypassCSP is a [CDP method](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setBypassCSP). You can call those methods directly with go-rod.
https://github.com/go-rod/rod/blob/026d63501e51f0494ce1121972cf8be3321a958d/lib/proto/page.go#L1966-L1971

The examples cover how to call CDP directly.
https://github.com/go-rod/rod/blob/4c4ccbecdd8110a434de73de08bdbb72e8c47cb0/examples_test.go#L370-L392
