### ISSUE TITLE
Allow for arbitrary functions as race context conditions

### ISSUE THREAD

**Issue by codegoalie** [go-rod/rod#534]
Hello! First off, thanks so much for maintaining rod! It's been a pleasure and exciting to write web scrapers. 🤓 

I have a use case where I want to use a Race to determine success of an action (login in this case), but one of the elements in in an iframe and the other is in the main page. I wasn't able to use the existing race API since it works with the same `Page` object. I could either see the element in the page or the element in the iframe, but not both.

I was thinking a new race context type could be added called `ElementFunc` which would have the same signature as the other `ElementX` race functions (`func (*Page) (*Element, error)`) but allow users to define their own function to determine if the element is detected or not.

Here's an example implementation:

```go
// ElementFunc takes a custom function to determine race success
func (rc *RaceContext) ElementFunc(fn func(*Page) (*Element, error)) *RaceContext {
    rc.branches = append(rc.branches, &raceBranch{
        condition: fn,
    })
    return rc
}
```
And an example usage (modified heavily from my real usage so might not be 100% correct):

```go
_, err = page.Race().Element(loggedInCheckSelector).MustHandle(func(e *rod.Element) {
    // Logged in
}).ElementFunc(func(p *rod.Page) (*rod.Element, error) {
   rFrame := p.MustElement(frameSelector).MustFrame()
   return rFrame.Element(signInEmailSelector)
}).MustHandle(func(e *rod.Element) {
    // Need to log in
}).MustDo()
```

I've actually already implemented this locally, tested it, and would be happy to open a PR!

Thanks!

**Comment by ysmood** [comment]
This is a very good edge case, I will definitely consider it when redesign the Race helper.

**Comment by aadog** [comment]
@codegoalie please submit you pr

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/pull/621#issuecomment-1146962010
