### ISSUE TITLE
抓取https网站遇到net::ERR_CERT_AUTHORITY_INVALID错误

### ISSUE THREAD

**Issue by herozzm** [go-rod/rod#535]
Version: 当前最新版本
在其他浏览器比如edge手动浏览是正常的（并未提示网站证书有问题），这种情况是什么原因？该如何解决？

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/e6fa94e51155820a16a582d2dfebeec08a91c562/must.go#L94
