### ISSUE TITLE
Deploying on Heroku

### ISSUE THREAD

**Issue by spiropoulos94** [go-rod/rod#537]
**Rod Version:** v0.101.8

When I try to deploy on heroku I get an error. It seems that the headless chrome cannot spin up in heroku environment

Error Message : 
```
 Failed to launch the browser, the doc might help https://go-rod.github.io/#/compatibility?id=os: /app/.cache/rod/browser/chromium-901912/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

**Comment by ysmood** [comment]
Have you checked https://go-rod.github.io/#/compatibility?id=os
