### ISSUE TITLE
page.Screenshot fullscreen generated unnecessary area

### ISSUE THREAD

**Issue by akalittle** [go-rod/rod#538]
**Rod Version:** v0.101.8

## The code to demonstrate your question

```go
// Please make sure your code is minimal and standalone
func main() {
	page := rod.New().MustConnect().
		MustPage("http://xxxxx8&preview=1").
		MustWaitLoad().
		MustEmulate(devices.IPhone6or7or8)
	// Start to analyze request events

	defer page.Close()

	wait := page.MustWaitRequestIdle()
	//
	wait()
	//
	b, _ := page.Screenshot(true, nil)
}
```

## What have you tried to solve the question

The screenshot generated is below : 
![image](https://user-images.githubusercontent.com/38489160/153571677-5509cc85-beb5-4447-8c21-18cf4dba0f60.png)
The place in red line is what the page is, however there are some unnecessary area generated ( in blue lines)

**Comment by ysmood** [comment]
Can you provide a visitable website URL that can reproduce this issue?

**Comment by akalittle** [comment]
> Can you provide a visitable website URL that can reproduce this issue?

Maybe you can try `http://h5.dooring.cn/h5_plus/preview?tid=9E4F7FD8` .

But I think it's because of some css cause this issue.

**Comment by ysmood** [comment]
It's because the page is smaller than the minimum size of the default device:

https://github.com/go-rod/rod/blob/ac7b6258060c517cad5bc6de34c1355b236bbe7d/page.go#L365

So the rendered `CSSContentSize` will be larger than the actual content.
