### ISSUE TITLE
上下文cancel问题

### ISSUE THREAD

**Issue by mntya** [go-rod/rod#539]
**Rod Version:** v0.102.1

## The code to demonstrate your question

```go
func main() {
        ctx := context.Background()
	browser := rod.New().ControlURL("debugURL").MustConnect().NoDefaultDevice()
	page, err := browser.Context(ctx).Timeout(time.Second * 5).Page(proto.TargetCreateTarget{})
	if err != nil {
		log.Fatal(err)
	}
	// 此处cancel后根据rod代码是使用父上下文
	page = page.CancelTimeout()
    
	// 6秒后，查询会报错，上下文已被cancel掉
	time.Sleep(time.Second * 6)
	info := page.MustInfo()
	fmt.Println(info.URL, info.Title)
}
```

## What have you tried to solve the question
我的理解返回的page对象具备根上下文，带有5秒超时，cancel掉后，应当只剩下根上下文，实际使用时，会报上下文被canecel掉了...

**Comment by ysmood** [comment]
因为你根上下文就带有了 5 秒超时

**Comment by mntya** [comment]
> 

嗯，我已经反应过来了，我以为browser的上下文超时和page是一样的。 我这边必须要给个打开tab页超时的设置以便未能打开情况下作出处理。
为了避免我提出issue的问题，我现在只能自己额外外部进行超时控制

**Comment by ysmood** [comment]
如果没有其他问题我先把这个 issue 关了

**Comment by mntya** [comment]
> 因为你根上下文就带有了 5 秒超时，仔细读我修改的代码
> 
> `page = page.Timeout(time.Second * 5)`

但是这个我在接下来已经cancel掉了？page = page.CancelTimeout()

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/4055f102b6d6828350fcb39fa1af31948453d20c/examples_test.go#L108

**Comment by mntya** [comment]
> https://github.com/go-rod/rod/blob/4055f102b6d6828350fcb39fa1af31948453d20c/examples_test.go#L108-L141

由于存在打不开tab的时候，我需要给打开tab这个操作一个超时时间，在page的超时不能满足

**Comment by ysmood** [comment]
```go
page := browser.MustPage()
page.MustNavigate("http://test.com")
```

**Comment by mntya** [comment]
> ```go
> page := browser.MustPage()
> page.Timeout(123).MustNavigate("http://test.com")
> ```

我这边存在程序block在`page := browser.MustPage()`的情况(打开标签页卡住、或导航卡住)，如果rod暂时没有方法能解决就算了

**Comment by ysmood** [comment]
`page := browser.MustPage()`

怎么可能卡住？创建的是一个空页面

**Comment by mntya** [comment]
> `page := browser.MustPage()`
> 
> 怎么可能卡住？创建的是一个空页面

我再测试确认下吧，反正浏览器数量上去后，各种问题都遇到了...

**Comment by ysmood** [comment]
那你就这样不就好了吗？Timeout 和 CancelTimeout 只是快捷方式，你完全可以不用他们，自己手动设置 context :

```go
page := browser.Timeout(123).MustPage()

page.DoSomething()

page.Context(ctx).DoSomethingElse()
```
