### ISSUE TITLE
获取frame内的元素直接panic

### ISSUE THREAD

**Issue by mntya** [go-rod/rod#541]
**Rod Version:** v0.102.1

```go
// Please make sure your code is minimal and standalone
func main() {
defer func() {
		if i := recover(); i != nil {
			fmt.Println("panic:", i)
		}
		fmt.Println("app will quit in 10s...")
		time.Sleep(time.Second * 10)
	}()
	browser := rod.New().ControlURL("debugURL").MustConnect().NoDefaultDevice()
	pages := browser.MustPages()
	page := pages[0]
	fmt.Println("got page ", page.TargetID)
	page.MustNavigate("https://coinlist.co/login")
	page.MustWaitLoad()

	e := page.MustElement("div:not([style*='display:']) > iframe[data-hcaptcha-widget-id]")
	fmt.Println("element got")
	frame := e.MustFrame()
	fmt.Println("frame got ", frame.IsIframe())
	c, err := frame.Element("#checkbox")
	if err != nil {
		fmt.Println("query checkbox:", err)
		return
	}
	fmt.Println("element got")
	c.MustClick()
	select {}
}
```

## 运行结果
c, err := frame.Element("#checkbox")语句会直接空指针panic

**Comment by mntya** [comment]
> **Rod Version:** v0.102.1
> 
> ```go
> // Please make sure your code is minimal and standalone
> func main() {
> 	browser := rod.New().MustConnect()
> 	pages := browser.MustPages()
> 	page := pages[0]
> 	fmt.Println("got page ", page.TargetID)
> 	page.MustNavigate("https://coinlist.co/login")
> 	page.MustWaitLoad()
> 
> 	e := page.MustElement("div:not([style*='display:']) > iframe[data-hcaptcha-widget-id]")
> 	fmt.Println("element got")
> 	frame := e.MustFrame()
> 	fmt.Println("frame got ", frame.IsIframe())
> 	c, err := frame.Element("#checkbox")
> 	if err != nil {
> 		fmt.Println("query checkbox:", err)
> 		return
> 	}
> 	fmt.Println("element got")
> 	c.MustClick()
> }
> ```
> 
> ## 运行结果
> c, err := frame.Element("#checkbox")语句会直接空指针panic

**Comment by mntya** [comment]
> 报错的是第5行 `page := pages[0]`

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/45312206/154789959-eb8f1d56-dc2d-423e-9ac4-01b7147c791e.png">

**Comment by ysmood** [comment]
你确定你运行的代码和上诉一致吗？

**Comment by mntya** [comment]
> 你确定你运行的代码和上诉一致吗？

我运行的只多了panic的defer,我修改下运行版本的code，你再试试

**Comment by mntya** [comment]
> 你确定你运行的代码和上诉一致吗？读你的代码，浏览器又没有建立新的页面，一个页面都没有，当然会报错

已更正代码，你看看呢

**Comment by ysmood** [comment]
你先自己运行成功了再问吧，我无法运行你的代码

**Comment by mntya** [comment]
> 你先自己运行成功了再问吧，我无法运行你的代码
> 
> <img alt="image" width="537" src="https://user-images.githubusercontent.com/1415488/154790763-8f4894e0-01b2-410b-9daf-1837333ce23e.png">

先手动开启个debug浏览器，把浏览器的debug url填入代码此行即可:browser := rod.New().ControlURL("debugURL").MustConnect().NoDefaultDevice()

**Comment by ysmood** [comment]
依然无法复现问题，没有打印任何内容

**Comment by mntya** [comment]
> 依然无法复现问题，没有打印任何内容
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 
> 	"github.com/go-rod/rod"
> )
> 
> func main() {
> 	page := rod.New().MustConnect().NoDefaultDevice().MustPage("https://coinlist.co/login")
> 	page.MustWaitLoad()
> 
> 	e := page.MustElement("div:not([style*='display:']) > iframe[data-hcaptcha-widget-id]")
> 	fmt.Println("element got")
> 	frame := e.MustFrame()
> 	fmt.Println("frame got ", frame.IsIframe())
> 	c, err := frame.Element("#checkbox")
> 	if err != nil {
> 		fmt.Println("query checkbox:", err)
> 		return
> 	}
> 	fmt.Println("element got")
> 	c.MustClick()
> 	select {}
> }
> ```

稍等，我重新提供直接可运行的代码吧

**Comment by mntya** [comment]
> 

页面应该是直接到了login界面去了，这个测试需要进入到hcaptcha的验证界面(使用本地浏览器大概率不会出现hcaptcha的验证)，不然程序会block住，就没有任何打印了。
我现在都是开了一个windows的云服务器，然后在里面复现的.

**Comment by mntya** [comment]
> 依然无法复现问题，没有打印任何内容，我不知道为啥要写的如此复杂才行，所以我简化了下
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 
> 	"github.com/go-rod/rod"
> )
> 
> func main() {
> 	page := rod.New().MustConnect().NoDefaultDevice().MustPage("https://coinlist.co/login")
> 	page.MustWaitLoad()
> 
> 	e := page.MustElement("div:not([style*='display:']) > iframe[data-hcaptcha-widget-id]")
> 	fmt.Println("element got")
> 	frame := e.MustFrame()
> 	fmt.Println("frame got ", frame.IsIframe())
> 	c, err := frame.Element("#checkbox")
> 	if err != nil {
> 		fmt.Println("query checkbox:", err)
> 		return
> 	}
> 	fmt.Println("element got")
> 	c.MustClick()
> 	select {}
> }
> ```

页面应该是直接到了login界面去了，这个测试需要进入到hcaptcha的验证界面(使用本地浏览器大概率不会出现hcaptcha的验证)，不然程序会block住，就没有任何打印了。
我现在都是开了一个windows的云服务器，然后在里面复现的.

**Comment by mntya** [comment]
> 

这个测试案例的环境有点特殊，需要开一个windows的云服务器(绝对会出现验证界面)，或者我把我现在的测试环境给你？问题点就在获取到frame过后，查找frame内到元素空指针了

**Comment by mntya** [comment]
> 依然无法复现问题，没有打印任何内容，我不知道为啥要写的如此复杂才行，所以我简化了下
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 
> 	"github.com/go-rod/rod"
> )
> 
> func main() {
> 	page := rod.New().MustConnect().NoDefaultDevice().MustPage("https://coinlist.co/login")
> 	page.MustWaitLoad()
> 
> 	e := page.MustElement("div:not([style*='display:']) > iframe[data-hcaptcha-widget-id]")
> 	fmt.Println("element got")
> 	frame := e.MustFrame()
> 	fmt.Println("frame got ", frame.IsIframe())
> 	c, err := frame.Element("#checkbox")
> 	if err != nil {
> 		fmt.Println("query checkbox:", err)
> 		return
> 	}
> 	fmt.Println("element got")
> 	c.MustClick()
> 	select {}
> }
> ```

这个测试案例的环境有点特殊，需要开一个windows的云服务器(绝对会出现验证界面)，或者我把我现在的测试环境给你？问题点就在获取到frame过后，查找frame内到元素空指针了

**Comment by mntya** [comment]
> 依然无法复现问题，没有打印任何内容，我不知道为啥要写的如此复杂才行，所以我简化了下
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 
> 	"github.com/go-rod/rod"
> )
> 
> func main() {
> 	page := rod.New().MustConnect().NoDefaultDevice().MustPage("https://coinlist.co/login")
> 	page.MustWaitLoad()
> 
> 	e := page.MustElement("div:not([style*='display:']) > iframe[data-hcaptcha-widget-id]")
> 	fmt.Println("element got")
> 	frame := e.MustFrame()
> 	fmt.Println("frame got ", frame.IsIframe())
> 	c, err := frame.Element("#checkbox")
> 	if err != nil {
> 		fmt.Println("query checkbox:", err)
> 		return
> 	}
> 	fmt.Println("element got")
> 	c.MustClick()
> 	select {}
> }
> ```

使用你简化后的代码，依然是这样的：
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/45312206/154798103-69116a39-a8ef-4c4e-8060-da7bff86244a.png">

**Comment by mntya** [comment]
> ```go
> package main
> 
> import (
> 	"fmt"
> 
> 	"github.com/go-rod/rod"
> )
> 
> func main() {
> 	page := rod.New().MustConnect().NoDefaultDevice().MustPage("https://coinlist.co/login")
> 	page.MustWaitLoad()
> 
> 	e := page.MustElement("div:not([style*='display:']) > iframe[data-hcaptcha-widget-id]")
> 	fmt.Println("element got")
> 	frame := e.MustFrame()
> 	fmt.Println("frame got ", frame.IsIframe())
> 	c, err := frame.Element("#checkbox")
> 	if err != nil {
> 		fmt.Println("query checkbox:", err)
> 		return
> 	}
> 	fmt.Println("element got")
> 	c.MustClick()
> 	select {}
> }
> ```

可以复现了，把导航的目标地址替换为:  https://captcha.website

**Comment by mntya** [comment]
是因为frame跨源导致的吗

**Comment by ysmood** [comment]
```go
package main

import (
	"fmt"

	"github.com/go-rod/rod"
)

func main() {
	page := rod.New().MustConnect().NoDefaultDevice().MustPage("https://captcha.website")
	page.MustWaitLoad()

	e := page.MustElement("div:not([style*='display:']) > iframe[data-hcaptcha-widget-id]")
	fmt.Println("element got")
	frame := e.MustFrame()
	fmt.Println("frame got ", frame.IsIframe())
	c, err := frame.Element("#checkbox")
	if err != nil {
		fmt.Println("query checkbox:", err)
		return
	}
	fmt.Println("element got")
	c.MustClick()
	select {}
}
```

**Comment by mntya** [comment]
有任何进展吗，boss

**Comment by ysmood** [comment]
目前感觉是 chromium 的 bug，别的 iframe 网站也有类似问题吗？

**Comment by mntya** [comment]
> 目前感觉是 chromium 的 bug，别的 iframe 网站也有类似问题吗？

我目前测试了一个另外的页面，有同样的问题存在。
我现在在某个repo看到他们说，这些captcha页面限制了Selenium的(同理那cdp一类的都已经失效了)，但不确定是否如此

**Comment by ysmood** [comment]
主要是这个 `Pierce: true` 无法正常获取 iframe 里的内容，这感觉是 bug

https://github.com/go-rod/rod/blob/14ebb72947cc99e916ed97897473be2b6c64f39d/page_eval.go#L349

**Comment by mntya** [comment]
> 主要是这个 `Pierce: true` 无法正常获取 iframe 里的内容，这感觉是 bug
> 
> https://github.com/go-rod/rod/blob/14ebb72947cc99e916ed97897473be2b6c64f39d/page_eval.go#L349

我对html不是太熟悉，iframe里面的内容是js动态生成的，是否是有这方面影响呢

**Comment by ysmood** [comment]
那也不该返回空 iframe

**Comment by ysmood** [comment]
目前可以为 iframe 创建一个页面来操作这种 iframe，我在其他iframe页面没有碰到类似问题，这个页面似乎是个特例：

```go
package main

import (
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/proto"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	page := rod.New().MustConnect().NoDefaultDevice().MustPage("https://captcha.website")
	f := page.MustElement("div:not([style*='display:']) > iframe[data-hcaptcha-widget-id]").MustFrame()
	p := page.Browser().MustPageFromTargetID(proto.TargetTargetID(f.FrameID))
	p.MustElement("#checkbox").MustClick()
	utils.Pause()
}
```

**Comment by mntya** [comment]
> 目前可以为 iframe 创建一个页面来操作这种 iframe，我在其他iframe页面没有碰到类似问题，这个页面似乎是个特例：
> 
> ```go
> package main
> 
> import (
> 	"github.com/go-rod/rod"
> 	"github.com/go-rod/rod/lib/defaults"
> 	"github.com/go-rod/rod/lib/proto"
> 	"github.com/go-rod/rod/lib/utils"
> )
> 
> func main() {
> 	defaults.Trace = true
> 	defaults.Show = true
> 
> 	page := rod.New().MustConnect().NoDefaultDevice().MustPage("https://captcha.website")
> 	f := page.MustElement("div:not([style*='display:']) > iframe[data-hcaptcha-widget-id]").MustFrame()
> 	p := page.Browser().MustPageFromTargetID(proto.TargetTargetID(f.FrameID))
> 	p.MustElement("#checkbox").MustClick()
> 	utils.Pause()
> }
> ```

好的，非常感谢！

**Comment by ysmood** [comment]
#548
