### ISSUE TITLE
how to fix ERR_TO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by simpleMemory** [go-rod/rod#549]
**Rod Version:** v0.102.1

## The code to demonstrate your question

```go
package main

import (
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"time"
)

func main() {
	wsUrl := launcher.New().Headless(false).MustLaunch()

	browser := rod.New().ControlURL(wsUrl).MustConnect().SlowMotion(500 * time.Millisecond)

	page := browser.MustPage("https://gmail.com")

	time.Sleep(10 * time.Second)

	page.MustNavigate(`https://accounts.google.com/signup/v2?service=mail&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&flowName=GlifWebSignIn&flowEntry=SignUp`).MustWaitLoad()

	time.Sleep(10 * time.Second)

}

```

## What have you tried to solve the question

```
panic: navigation failed: net::ERR_TOO_MANY_REDIRECTS

goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2(0x8f91c0, 0xc0002884b0)
	D:/GOPATH/pkg/mod/github.com/go-rod/rod@v0.102.1/lib/utils/utils.go:57 +0x3c
github.com/go-rod/rod.genE.func1(0xc0001a47c0, 0x1, 0x1)
	D:/GOPATH/pkg/mod/github.com/go-rod/rod@v0.102.1/must.go:35 +0x12f
github.com/go-rod/rod.(*Browser).MustPage(0xc0001d6000, 0xc00011ff50, 0x1, 0x1, 0x0)
	D:/GOPATH/pkg/mod/github.com/go-rod/rod@v0.102.1/must.go:70 +0x267
main.main()
	D:/GOPATH/src/tiktok-auto/main4.go:16 +0x18d
```

This address: https://gmail.com will open the page after a series of redirects, rod does not seem to handle this process correctly, what do I need to do to make rod execute correctly after waiting for the redirects

Request process.
![image](https://user-images.githubusercontent.com/45378126/156684784-0876c0db-e65d-4137-b202-b8f24a1a9b2e.png)
You can see the correct page opening after several redirects

**Comment by ysmood** [comment]
After running your code, can't see this error, everything works well.

**Comment by simpleMemory** [comment]
For well-known reasons, I can't access this site directly, and the program needs to include a proxy that

**Comment by simpleMemory** [comment]
u := launcher.New().Bin(path).Headless(false).Proxy("xxxx").MustLaunch()
Please add a proxy to try

**Comment by ysmood** [comment]
Still works fine for me
