### ISSUE TITLE
Feature request : if the program exits, no matter how to exit, it is abnormally exited or unabnormally exited, quit chromium too.

### ISSUE THREAD

**Issue by tpsmr** [go-rod/rod#551]
if the program exits, no matter how to exit, it is abnormally exited or unabnormally exited, quit chromium too.

**Comment by ysmood** [comment]
Already supported:

<img width="947" alt="image" src="https://user-images.githubusercontent.com/1415488/157146294-64dfdb30-1221-4aba-99c6-5e1575a1160a.png">
