### ISSUE TITLE
Cannot overwrite Request.Body() when hijacking a request

### ISSUE THREAD

**Issue by Jacobinski** [go-rod/rod#552]
**Rod Version:** v0.102.1 and v0.103.0

## Description

I've been having trouble overwriting the `ctx.Request.Body()` of POST requests when using request hijacking. What I'm trying to do is to intercept a request, modify the request body using `ctx.Request.SetBody()`, and then let it continue along it's request path, similar to your [Example_hijack_requests](https://github.com/go-rod/rod/blob/4c4ccbecdd8110a434de73de08bdbb72e8c47cb0/examples_test.go#L455-L491) unit test. Unfortunately,  `ctx.Request.Body()` does not appear to be updated by `ctx.Request.SetBody()` and the value remains the same, both when using `fmt.Printf(ctx.Request.Body())`, and when inspecting the POST request in Chrome devtools.

I think this is might related to the fact that [(ctx *HijackRequest) Body()](https://github.com/go-rod/rod/blob/6bc1fd40ef29342ee1464bf490ddfc3f8c1031eb/hijack.go#L284-L287) returns `ctx.event.Request.PostData` and[(ctx *HijackRequest) SetBody(obj interface{})](https://github.com/go-rod/rod/blob/6bc1fd40ef29342ee1464bf490ddfc3f8c1031eb/hijack.go#L305-L321) modifies a different variable, `ctx.req.Body`?

## Demonstration Code

This code attempts to POST a login request to Reddit, overwriting the request body's username and password with "fakeUsername" and "fakePassword". The console output shows that nothing changes
```
Original Request.Body(): csrf_token=f2c31237a4fc9ca4ffcbfd43af341fa7e65985f4&otp=&password=password&dest=https%3A%2F%2Fwww.reddit.com&username=username
New Request.Body(): csrf_token=f2c31237a4fc9ca4ffcbfd43af341fa7e65985f4&otp=&password=password&dest=https%3A%2F%2Fwww.reddit.com&username=username
```
as does the Chrome devtools view of the request:
<img width="934" alt="image" src="https://user-images.githubusercontent.com/14207293/156874026-6814d4cf-98e2-4655-a2b7-7e2fcc8188ac.png">

```go
package main

import (
	"fmt"
	"time"

	"github.com/go-rod/rod"
)

const loginButtonSelector = "body > div > main > div.OnboardingStep.Onboarding__step.mode-auth > div > div.Step__content > form > fieldset:nth-child(8) > button"

func main() {
	page := rod.New().MustConnect().MustPage("http://www.reddit.com/login/")

	page.MustElement("#loginUsername").MustInput("username")
	page.MustElement("#loginPassword").MustInput("password")

	router := page.HijackRequests()
	defer router.MustStop()
	router.MustAdd("*/login", func(ctx *rod.Hijack) {
		// Attempt to overwrite the POST payload
		fmt.Printf("Original Request.Body(): %v\n", ctx.Request.Body())
		ctx.Request.SetBody("username=fakeUser&password=fakePassword")
		// This *should* be an updated POST payload, but instead it shows the original payload.
		fmt.Printf("New Request.Body(): %v\n", ctx.Request.Body())
	})
	go router.Run()

	page.MustElement(loginButtonSelector).MustClick()

	time.Sleep(time.Hour)
}
```

## What have you tried to solve the question

Reading the documentation, codebase, and GitHub issue tracker. I couldn't find very much about modifying a Request's body.

**Comment by Jacobinski** [comment]
I've just forked go-rod and changed the implementation to 
```
func (ctx *HijackRequest) SetBody(obj interface{}) *HijackRequest {
	if s, ok := obj.(string); ok {
		ctx.event.Request.PostData = s
	}
	return ctx
}
```
This allows the `router.MustAdd` to correctly display a change to `Request.Body()`, however the Chrome Devtools still shows the original POST data. Any ideas what I might be doing wrong? Thanks in advance.

**Comment by Jacobinski** [comment]
Is there a way that I run a `POST` directly from go-rod, similar to https://stackoverflow.com/a/31303228? That's what I'm trying to achieve with this request hijacking; a direct `POST` command would provide me with the perfect solution.

**Comment by ysmood** [comment]
[Read the example code, you miss used the ](https://github.com/go-rod/rod/blob/4c4ccbecdd8110a434de73de08bdbb72e8c47cb0/examples_test.go#L473-L477)

**Comment by Jacobinski** [comment]
Thanks!`LoadResponse()` will work for me.
