### ISSUE TITLE
Configuration to specify path of browser download

### ISSUE THREAD

**Issue by pthieu** [go-rod/rod#555]
Looking at the code: https://github.com/go-rod/rod/blob/eb9261e63c6ae8ae621e524cf044eb239603c89e/lib/launcher/browser.go#L85

Looks like the path is set to the `/${user home}/.cache/rod` always. I have a situation where I'm trying to download the browser in an AWS Lambda function. I get the following error:

```
Download: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/975577/chrome-linux.zip
panic: mkdir .cache: read-only file system
```

The reason being that only `/tmp` in a Lambda instance is writable: https://stackoverflow.com/questions/39383465/error-read-only-file-system-in-aws-lambda-when-downloading-a-file-from-s3

If there's the ability to change the download path, it could make it quite easy to use `go-rod` in AWS Lambda instead of having to use Docker + ECR, which would drive costs and complexity up.

**Comment by ysmood** [comment]
Yes, you can change it:

https://github.com/go-rod/rod/blob/50d33edba5846f5c9b50ffa2ebc9a30297fd9c1f/lib/launcher/browser.go#L75-L76

**Comment by pthieu** [comment]
Ah I missed that, sorry. Thanks for the quick response.

**Comment by pthieu** [comment]
@ysmood sorry, I'm actually a bit confused here
I'm looking into the launcher code and there isn't a `launcher.DefaultBrowserDir`: https://github.com/go-rod/rod/blob/eb9261e63c6ae8ae621e524cf044eb239603c89e/lib/launcher/launcher.go

Do you mean `launcher.Browser.DefaultBrowserDir`?

**Comment by pthieu** [comment]
Even though the struct exists and `launcher.Browser.Dir` is a public field, it says it's undefined.
![image](https://user-images.githubusercontent.com/2908721/157619467-892b656c-709f-4bdc-89d6-64a9f6ee1ec3.png)

**Comment by ysmood** [comment]
Yes.

**Comment by pthieu** [comment]
This doesn't seem to exist:

![image](https://user-images.githubusercontent.com/2908721/157701751-3a554b69-708d-428f-887d-a2a95bb621c7.png)

**Comment by ysmood** [comment]
`launcher.DefaultBrowserDir`

https://github.com/go-rod/rod/blob/50d33edba5846f5c9b50ffa2ebc9a30297fd9c1f/lib/launcher/browser.go#L59
