### ISSUE TITLE
Hijacking prevents proper Encoding of PostData

### ISSUE THREAD

**Issue by sirdavic** [go-rod/rod#564]
**Rod Version:** v0.103.0

```go
router := page.HijackRequests()
	router.MustAdd("*", func(ctx *rod.Hijack) {

		ctx.MustLoadResponse()
})
go router.Run()
```

Run this on https://www.google.com/recaptcha/api2/demo, the site expects an **ASCII** request postdata on https://www.google.com/recaptcha/api2/reload?k=6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-, but GoLang has UTF-8 as default encoding for strings https://github.com/go-rod/rod/blob/30973d70d3cb5c725e7d17873f15bfdfee3fbce0/lib/proto/network.go#L342 Therefore the request cannot succeed. Converting UTF-8 to ASCII again is impossible.

Using ```ctx.ContinueRequest(&proto.FetchContinueRequest{})``` works just fine.

**Comment by ysmood** [comment]
utf8 and ASCII should be the same for English chars, is the site using non-English chars for the API?

**Comment by earthlion** [comment]
> utf8 and ASCII encoding should be the same for English chars, is the site using non-English chars for the API?
> 
> However, you can use this to post binary data and encode it by yourself:
> 
> https://github.com/go-rod/rod/blob/30973d70d3cb5c725e7d17873f15bfdfee3fbce0/lib/proto/network.go#L347-L348

For example, hex 0xA4 is displayed as 0x20. Converting back doesn't work.

How would one read the slice?

**Comment by ysmood** [comment]
0xA4 is 164 which is not valid ascii, please check here: https://www.cs.cmu.edu/~pattis/15-1XX/common/handouts/ascii.html

**Comment by earthlion** [comment]
https://bytetool.web.app/en/ascii/code/0xa4/

Could be that I switched it up with Windows-1252. Well either way, test the example code above and tell me if it loads the captcha for you or gives invalid API parameters error. I've tested it with two identical requests (1:1) and one had a different postdata encoding (not header) and it worked.

**Comment by ysmood** [comment]
Can you give more detailed steps to reproduce your issue? Such as an executable code example.
