### ISSUE TITLE
eval js error: SyntaxError: Unexpected token ';'

### ISSUE THREAD

**Issue by moxcomic** [go-rod/rod#566]
**Rod Version:** v0.104.0

## The code to demonstrate your question

```javascript
() => {
  console.log('test');
};
```

## What have you tried to solve the question

在`v0.104.0`版本中js如果带有`;`会报`eval js error: SyntaxError: Unexpected token ';'`错误，如果把`;`去掉则正常运行，在`v0.103.0`版本没有这个问题，而且这个问题好像导致`page.Wait(nil, condition, nil)`也不生效。

**Comment by ysmood** [comment]
Thanks for your report, should be fixed in v0.104.1

**Comment by moxcomic** [comment]
> Thanks for your report, should be fixed in v0.104.1

在`v.0.104.1`下`page.MustWait`方法依然无法使用报`eval js error: TypeError: (!((typeof navigator) === undefined)).apply is not a function`问题, 在`v0.103.0`没有问题

```go
page.MustWait(`typeof navigator !== undefined`, nil)
```

**Comment by ysmood** [comment]
这不是bug，api调整了，请看下 Page.Eval相关的文档

**Comment by moxcomic** [comment]
> 这不是bug，api调整了，请看下 Page.Eval相关的文档

抱歉，没有找到相关的信息，能否给个例子

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/releases/tag/v0.104.0

> Now all eval-related APIs only accept function definitions, other js expressions will throw errors.
