### ISSUE TITLE
并发pagePool 会出现context deadline exceeded，一般是什么原因造成的？

### ISSUE THREAD

**Issue by herozzm** [go-rod/rod#572]
**Rod Version:**v0.104.4

## The code to demonstrate your question

```go
func main() {
    var browser *rod.Browser
    browser = rod.New().MustConnect()
    defer browser.MustClose()
    

Again:
    //10个并发，建立10的page池
    pool := rod.NewPagePool(10)
    
    var wg sync.WaitGroup
    
    for i:=0; i<10; i++ {
        wg.Add(1)
        go func() {
            defer wg.Done()
            create := func() *rod.Page {
                return browser.MustIncognito().MustPage()
            }
            page := pool.Get(create)  //这里会出现 error: context deadline exceeded
            defer pool.Put(page)
            
            page.Timeout(timeOut).MustNavigate("https://www.test.com").MustWaitLoad()
            
            //some code
             
        }()
    }
    wg.Wait()
    
    pool.Cleanup(func(p *rod.Page) { p.MustClose() })

    time.Sleep(20 * time.Second)
    goto Again  //重复抓取
}

```

## What have you tried to solve the question
并发的代码参考的是：https://github.com/go-rod/rod/blob/46baf3aad803ed5cd8671aa325cbae4e297a89a4/examples_test.go#L533
以上是简化过的代码，实际业务代码复杂一些，并发出现了rod的panic：line error: context deadline exceeded
是不是pool池用完了之后没有释放，导致不够？

**Comment by ysmood** [comment]
不是

**Comment by herozzm** [comment]
> 不是，如果你觉得 pool 有问题可以直接自己写，rod.NewPagePool 只有几行代码，只是一个帮助函数，复杂的需求可以自己写。
> 
> 你的示例代码看不出任何问题。

是我的代码问题，我将 `pool` 传递给其他函数的时候没有传递指针，而是直接传值的问题

**Comment by herozzm** [comment]
> 不是，如果你觉得 pool 有问题可以直接自己写，rod.NewPagePool 只有几行代码，只是一个帮助函数，复杂的需求可以自己写。
> 
> 你的示例代码看不出任何问题。

可能很多人将browser.Timeout 理解错了，都理解成 如果网页超过这个时间打不开就关闭，但实际上，从打开网页开始算时间，如果超过这个时间，后面的链式函数都无法操作？

**Comment by ysmood** [comment]
这不就是 Go 的通用做法吗，文档不是写的很清楚了吗，你确定其他人也会理解错？
