### ISSUE TITLE
请问如何实现从电脑拖动一个文件到页面某个固定处?

### ISSUE THREAD

**Issue by zhangya4548** [go-rod/rod#575]
请问如何实现从电脑拖动一个文件到页面某个固定处? 求有示例demo?

**Comment by ysmood** [comment]
#392

**Comment by zhangya4548** [comment]
> 这不是鼠标，是拖动文件到浏览器，仔细看 InputDragData， 这个可以是文件列表或者图片等。
> 
> 目前没有详细的例子，等我有时间再写。

好的我研究研究

另外有没有监听页面上某个按钮被点击的示例?

**Comment by ysmood** [comment]
> 另外有没有监听页面上某个按钮被点击的示例?

请不要讨论和 issue 标题无关的内容
