### ISSUE TITLE
有没有监听页面上某个按钮被点击的示例?

### ISSUE THREAD

**Issue by zhangya4548** [go-rod/rod#576]
有没有监听页面上某个按钮被点击的示例?

**Comment by zhangya4548** [comment]
Rod 版本  Version: v0.105.1

有没有监听页面上某个按钮被点击的示例?
例如,页面打开加载完成后, 在等待用户点击 a 按钮,  当用户点击 a 按钮时候, 我希望能获取到通知反馈

**Comment by ysmood** [comment]
`Page.WaitOpen`
