### ISSUE TITLE
Frameless Windows?

### ISSUE THREAD

**Issue by Humphryyy** [go-rod/rod#577]
**Rod Version:** v0.105.1

## Description
Is it possible to open a frameless (Not to be confused with headless) chromium window?

**Comment by Humphryyy** [comment]
I've tried the `--kiosk` flag and `--app`, no luck.

**Comment by ysmood** [comment]
`launcher.New().Delete("no-first-run").Delete("no-startup-window").Set("kiosk")`

**Comment by ysmood** [comment]
Can you make a PR to add the flag helper?

Like `launcher.AppMode()`

**Comment by Humphryyy** [comment]
Sweet, is there any way for it not to be full-screen?

> ```go
> launcher.New().Delete("no-first-run").Delete("no-startup-window").Set("kiosk", "about:blank")
> ```
