### ISSUE TITLE
How to set up timeout If can't find the element, how to skip it.

### ISSUE THREAD

**Issue by aswallz** [go-rod/rod#585]
How to set up timeout If can't find the element, how to skip it.

**Comment by ysmood** [comment]
What do you mean?

**Comment by xines** [comment]
@aswallz 

Use the Timeout helper function: https://go-rod.github.io/#/context-and-timeout?id=timeout

Or use a loop and check the element if exists.

A simplified way would be:
```go
timeout := 10
for {
	// Check element
	foundEle, _, _ := page.HasX(`//*[@id="example"]`)
	if foundEle {
		break
	}

	// Timeout check
	if timeout < 1 {
		break
	}
	timeout--

	// Prevent loop being too aggressive
	time.Sleep(time.Duration(1 * time.Second))
}

**Comment by aswallz** [comment]
Thanks i got.
