### ISSUE TITLE
如何实现拦截文件选择对话

### ISSUE THREAD

**Issue by zzandww** [go-rod/rod#588]
**Rod Version:** v0.106.1

 

## 拦截文件对话框
某些网站的文件框是动态生成的. 这时候就需要拦截文件对话框来上传相应的文件.
请问在rod中有相应的办法吗?
类似于 [FileChooser](https://playwright.dev/dotnet/docs/api/class-filechooser)

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/4c0d5269c12b41eda3d70a4801fcdaff7a27cf3c/lib/proto/page.go#L2657-L2660

**Comment by zzandww** [comment]
> 目前只有比较底层的方法，希望有兴趣的朋友可以帮忙用下面的方法实现出更易于使用的接口：
> 
> https://github.com/go-rod/rod/blob/4c0d5269c12b41eda3d70a4801fcdaff7a27cf3c/lib/proto/page.go#L2657-L2660

非常感谢,已经实现了.  
但是本人golang水平实在比较菜,DevTools协议也是一半靠猜着来实现,
不知道有没有其它问题.  但是是能正常达成目的. 

代码贴出来给其他有同样问题的朋友参考一下.

`func (p *Page) HandleFileChooserDialog() {

	err := proto.PageSetInterceptFileChooserDialog{Enabled: true}.Call(p)
	if err == nil {
		 wait := p.EachEvent(func(ee *proto.PageFileChooserOpened) {
			 node := &proto.DOMNode{
				 FrameID: ee.FrameID ,
				 BackendNodeID: ee.BackendNodeID,
			 }
			 p.MustElementFromNode(node).MustSetFiles("a.png")
		 })
		 wait()
	}
}`

**Comment by ysmood** [comment]
非常厉害了，能否帮忙提交个 PR 把这个功能加入到 rod 呢？实现出这样的效果，名字你自己确定：

```go
el := page.MustWaitFileChooserOpen()
el.MustSetFiles("a.png")
```

**Comment by zzandww** [comment]
OK,我试试看.

**Comment by zhangya4548** [comment]
兄弟你这个有完整代码吗?可以发我查考下吗?

**Comment by zhangya4548** [comment]
> > 只有比较朋友的方法，有兴趣的方法可以帮忙用下面的方法实现更希望使用现在的接口：
> > https://github.com/go-rod/rod/blob/4c0d5269c12b41eda3d70a4801fcdaff7a27cf3c/lib/proto/page.go#L2657-L2660
> 
> 非常感谢，已经有了其他的问题。 但是golang的实际水平比较菜，Dev实现工具也算是实现了， 不知道有没有其他问题。是能获得成功的目的。
> 
> 代码贴出来给其他有同样问题的朋友参考一下。
> 
> ```go
> func ( p  * Page ) HandleFileChooserDialog () {
> 
> 	错误 ：=原型。PageSetInterceptFileChooserDialog {启用：真}。如果err == nil {
> 		  wait := p ，则调用( p )
> 	 。EachEvent ( func ( ee * proto. PageFileChooserOpened ) {
> 			  node := & proto. DOMNode {
> 				  FrameID : ee . FrameID ,
> 				  BackendNodeID : ee . BackendNodeID        ,
> 			 }
> 			 磷。MustElementFromNode (节点)。MustSetFiles ( "a.png" )
> 		 })
> 		 等待()
> 	}
> }
> ```

兄弟你这个有完整代码吗?可以发我查考下吗?

**Comment by ysmood** [comment]
新版本支持这样的用法了：

https://github.com/go-rod/rod/blob/043bc992b0917ecd2cbb54ab5b56b51e686bf076/page_test.go#L573-L582
