### ISSUE TITLE
最小化浏览器时page.MustElement卡死不动

### ISSUE THREAD

**Issue by feeops** [go-rod/rod#589]
**Rod Version:** v0.106.0

启动程序，浏览器会自动打开页面，最小化浏览器后，page.MustElement不会执行，把浏览器恢复后运行

操作系统是最新版的Mac OS，浏览器是最新版的chrome M1版

```go
package main

import (
	"fmt"
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
)

func main() {

	u := launcher.MustResolveURL("9222")

	browser := rod.New().NoDefaultDevice().ControlURL(u).MustConnect()

	buff := "https://buff.163.com/goods/34399#tab=selling"

	page := browser.MustPage(buff).MustWaitLoad()
	fmt.Println("start sleep")
	utils.Sleep(10)
	fmt.Println("end sleep")
	page.MustElement("li.history > a").MustClick()

	fmt.Println("end click")

}
```

**Comment by ysmood** [comment]
这个是浏览器本身的问题，目前没有太好的方法绕开。建议使用 headless 模式就不会有这个问题了。

**Comment by feeops** [comment]
我使用chromedp就没有这个问题，可以最小化在后台操作，会不会定位并操作元素的逻辑不太一样？

**Comment by feeops** [comment]
> 对，你用的比较简单，chromedp 用些复杂的 wait 也会有这个卡死的问题

这边测试了一下，同样是简单的元素，chromedp最小化不会存在不能执行的问题，应该跟浏览器本身没有关系

这是示例代码

`package main

import (
	"context"
	"fmt"
	"github.com/chromedp/chromedp"
	"log"
	"time"
)

func main() {

	wsURL := "ws://127.0.0.1:9222/"

	// pay attention to the url below
	ctx, cancel := chromedp.NewRemoteAllocator(context.Background(), wsURL)
	defer cancel()

	buffURL := "https://buff.163.com/goods/34399#tab=selling"

	ctx, _ = context.WithTimeout(ctx, 10*time.Hour)

	ctx, _ = chromedp.NewContext(ctx, chromedp.WithErrorf(log.Printf))

	if err := chromedp.Run(ctx,
		chromedp.Navigate(buffURL),
	); err != nil {
		log.Fatal(err)
	}
	fmt.Println("start sleep")
	time.Sleep(10 * time.Second)

	if err := chromedp.Run(ctx,
		chromedp.Click("li.history > a", chromedp.ByQuery),
	); err != nil {
		log.Fatal(err)
	}
	fmt.Println("end sleep")
	time.Sleep(10 * time.Second)

	fmt.Println("end")

}
`

**Comment by ysmood** [comment]
我跑了下如下的代码，没有卡住，你可以录个视频来描述下你的问题吗？我无法复现：

```go
package main

import (
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/defaults"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	defaults.Show = true
	defaults.Trace = true

	browser := rod.New().MustConnect()
	page := browser.MustPage()

	page.MustWindowMinimize()

	utils.Sleep(3)

	page.MustNavigate("https://buff.163.com/goods/34399#tab=selling")
	page.MustElement("li.history > a").MustClick()
}

```

**Comment by feeops** [comment]
复现步骤
运行程序，当程序输出start sleep时，手动将浏览器最小化
过一会，程序就会输出end sleep，但等待很长时间都不会输出end click

将浏览器再次打开后，才会执行点击并输出end click

录屏如下，可以看到，长时间没有输出end click


https://user-images.githubusercontent.com/92842117/164255731-60a4e114-2584-45d3-9b44-998afb9e862e.mp4

**Comment by ysmood** [comment]
你试了我的代码吗，也有一样的问题吗？

**Comment by feeops** [comment]
> 你试了我的代码吗，也有一样的问题吗？

也会遇到，这是我测试的代码

```
package main

import (
	"fmt"
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/defaults"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	defaults.Show = true
	defaults.Trace = true

	u := launcher.MustResolveURL("9222")

	page := rod.New().ControlURL(u).MustConnect().MustPage().MustWindowMinimize()

	utils.Sleep(10)

	page.MustNavigate("https://buff.163.com/goods/34399#tab=selling").
		MustElement("li.history > a").
		MustClick()

	fmt.Println("end")
}
```

在sleep的时候迅速将浏览器最小化

调试信息
```
[rod] 2022/04/21 10:11:41 [query] rod.element("li.history > a")  <page:612B9760>
[rod] 2022/04/21 10:11:41 [query] rod.element("li.history > a")  <page:612B9760>
[rod] 2022/04/21 10:11:41 [wait] interactable <a>
[rod] 2022/04/21 10:11:41 [input] scroll into view <a>
[rod] 2022/04/21 10:11:41 [wait] visible <a>
[rod] 2022/04/21 10:11:41 [wait] stable RAF <a>
```


最后一行print会迟迟不输出

这里必须要求元素visible吗？当它最小化，元素就不可见就不能操作了？

**Comment by ysmood** [comment]
你录像里缺少了启动浏览器的过程，能描述下吗？

**Comment by feeops** [comment]
浏览器是已经启动的，我写的代码中是连接已经存在的浏览器，chromedp中连接已经存在浏览器是没有任何问题的

你的代码中是重新下载并启动了一个新浏览器

**Comment by ysmood** [comment]
> 你的代码中是重新下载并启动了一个新浏览器

所以我的代码有问题吗？你还是没有回答我的问题。

**Comment by feeops** [comment]
> > 你的代码中是重新下载并启动了一个新浏览器
> 
> 所以我的代码也有问题吗？你还是没有回答我的问题。你就不能试试我的代码吗？

这个测试的代码跟你的代码差不多啊，只不过是将下载浏览器换成了连接已有浏览器啊

```
package main

import (
	"fmt"
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/defaults"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	defaults.Show = true
	defaults.Trace = true

	u := launcher.MustResolveURL("9222")

	page := rod.New().ControlURL(u).MustConnect().MustPage().MustWindowMinimize()

	utils.Sleep(10)

	page.MustNavigate("https://buff.163.com/goods/34399#tab=selling").
		MustElement("li.history > a").
		MustClick()

	fmt.Println("end")
}
```

**Comment by ysmood** [comment]
能否配合下调试，你运行下我的代码如果没有问题，就证明是你启动的方式导致的问题。你现在没有描述你启动的方式，如果缺了某些命令行参数就会导致这个问题。chromedp 也是如此，你只不过没有使用 chromedp 的 eval 才侥幸没有遇到问题而已。

**Comment by feeops** [comment]
在mac上的启动方式是
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222

chromedp执行是没有问题的

**Comment by feeops** [comment]
加上这个参数就可以了，谢谢了
