### ISSUE TITLE
在获取 iframe 对象后，再此基础上在获取其中的元素的时候崩溃

### ISSUE THREAD

**Issue by allanpk716** [go-rod/rod#598]
使用 go-rod 很久了，在项目中算很稳定（完成的功能很久没有动过了，能稳定使用，除了最近升级了 go-rod到最新），但是刚才发现频繁故障，于是跟踪了下，发现了下面的问题。

PS：项目很棒，谢谢你的付出。

## go-rod version

**Rod Version**: v0.106.5

## 测试的代码
![image](https://user-images.githubusercontent.com/1176000/167263474-e43d6209-e508-4ba9-8a46-4e179a90828f.png)

获取 iframe 后，再在 iframe 去判断 dragBtn 元素的时候就崩溃了。相同的代码，应该在一个月前是正确的。

## 测试的页面

目标网页：https://subhd.tv/a/526509
点击下载字幕的时候会有一个弹窗

![image](https://user-images.githubusercontent.com/1176000/167263610-79d7ea39-7212-4e54-a40c-1db836ebe06d.png)

## 故障 Stack 信息
`goroutine 19 [running]:
runtime/debug.Stack()
	C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x7a
github.com/go-rod/rod.Try.func1()
	C:/WorkSpace/Go2Hell/pkg/mod/github.com/go-rod/rod@v0.106.5/utils.go:211 +0x4a
panic({0x1223f00, 0x1120f60})
	C:/Program Files/Go/src/runtime/panic.go:1047 +0x262
github.com/go-rod/rod.(*Page).getJSCtxID(0xc0004ac2c0)
	C:/WorkSpace/Go2Hell/pkg/mod/github.com/go-rod/rod@v0.106.5/page_eval.go:349 +0x316
github.com/go-rod/rod.(*Page).ensureJSHelper(0xc0004ac2c0, 0x1124fc0)
	C:/WorkSpace/Go2Hell/pkg/mod/github.com/go-rod/rod@v0.106.5/page_eval.go:248 +0x6a
github.com/go-rod/rod.(*Page).formatArgs(0xc0004ac2c0, 0xc000440240)
	C:/WorkSpace/Go2Hell/pkg/mod/github.com/go-rod/rod@v0.106.5/page_eval.go:233 +0x385
github.com/go-rod/rod.(*Page).evaluate(0xc0004ac2c0, 0xc000440240)
	C:/WorkSpace/Go2Hell/pkg/mod/github.com/go-rod/rod@v0.106.5/page_eval.go:149 +0x7e
github.com/go-rod/rod.(*Page).Evaluate(0xc0004ac2c0, 0xc000440240)
	C:/WorkSpace/Go2Hell/pkg/mod/github.com/go-rod/rod@v0.106.5/page_eval.go:128 +0x76
github.com/go-rod/rod.(*Page).ElementByJS.func2()
	C:/WorkSpace/Go2Hell/pkg/mod/github.com/go-rod/rod@v0.106.5/query.go:172 +0xbf
github.com/go-rod/rod/lib/utils.Retry({0x150ae58, 0xc0000f44b0}, 0xc00047ccf0, 0xc0000e2550)
	C:/WorkSpace/Go2Hell/pkg/mod/github.com/go-rod/rod@v0.106.5/lib/utils/sleeper.go:142 +0x46
github.com/go-rod/rod.(*Page).ElementByJS(0xc0004ac2c0, 0xc000440240)
	C:/WorkSpace/Go2Hell/pkg/mod/github.com/go-rod/rod@v0.106.5/query.go:167 +0x179
github.com/go-rod/rod.(*Page).Element(0xc0004ac2c0, {0x1332c66, 0x15})
	C:/WorkSpace/Go2Hell/pkg/mod/github.com/go-rod/rod@v0.106.5/query.go:143 +0x10b
github.com/go-rod/rod.(*Page).MustElement(0xc0004ac2c0, {0x1332c66, 0x15})
	C:/WorkSpace/Go2Hell/pkg/mod/github.com/go-rod/rod@v0.106.5/must.go:519 +0x73
github.com/allanpk716/ChineseSubFinder/internal/logic/sub_supplier/subhd.(*Supplier).passWaterWall(0xc00047cb10, 0xc0004ac0b0)
	C:/WorkSpace/Go2Hell/src/github.com/allanpk716/ChineseSubFinder/internal/logic/sub_supplier/subhd/subhd.go:633 +0xa6
github.com/allanpk716/ChineseSubFinder/internal/logic/sub_supplier/subhd.(*Supplier).downloadSubFile.func1()
	C:/WorkSpace/Go2Hell/src/github.com/allanpk716/ChineseSubFinder/internal/logic/sub_supplier/subhd/subhd.go:600 +0xc54
github.com/go-rod/rod.Try(0xc0000e2ff8)
	C:/WorkSpace/Go2Hell/pkg/mod/github.com/go-rod/rod@v0.106.5/utils.go:215 +0x88
github.com/allanpk716/ChineseSubFinder/internal/logic/sub_supplier/subhd.(*Supplier).downloadSubFile(0xc00047cb10, 0xc0002e6120, 0xc0004ac0b0, {0xc0000ffc50, 0x9})
	C:/WorkSpace/Go2Hell/src/github.com/allanpk716/ChineseSubFinder/internal/logic/sub_supplier/subhd/subhd.go:509 +0x274
github.com/allanpk716/ChineseSubFinder/internal/logic/sub_supplier/subhd.(*Supplier).DownFile(0xc00047cb10, 0xc0002e6120, {0xc0000ffc50, 0x9}, 0x0, 0x4, 0x1)
	C:/WorkSpace/Go2Hell/src/github.com/allanpk716/ChineseSubFinder/internal/logic/sub_supplier/subhd/subhd.go:490 +0x305
github.com/allanpk716/ChineseSubFinder/internal/logic/file_downloader.(*FileDownloader).GetEx(0xc000402288, {0x13184cc, 0x5}, 0xc0002e6120, {0xc0000ffc50, 0x9}, 0x0, 0x4, 0x1, 0xc0000e3790)
	C:/WorkSpace/Go2Hell/src/github.com/allanpk716/ChineseSubFinder/internal/logic/file_downloader/downloader_hub.go:91 +0x2fc
github.com/allanpk716/ChineseSubFinder/internal/logic/sub_supplier/subhd.(*Supplier).GetSubListFromFile4Series(0xc00047cb10, 0xc000152080)
	C:/WorkSpace/Go2Hell/src/github.com/allanpk716/ChineseSubFinder/internal/logic/sub_supplier/subhd/subhd.go:178 +0x11aa
github.com/allanpk716/ChineseSubFinder/internal/logic/sub_supplier/subhd.TestSupplier_GetSubListFromFile4Series(0xc00045c4e0)
	C:/WorkSpace/Go2Hell/src/github.com/allanpk716/ChineseSubFinder/internal/logic/sub_supplier/subhd/subhd_test.go:70 +0x425
testing.tRunner(0xc00045c4e0, 0x14b23c8)
	C:/Program Files/Go/src/testing/testing.go:1259 +0x1db
created by testing.(*T).Run
	C:/Program Files/Go/src/testing/testing.go:1306 +0x673
`

## 具体的故障截图
![image](https://user-images.githubusercontent.com/1176000/167263424-7514a356-cd1d-4c20-9bf8-17cdfcc0816c.png)

**Comment by allanpk716** [comment]
但是如果我是在这个页面 https://007.qq.com/online.html 上测试相同的代码又没有问题。以至于我也不敢确定是否是 rod 的问题。

测试代码（没有问题的）：https://github.com/allanpk716/ChineseSubFinder/blob/af1f2d2121406084e7857f22203c3a0c94ba2d1a/internal/pkg/pass_water_wall/pass_water_wall_test.go#L7

测试代码（遇到问题的）：
https://github.com/allanpk716/ChineseSubFinder/blob/af1f2d2121406084e7857f22203c3a0c94ba2d1a/internal/logic/sub_supplier/subhd/subhd_test.go#L54

https://github.com/allanpk716/ChineseSubFinder/blob/af1f2d2121406084e7857f22203c3a0c94ba2d1a/internal/logic/sub_supplier/subhd/subhd.go#L620

1. 前者可以直接运行测试
2. 后者的项目的测试代码，需要依赖 https://github.com/allanpk716/ChineseSubFinder-TestData 放在 https://github.com/allanpk716/ChineseSubFinder 的同级目录 A 下：
A --
     --- ChineseSubFinder
     --- ChineseSubFinder-TestData

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/issues/548

**Comment by allanpk716** [comment]
谢谢，根据你提到的这个 issue 的解决方案搞定了。
