### ISSUE TITLE
stream error: stream ID 1; INTERNAL_ERROR; received from peer

### ISSUE THREAD

**Issue by aadog** [go-rod/rod#600]
**Rod Version:** v0.106.6-0.20220507105211-27a23eccf51a

## The code to demonstrate your question

```go
	p, _ := launcher.LookPath()
	u := launcher.New().Bin(p).Headless(false).MustLaunch()
	browser := rod.New().ControlURL(u).MustConnect()
	router := browser.HijackRequests()
	router.MustAdd("*", func(ctx *rod.Hijack) {
		ctx.MustLoadResponse()
	})
	go router.Run()
	browser.MustPage("https://www.baidu.com")
	for {
		time.Sleep(time.Second)
	}
```

## What have you tried to solve the question
panic: stream error: stream ID 1; INTERNAL_ERROR; received from peer

goroutine 74 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0x9498e0, 0xc00041c018})
        C:/Users/pwt/go/pkg/mod/github.com/go-rod/rod@v0.106.6-0.20220507105211-27a23eccf51a/lib/utils/utils.go:59 +0x25
github.com/go-rod/rod.genE.func1({0xc00009a4f0, 0x1, 0x1})
        C:/Users/pwt/go/pkg/mod/github.com/go-rod/rod@v0.106.6-0.20220507105211-27a23eccf51a/must.go:35 +0x106
github.com/go-rod/rod.(*Hijack).MustLoadResponse(0xc00060e080)
        C:/Users/pwt/go/pkg/mod/github.com/go-rod/rod@v0.106.6-0.20220507105211-27a23eccf51a/must.go:1060 +0xe8
main.main.func1(0xc00060e080)
        C:/Users/pwt/src/awesomeProject/main.go:15 +0x1e
github.com/go-rod/rod.(*HijackRouter).initEvents.func1.1()
        C:/Users/pwt/go/pkg/mod/github.com/go-rod/rod@v0.106.6-0.20220507105211-27a23eccf51a/hijack.go:75 +0x173
created by github.com/go-rod/rod.(*HijackRouter).initEvents.func1
        C:/Users/pwt/go/pkg/mod/github.com/go-rod/rod@v0.106.6-0.20220507105211-27a23eccf51a/hijack.go:68 +0xe5

**Comment by aadog** [comment]
How to get the response value and modify it

**Comment by aadog** [comment]
And how to set the return of [] byte type

**Comment by ysmood** [comment]
Don't put two unrelated questions into one issue

**Comment by aadog** [comment]
ok

**Comment by ysmood** [comment]
I think it's an upstream issue related to #395

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/issues/672#issuecomment-1205874364
