### ISSUE TITLE
关于 launcher 无法启动浏览器的问题

### ISSUE THREAD

**Issue by Niexiawei** [go-rod/rod#601]
**Rod Version:** v0.106.6

## The code to demonstrate your question

```go
// Please make sure your code is minimal and standalone
func main() {
	_launcher := launcher.New().
		Set("--no-sandbox").
		Set("--disable-setuid-sandbox").
		Set("--disable-dev-shm-usage").
		Set("--disable-web-security").
		Set("--disable-blink-features=AutomationControlled").
		Set("--disable-features=IsolateOrigins,site-per-process").
		Set("--disable-backgrounding-occluded-windows").
		Delete("--enable-automation").
		//Headless(config.Config.Pages.Headless).
		Bin("D:\\chrome-win\\chrome.exe").
		MustLaunch()

	fmt.Println(_launcher)
}
```

![image](https://user-images.githubusercontent.com/29922984/167587161-4f320f24-89a8-4c8b-a831-cf23c0edd2ec.png)
![image](https://user-images.githubusercontent.com/29922984/167587217-9733c1f3-d4b9-47aa-94ed-4f7c37b57d98.png)

## What have you tried to solve the question

无法启动浏览器 程序会持续运行一直阻塞

作者是否遇见这种问题

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/f6d19fe89819b9f580db669bdf64d7e0a4a1cb95/lib/launcher/example_test.go#L20-L24

**Comment by Niexiawei** [comment]
![image](https://user-images.githubusercontent.com/29922984/167605591-0e05d9a1-80f1-491a-b592-deaff3c34a92.png)
依旧没有输出

**Comment by ysmood** [comment]
重启电脑

**Comment by Niexiawei** [comment]
重启过了 所以搞不明白啥问题 才来这边提问  但是使用 exec.Command 函数又是可以启动的

**Comment by ysmood** [comment]
其他的启动方式是过了吗？

**Comment by Niexiawei** [comment]
都尝试过了
我放到本机的 wsl2中 是可以的
但在win中还是不行

**Comment by ysmood** [comment]
`launcher.New().MustLaunch()` 去掉其他选项也不行吗？

**Comment by Niexiawei** [comment]
![image](https://user-images.githubusercontent.com/29922984/167620290-dcc07b1e-e2d9-4b88-97c8-f6d6521a174a.png)
是的 依旧存在这个问题

我本地还有其他 nodejs puppeteer 项目 是可以正常运行的

**Comment by ysmood** [comment]
我试了下我的 window10，没有任何问题。能再试试关闭 leakless 吗？

```go
launcher.New().Leakless(false).MustLaunch()
```

**Comment by Niexiawei** [comment]
关闭 Leakless 后可以运行了

请问一下 Leakless 作用是什么 我追溯了一下源码 发现是一串 base64

**Comment by ysmood** [comment]
看文档，说的很清楚了

**Comment by Niexiawei** [comment]
好的  非常感谢你的解答
