### ISSUE TITLE
本机有代理，却不能访问境外网站，境内可以是什么原因？

### ISSUE THREAD

**Issue by zlq1252** [go-rod/rod#604]
//-------------------------------------------------------这样写百度是可以访问↓------------------------------------------
path, _ := launcher.LookPath()
	u := launcher.New().Delete("--headless").Set("--window-size=1920,1080").Bin(path).MustLaunch()
	browser := rod.New().ControlURL(u).MustConnect()
	router := browser.HijackRequests()
	defer router.Stop()
	router.MustAdd("", func(ctx *rod.Hijack) {
		ctx.LoadResponse(http.DefaultClient, true)
                fmt.Println(ctx.Request.URL().String())
	})

	go router.Run()
	page := browser.MustPage()
	wait := page.MustWaitNavigation()
	page.MustNavigate("https://baidu.com/")
	wait()

//-----------------------------------------------------------这样写谷歌不能访问↓-------------------------------------------------------

path, _ := launcher.LookPath()
	u := launcher.New().Delete("--headless").Set("--window-size=1920,1080").Bin(path).MustLaunch()
	browser := rod.New().ControlURL(u).MustConnect()
	router := browser.HijackRequests()
	defer router.Stop()
	router.MustAdd("", func(ctx *rod.Hijack) {
		ctx.LoadResponse(http.DefaultClient, true)
                fmt.Println(ctx.Request.URL().String())
	})

	go router.Run()
	page := browser.MustPage()
	wait := page.MustWaitNavigation()
	page.MustNavigate("https://google.com/")
	wait()

**Comment by ysmood** [comment]
#322
