### ISSUE TITLE
如何取消 -rod 的flag提示呢？

### ISSUE THREAD

**Issue by labulac** [go-rod/rod#619]
**Rod Version:** v0.107.0

## The code to demonstrate your question

1. Clone Rod to your local and cd to the repository:

   ```bash
   git clone https://github.com/go-rod/rod
   cd rod
   ```

1. Use your code to replace the content of function `TestLab` in file `lab_test.go`.

1. Test your code with: `go test -run TestLab`.

1. Replace this section with your entire `lab_test.go` content, like below:

```go
package main

import (
	"flag"
	"fmt"

	"github.com/go-rod/rod"
)

var T = flag.String("t", "", "测试")

func main() {
	flag.Parse()
	fmt.Println(*T)
	page := rod.New().MustConnect().MustPage("https://www.baidu.com/")
	page.MustWaitLoad().MustScreenshot("a.png")
}

```

## What you expected to see

use `go run main.go -h`
display this
```bash
$ go run main.go -h
Usage of C:\main.exe:
  -rod string
        Set the default value of options used by rod.
  -t string
        测试
```

## What you instead got

only display 
```
 -t string
        测试
```
do not display  `-rod` flag

## What have you tried to solve the question

none

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/e25267d592adf3c5f65f51712f7b79f5c80e2e20/lib/defaults/defaults.go#L138-L148
