### ISSUE TITLE
[REPL]use go rod with gore ( https://github.com/x-motemen/gore )

### ISSUE THREAD

**Issue by zerobuilder** [go-rod/rod#625]
**Rod Version:** v0.107.2

## situation

While developing a web script that needs to perform many operations, I encountered a bug in the middle, but couldn't terminate the program to debug where the error occurred.

## What you got

I'm not good enough to solve this problem

## What you expected to see

A example code about go rod with gore and [stealth](https://github.com/go-rod/stealth).

A example code including rod and stealth with [gore](https://github.com/x-motemen/gore) /[go-pry
](https://github.com/d4l3k/go-pry)/[go-macro](https://github.com/cosmos72/gomacro)

## What have you tried to solve the question

use go rod with gore ( https://github.com/x-motemen/gore ) , but failed.i did not save my code.

**Comment by ysmood** [comment]
?

**Comment by ysmood** [comment]
#322

**Comment by ysmood** [comment]
Duplicated with #333
