### ISSUE TITLE
关于 context 的问题

### ISSUE THREAD

**Issue by Niexiawei** [go-rod/rod#626]
**Rod Version:** v0.107.1

```go
	_ = login.Page.Navigate(config.Config.MeituanLogin.Url)
	loginFrame := login.Page.Timeout(5 * time.Second).
		MustElement("iframe[title=登录模块]").
		CancelTimeout().
		MustFrame()

	loginFrame.Timeout(3 * time.Second).MustElement("#loginContainer .container .header__nav .header__nav-link_0").MustClick().CancelTimeout()
	login.LoginFrame = &pages.Page{loginFrame}
	login.writerAccountInfo()
```

![image](https://user-images.githubusercontent.com/29922984/173980228-7c283a2c-e0ec-4d67-af31-ea9fd43ff3e7.png)

我在  第一段代码中 执行了 CancelTimeout() 按照我的理解 返回的 loginFrame 应该是不携带 timeout的
但是在第二段代码执行后 就会执行报错 panic: context canceled

![image](https://user-images.githubusercontent.com/29922984/173980474-3cc41fb3-ff45-4286-b963-07b345e8f872.png)
不知道这么写是否正确 还是我理解上面有错误

**Comment by Niexiawei** [comment]
![image](https://user-images.githubusercontent.com/29922984/173980960-c08b64da-3806-4a7d-b36a-be64b228275b.png)

把第二段代码中的 timeout 移除后依旧会出现这个问题

**Comment by ysmood** [comment]
`panic: context canceled` 不是 timeout， timeout 报错应该是 `deadline exceeded`

**Comment by Niexiawei** [comment]
那请问一下  为什么会出现context cancel呢  是我使用方式有问题吗

**Comment by ysmood** [comment]
#322 如果你不按照第3条来提问，我也不知道问题是什么
