### ISSUE TITLE
Does this libratry has any way for setting timeout for functoins?

### ISSUE THREAD

**Issue by ITChelik** [go-rod/rod#630]
**Rod Version:** v0.107.2

```go
func  requestWarining(page *rod.Page) (err error) {
	waringText := ""
	timeOutToCheck, cancel := context.WithTimeout(context.Background(), time.Second)
	go func() {
		warningElem, err := page.Element("#alert > div.sc-cvbbAY.dbHDoR > div")
		if err == nil {
			waringText, err = warningElem.Text()
			if err != nil {
				p.logger.Error(err)
			}
			cancel()
		}
	}()
	<-timeOutToCheck.Done()
	if waringText != "" {
		return fmt.Errorf(waringText)
	}

	return nil
}
```

## What you got

I can't find any way to set timeouts for functions. Ex.: page.Element() function

## What you expected to see

An element can be visible in an interval between 0 and 1 seconds, and if page.Element() doesn't find it during aforementioned interval, fuction gets stuck in an infinite loop. 
So i made self function for timeout.

## What have you tried to solve the question

I read the documentation and saw `page.Timeout()` method, but this method sets timeout for the element which i being selected and not for the function

**Comment by ysmood** [comment]
`page.Timeout(time.Second).Element("#alert > div.sc-cvbbAY.dbHDoR > div")`
