### ISSUE TITLE
rod try on hijack requests

### ISSUE THREAD

**Issue by musicyin** [go-rod/rod#639]
Minimal Code:

```
router := browser.HijackRequests()
router.MustAdd("*somethinghavetimeout*", func(ctx *rod.Hijack) {
		ctx.MustLoadResponse()
})
go router.Run()
```

Got error
panic: Get "*********somethinghavetimeout***********": dial tcp websiteip:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
How to retry and not panic?

**Rod Version:** v0.107.2

**Comment by ysmood** [comment]
#322
