### ISSUE TITLE
use of closed network connection

### ISSUE THREAD

**Issue by zplzpl** [go-rod/rod#644]
**Rod Version:** v0.107.3
**System:** macos

## The code to demonstrate your question

```
browser := rod.New().ControlURL(u).MustConnect()

// wait a few hours ...

browser.MustIncognito() <--- get error

```

## What you got

<img width="538" alt="image" src="https://user-images.githubusercontent.com/7931755/177465455-61d19c6b-7177-4c52-9cc1-bc380276e310.png">

## What you expected to see

don't make this error

## What have you tried to solve the question

nope.

Does the connection have a function of automatically closing the timeout?

**Comment by ysmood** [comment]
We don't have this issue after hours of scraping. Need a stable way to reproduce it.

**Comment by ysmood** [comment]
Please follow #322

**Comment by Nikola-Milovic** [comment]
@zplzpl did you figure out what was causing this? We have similar issues
