### ISSUE TITLE
Running remote Rod doesn't kill the websocket

### ISSUE THREAD

**Issue by youshy** [go-rod/rod#65]
**Describe the bug**
I've been playing around with remote Rod image using docker. When running it this way, the underlying connections from Docker on websocket doesn't seem to close properly. This is from heap pprof:

```
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
                                             325MB   100% |   github.com/gorilla/websocket.newConn /go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:293 (inline)
     325MB 58.69% 58.69%      325MB 58.69%                | bufio.NewReaderSize /usr/local/go/src/bufio/bufio.go:56
----------------------------------------------------------+-------------
                                          130.10MB   100% |   github.com/gorilla/websocket.(*Dialer).DialContext /go/pkg/mod/github.com/gorilla/websocket@v1.4.2/client.go:327
  130.10MB 23.50% 82.19%   130.10MB 23.50%                | github.com/gorilla/websocket.newConn /go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:302
----------------------------------------------------------+-------------
```

**To Reproduce**

```go
func example() {
	browser := connectSetup()
	defer browser.Close()
}

func connectSetup() *rod.Browser {
	rodImageUri := os.Getenv("ROD_DOCKER_URI")
	client := launcher.NewRemote(rodImageUri).Reap(true).Client()
	browser := rod.New().Client(client).Trace(false).Connect().Timeout(time.Minute)
	return browser
}
```

The function is run as a part of a HTTP handler.

**Expected behavior**
Memory should be freed after the function ends.

**Rod Version:** v0.38.0

**OS:** MacOS

**Comment by ysmood** [comment]
Can you try the latest version, I fixed some leak issue recently.

**Comment by ysmood** [comment]
Thank you! I will check it too.

**Comment by ysmood** [comment]
Actually, after some investigation, I feel it's a bug of the WebSocket lib or Chrome. But not 100% sure yet.

**Comment by youshy** [comment]
I had the same hunch, as when checking Rod docker logs, it was closing the sockets properly.

**Comment by ysmood** [comment]
Now we are using `go.uber.org/goleak` in CI to enforce no leaking, see #67.

The CI for `v0.41.0` passed: https://github.com/go-rod/rod/actions/runs/150264755

So I will close this ticket, if you find any issue, please let me know, we can open it again.

Also, this issue #79 might be interesting for you.
