### ISSUE TITLE
how to pre load a js file before opening a new page,possible show me a demo code,How to add external resources (image, js, css, etc)?

### ISSUE THREAD

**Issue by passerbyo** [go-rod/rod#651]
**Rod Version:** v0.108.1

## The code to demonstrate your question

```no,just a question```

## What you got

how to pre load a js file before opening a new page,possible show me a demo code,How to add external resources (image, js, css, etc)?just like add stealth.min.js

## What you expected to see

how to pre load a js file before opening a new page,possible show me a demo code,How to add external resources (image, js, css, etc)?just like add stealth.min.js

## What have you tried to solve the question

how to pre load a js file before opening a new page,possible show me a demo code,How to add external resources (image, js, css, etc)?just like add stealth.min.js

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/bc44c39c9b4352c15d00bef6f6a1071205d2c388/lib/examples/disable-window-alert/main.go
