### ISSUE TITLE
How can I handle errors for the elements p.MustElement

### ISSUE THREAD

**Issue by vipulsingh24** [go-rod/rod#657]
Rod Version: v0.107.3

Looking to handle the error or panic in case the element not found or something else want wrong, while selecting or clicking an element.

For example, in page.MustElement if frame not found
`pF := page.MustElement("#selector_name").MustFrame()`

or while clicking a button, I see there were errors like `panic: element has no visible shape or outside the viewport: <#selector_name>`
`pF.MustElement("#selector_name").MustClick()`

**Comment by ysmood** [comment]
Because

> element has no visible shape or outside the viewport

How to click button that is not visible on the page?

Maybe your selector seclects a wrong button.

**Comment by ysmood** [comment]
#322

**Comment by vipulsingh24** [comment]
Yes @ysmood , so is there any way I can handle it. How should I check is that element present in the html or not?

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/4bbedf835b6185eee54068e16d2d4e7d7171073d/element.go#L143-L146
