### ISSUE TITLE
文档里使用代理例子代码报错，navigation failed: net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by oceanchang** [go-rod/rod#663]
**Rod Version:** v0.108.1

## The code to demonstrate your question

```go
package main

import (
	"log"
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/launcher/flags"
)

func main() {
	l := launcher.New()
	l = l.Set(flags.ProxyServer, "127.0.0.1:3128")
	controlURL, _ := l.Launch()
	browser := rod.New().ControlURL(controlURL).MustConnect()
	//go browser.MustHandleAuth("test_name", "test_pass")() 
	browser.MustIgnoreCertErrors(true)

	page := browser.MustPage()
	defer page.MustClose()
	err := page.Navigate("https://api.ipify.org")
	if err != nil {
		log.Println(err)
	}
	err = page.WaitLoad()
	if err != nil {
		log.Println(err)
	}
	println(page.MustElement("html").MustText())
}
```

## What you got
运行代码报错：navigation failed: net::ERR_EMPTY_RESPONSE
socks代理使用v2ray搭建，匿名可用，通过SwitchyOmega插件在浏览器验证可以正常代理使用
v2ray access.log 提示
rejected  proxy/socks: unknown Socks version

## What you expected to see
在源码里没能找到proxy这块儿如何实现的，不清楚这错误是代码问题？还是代理问题？
顺便问一下，是只支持socks5代理，不支持http或https代理，对吗？

**Comment by ysmood** [comment]
可以看看chrome的文档或者Google，这不属于rod的开发范围。

**Comment by oceanchang** [comment]
> 可以看看chrome的文档或者Google，这不属于rod的开发范围。

ok，如果不是rod范围，试了一下就搞定了，l = l.Set(flags.ProxyServer, "socks5://127.0.0.1:3128")
