### ISSUE TITLE
panic when use gin and rod, Failed to get the debug url,Opening in existing browser session. 

### ISSUE THREAD

**Issue by passerbyo** [go-rod/rod#664]
Rod Version: v0.108.1

## The code to demonstrate your question

```go

import (
  "github.com/gin-gonic/gin"
  "github.com/rakyll/statik/fs"
  "github.com/go-rod/rod"
  "github.com/go-rod/rod/lib/launcher"
  "github.com/go-rod/stealth"
)

func TestLab(t *testing.T) {
     r := gin.Default()
     r.GET("/run",func(c *gin.Context){
           go rod.rodhandle()
      })
      r.Run()
}

func rodhandle() {
  u := launcher.New().
  Headless(false).
  MustLaunch()
  browser := rod.New().ControlURL(u).MustConnect().Trace(true).MustIncognito()
  defer browser.MustClose()
  page := stealth.MustPage(browser)
  defer page.MustClose()
  page.MustNavigate("https://google.c/
  om/")
  page.MustWaitLoad()
}
```
second time to access /run url will see and panic.

## What you got

panic: [launcher] Failed to get the debug url: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null) Opening in existing browser session. [0722/023228.007212:ERROR:nacl_helper_linux.cc(315)] NaCl helper process running without a sandbox! Most likely you need to configure your SUID sandbox correctly

**Comment by ysmood** [comment]
#322

**Comment by ysmood** [comment]
Please check second rule of #322

**Comment by ysmood** [comment]
Please check the first rule of https://github.com/go-rod/rod/issues/322

**Comment by ysmood** [comment]
https://en.wikipedia.org/wiki/Syntax_highlighting

**Comment by ysmood** [comment]
#665
