### ISSUE TITLE
panic when use gin and rod, Failed to get the debug url and Opening in existing browser session,detail see following

### ISSUE THREAD

**Issue by passerbyo** [go-rod/rod#665]
Rod Version: v0.108.1

## The code to demonstrate your question

i got a bug. **here is my go code**

i use command ```curl http://127.0.0.1/run``` to run code.

```go
package main

import (
  "github.com/gin-gonic/gin"
  "github.com/rakyll/statik/fs"
  "github.com/go-rod/rod"
  "github.com/go-rod/rod/lib/launcher"
  "github.com/go-rod/stealth"
)

func rodhandle() {
  u := launcher.New().
  Headless(false).
  MustLaunch()
  browser := rod.New().ControlURL(u).MustConnect().Trace(true).MustIncognito()
  defer browser.MustClose()
  page := stealth.MustPage(browser)
  defer page.MustClose()
  page.MustNavigate("https://google.com/")
  page.MustWaitLoad()
}

func main(){
  r := gin.Default()
  r.GET("/run",func(c *gin.Context){
    go rod.rodhandle()
  })
  r.Run()
}
```

second time to access /run url will see and panic

## What you got

when i run my code with ```go run main.go``` and ```curl http:127.0.0.1:8080/run``` at second time, the shell shows my following log,
panic: [launcher] Failed to get the debug url: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null) Opening in existing browser session. [0722/023228.007212:ERROR:nacl_helper_linux.cc(315)] NaCl helper process running without a sandbox! Most likely you need to configure your SUID sandbox correctly

## What you expected to see

when i ```curl http:127.0.0.1:8080/run``` and xode runs normally

## What have you tried to solve the question

I'm relatively new to Go, I haven't tried to hack Rod, I have no clue on where to look

**Comment by ysmood** [comment]
Please check the first rule of #322

**Comment by ysmood** [comment]
https://en.wikipedia.org/wiki/Syntax_highlighting

**Comment by ysmood** [comment]
`MustIncognito` creates an incognito browser, which is not the origin browser anymore, close it doesn't close the origin browser object.

You should code like this:

```go
func rodhandle() {
  u := launcher.New().
  Headless(false).
  MustLaunch()
  b := rod.New().ControlURL(u).MustConnect().Trace(true)
  defer b.MustClose()
  browser := b.MustIncognito()
  page := stealth.MustPage(browser)
  defer page.MustClose()
  page.MustNavigate("https://google.com/")
  page.MustWaitLoad()
}
```

**Comment by tyron** [comment]
@passerbyo as a general rule for being polite, please don't randomly mention people in your issues. I have no real involvement with the project and I'm not even sure where you got my username from. Thanks

**Comment by ysmood** [comment]
@passerbyo The #322 says

> ping `@go-rod/everyone`

`@go-rod/everyone` already means everyone, you don't have to ping everyone again. Please help to keep github a clean place.
