### ISSUE TITLE
Is it possible to specify the XY position of Click()/MustClick() on an element?

### ISSUE THREAD

**Issue by Jacobinski** [go-rod/rod#666]
In the Playwright browser automation framework, it is possible to specify the [location on an element to click](https://playwright.dev/docs/api/class-locator#locator-click). This is useful for image inputs that change their actions depending on click location (ex: maps, captchas, etc).

Is it possible to achieve the same thing with go-rod?

`Rod Version: v0.108.1`

**Comment by ysmood** [comment]
Yes:

```go
page.Mouse.MustMove(100, 100).MustClick(proto.InputMouseButtonLeft)
```

**Comment by Jacobinski** [comment]
Thanks!
