### ISSUE TITLE
Recaptcha not load properly when hijack

### ISSUE THREAD

**Issue by musicyin** [go-rod/rod#672]
Rod Version: v0.108.1

```go
browser := rod.New().ControlURL(launcher.New().Delete("headless").MustLaunch()).MustConnect()
router := browser.HijackRequests()
router.MustAdd("*", func(ctx *rod.Hijack) {
	ctx.MustLoadResponse()
})
go router.Run()
page := browser.MustPage("")
page.MustNavigate("https://www.google.com/recaptcha/api2/demo")
time.Sleep(50000 * time.Second)
```

**What you got**
The recaptcha got error
**What you expected to see**
The recaptcha can normally solve

**Comment by ysmood** [comment]
If you want to transparently handle requests, you should code like this:

```go
router.MustAdd("*", func(ctx *rod.Hijack) {
	ctx.ContinueRequest(&proto.FetchContinueRequest{})
})
```

**Comment by ysmood** [comment]
Also check #395

**Comment by musicyin** [comment]
> If you want to transparently handle requests, you should code like this:
> 
> ```go
> router.MustAdd("*", func(ctx *rod.Hijack) {
> 	ctx.ContinueRequest(&proto.FetchContinueRequest{})
> })
> ```

How can I get the response of it ?

I have try
		ctx.ContinueRequest(&proto.FetchContinueRequest{})
		fmt.Println(&proto.FetchGetResponseBody{})
		fmt.Println(ctx.Response.Body())
but it only have empty response

Thank you.

**Comment by ysmood** [comment]
The cdp protocol is not designed to use hijack every request, you have to filter specific URLs.
This is an upstream issue of chromium, you can ask the chromium team to fix it.

You can do either this:

```go
	router.MustAdd("*index.js", func(ctx *rod.Hijack) {
		ctx.MustLoadResponse()
		fmt.Println(ctx.Response.Body())
	})
```

or this:

```go
	router.MustAdd("*", func(ctx *rod.Hijack) {
		if strings.HasSuffix(ctx.Request.URL().String(), "index.js") {
			ctx.MustLoadResponse()
			fmt.Println(ctx.Response.Body())
		} else {
			ctx.ContinueRequest(&proto.FetchContinueRequest{})
		}
	})
```
