### ISSUE TITLE
how to get network log like selenium driver.get_log("performance")?

### ISSUE THREAD

**Issue by DC3x6** [go-rod/rod#674]
Rod Version: lastest

## 问题描述

在使用过程中，我尝试像selenium一样get_log(),但我只找到LogLogEntry，但是这个结构体并没有Call方法。

**Comment by ysmood** [comment]
FYI https://github.com/go-rod/rod/blob/master/lib/proto/performance_timeline.go

**Comment by ysmood** [comment]
Could you provide some log samples for us to compare?

**Comment by DC3x6** [comment]
get_log() by python selenium:
![log](https://user-images.githubusercontent.com/42593507/183070546-d930a0bd-db1c-4571-ba40-54844811c606.png)
![log1](https://user-images.githubusercontent.com/42593507/183070626-f965e9ec-38d9-4da6-be7d-3ca1eec1b145.png)


in chrome devtools:
![log3](https://user-images.githubusercontent.com/42593507/183070957-ed0a5145-540f-4e0c-92c5-d39f441b9837.png)

**Comment by ysmood** [comment]
Can you try this `go run main.go -rod=cdp`, main.go is your program.

**Comment by DC3x6** [comment]
chat with discord?

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/4710d7f82e7892a0699a5cd124d63e55459ad2ae/lib/cdp/example_test.go#L45-L56

**Comment by ysmood** [comment]
Ask to reopen if it's still not resolved.

**Comment by dtwangquan** [comment]
同问，我也想了解下这个问题

**Comment by DC3x6** [comment]
> 同问，我也想了解下这个问题

搞定了嘛？

**Comment by ysmood** [comment]
@DC3x6 你具体需要哪些数据呢，能否给份 selenium 和 rod 的数据对比。描述下 rod 缺了什么数据
