### ISSUE TITLE
How can we trigger the protocol error of browser ?

### ISSUE THREAD

**Issue by musicyin** [go-rod/rod#675]
Rod Version: v0.108.1

```go
var check = func(v interface{}) {
	err := v.(error)
	if err != nil {
		page.MustEval(`() => {
                 window.location.reload(true);
			}`)
		fmt.Println("ERROR : ", err)
	}
}
		rodlauncher := launcher.New()
			Set("lang", "en").
			Set("disable-web-security").
			Set("allow-running-insecure-content").
			Delete("headless")
		launchers = rodlauncher.MustLaunch()
		browser = rod.New().Trace(true).WithPanic(check).ControlURL(launchers).MustConnect()

```

What you got
"ERR_HTTP2_PROTOCOL_ERROR" ERROR got , doesn't have any error message

What you expected to see
"ERR_HTTP2_PROTOCOL_ERROR" ERROR got , reload the page.

What have you tried to solve the question
Set WithPanic Function to trigger the error message ("ERR_HTTP2_PROTOCOL_ERROR") , but not work

**Comment by ysmood** [comment]
How to reproduce ERR_HTTP2_PROTOCOL_ERROR?
