### ISSUE TITLE
About error propagation on Must chained function implementations

### ISSUE THREAD

**Issue by state303** [go-rod/rod#677]
Rod Version: v0.108.2

## A Question...

Consider one might utilize a Must func chaining...

```go
...
url := "somewhere"

// if using Must chaining...
text := p.MustNavigate(url).MustElement("ul > li").MustText()

// otherwise one might do...
if err := p.Navigate(url); err == nil {
  handleErr(err)
  return
}
elem, err := p.Element("ul > li")
if err != nil {
  handleErr(err)
  return
}
... // on and on... or...

// what if...
text, err := p.MustNavigate(url).MustElement("ul > li").MustText().Do() // Do() will terminate the function call
...

```

I believe that usage of Must chaining already implies that the developer giving up the conciseness on error handling, in exchange of readability.

I looked into some PRs (more specifically for  #428 AND #433); panics can only be handled via panic handler from browser end.

By the nature of the current Must chaining implementation, I imagine a bit of tweaks __could__ keep us away from panic handling, by propagating the initial error. But, again, i assume there has been countless discussions upon this issue.

So... I would like to know whether there is any ongoing discussion behind this issue, or even this being an issue any longer.

Eagerly waiting for response 👍

**Comment by ysmood** [comment]
Check this one: https://github.com/go-rod/rod/issues/166

**Comment by state303** [comment]
@ysmood Thank you! I will look into it 👍

**Comment by state303** [comment]
I do agree on the part where it is more error prone. But still I do believe there could...(?) be a better way.
I will close this issue for now. Hopefully I could bring some useful PR about it.

Thank you!

**Comment by ysmood** [comment]
Sure, I'd really like a better design. I'm looking forward to your ideas 👍🏼
