### ISSUE TITLE
How to disable Taskkill.exe?

### ISSUE THREAD

**Issue by OsKaR82** [go-rod/rod#678]
Hello, I am testing with go-rod and every time the browser is closed, taskkill.exe appears, which closes the entire program, can it be disabled? I don't see it in the documentation. Greetings.
![Taskkill](https://user-images.githubusercontent.com/110895936/183607399-b055edb8-8fb9-4b6e-b3ed-fd8f9ec530f2.jpg)

**Comment by ysmood** [comment]
Disable the leakless:

```go
u := launcher.New().Leakless(false).MustLaunch()
rod.New().ControlURL(u).MustConnect()
```

**Comment by OsKaR82** [comment]
> Leakless

Thank you very much, I didn't see it in the documentation: https://go-rod.github.io/#/contribute-doc

**Comment by ysmood** [comment]
Better to use the IDE to see the doc of methods, not the tutorial website.
