### ISSUE TITLE
How to read the browser clipboard contents

### ISSUE THREAD

**Issue by Craig-Stone** [go-rod/rod#682]
Rod Version: v0.107.3

Our web application has a copy to clipboard button after some generated text to help the user copy/paste that into some configuration settings in their phone.

I'm using rod to test the other functionality of our application and I was trying to figure out if there is a way to obtain the browser clipboard contents to verify that the clipboard button is really working.

So far I'm investigating some javascript of: navigator.clipboard.readText()

This might need some other configuration settings on the browser to enable the functionality.

If I figure out how to do it, I'll update this ticket.

If anyone else has done this before or has any pointers, then please reply to this question.

Much appreciated :)

**Comment by Craig-Stone** [comment]
I have found a site with a demonstration of copying and pasting data to and from the clipboard.
https://googlechrome.github.io/samples/async-clipboard/
I enabled the chrome://flags/#enable-experimental-web-platform-features and performed a test on the live output and it works correctly.  I will try to figure out how to do something similar in rod.

**Comment by ysmood** [comment]
FYI:

```go
	proto.BrowserGrantPermissions{
		Permissions:      []proto.BrowserPermissionType{proto.BrowserPermissionTypeClipboardReadWrite},
		BrowserContextID: browser.BrowserContextID,
	}.Call(browser)
```

**Comment by Craig-Stone** [comment]
To get the clipboard contents I used the following functions:

`val, err = p.page.Eval(`() => { let x = navigator.clipboard.readText(); return x; }`)
text = val.Value.String()
`
This poppped up message requesting permissions.  I'm going to try the browser permissions example above by ysmood and hopefully that will be the full solution.

**Comment by Craig-Stone** [comment]
Current working solution:
After creating a browser and a Page grant permissions with the following:
`	proto.BrowserGrantPermissions{
		Permissions:      []proto.BrowserPermissionType{proto.BrowserPermissionTypeClipboardReadWrite, proto.BrowserPermissionTypeClipboardSanitizedWrite},
		BrowserContextID: browser.BrowserContextID,
	}.Call(browser)
`

NOTE: that the BrowserPermissionTypeClipboardSanitizedWrite was required as well otherwise my copy to clipboard function failed. I needed to copy to clipboard in our web application, then read clipboard contents back independently with rod to ensure our app was working correctly.

Then when getting the clipboard contents back I used the following:
`func ClipboardText(page *rod.Page) (string, error) {
	var (
		err error
		val *proto.RuntimeRemoteObject
	)
	if val, err = page.Eval(`() => { let x = navigator.clipboard.readText(); return x; }`); err != nil {
		return "", err
	}

	return val.Value.String(), nil
}
`

**Comment by Craig-Stone** [comment]
Thank you very much for your assistance in this.  Hopefully the notes above will help someone else needing to perform this same functionality.
