### ISSUE TITLE
默认情况下，当按钮不在可视区域时，是无法点击，一直卡住的

### ISSUE THREAD

**Issue by feeops** [go-rod/rod#684]
Rod Version: v0.108.2

问题说明

默认情况下，如果网页比较长，按钮在网页中是有的，当按钮不在可视区域时，是无法点击，一直卡住的

有办法通过添加chrome浏览器参数解决此问题吗？

或者有变通办法自动先移动那个元素上？

**Comment by ysmood** [comment]
请再读读文档：

https://github.com/go-rod/rod/blob/4710d7f82e7892a0699a5cd124d63e55459ad2ae/element.go#L101-L104

**Comment by ysmood** [comment]
#322
