### ISSUE TITLE
Element dragging in iframe doesn't work

### ISSUE THREAD

**Issue by yeyu12** [go-rod/rod#688]
The dragging of elements in the iframe does not take effect, MustMove can move the cursor, MustDown and MustUp, the right button is valid, and the left button is invalid. Please help me to see what is wrong with the code. thank you very much.

``` go
func Test() {
	laun := launcher.New().
		Headless(false).
		Devtools(true)
	browser := rod.New().ControlURL(
		laun.MustLaunch(),
	).Timeout(3 * time.Minute).Trace(true).NoDefaultDevice().MustConnect().MustIncognito().MustIgnoreCertErrors(true)

	s.MonitorPage()

	page, _ := stealth.Page(browser)

	page.MustNavigate("my url")
	page.MustElementX("//*[@id=\"app\"]/section[1]/div/div/div/div[2]/div[1]/a[1]").MustClick()
	page.MustElementX("//*[@id=\"code\"]").MustClick()
	iframe := s.Page.MustElement("#tcaptcha_iframe").MustWaitVisible().MustFrame()
	iframe.MustElement("#tcaptcha_drag_thumb").MustWaitVisible()

	pt := iframe.MustElement("#tcaptcha_drag_thumb").MustShape().OnePointInside()

	x := page.MustEval(JsGetElementViewX(), "tcaptcha_transform").Str()
	y := page.MustEval(JsGetElementViewY(), "tcaptcha_transform").Str()
	ix := iframe.MustEval(JsGetElementViewX(), "slide").Str()
	iy := iframe.MustEval(JsGetElementViewY(), "slide").Str()
	startWidth := pt.X + 25
	startHeight := pt.Y - 5
	endWidth := 315
	endHeight := 15
	iframe.Overlay(startWidth, startHeight, float64(endWidth), float64(endHeight), "iframe")
	rand.Seed(time.Now().Unix())
	startX := gconv.Float64(x) + gconv.Float64(ix) + gconv.Float64(rand.Intn(30)+45)
	startY := gconv.Float64(y) + gconv.Float64(iy) + gconv.Float64(rand.Intn(30)+15)
	iframe.Mouse.MustMove(startX, startY)
	iframe.Mouse.MustClick("right")
	time.Sleep(3 * time.Second)
	iframe.Mouse.MustMove(startX+50, startY)
	iframe.Mouse.MustUp("left")

	time.Sleep(30 * time.Second)
}

func JsGetElementViewX() string {
	return `(path)=>document.getElementById(path).getBoundingClientRect().left + document.documentElement.scrollLeft`
}

func JsGetElementViewY() string {
	return `(path)=>document.getElementById(path).getBoundingClientRect().top + document.documentElement.scrollTop`
}
```

**Comment by yeyu12** [comment]
Using v0.109.1

**Comment by ysmood** [comment]
Please use the `fixtures/drag.html` page as an example, or we will have some legal issues, such as:

https://github.com/go-rod/rod/blob/2eb3f6671105cf117692d8585135c23a491cbde4/input_test.go#L172-L185

**Comment by yeyu12** [comment]
Can I record the screen for you?

**Comment by ysmood** [comment]
no, please use the `fixtures/drag.html` and write some code to reproduce your issue.

**Comment by yeyu12** [comment]
Here is my implementation     https://github.com/yeyu12/rod-drag-test

**Comment by ysmood** [comment]
Sorry, the sample is too complex, I don't have time to check the full code of it.

One tip, if you want to get the position of an element, use `Element.Shape`:

https://github.com/go-rod/rod/blob/043bc992b0917ecd2cbb54ab5b56b51e686bf076/element.go#L193-L201

**Comment by yeyu12** [comment]
I've got the element's position, and the mouse coordinates are valid, but I just can't move the element. Element click and move code in line 50~54

**Comment by ysmood** [comment]
You can debug with cli flag `-rod=trace`, it will show a fake mouse icon.

**Comment by yeyu12** [comment]
The problem of not being able to slide is because the coordinates of its own positioning are used, resulting in the problem that the mouse cannot be pressed. But now it happens again, the mouse is pressed and moved, but the mouse release code doesn't take effect

**Comment by yeyu12** [comment]
There is no problem in the example I provided, but there is a problem in my actual project.

**Comment by ysmood** [comment]
Have you tried to use `trace` to debug your actual project?
