### ISSUE TITLE
Get Devtools console Network tab information (loaded URLs)

### ISSUE THREAD

**Issue by ryooxxx** [go-rod/rod#689]
Rod Version: latest (0.109.1)

Hello ! First, thanks a lot for your job on this tool !

I would like to get the content (the URLs that get loaded) of the Network tab in the Devtools console (F12 key) when going on a web page.

For instance : navigate on https://www.google.com, what for the page to be fully loaded (I know how to do this), then get the Network tab information / the different requests (the URLs that get loaded) the page made (that's what I don't know how to do).

Could you please provide a working example with https://www.google.com ?

Thanks a lot in advance !

**Comment by ysmood** [comment]
```go
package main

import (
	"fmt"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/proto"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	browser := rod.New().MustConnect()

	router := browser.HijackRequests()

	router.MustAdd("*", func(ctx *rod.Hijack) {
		fmt.Printf("[%s] %s\n", ctx.Request.Type(), ctx.Request.URL().String())

		ctx.ContinueRequest(&proto.FetchContinueRequest{})
	})

	go router.Run()

	browser.MustPage("https://www.google.com/")

	utils.Pause()
}
```

**Comment by ryooxxx** [comment]
Thank you very much ! It's working perfectly ! Have a great day !
