### ISSUE TITLE
page race with search include iframes

### ISSUE THREAD

**Issue by dataflowjs** [go-rod/rod#701]
Rod Version: v0.109.1

Hi, please can you explain how can i do Race to search element include iframes? something like

```go
page.Race().Search("selector").Handle().Search("selector 2").Handle().Do()
```

And ElementVisible include iframes

```go
page.Race().VisibleIncludeIframes("selector").Handle().VisibleIncludeIframes("selector 2").Handle().Do()
```

Its will be very good to find what i need, but at this moment i cant understand how can i do it. :/

**Comment by ysmood** [comment]
We don't support it yet, hope some one can add it, should be pretty simple to implement it.

**Comment by alexferrari88** [comment]
I'd work on it if I could understand what you mean.
What are you trying to accomplish?

**Comment by dataflowjs** [comment]
@alexferrari88 just trying to find element on main page or in iframe to understand next step
the problem is that page.Race() at this moment cant do Search()

**Comment by kvii** [comment]
I've create a PR to fix this.
