### ISSUE TITLE
Support pipe along with websockets

### ISSUE THREAD

**Issue by moredure** [go-rod/rod#702]

**Comment by ysmood** [comment]
What do you mean?

**Comment by moredure** [comment]
@ysmood --remote-debugging-pipe transport for chrome instead of websockets

**Comment by ysmood** [comment]
Could you share the reason why you want to use fd way? fd is not well supported on Windows.

**Comment by moredure** [comment]
Sorry, I just saw that puppeteer skipped than transported as not that big enhancement. I thought maybe it has less number of limitations, but probably I am wrong

**Comment by ysmood** [comment]
Actually with rod, you can easily use it. Because rod allows you to choose what websocket lib you want to use, check this example: 

https://github.com/go-rod/rod/blob/master/lib/examples/custom-websocket/main.go
