### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by seal** [go-rod/rod#703]
Currently can't use a socks5 proxy with example code provided
Errors:
panic: write tcp 127.0.0.1:54724->127.0.0.1:54722: use of closed network connection
or sometimes:
panic: navigation failed: net::ERR_SOCKS_CONNECTION_FAILED

Rod Version: v0.109.3

Proxy works as:
![image](https://user-images.githubusercontent.com/25641834/186701448-41ca8ec8-9181-4eb0-8e5b-7894f3e1b1c3.png)

> Go version: `go version`
go version go1.18.1 windows/amd64
> package version: run `git rev-parse HEAD` inside the repo
660bb46677a59d9964b2967e926a313f04ae1b1b

```golang
func PlaySong(account Account) {
	url := launcher.New().
		Headless(false).
		Set(flags.ProxyServer, "socks5://"+account.Proxy).
		//Proxy(). Have tried Set and Proxy, neither work 
		Delete("use-mock-keychain"). // delete flag "--use-mock-keychain"
		MustLaunch()
	browser := rod.New().ControlURL(url).MustConnect()
	browser.MustIgnoreCertErrors(true)
	defer browser.MustClose()
	go browser.MustHandleAuth(account.ProxyUser, account.ProxyPass)()

	browser.MustPage("http://ip-api.com/json")
	time.Sleep(100 * time.Second)

}
```

**Comment by ysmood** [comment]
Please fix your markdown #322

**Comment by seal** [comment]
@go-rod @everyone

**Comment by seal** [comment]
@go-rod @everyone

**Comment by seal** [comment]
@go-rod @everyone

**Comment by seal** [comment]
@ysmood Please open

**Comment by ysmood** [comment]
Check the chromium doc:

https://chromium.googlesource.com/chromium/src/+/HEAD/net/docs/proxy.md#SOCKSv5-proxy-scheme

> No authentication methods are supported for SOCKSv5 in Chrome (although some do exist for the protocol).

Works fine to me if you don't use `go browser.MustHandleAuth(account.ProxyUser, account.ProxyPass)()`.

The example proxy something like this `mitmproxy --mode socks5`.

**Comment by ysmood** [comment]
A potential solution can be found here: https://github.com/go-rod/rod/issues/305

**Comment by seal** [comment]
```go
	defer func() {
		if cerr := recover(); cerr != nil {
			fmt.Println(cerr)
			fmt.Println(string(debug.Stack()))
		}
	}()

	fmt.Printf("Proxy: %s", account.Proxy)
	px, _ := url.Parse("socks5://" + account.ProxyUser + ":" + account.ProxyPass + "@" + account.Proxy) // auth
	//px, _ := url.Parse("socks5://" + account.Proxy)
	u := launcher.New().RemoteDebuggingPort(9222).Headless(false).MustLaunch()
	browser := rod.New().ControlURL(u).MustConnect()
	defer browser.MustClose()
	page := stealth.MustPage(browser)

	client := &http.Client{
		Timeout:   1 * time.Minute,
		Transport: &http.Transport{Proxy: http.ProxyURL(px)},
	}
	router := browser.HijackRequests()
	router.MustAdd("*", func(ctx *rod.Hijack) {
		err := ctx.LoadResponse(client, true)
		if err != nil {
			fmt.Println(err)
		} else {
			// You can get the response body and all from here
		}
	})

	go router.Run()
	page.HijackRequests()
	page = browser.MustPage("http://www.httpbin.org/ip")
	page.MustWaitIdle()
	time.Sleep(500 * time.Second)
```


Sorted
