### ISSUE TITLE
How to close or disable pop-ups like login prompts?

### ISSUE THREAD

**Issue by oceanchang** [go-rod/rod#713]
Rod Version: v0.109.3

## The code to demonstrate your question

1. Clone Rod to your local and cd to the repository:

   ```bash
   git clone https://github.com/go-rod/rod
   cd rod
   ```

1. Use your code to replace the content of function `TestLab` in file `lab_test.go`.

1. Test your code with: `go test -run TestLab`, make sure it fails as expected.

1. Replace ALL THE CONTENT under "The code to demonstrate your question" with your `TestLab` function, like below:

```go
func TestLab(t *testing.T) {
    g := setup(t)
    g.Eq(1, 2) // the test should fail, here 1 doesn't equal 2
}
```

## What you got

![alt tieba](https://user-images.githubusercontent.com/10527571/189277537-9c554fbb-0dbb-4624-bd4b-faba494c70bc.png "tieba")

When simulating a mouse click operation to turn pages, this kind of login prompt pop-up window will be encountered. 

## What you expected to see

I hope to be able to automatically close various types of pop-up windows that obstruct mouse operations. Is there a good way?

## What have you tried to solve the question

How should I deal with it? Is there sample code?

Searched the previous issue to find the code and tested that it can handle pop-up windows such as alert confirm, which cannot be handled for screenshots

go page.EachEvent(func(e *proto.PageJavascriptDialogOpening) {
		restore := page.EnableDomain(&proto.PageEnable{})
		defer restore()
		_ = proto.PageHandleJavaScriptDialog{
			Accept:     true,
			PromptText: "",
		}.Call(page)
	})()

**Comment by ysmood** [comment]
Do you see the close button on the top right?

```go
page.MustElement(closeButtonCSS).MustClick()
```
