### ISSUE TITLE
macOS M1 Pro使用Docker 远程调试报错

### ISSUE THREAD

**Issue by kingname** [go-rod/rod#715]
Rod版本：v0.109.1
系统版本：macOS Monterey 12.5.1，m1Pro
执行方式：

```bash
docker run --name rod -p 26712:7317 -it ghcr.io/go-rod/rod
```

Go代码：

https://github.com/go-rod/rod/blob/master/lib/examples/launch-managed/main.go

把https://github.com/go-rod/rod/blob/0acf6e25d0c2a200f390001fd55a890f4d15180e/lib/examples/launch-managed/main.go#L20 这一行中填写上`ws://127.0.0.1:26712`

运行后报错，Go这边的报错如下：

<img width="909" alt="image" src="https://user-images.githubusercontent.com/5440523/189574167-bb79c1b2-e6d9-4f58-9fcd-81b6293193f7.png">

Docker中的b报错如下：

<img width="1538" alt="image" src="https://user-images.githubusercontent.com/5440523/189574199-9fc7ed0e-6d24-4b27-b6c7-1518bcf5d9c3.png">

在下载完成浏览器，解压进度到100%的时候报错。

**Comment by kingname** [comment]
来信已收到，我会尽快回复。

**Comment by ysmood** [comment]
Duplicated #268
