### ISSUE TITLE
编译出的windows程序中的leakless.exe会被腾讯电脑管家和360当做病毒程序

### ISSUE THREAD

**Issue by feeops** [go-rod/rod#720]
Rod Version: v0.109.3

## What you got

编译出的windows程序中的leakless.exe会被腾讯电脑管家和360当做病毒程序

## What you expected to see

blank

## What have you tried to solve the question

blank

**Comment by ysmood** [comment]
可以添加 leakless 到白名单吗？

**Comment by rpdg** [comment]
我也遇到类似问题，我使用的是win10自带反病毒。
运行会panic：
`panic: fork/exec D:\TEMP\leakless-0c3354cd58f0813bb5b34ddf3a7c16ed\leakless.exe: Operation did not complete successfully because the file contains a virus or potentially unwanted software.`

目前的临时办法是使用 v0.107附带的 leakless.exe 替换后就正常了。还是希望作者能解决

**Comment by ysmood** [comment]
可以自己编译 leakless，读读 readme ：https://github.com/ysmood/leakless#custom-build-for-goos-or-goarch

**Comment by feeops** [comment]
> 附带的 leakless.exe

附带的 leakless.exe 在哪下载？

**Comment by feeops** [comment]
> 可以添加 leakless 到白名单吗？

技术上是可以的，但比较麻烦，而且打包出来的文件要分发给很多用户去使用，让他们添加白名单也挺麻烦的
能从代码层面解决是最好的

**Comment by ysmood** [comment]
我可以试试修改这块的架构，确实也很 hacky，但目前有些其他事情优先级会更高。

**Comment by hellodword** [comment]
> > 可以添加 leakless 到白名单吗？
> 
> 技术上是可以的，但比较麻烦，而且打包出来的文件要分发给很多用户去使用，让他们添加白名单也挺麻烦的 能从代码层面解决是最好的

语言通病，甚至可能和 go 版本、编译选项等因素都有关系，不建议开源项目为这种问题操心

https://go.dev/doc/faq#virus

商业化可以联系 360 和腾讯申诉

https://open.soft.360.cn/report.php
https://guanjia.qq.com/online_server/lj/

**Comment by ysmood** [comment]
@feeops 类似这样关闭 leakless 还会报错吗？

```go
	u := launcher.New().Leakless(false).MustLaunch()

	browser := rod.New().ControlURL(u).MustConnect()
```

**Comment by feeops** [comment]
> @feeops 类似这样关闭 leakless 还会被当作病毒吗？
> 
> ```go
> 	u := launcher.New().Leakless(false).MustLaunch()
> 
> 	browser := rod.New().ControlURL(u).MustConnect()
> ```

这样程序退出的时候，浏览器还能自动退出吗？

**Comment by aogg** [comment]
+1

**Comment by Fly-Playgroud** [comment]
供还遇到这个问题的人参考：wand（github.com/headlesslab/wand）的代码起点是 go-rod 在 393ac0d 的快照，之后由 headlesslab 独立维护，今天发布的 v0.1.0-rc.1 已经不再有这个问题——leakless 被整体移除，不再向临时目录写入任何可执行文件，也就没有被杀毒软件识别的对象。原来的保证（Launch() 启动的浏览器不会比 wand 进程活得更久）改由操作系统提供：Windows 用 job object，Linux 用父进程终止信号，macOS 用一条 wand 持有的管道，CI 上分别由 TestGuardJobObject、TestGuardPdeathsig、TestGuardTether 验证。https://github.com/headlesslab/wand/releases/tag/v0.1.0-rc.1
