### ISSUE TITLE
Move the mouse according to the curve.

### ISSUE THREAD

**Issue by kvii** [go-rod/rod#722]
Rod Version: v0.109.3

The current "Move" method only uses a "for" loop to increase x and y at each step.

Can we use a Curve interface to abstract it? Then we can use a cubic-bezier curve to control it.

There is an example:

```go
func example(page *Page, x, y float64) {
	page.Mouse.Move(Curves("ease-out", x, y, 100))
}

func (m *Mouse) Move(c Curve) error {
	for c.Next() {
		m.MoveTo(c.Current().Position())
	}
	return nil
}

type Point struct {
	X, Y float64
}

func (p Point) Position() (x, y float64) { return p.X, p.Y }

// create a cubic curve
func Curves(method string, x, y float64, step int) Curve

type Curve interface {
	Next() bool
	Current() Point
}
```

**Comment by ysmood** [comment]
Good idea! Let's keep the interface simple and easy to understand, how about this:

```go
type MouseMovement interface {
	// Next returns the next mouse position, if it returns nil, the movement is done.
	Next() *proto.Point
}
```

**Comment by kvii** [comment]
That means we need to write some code like below:

```go
for {
  cur := c.Next()
  if cur == nil {
    return nil
  }
  // ...
}
```

Or we create the curve points immediately like this?

``` go
// create a cubic curve
func Curve(method string, x, y float64, step int) []*proto.Point
```

**Comment by ysmood** [comment]
Check this new method:

https://github.com/go-rod/rod/blob/0370b6fe230c67a858ff90c99e50cd2b1a959eb2/input.go#L253-L255
