### ISSUE TITLE
是否可获得页面高度

### ISSUE THREAD

**Issue by qq446887609** [go-rod/rod#730]
Rod Version: v0.111.0

## The code to demonstrate your question

该代码只可以获得视窗高度:
``` page.MustGetWindow().Height```

我想获得页面高度 实现鼠标滚动到页面顶部 中部 底部

**Comment by ysmood** [comment]
可以执行 js 获取

**Comment by qq446887609** [comment]
> 可以执行 js 获取，google 一下很多方法

感谢提示！豁然开朗
