### ISSUE TITLE
When go rod MustPage a URL.The browser will pop up and activate.How can I run it background?

### ISSUE THREAD

**Issue by feeops** [go-rod/rod#736]
Rod Version: v0.111.0

## The code to demonstrate your question

When go rod MustPage a URL.The browser will pop up and activate.How can I run it background?

中文：
当使用go rod MustPage方法时，浏览器会激活并且抢占前台的窗口，能办法能让它在后台运行吗？

**Comment by ysmood** [comment]
You can use the headless mode to run the page in the background. This is an example that uses a headful browser and a headless browser at the same time:

https://github.com/go-rod/rod/blob/647d5da750671d10232cfbe159871a2aec819bf0/lib/examples/use-rod-like-chrome-extension/main.go

Or maybe you can use `page.MustWindowMinimize()` to hide the window.

**Comment by feeops** [comment]
> 

MustWindowMinimize do not work.

The browser will pop up and activate and minimize.

**Comment by ysmood** [comment]
Then I think you need to use headless mode.
