### ISSUE TITLE
页面填充最大窗口

### ISSUE THREAD

**Issue by qq446887609** [go-rod/rod#741]
Rod Version: v0.111.0

我想获得最大视口
page.setViewport
方法需要指定大小
有没有其他方法

**Comment by ysmood** [comment]
没看懂

**Comment by qq446887609** [comment]
> 没看懂

page页面在高分辨率下无法填充整个浏览器

**Comment by qq446887609** [comment]
> 没看懂

为什么MustPage打开的页面响应式都失效了

**Comment by qq446887609** [comment]
> 没看懂

Puppeteer中 打开 Chromium 自适应窗口大小 可以这样写
(async () => {
    const browser = await puppeteer.launch({
        defaultViewport: null
    })
})();
go-rod的方式是怎么样的

**Comment by ysmood** [comment]
请再读一次教程

https://go-rod.github.io/i18n/zh-CN/#/get-started/README?id=%e4%ba%86%e8%a7%a3%e5%8f%91%e7%94%9f%e4%ba%86%e4%bb%80%e4%b9%88
