### ISSUE TITLE
Failed to override document property

### ISSUE THREAD

**Issue by musicyin** [go-rod/rod#743]
Rod Version: v0.112.0

## The code to demonstrate your question

```go
page.EvalOnNewDocument(`
window.onblur = null;
window.blurred = false;

document.hasFocus = function () {return true;};
window.onFocus = function () {return true;};

Object.defineProperty(document, "hidden", { value : false});
Object.defineProperty(document, "mozHidden", { value : false});
Object.defineProperty(document, "msHidden", { value : false});
Object.defineProperty(document, "webkitHidden", { value : false});
Object.defineProperty(document, 'visibilityState', { get: function () { return "visible"; } });

document.onvisibilitychange = undefined;

for (event_name of ["visibilitychange",
                    "webkitvisibilitychange",
                    "blur", // may cause issues on some websites
                    "mozvisibilitychange",
                    "msvisibilitychange"]) {
  window.addEventListener(event_name, function(event) {
        event.stopImmediatePropagation();
    }, true);
}
	}`)

	err := page.Navigate("file:///C:/Users/Administrator/Desktop/adscore.html")
	if err != nil {
		fmt.Println(err.Error())
	}
	time.Sleep(5 * time.Second)
	page.MustScreenshotFullPage("C:\\b.jpeg")
```

## What you got

document.hasFocus() = false

## What you expected to see

document.hasFocus() = true

## What have you tried to solve the question

use Object.defineProperty to override the property.
When the mouse click on outside of browser , hasFocus() return false
We can test that with chrome command line "--headless=chrome" to know that the function is work or not

The detected page :
https://raw.githubusercontent.com/chris124567/puppeteer-bypassing-bot-detection/master/tests/adscore.html

Is there any way to evalonnewdocument with this js ?
JS : https://github.com/chris124567/puppeteer-bypassing-bot-detection/blob/master/apply-evasions.js

Because of the stealth plugin is detected for creepjs and some website

**Comment by ysmood** [comment]
Do you mean `document.hasFocus` cannot be override?

**Comment by musicyin** [comment]
> Do you mean `document.hasFocus` cannot be override?

yes , it seem that can override on puppeteer

**Comment by musicyin** [comment]
is there any solution of it?

**Comment by musicyin** [comment]
I worked well with puppeteer with this code
`                await page.evaluateOnNewDocument(() => {
                    Object.defineProperty(Document.prototype, "hasFocus", {
                        value: function hasFocus(document) {
                            return true;
                        },
                    });
                    Object.defineProperty(Document.prototype, "hidden", {
                        get: () => false,
                    });
                    Object.defineProperty(Document.prototype, "visiblityState", {
                        get: () => "visible",
                    });
                    Object.defineProperty(BarProp.prototype, "visible", {
                        get: () => true,
                    });
                    Object.defineProperty(Document.prototype, "onvisiblitychange", {
                        set: (params) => function () {
                        },
                    });
                    Object.defineProperty(window, "alert", {
                        value: function alert(parameter) {
                            return undefined;
                        },
                    });
                });`

But go-rod not.. It is a bug?

**Comment by ysmood** [comment]
your js has syntax error
