### ISSUE TITLE
About the case of go-rod saving cookies for a certain website

### ISSUE THREAD

**Issue by cplasfwst** [go-rod/rod#757]
Rod Version: v0.112.0
Dear go-rod developer team, hello
First of all, thank you very much for developing such a good third-party library, which is very helpful to me
, but now I encounter a problem, maybe I am also a newcomer, but I have used chromedp before, and now I have changed to use go-rod, I will not save the cookies of the current page data, how to save all cookies? Is there a case that I can refer to?

**Comment by ysmood** [comment]
[Search the issues](https://github.com/go-rod/rod/blob/master/lib/examples/compare-chromedp/cookie/main.go)
