### ISSUE TITLE
How do you call back DOM events?

### ISSUE THREAD

**Issue by a234146540** [go-rod/rod#758]
[DOM.attributeModified](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-attributeModified)
[DOM.attributeRemoved](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-attributeRemoved)
[DOM.characterDataModified](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-characterDataModified)
[DOM.childNodeCountUpdated](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-childNodeCountUpdated)
[DOM.childNodeInserted](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-childNodeInserted)
[DOM.childNodeRemoved](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-childNodeRemoved)
[DOM.documentUpdated](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-documentUpdated)
[DOM.setChildNodes](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-setChildNodes)
[DOM.distributedNodesUpdated](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-distributedNodesUpdated) EXPERIMENTAL
[DOM.inlineStyleInvalidated](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-inlineStyleInvalidated) EXPERIMENTAL
[DOM.pseudoElementAdded](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-pseudoElementAdded) EXPERIMENTAL
[DOM.pseudoElementRemoved](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-pseudoElementRemoved) EXPERIMENTAL
[DOM.shadowRootPopped](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-shadowRootPopped) EXPERIMENTAL
[DOM.shadowRootPushed](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-shadowRootPushed) EXPERIMENTAL
[DOM.topLayerElementsUpdated](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-topLayerElementsUpdated) EXPERIMENTAL
Handsome engineers, how can these events be rolled back?
Rod Version: v0.112.0
Chrome 107.0.5304.107

**Comment by ysmood** [comment]
I don't understand what you mean.

**Comment by a234146540** [comment]
I want to call back an event on the DOM. How do I do that in a ROD
`go page.EachEvent(func(e *proto.DOMChildNodeInserted) {
		fmt.Println(e)
	}, func(e *proto.DOMChildNodeCountUpdated) {
		fmt.Println(e)
	})`
there is no any response

**Comment by ysmood** [comment]
Sorry, I still don't understand what are you talking about.
