### ISSUE TITLE
How to get all response data？

### ISSUE THREAD

**Issue by yinziyang** [go-rod/rod#764]
Rod Version: v0.112.2

I try to use `proto.FetchGetResponseBody` to get all response data

but error `-32000 Can only get response body on HeadersReceived pattern matched requests.`

```go
    go page.EachEvent(func(e *proto.FetchRequestPaused) {
        m := proto.FetchGetResponseBody{RequestID: e.RequestID}
        r, err := m.Call(page)
        log.Println("->", r, err)  // -32000 Can only get response body on HeadersReceived pattern matched requests.
    })()
    
    page.Timeout(10 * time.Second).Navigate(url)
```

**Comment by yinziyang** [comment]
I got it

```go
go page.EachEvent(func(e *proto.NetworkResponseReceived) {
    m := proto.NetworkGetResponseBody{RequestID: e.RequestID}
    r, err := m.Call(page)
}
```

**Comment by yangyang5214** [comment]
May be use  **loadingFinished**

- responseReceived

Fired when HTTP response is available.

https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-responseReceived

- loadingFinished

Fired when HTTP request has finished loading.

https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-loadingFinished


--- 
when network is slow, or request  is image url,  use  **responseReceived** response body  will get incomplete picture
