### ISSUE TITLE
Is it possible to listen socket?

### ISSUE THREAD

**Issue by dunaevv** [go-rod/rod#765]
Rod Version: v0.112.0

I have Python code(Playwright):
```
....
page = browser.new_page()
page.on("websocket", on_web_socket)

def on_web_socket(ws):
    """Listen socket"""
    print(f"[*] WebSocket opened: {ws.url}")
    # ws.on("framesent", lambda payload: print(payload))
    ws.on("framereceived", on_data)
    # ws.on("close", lambda payload: print("WebSocket closed"))
```
So, I can go to source and listen socket, can I do the same with go-rod?
Thanks in advance!

**Comment by ysmood** [comment]
Yes, you can do that with Rod, check the proto api:

https://github.com/go-rod/rod/blob/11886f223c0128600fdcf8fd4dbadac91e2f75e6/lib/proto/network.go#L2588-L2589

**Comment by dunaevv** [comment]
> Yes, you can do that with Rod, check the proto api:
> 
> https://github.com/go-rod/rod/blob/11886f223c0128600fdcf8fd4dbadac91e2f75e6/lib/proto/network.go#L2588-L2589
> 
> This the doc about how to use it:
> 
> https://go-rod.github.io/#/events/README

Awesome! Thank u sir!
