### ISSUE TITLE
Docker container takes to much space when scrapying something

### ISSUE THREAD

**Issue by johnniev5** [go-rod/rod#771]
When using docker container to scrapy something, as time goes by, it will take a lot of space, when the space reaches full, the program can not work well, so how to resolve the problem to aviod it? Thanks.

**Comment by johnniev5** [comment]
> Please add a valid `Rod Version: v0.0.0` to your issue. Current version is v0.112.2
> 
> _generated by [check-issue](https://github.com/go-rod/rod/actions/runs/3611788856)_

**Comment by johnniev5** [comment]
All versions are involved

> Please add a valid `Rod Version: v0.0.0` to your issue. Current version is v0.112.2
> 
> _generated by [check-issue](https://github.com/go-rod/rod/actions/runs/3611788856)_

All versions are involved

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/b5d1eebc1a79dcb4a8c32b8eeb4ab6be6f37faf7/lib/launcher/manager.go#L58-L59

Can you provide producible example code?
