### ISSUE TITLE
Missing EvaluateAsDevTools function

### ISSUE THREAD

**Issue by Serizao** [go-rod/rod#775]
Hello, like chromedp i would like too know if `EvaluateAsDevTools`  function (https://github.com/chromedp/chromedp/blob/ac112ec8eaa42607d85f349c75405957ce01d2fe/eval.go#L105-L107) is on the roadmap of project ?

I think it's really interresting for some js function wich only work on devtool context like  getEventListeners

Rod Version: v0.112.3

**Comment by ysmood** [comment]
Rod already supports it:

https://github.com/go-rod/rod/issues/393#issuecomment-824881676
