### ISSUE TITLE
SetCookie and Browser.SetCookie set cookie does not take effect, some troubleshooting and solution ideas

### ISSUE THREAD

**Issue by Fly-Playgroud** [go-rod/rod#777]
Sometimes when the use of `Page.setCookies` and `Browser.SetCookies` does not work, the following troubleshooting measures can be taken:

- Domain field of `Network.CookieParam` must be filled with the same hostName of the URL address you are visiting, not "*"
- Cookie key-value pairs cannot contain special characters, such as hidden spaces, etc. In particular, cookies obtained from some parsing cookie functions often contain hidden spaces and are easily overlooked. You must use `strings.Trim` delete these spaces.
```go
cookies = append(cookies, &proto.NetworkCookieParam{
				Name:   strings.Trim(cookieParts[0], " "),
				Value:  strings.Trim(cookieParts[1], " "),
				Domain: Domain,
				Path:   "/",
			})
```
- When a cookie does not take effect, never ignore the err of `XXX.SetCookie`. You must check whether `err != nil`, or use an API like `XXX.MustSetCookie`, which will throw a panic directly in the case of an invalid cookie.
- You can use the website https://httpbin.org/get to check if cookies are taking effect for simple testing purposes.

**Comment by ysmood** [comment]
👍🏼
