### ISSUE TITLE
Help! unable to effectively use stealth plugin in google meet

### ISSUE THREAD

**Issue by navicstein** [go-rod/rod#784]
Rod Version: v0.112.2

I'm creating a google meet & zoom bot that can join a call & record audio/video files, however, I have limited knowledge on how the stealth plugin  works but somehow google meet blocks the request, I'm pretty sure it's not a stealth plugin problem I think the `rod.New()` removes or blocks meet request in a way I don't understand however everything works fine in `UserMode`  on my machine

but I cant use `UserMode` in a docker environment because google meet expects & physical camera/mic device (I also can fake them with `use-fake-ui-for-media-stream` & `use-fake-device-for-media-stream` because I need to capture tab audio) without any of these devices, meet runs in a "Getting Ready. Loop" [see scrshot](https://www.lifewire.com/thmb/f1_9uN4hONp08GpUOlLxsIO3vz0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/google-meet-getting-ready-loop-58ce99a5aff84327a37b2f4e6e27e685.png)

Im not sure how to go about my issue

This is the error from using Rod on google meet with/without stealth plugin
> #The caller does not have permission

![Screenshot from 2022-12-30 12-34-55](https://user-images.githubusercontent.com/46540492/210068722-c704491b-5763-4b06-9e36-04770e98d662.png)

## The code to demonstrate your question
```go
package main

import (
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/proto"
	"github.com/go-rod/stealth"
)

func main() {

	var (
		url = "https://meet.google.com/wdo-zasj-gif"
		l   *launcher.Launcher

		// i can toggle usermode here
		userMode = false
	)

	if userMode {
		l = launcher.NewUserMode()
	} else {
		l = launcher.New()
	}

	wsUrl := l.
		// TODO: lookup bin path
		Bin("/usr/bin/google-chrome").
		UserDataDir("/tmp/profile").
		Leakless(true).
		Devtools(true).
		Headless(false).
		NoSandbox(true).
		MustLaunch()

	browser := rod.New().
		SlowMotion(time.Second).
		ControlURL(wsUrl).
		NoDefaultDevice().
		MustConnect()

	_ = proto.BrowserGrantPermissions{
		Origin: url,
		Permissions: []proto.BrowserPermissionType{
			proto.BrowserPermissionTypeVideoCapture,
			proto.BrowserPermissionTypeAudioCapture,
		},
	}.Call(browser)

	page := stealth.MustPage(browser)

	// bypass CPS for stealth plugin
	proto.PageSetBypassCSP{Enabled: true}.Call(page)
	proto.PageSetAdBlockingEnabled{Enabled: true}.Call(page)

	page.MustNavigate(url).MustWaitLoad()

	// </fi>
	time.Sleep(time.Hour)
}


```
GRCP calls are blocked in using `rod.New`

**Comment by ysmood** [comment]
I think you don't need stealth for google products.

**Comment by navicstein** [comment]
I agree, I think my issue is about an XY problem.
I also replicated the same problem with puppeteer-stealth plugin and removing `defaultArgs` from the available extension made it work from Nodejs

So I later did some experiments on gitpod and got the same result not really about Rod 😓

I'll investigate more about Google meet timeouts, Tha is for the feedback

**Comment by ysmood** [comment]
This helper might help for debugging:

https://github.com/go-rod/rod/blob/0812d731df266c65ae0728238de6d83241acfe1c/lib/launcher/launcher.go#L328-L329

**Comment by navicstein** [comment]
After weeks of debugging, i was able to solve this problem by using `UserMode` and setting `disable-dev-shm-usage` flag

**Comment by ysmood** [comment]
👍
