### ISSUE TITLE
Element.ShadowRoot panics when ShadowRoots is empty

### ISSUE THREAD

**Issue by pcen** [go-rod/rod#787]
Rod Version: v0.112.3

The following code can panic `panic: runtime error: index out of range [0] with length 0`:

```golang
sr, err := el.ShadowRoot()
```

This is somewhat unexpected since there is a corresponding `MustShadowRoot` method, I expect calling `ShadowRoot` to be safe in panic-safe code. I propose it would make more sense for `ShadowRoot` to check the length of `ShadowRoots` and return an error if the slice is empty.

**Comment by ysmood** [comment]
Yes, it shouldn't panic in this case
