### ISSUE TITLE
Incognito browser on docker image seems not be killed.

### ISSUE THREAD

**Issue by claudioquaglia** [go-rod/rod#795]
Rod Version: v0.112.3

## The code to demonstrate your question
Seems like there's some zombie process left on the browser docker image keeps running after `browser.MustClose()` is called. 

Here's the example code used for the test:
1) Run browser docker image with `docker run --rm -p 7317:7317 ghcr.io/go-rod/rod`
2) Run the snippet:
```go
package main

import (
	"fmt"
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	for range "....." {
		job()
	}

	fmt.Println("done!")

	utils.Pause()
}

func job() {
	l := launcher.MustNewManaged("")

	browser := rod.New().Client(l.MustClient()).MustConnect().MustIncognito()

	fmt.Println(
		browser.MustPage("https://mdn.dev/").MustEval("() => document.title"),
	)

	utils.Sleep(3)

	browser.MustClose()
}

```

## What you got

If you look at the docker stats you will see an increase in memory consumption after each request, and looking at the `top` of the container you will see all zombie chrome processes like in the screenshot:

![image](https://user-images.githubusercontent.com/3089581/216005276-d921a3d2-c443-4c4c-b4c1-b9986cfe568a.png)

## What you expected to see

to don't have the Chrome process running once the `browser.MustClose()` is called.

**Comment by ysmood** [comment]
Because you only close the new tab, not the old one, just run it on you local with headful mode, you will understand:

```go
// Package main ...
package main

import (
	"fmt"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	for range "....." {
		job()
	}

	fmt.Println("done!")

	utils.Pause()
}

func job() {
	l := launcher.MustNewManaged("")

	mainBrowser := rod.New().Client(l.MustClient()).MustConnect()

	browser := mainBrowser.MustIncognito()

	fmt.Println(
		browser.MustPage("https://mdn.dev/").MustEval("() => document.title"),
	)

	utils.Sleep(3)

	mainBrowser.MustClose()
}
```

https://user-images.githubusercontent.com/1415488/216010629-0728c247-ac77-413b-80a6-4ade54be796c.mp4
