### ISSUE TITLE
How to check if an element is disabled?

### ISSUE THREAD

**Issue by Jacobinski** [go-rod/rod#798]
Rod Version: v0.112.3

# Question

Is there a recommended way to check if an `Element` is disabled? The way that Playwright [1] does it is by calling `elementHandle.isDisabled()` but there doesn't appear to be a simple equivalent in go-rod.  

The simplest way that I can think of to check if an element is disabled feels very hacky:

```go
b := page.MustElement("button")
if _, err := b.Attribute("disabled"); err != nil {
   // Throws an error if "disabled" is not a valid attribute
} else {
  // "disabled" is a valid attribute.
}

```

[1] https://playwright.dev/docs/api/class-elementhandle#element-handle-is-disabled

**Comment by ysmood** [comment]
Better to read this doc：

https://pkg.go.dev/github.com/go-rod/rod#Element.Property

Could you use this method to make a PR to add a equivalent method as isDisabled?

**Comment by Jacobinski** [comment]
Thanks for the pointer to the Attribute vs Property discussion.  I'll send a PR for adding `Disabled()` to the codebase. Please let me know if you would prefer it to be `isDisabled()`.
