### ISSUE TITLE
Correct way to choose an <option> in <select> element

### ISSUE THREAD

**Issue by petros789** [go-rod/rod#80]
I am able to read the `<option>` values of a `<select>` element but I am confused on the correct way to choose a specified `<option>` element using Rod. 

Here is an example code that reads the text values of the option elements and tries to click on the correct one, though the `elem.Click()` doesn't seem to be the correct solution.

```
for _, elem := range page.ElementsX(`//select//option`) {
	if elem.Text() == "correct reponse" {
		elem.Click()
	}
}
```

**Comment by ysmood** [comment]
I think you want to use `elem.Property("value")`

**Comment by ysmood** [comment]
You can also try `elem.Property("selectedIndex").Int()`, depends on what you want to do.

**Comment by ysmood** [comment]
For `Text()` it's pretty clear, it will return what you see on web UI. For example:

```html
<select>
<option value="a">Hey</option>
</select>
```

You see `Hey`, not the value `a`:

<img width="90" alt="Screen Shot 2020-06-28 at 16 20 41" src="https://user-images.githubusercontent.com/1415488/85941049-53f5c680-b95b-11ea-8f12-8fb5a4af4e7e.png">

**Comment by petros789** [comment]
I do want to see the value `Hey` in the above example, so I'm using the `Text()` on purpose currently. My question revolves around how do I choose an `<option>` element from a set of them. For example, If there are multiple elements in the `<select>`:

```
<select>
<option selected="selected">Current selection</option>
<option>Hey</option>
<option>Correct value</option>
</select>
```

How would I go about choosing the `<option>correct value</option>`?

**Comment by ysmood** [comment]
Maybe you want to use `elem.Select("Correct value")` to select:

https://github.com/go-rod/rod/blob/24e77a63a055f4b2686ea48396eeeee08ad84320/element_test.go#L101-L108

**Comment by petros789** [comment]
That worked! Thank you so much for the help!

**Comment by danieldids** [comment]
I've just discovered go-rod and I find it much much easier to work with than chromedp. That said, in my opinion, the documentation for (Must)Select is not clear to say that you should select an option based on its text contents, and not on it's properties or id for instance. I was trying hard with things like
```page.MustElement(`select[id="in_tipo_doc"]`).MustSelect(`option[value=1]`)```
and many other variants of this idea, and nothing was working.

One thing to make it even more confusing was that by using ```page.MustElement(`select[id="in_tipo_doc"]`).MustElement(`option[value="1"]`).MustText()``` would yield (correctly) the element text contents, so I was sure the element was being scrapped correctly.

Anyway, I'm happy to have found this thread explaining how to use MustSelect. Brain no hurts more. Me happy again. :-D
