### ISSUE TITLE
How to use "PageRemoveScriptToEvaluateOnNewDocument" ?

### ISSUE THREAD

**Issue by SantoshSah** [go-rod/rod#801]
Rod Version: v0.109.3

## The code to demonstrate your question

```go
proto.PageRemoveScriptToEvaluateOnNewDocument{
			Identifier: "test.js",
		}.Call(loginPage)
```

## What you got

Did not remove `test.js` file

## What you expected to see

Expectation was to remove `test.js` file from browser

## What have you tried to solve the question

I tried to set following identifier:
i) `https://example.com/test.js`
ii) `/test.js`
iii) `test.js`

**Comment by ysmood** [comment]
Please check the doc of `EvalOnNewDocument`, or read the source code of this function:

https://github.com/go-rod/rod/blob/222708196269908577233f6154743e700a960b62/page.go#L624-L638

You can use the helper rod provides:

```go
remove, err := page.EvalOnNewDocument(`console.log('ok')`)

remove() // remove the js
```

**Comment by SantoshSah** [comment]
@ysmood Thank you for the reply. Does it remove only portion of js code or whole js file? I tried to remove js file using above sample code but it did not work. I used like below:

```
remove, err := page.EvalOnNewDocument("test.js")

remove() // remove the js
```
It would be helpful if there could be working example to remove js file.

**Comment by ysmood** [comment]
Could you help to make a PR to update the doc of EvalOnNewDocument, it only accept js source code string, not file path.

**Comment by SantoshSah** [comment]
Sure, i will spin up a PR on weekend. Is there any way to avoid to load a js file by go-rod?

**Comment by ysmood** [comment]
> Is there any way to avoid to load a js file by go-rod?

Search issues
