### ISSUE TITLE
Errors with Windows defender (leakless.exe)

### ISSUE THREAD

**Issue by dracoDevs** [go-rod/rod#802]
Rod Version: v0.112.4

# I get the following error when launching a browser

`fork/exec C:\Users\User\AppData\Local\Temp\leakless-0c3354cd58f0813bb5b34ddf3a7c16ed\leakless.exe: Operation did not complete successfully because the file contains a virus or potentially unwanted software.`

This practically makes it impossible to make a production product using `go-rod`, I am interested in possible solutions to this error that can be done with code as opposed to requesting my users to manually whitelist the file.

# More control over installation location .etc

In addition, when installing chrome if a user does not have chrome installed, is there a better way to control where the file is installed so I can control the use of the file in production?

I think it would be wise to allow more control to the user for said operations so we can better optimize the package for production ready products.

**Comment by ysmood** [comment]
Yes, rod already allows you to control where to install, please check the launcher API:

https://github.com/go-rod/rod/blob/0d0e59e419b7cd7d31fb6fa773fbef9511727267/lib/launcher/browser.go#L75

About virus part, please search issues before asking.
