### ISSUE TITLE
When refreshing the websocket connection, rod.NewManager  disconnect and exit

### ISSUE THREAD

**Issue by Fly-Playgroud** [go-rod/rod#809]
I use rod.NewManager to remotely call chrome. I found that rod.NewManager will use `Launch ws://127.0.0.1:4398/devtools/browser/801d6b17-38ce-4890-8931-01fba360687c` local websocket link to launch chrome. 

But when I replace 127.0.0.1:4398 with the IP and port of the server (`[rod-Remote] listening on: 10.65.7.129:7317`) ws://10.65.7.129:7317* ，I used JS to write a simple page, new a webSocket link ws://10.65.7.129:7317/devtools/page in the simple page, I was able to connect successfully for the first time, but when I refreshed the page again, the rod.NewManager The program will be interrupted and exited, and it will not be able to connect again. 

But when I link ws://127.0.0.1:4398/devtools/page to refresh the page, the connection will succeed again.

I would like to ask why?How to use the server IP and port access to refresh without disconnecting?

我使用 rod.NewManager远程调用 chrome。我发现 rod.NewManager 会使用 `Launch ws://127.0.0.1:4398/devtools/browser/801d6b17-38ce-4890-8931-01fba360687c `  本地websocket 链接去启动 chrome。但是当我将 127.0.0.1:4398 替换成服务器的 (`[rod-Remote] listening on: 10.65.7.129:7317`) 的IP和端口 ws://10.65.7.129:7317* 。
我自己去用 JS 在页面中写了一个简单的 webSocket 链接 ws://10.65.7.129:7317/devtools/page 的时候，第一次能够成功连接，但是当我再次刷新页面时，rod.NewManager 的程序就会中断退出，无法再次连接。但是当我链接 ws://127.0.0.1:4398/devtools/page 刷新页面时，还会再次连接成功。
想请教这是为何？怎样使用服务器IP和端口访问刷新时，才不会断开连接？

```go
	m := launcher.NewManager()

	if !quite {
		m.Logger = log.New(os.Stdout, "", 0)
	}
	servHandler := http.NewServeMux()
	
	if allowAll {
		m.BeforeLaunch = func(l *launcher.Launcher, rw http.ResponseWriter, r *http.Request) {
			if chromePath, hasChrome := launcher.LookPath(); hasChrome {
				l.Bin(chromePath)
			}
		}
		servHandler.Handle("/", m)
	}
	m.APIMapFunc["/login"] = func(l *launcher.Launcher, rw http.ResponseWriter, r *http.Request) {
		if l != nil {
			localTabUrl, err := hawkRemote.GetLoginURl(l.ServiceURL + "/json")
			if err != nil {
				log.Fatal(err)
				return
			}
			remoteTabUrl, _ := url.Parse(localTabUrl)
			remoteTabUrl.Host = opts.Address
			source := strings.Replace(types.LoginPage, "{{WSSURL}}", remoteTabUrl.String(), 1)
			rw.Write([]byte(source))
		}

	}

	l, err := net.Listen("tcp", opts.Address)
	if err != nil {
		utils.E(err)
	}


```

**Comment by ysmood** [comment]
The websocket of RodManager is not cdp protocol, you can't use it like the cdp remote debugging port.

**Comment by Fly-Playgroud** [comment]
I alread solve it
