### ISSUE TITLE
Rod launch hangs with custom Chromium.

### ISSUE THREAD

**Issue by caner-cetin** [go-rod/rod#810]
Rod Version: v0.112.5

## The code to demonstrate your question

Hey.
```go
var (
	_, b, _, _ = runtime.Caller(0)

	// Root contains the root folder path of the project.
	Root = filepath.Join(filepath.Dir(b), "../..")
)

func main() {
launcher := LambdaLaunchString()
fmt.Printf("Launching browser instance with %s", Root+"/opt/chromium/chromium")
defer launcher.Cleanup()
defer launcher.Kill()
u, err := launcher.Launch()
if err != nil {
	panic(err)
}
browser := rod.New().ControlURL(u).MustConnect()
}
```
Indefinitely hangs where LambdaLaunchString is:
```go
func LambdaLaunchString() {
return launcher.New().
		Bin(fmt.Sprintf("%s%s", projectpath.Root, "/opt/chromium/chromium"))
		// omitted
}
```
If I comment out Bin part, it is all fine, but launch indefinitely hangs when I use custom bin.

```go
fmt.Printf("Launching browser instance with %s", Root+"/opt/chromium")
```
prints

![image](https://user-images.githubusercontent.com/92731060/219716426-4c34223d-028b-46f2-8499-33f6884dc5e9.png)

where I clearly have a Chromium bin.

![image](https://user-images.githubusercontent.com/92731060/219716522-136e5750-2245-4196-a307-40c7d9833e1f.png)

Got the Chromium from https://raw.githubusercontent.com/alixaxel/chrome-aws-lambda/master/bin/chromium.br to make it lighweight for AWS, but it just doesnt launch.

## What you got

Cant see any error, just hangs.

## What you expected to see

Launch?

## What have you tried to solve the question

Tried other custom Chromiums too and none of them worked.

**Comment by canercetin-randomguy** [comment]
https://github.com/YoungiiJC/go-rod-aws-lambda Got the Chromium bin from this Dockerfile, and even tho I run an identically Docker container, it indefinitely hangs again inside the container.

**Comment by ysmood** [comment]
chromium.br is for aws lambda, not for normal linux like ubuntu, could you provide your linux info:

```bash
cat /etc/issue
```

**Comment by sethgrid** [comment]
@caner-cetin did you ever get this working? I'm using golang:latest as my base image and when I try to run a test with go-rod it indefinitely hangs for me too. It works when ran outside a container on my mac. But in the container it hangs. 

```
FROM golang:latest

WORKDIR /go/src/app

RUN apt-get update \
    && apt-get -y dist-upgrade \
    && apt-get install -y mariadb-client \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

COPY go.mod go.sum ./
RUN go mod download
COPY . .

# the following calls 
RUN go test ./...
```

My test is basically:
```
	// linux requires headless chrome root user to set --no-sandbox
	l := launcher.New()
	l.NoSandbox(true)
	fmt.Println("**** about to rod.New *******")
	page := rod.New().ControlURL(l.MustLaunch()).MustConnect().MustPage(theURL).MustWaitStable()
	defer page.MustClose()
	fmt.Println("***** Never gets here ***** ")
	// if you are not sure what is going on, you ca
```

I'd really like to get this running; my CI will be :fire: after this

**Comment by caner-cetin** [comment]
For future readers (I know one exists), I suggest you to create another issue. This issue was related with my job, I forgot to give the info, and issue is long long dead now.

**Comment by caner-cetin** [comment]
...
