### ISSUE TITLE
Launcher Set方法无法使用=号

### ISSUE THREAD

**Issue by herozzm** [go-rod/rod#812]
Rod Version: v0.112.5

我需要禁止图片显示，加入了
```go
...
.Set("blink-settings=imagesEnabled", "false")
```
报错，查看代码发现name中不能出现=

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/aba92529f50ff3a5a00f235399ba1dd3cbb04453/lib/launcher/launcher.go#L161-L162

能帮忙优化下文档吗？

在 panic 信息里加个示例：

https://github.com/go-rod/rod/blob/aba92529f50ff3a5a00f235399ba1dd3cbb04453/lib/launcher/launcher.go#L164

如 `panic("you should use something like Set("a", "b"), not Set("a=b") ")`

**Comment by herozzm** [comment]
那我如何设置`Set("blink-settings=imagesEnabled", "false")`这样的格式？
难道要这样写？
`Set("blink-settings", "=imagesEnabled=false")`

**Comment by ysmood** [comment]
是的

https://peter.sh/experiments/chromium-command-line-switches/#blink-settings
