### ISSUE TITLE
Issue with Downloading the File

### ISSUE THREAD

**Issue by vinod-tgm** [go-rod/rod#813]
Rod Version: v0.112.6

```go
package main

import (
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	l, _ := launcher.New().Set("disable-web-security").
		Set("disable-setuid-sandbox").
		Set("no-sandbox").
		Set("no-first-run", "true").
		Set("disable-gpu").
		Headless(true).
		Launch()
	browser := rod.New().ControlURL(l).MustConnect()

	page := browser.MustPage("https://www.opentable.com/state-of-industry")
	wait := browser.MustWaitDownload()
	page.MustElement("#mainContent > main > section:nth-child(2) > div:nth-child(4) > div.LC0YAkArXSRfpdP5lcLk > button > div").MustClick()
	_ = utils.OutputFile("t.csv", wait())
}
```
The Program get Struck at OutputFile generation.

**Comment by ysmood** [comment]
```go
page.MustElementR("button", "Download dataset").MustWaitStable().MustClick()
```

**Comment by vinod-tgm** [comment]
I am facing an issue while running the code on an amazon Linux machine. Can you suggest a way to overcome this?

**Error Info:**
panic: [launcher] Failed to launch the browser, the doc might help https://go-rod.github.io/#/compatibility?id=os: /home/ec2-user/.cache/rod/browser/chromium-1095419/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0x796b40?, 0xc000022f90?})
        /home/ec2-user/go/pkg/mod/github.com/go-rod/rod@v0.112.6/lib/utils/utils.go:65 +0x25
github.com/go-rod/rod.genE.func1({0xc000022fa0?, 0x0?, 0x0?})
        /home/ec2-user/go/pkg/mod/github.com/go-rod/rod@v0.112.6/must.go:36 +0x5a
github.com/go-rod/rod.(*Browser).MustConnect(0xc0000a6900)
        /home/ec2-user/go/pkg/mod/github.com/go-rod/rod@v0.112.6/must.go:51 +0x89
main.main()
        /home/ec2-user/opentable/main.go:19 +0x12d
exit status 2

**Comment by Vedvund** [comment]
@vinod-tgm Wait for the file to be downloaded.
```
package main

import (
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
	"log"
	"time"
)

func main() {
	l, _ := launcher.New().
		Set("disable-web-security").
		Set("disable-setuid-sandbox").
		Set("no-sandbox").
		Set("no-first-run").
		Set("disable-gpu").
		Headless(true).
		Launch()

	browser := rod.New().ControlURL(l).MustConnect()
	defer browser.MustClose()

	page := browser.MustPage("https://www.opentable.com/state-of-industry")
	button := page.MustElement("#mainContent > main > section:nth-child(2) > div:nth-child(4) > div.LC0YAkArXSRfpdP5lcLk > button > div > span")

	download := browser.MustWaitDownload()
	time.Sleep(time.Second * 5) // wait for download to complete
	button.MustClick()

	err := utils.OutputFile("t.csv", download())
	if err != nil {
		log.Fatalln("Error", err)
	}
}
```
