### ISSUE TITLE
win 安装报错: 404 Not Found

### ISSUE THREAD

**Issue by xiaoxuan6** [go-rod/rod#816]
```
$ go get -u github.com/go-rod/rod
go: downloading github.com/go-rod/rod v0.112.5
go: github.com/go-rod/rod@v0.112.5: verifying module: github.com/go-rod/rod@v0.112.5: checking tree#15558094 against tree#15723956: reading https://goproxy.io/sumdb/sum.golang.org/tile/8/1/237: 404 Not Found
        server response: not found
```

# env
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\goWeb\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\goWeb
set GOPRIVATE=
set GOPROXY=https://goproxy.io
set GOROOT=E:\Go1.18
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=E:\Go1.18\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\goWeb\static\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

**Comment by ysmood** [comment]
你设置了代理

> set GOPROXY=https://goproxy.io/

这个代理向来就不稳定，而且它地址早就换了。请多学习下科学上网。
