### ISSUE TITLE
Pdf creation throws error: -32000 Show invalid printer settings error

### ISSUE THREAD

**Issue by gabguy** [go-rod/rod#824]
Rod Version: v0.112.5

I'm trying to create a PDF file with rod passing it some options:

```golang
package main

import (
        "github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/proto"
)

func main() {
	path, _ := launcher.LookPath()
	u := launcher.New().Bin(path).MustLaunch()
	browser = rod.New().ControlURL(u).MustConnect()
	defer browser.MustClose()
	page, err := browser.Page(proto.TargetCreateTarget{URL: "example"})
	page.WaitLoad()
	top := 25
	pdfOptions := &proto.PagePrintToPDF{
			MarginTop:           &top,
	}
	r, err := page.PDF(pdfOptions) // <-- This is where I'm getting the error
}
```

The error I'm getting is:
-32000 Show invalid printer settings error

There might be an issue with how the margin is being passed to Chromium by rod?
I was using Puppeteer before, and it seems like they pass it as one object of margin and the top, bottom etc. are in it as props.

![image](https://user-images.githubusercontent.com/7655154/222181259-65138ae0-2e45-43e3-aa24-0ef0d2f6195c.png)

Can you please help me figure out what is wrong?

**Comment by ysmood** [comment]
I think it's a bug of chromium, 25 is too large.

The code below works fine to me:

```go
package main

import (
	"io"
	"os"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/proto"
	"github.com/go-rod/rod/lib/utils"
	"github.com/ysmood/gson"
)

func main() {
	page := rod.New().MustConnect().MustPage("https://www.google.com").MustWaitLoad()

	r, err := page.PDF(&proto.PagePrintToPDF{
		MarginTop: gson.Num(3),
	})
	utils.E(err)

	f, err := os.OpenFile("out.pdf", os.O_CREATE|os.O_WRONLY, 0644)
	utils.E(err)
	_, err = io.Copy(f, r)
	utils.E(err)
	f.Close()
}

```

**Comment by gabguy** [comment]
@ysmood Thanks for the fast response.
Is there a source for the range of valid values for the margins somewhere so I can do data validation before invoking the function?

**Comment by gabguy** [comment]
@ysmood Also, are these margins in cm or inches?

**Comment by ysmood** [comment]
> You write "Top margin in inches. Defaults to 1cm (~0.4 inches)" in the docs, so it is a bit confusing if it defaults to inches or cm.

It's not me, it's the chromium team, you can raise an ticket for them to fix it. The doc is generated from here: https://chromedevtools.github.io/devtools-protocol/

**Comment by gabguy** [comment]
@ysmood I found my issue:
I was receiving the margin values as pixels from an external source.
Rod excepts to get those values as inches, this was the problem. I added conversion to inches and everything works fine.
Thanks
