### ISSUE TITLE
点击一个按钮后js向页面写入了一段html代码，如何获取这个元素 

### ISSUE THREAD

**Issue by zk3151463** [go-rod/rod#839]
点击一个按钮后js向页面写入了一段html代码，如何获取这个元素

**Comment by ysmood** [comment]
抱歉没看懂

**Comment by zk3151463** [comment]
比如说我操作一个登陆页面，点击登录后它弹出一个弹窗，如何获取这个弹窗，我用文档里方法一直没有成功

**Comment by zk3151463** [comment]
// Getbrewdir()
	path, _ := launcher.LookPath()
	u := launcher.New().Set("cleanup").Bin(path).Headless(false).MustLaunch()

	page := rod.New().ControlURL(u).Timeout(time.Minute).MustConnect()
	// browser.NoDefaultDevice()
	// page := stealth.MustPage(browser)
	// page.MustWindowMinimize()
	// page1 := page.MustNavigate("https://login.taobao.com/member/login.jhtml?style=mini&newMini2=true&redirectURL=https://myseller.taobao.com/home.htm/QnworkbenchHome/")
	page1 := page.MustPage("https://login.taobao.com/member/login.jhtml?style=mini&newMini2=true&redirectURL=https://myseller.taobao.com/home.htm/QnworkbenchHome/")

	el := page1.MustElement(`#fm-login-id`)
	// el.MustInput("15594981935") //账户
	el.MustInput("33333") //账户
	el1 := page1.MustElement(`#fm-login-password`)
	// el1.MustInput("luoziyun123456") //密码
	el1.MustInput("12121212") //密码

	// 左击
	btn := page1.MustElement(`[type=submit]`)
	btn.MustClick()
	// 等待浏览器处理新内容
	page1.MustWaitRequestIdle()
	// isdl := page1.MustHas("#nc_1_n1z")
	page2, _ := page.Pages()

	page1 = page.MustPages()[0]
	ishua := page2[0].MustHas("#nc_1_n1z")
	fmt.Println(ishua)

	if ishua {
		slider := page1.MustElement("#nc_1_n1z")
		fmt.Println(page1.MustElement("#nc_1_n1z").MustHTML())
		fmt.Println(222)
		fmt.Println(slider.MustShape().Box().Y)
	}
	// fmt.Println(page1.MustHTML())
	// page1 = page.MustNavigate("https://item.upload.taobao.com/sell/merge/category.htm?spm=a21dvs.23580594.0.0.3bc1645ewKrOEF")

	// page1.MustSetCookies()
	fmt.Println("11", *page1.MustCookies()[0])
	time.Sleep(time.Hour)

**Comment by zk3151463** [comment]
package main

import (
	"fmt"
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
)

func main() {
	// Getbrewdir()
	path, _ := launcher.LookPath()
	u := launcher.New().Set("cleanup").Bin(path).Headless(false).MustLaunch()

	page := rod.New().ControlURL(u).Timeout(time.Minute).MustConnect()

	page1 := page.MustPage("https://login.taobao.com/member/login.jhtml?style=mini&newMini2=true&redirectURL=https://myseller.taobao.com/home.htm/QnworkbenchHome/")

	el := page1.MustElement(`#fm-login-id`)
	el.MustInput("33333") //账户
	el1 := page1.MustElement(`#fm-login-password`)
	el1.MustInput("12121212") //密码

	// 左击
	btn := page1.MustElement(`[type=submit]`)
	btn.MustClick()
	// 等待浏览器处理新内容
	page1.MustWaitRequestIdle()
	// isdl := page1.MustHas("#nc_1_n1z")
	page2, _ := page.Pages()

	page1 = page.MustPages()[0]
	ishua := page2[0].MustHas("#nc_1_n1z")
	fmt.Println(ishua)

	if ishua {
		slider := page1.MustElement("#nc_1_n1z")
		fmt.Println(page1.MustElement("#nc_1_n1z").MustHTML())
		fmt.Println(222)
		fmt.Println(slider.MustShape().Box().Y)
	}

	fmt.Println("11", *page1.MustCookies()[0])
	time.Sleep(time.Hour)

}

**Comment by ysmood** [comment]
请仔细读读这个 #322
