### ISSUE TITLE
请问在没有浏览器的服务器上能够使用吗

### ISSUE THREAD

**Issue by 914795561** [go-rod/rod#84]
请问在没有浏览器的服务器上能够使用吗？

**Comment by ysmood** [comment]
当然是可以的，FAQ 里有提到这个问题，如何在 docker 和 rod：

https://github.com/go-rod/rod#q-how-to-use-rod-with-docker

**Comment by 914795561** [comment]
browser.ServeMonitor(":7777"),请问这个的作用是什么呢?

**Comment by ysmood** [comment]
这个 monitor 的原理就是通过播放 screenshot 来监视 headless 模式的浏览器正在干什么，常用于 debug 无头模式。

你远程控制服务器集群里的浏览器，如果想要 debug，这个 monitor 就是用来给你可视化可观看浏览器正在干啥的。

**Comment by 914795561** [comment]
那这个7777端口我该在哪里设置?

**Comment by ysmood** [comment]
这是你用浏览器访问的，浏览器相当于播放器，你按照教程运行 docker 跑一下就知道，非常简单的。

**Comment by ysk229** [comment]
> 当然是可以的，FAQ 里有提到这个问题，docker 和 rod：
> 
> https://github.com/go-rod/rod#q-how-to-use-rod-with-docker

请问一下，这个链接失效，打不开。我需要这样的配置，要不然在headless 模式下，只能后台截图，这样觉得太麻烦了，请问一下，有没有这相关方面的配置啊？？
