### ISSUE TITLE
chromium-1101464 Failed to load Chrome DLL

### ISSUE THREAD

**Issue by msly** [go-rod/rod#846]
Rod Version: v0.112.8

```go
browser := rod.New().Timeout(time.Minute).MustConnect()
```

got error:
panic: [launcher] Failed to get the debug url: [0324/001356.674:ERROR:main_dll_loader_win.cc(109)] Failed to load Chrome DLL from AppData\Roaming\rod\browser\chromium-1101464\chrome-win\chrome.dll

**Comment by ysmood** [comment]
what's your Windows version?

**Comment by r6c** [comment]
me too.

```
panic: [launcher] Failed to get the debug url: [0423/142038.791:ERROR:main_dll_loader_win.cc(109)] Failed to load Chrome DLL from C:\Users\Administrator\AppData\Roaming\rod\browser\chromium-1101464\chrome-win\chrome.dll
```
windows server 2016 datacenter x64

**Comment by ysmood** [comment]
Rod uses github actions' Windows to test, like this one, it uses Windows Server 2022:

https://github.com/go-rod/rod/actions/runs/4738920992/jobs/8413271753

I don't have your version of Windows to test. Could you run chromium on your os without Rod?

**Comment by r6c** [comment]
> Rod uses github actions' Windows to test, like this one, it uses Windows Server 2022:
> 
> https://github.com/go-rod/rod/actions/runs/4738920992/jobs/8413271753
> 
> I don't have your version of Windows to test. Could you run chromium on your os without Rod? I mean try to download chromium from their official site and run it directly.

Like @msly  said, Change to v0.112.6 is OK. chromium running is ok

**Comment by msly** [comment]
> Rod uses github actions' Windows to test, like this one, it uses Windows Server 2022:
> 
> https://github.com/go-rod/rod/actions/runs/4738920992/jobs/8413271753
> 
> I don't have your version of Windows to test. Could you run chromium on your os without Rod? I mean try to download chromium from their official site and run it directly.

chromium-1101464 problem, run directly also report error

**Comment by msly** [comment]
win 10
