### ISSUE TITLE
How can I hide chrome.exe command window

### ISSUE THREAD

**Issue by merdw** [go-rod/rod#854]
Rod Version: v0.112.8

I want to hide chrome.exe command prompt window in headless mode. I search it but nothing.

I found solution for c# selenium like this:
```
var chromeDriverService = ChromeDriverService.CreateDefaultService();
chromeDriverService.HideCommandPromptWindow = true;
return new ChromeDriver(chromeDriverService,  new ChromeOptions());
```

How can I hide like this in Rod?

**Comment by ysmood** [comment]
Is't a common golang problem, search the golang build flag: `-ldflags "-H=windowsgui"`

**Comment by merdw** [comment]
I knew this but thats only hide main command line.
`go build -ldflags "-H=windowsgui"`

thanks for single-process flag is worked for me.
