### ISSUE TITLE
How to use http proxy, it is best to give a sample code

### ISSUE THREAD

**Issue by oceanchang** [go-rod/rod#857]
Rod Version: v0.108.1

## The code to demonstrate your question

```go
package main

import (
	"log"
	"time"
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/launcher/flags"
)

func main() {
	http_proxy_url := "http://user:password@ip:port"
	l := launcher.New().Headless(false)
	//l = l.Set(flags.ProxyServer, "socks5://127.0.0.1:9150") 
	l = l.Set(flags.ProxyServer, http_proxy_url)

	controlURL, _ := l.Launch()
	browser := rod.New().ControlURL(controlURL).MustConnect()
	go browser.MustHandleAuth("username", "password")() 
	browser.MustIgnoreCertErrors(true)

	page := browser.MustPage()
	defer page.MustClose()
	err := page.Navigate("https://api.ipify.org")
	if err != nil {
		log.Println(err)
	}
	err = page.WaitLoad()
	if err != nil {
		log.Println(err)
	}

	println(page.MustElement("html").MustText())
	time.Sleep(30*time.Second)
}

```

## What you got

2023/04/08 15:57:47 navigation failed: net::ERR_NO_SUPPORTED_PROXIES
无法访问此网站

网址为 https://api.ipify.org/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。

ERR_NO_SUPPORTED_PROXIES

## What you expected to see

ip address

## What have you tried to solve the question

How to use http proxy, it is best to give a sample code

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/e24573b407a97aa3fa9a295a5f430d931bdae103/examples_test.go#L347-L369

Please google and learn how to use mitmproxy

https://github.com/go-rod/rod/blob/e24573b407a97aa3fa9a295a5f430d931bdae103/examples_test.go#L363

**Comment by oceanchang** [comment]
> 

Thank you, can you add the code that the proxy needs the username and password

**Comment by oceanchang** [comment]
> https://github.com/go-rod/rod/blob/e24573b407a97aa3fa9a295a5f430d931bdae103/examples_test.go#L347-L369
> 
> Please google and learn how to use mitmproxy
> 
> https://github.com/go-rod/rod/blob/e24573b407a97aa3fa9a295a5f430d931bdae103/examples_test.go#L363

thanx
