### ISSUE TITLE
Wait for XHR request to complete

### ISSUE THREAD

**Issue by matt9mg** [go-rod/rod#868]
Rod Version: v0.112.8

## The code to demonstrate your question
```go
upload := page.MustElement("button.upload-files-btn")
upload.MustClick()
wait := page.WaitRequestIdle(5 * time.Second, []string{"https://bestfile.io/upload"}, nil)

wait()

log.Println("here")
```

## What you got
ALL XHR request were not complete where the string matched https://bestfile.io/upload before "here" was printed on the terminal

## What you expected to see
"Here" would be printed after the XHR request was completed

## What have you tried to solve the question
Review documentation and read core code also running

```go
w2 := page.EachEvent(func(sent *proto.NetworkRequestWillBeSent) {
log.Println(sent.Request.URL)
})

w2()
```

After the upload.MustClick() and I cannot see the request url

**Comment by ysmood** [comment]
Read the doc of `WaitRequestIdle`, it can't guarantee there's no more xhr requests.

**Comment by matt9mg** [comment]
Thanks, that is a shame.

What I'll do instead is add a blocking section to access the page until all the success messages appear, placed an example below of how I overcame this just encase anyone else has the same issue

```go
for {
		element, _ := page.Element(`div.success`)

		if element != nil {
			break
		}

		time.Sleep(1 * time.Second)
	}
	
	... continue with rest of code
```

**Comment by ysmood** [comment]
You don't need the for loop, read the doc of `page.Element`.
