### ISSUE TITLE
Unable to play DRM content (Widevine CDM)

### ISSUE THREAD

**Issue by alfonmga** [go-rod/rod#875]
Rod Version: v0.113.0

## The code to demonstrate your question

```go
package rod_test

import (
	"context"
	"fmt"
	"testing"
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
)

func TestRod(t *testing.T) {
	ctx := context.Background()

	l := launcher.
		NewUserMode().
		Context(ctx).
		Bin("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome").
		Headless(false).
		Devtools(true).
		Leakless(true)

	defer l.Kill()

	b := rod.New().Context(ctx).ControlURL(l.MustLaunch()).MustConnect().NoDefaultDevice()
	defer b.MustClose()

	p := b.MustPage("https://open.spotify.com/playlist/37i9dQZF1DWV7cvDzE3MOI")
	defer p.MustClose()

	router := p.HijackRequests()
	defer router.MustStop()
	router.MustAdd("*/license", func(ctx *rod.Hijack) {
		ctx.MustLoadResponse()
		respCode := ctx.Response.Payload().ResponseCode
		if respCode != 200 {
			panic(fmt.Errorf("Widevine HTTP license check failed with code %d url %s", respCode, ctx.Request.URL()))
		}
	})
	go router.Run()

	p.Timeout(7 * time.Second).MustElement("[data-testid='action-bar-row'] [data-testid='play-button'][aria-label^='Play']").MustClick()
	time.Sleep(33 * time.Second)
}
```

_* You must be authenticated on [Spotify](https://open.spotify.com) before running the test._

## What you got

`panic: Widevine HTTP license check failed with code 400 url https://gew1-spclient.spotify.com/widevine-license/v1/audio/license`

## What you expected to see

No errors related to Widevine CDM.

## What have you tried to solve the question

Widevine is updated `chrome://components/`:
![updated widevine](https://github.com/go-rod/rod/assets/9363272/9c395cbb-3bf8-4616-ad2d-e14203527819)

Chrome is updated `chrome://settings/help`:
![updated chrome](https://github.com/go-rod/rod/assets/9363272/760d503a-c414-4ed1-9b3f-3177a4c0741d)

**If I open a new tab and try to play DRM content in the same browser instance launched by Rod, it works.
Same behaviour on the Brave browser.**

**Comment by ysmood** [comment]
Have you tried Chrome?

**Comment by alfonmga** [comment]
> Have you tried Chrome?

Yes, I tried Chrome and Brave browser. Can you reproduce the issue?

**Comment by alfonmga** [comment]
Replacing `ctx.MustLoadResponse()` for `ctx.ContinueRequest(&proto.FetchContinueRequest{})` in the hijacker solved this issue for me.

[This comment issue helped me.](https://github.com/go-rod/rod/issues/672#issuecomment-1205874364)

#395 could have prevented this.

**Comment by ysmood** [comment]
👍🏼
