### ISSUE TITLE
请问是否有页面上下文隔离

### ISSUE THREAD

**Issue by yundmb** [go-rod/rod#882]
Rod Version: v0.113.1
是否可以做到上下文隔离，访问同一个域名，但是设置不同的cookie，是否可以做到相互隔离？

**Comment by ysmood** [comment]
能解释下为什么需要这样做吗？

**Comment by yundmb** [comment]
> 能解释下为什么需要这样做吗？

测试时有这样的需求，我看playwrights是有的，他有一个NewContext的方法，可以做到会话隔离，但是playwrights-go已经很久不更新了，想问下rod是否有这样的功能。

**Comment by ysmood** [comment]
有的 `MustIncognito`

https://go-rod.github.io/i18n/zh-CN/#/browsers-pages
