### ISSUE TITLE
screenshot 图片带有滚动条，应该如何禁用这个行为

### ISSUE THREAD

**Issue by GuoYiJi** [go-rod/rod#885]
你好，我使用官方的 example，screenshot 到图片的行为带有滚动条，请问这个是特性吗？我对比 Puppeteer 是不会有滚动条的
![image](https://github.com/go-rod/rod/assets/13943322/60ec091c-57cc-4a4c-9017-fa03ab48e24b)

**Comment by GuoYiJi** [comment]
我的版本是 v0.113.1
该问题认为在设备设置为 mobile 出现，如 iPhone

**Comment by ysmood** [comment]
[EmulationSetScrollbarsHidden](https://github.com/go-rod/rod/blob/cacd1405f55221dade8f1f6887b015f7c4f8d314/lib/proto/emulation.go#L323)

**Comment by ysmood** [comment]
有兴趣的话可以，提交一个 PR 在 screenshot 的时候默认隐藏 scrollbar
