### ISSUE TITLE
How to dump the dom just like chromium --dump-dom

### ISSUE THREAD

**Issue by m10x** [go-rod/rod#897]
Rod Version: v0.113.3

I want to dump the DOM, after javascript is being executed. Similar to `/usr/bin/chromium --headless --no-sandbox --dump-dom URL`. However using page.MustHTML() is returning the source code without javascript being executed and I'm not able to find another function which does that.

```go
func runHTMLinHeadless(html string) {
	page := rod.New().MustConnect().MustPage("about:blank")
	page.MustSetDocumentContent(html)
	fmt.Println(page.MustHTML())
}
```

**Comment by ysmood** [comment]
`Page.GetResource`

**Comment by ysmood** [comment]
`Page.GetResource`

**Comment by m10x** [comment]
GetResource expects an URL, however I want to pass a html string or use `page.MustSetDocumentContent(html)` just like in the example

**Comment by ysmood** [comment]
```go
func runHTMLinHeadless(html string) {
	page := rod.New().MustConnect().MustPage("about:blank")
	page.MustSetDocumentContent(html).MustWaitStable()
	fmt.Println(page.MustHTML())
}
```

**Comment by m10x** [comment]
Thanks this works flawlessly!
