### ISSUE TITLE
调试代码调用Element方法时总会遇到context deadline exceeded报错

### ISSUE THREAD

**Issue by Will-Liang** [go-rod/rod#900]
Rod Version: v1.2.4

## The code to demonstrate your question

调试代码调用Element方法时总会遇到context deadline exceeded报错。
调用了page.HTML()，理论上可以找到这个元素

**Comment by ysmood** [comment]
https://go-rod.github.io/#/context-and-timeout

**Comment by sqzxcv** [comment]
应该是设置timeout后, 没有cancel
