### ISSUE TITLE
【SetDocumentContent】能像puppeteer一样监听load

### ISSUE THREAD

**Issue by tyouzu1** [go-rod/rod#901]
背景： 我是Nodejs服务迁移到go这边，选了rod，然后因为之前主要逻辑的实现是通过puppeteer的setContent来实现的。html内容内可能有各种url资源加载。所以需要等待一段时间。
```js
 await page.setContent(data.html, { waitUntil: 'load' });
```
问题：转到rod这边后，找到了SetDocumentContent，但是SetDocumentContent没有这种参数，于是就使用了各种等待的方法。
然后发现除了MustWaitLoad，其他的基本都是超时时间，这样等待的话效率上太低，

现状：
SetDocumentContent后MustWaitLoad不能等待资源加载，其他等待方法均为超时等待，MustWaitLoad为监听load。只能说通过拦截请求来实现我要的效果，但怎么都感觉不是最佳实践。

```go
		utils.E(proto.FetchEnable{
			Patterns: []*proto.FetchRequestPattern{
				{URLPattern: "*"},
			},
		}.Call(page))
		go page.EachEvent(func(e *proto.FetchRequestPaused) {
			if e.Request.URL == "http://example.com/" {
				utils.E(proto.FetchFulfillRequest{
					RequestID:    e.RequestID,
					ResponseCode: 200,
					Body:         html,
				}.Call(page))
			} else {
				utils.E(proto.FetchContinueRequest{RequestID: e.RequestID}.Call(page))
			}
		})()

		page.MustNavigate("http://example.com/")
		page.MustWaitLoad()
```

需求：SetDocumentContent能像puppeteer一样去监听load，或者说又什么其他办法可以实现？

**Comment by tyouzu1** [comment]
@ysmood

**Comment by ysmood** [comment]
`page.MustWaitStable()`

**Comment by tyouzu1** [comment]
> page.MustWaitStable()

感谢…本地版本有点低 难怪没找到😭
