### ISSUE TITLE
Touch scroll for a element inside a popup dialog.

### ISSUE THREAD

**Issue by sheldondz** [go-rod/rod#902]
Rod Version: v0.113.4

Currently using Rod for some web scraping activity to understand user reviews for a brand

One of the websites we trying  to scrape  the UI has a button "see all reviews" which popups up a dialog, the listing of reviews inside the dialog is infinite scrollable via touch only to load more reviews.

Wanted to know more on how we can use the touch scroll here to load more reviews.

**Comment by ysmood** [comment]
For example:

```go
page.MustElement('.elem').MustHover()
page.MustScroll(0, 300)
```
