### ISSUE TITLE
Block network request

### ISSUE THREAD

**Issue by lanphan** [go-rod/rod#904]
Hello,

Puppeteer has an awesome feature to block some network requests, so that it can speedup scraping process, you can take a look at 1 example here, I hope you consider to add this feature

https://screenshotone.com/blog/how-to-block-requests-with-puppeteer/

**Comment by ysmood** [comment]
Already supported:

https://go-rod.github.io/#/network/README?id=blocking-certain-resources-from-loading

**Comment by lanphan** [comment]
It's great, thanks so much @ysmood
