### ISSUE TITLE
作者您好，默认下载的是Chromium,可以默认下载chrome的吗？

### ISSUE THREAD

**Issue by AaronChengHao** [go-rod/rod#907]
Rod Version: v0.113.3

作者您好，默认下载的是Chromium,可以默认下载chrome的吗？

**Comment by ysmood** [comment]
可以，自己配置:

https://pkg.go.dev/github.com/go-rod/rod/lib/launcher#Browser

**Comment by AaronChengHao** [comment]
> 可以，自己配置:
> 
> https://pkg.go.dev/github.com/go-rod/rod/lib/launcher#Browser

可以有一个示例吗？不太懂这个要怎么配。😄

**Comment by ysmood** [comment]
示例：

https://github.com/go-rod/rod/blob/e4fc5d874fdada711e29c150bc08580276152aa0/lib/launcher/browser.go#L105
