### ISSUE TITLE
Unable to launch chromium in debian:bullseye-slim docker container

### ISSUE THREAD

**Issue by subash-krishnappa** [go-rod/rod#912]
Rod Version: v0.114.1

Am trying to launch chromium in docker container, have used a dockerFile to download the dependency:

partial content of DockerFile:
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt -y install ./google-chrome-stable_current_amd64.deb

RUN apt -y install chromium

Code snippet to get binary
<img width="445" alt="image" src="https://github.com/go-rod/rod/assets/116137464/e6872a25-7ca9-4b7f-9d32-c4624dce4851">

But i get an error as below
<img width="1257" alt="image" src="https://github.com/go-rod/rod/assets/116137464/23557f2f-d823-47fa-b6c9-31387cdf8b4d">

But the same test when triggered locally works perfectly fine, kindly guide me if thrs any configs that am missing here?

Code to launch chromium:

<img width="524" alt="image" src="https://github.com/go-rod/rod/assets/116137464/16573cff-427d-460f-b7c2-d78f43cc2a08">

**Comment by ysmood** [comment]
Please provide reproducible code.

**Comment by subash-krishnappa** [comment]
<img width="1400" alt="image" src="https://github.com/go-rod/rod/assets/116137464/e861f127-583c-42b9-b701-ba6a2f4293d1">
 I have created a sample project for reproducing the issue, its accessible at: 
 https://github.com/subash-krishnappa/goRodSample

**Comment by ysmood** [comment]
Please check this: https://go-rod.github.io/#/compatibility?id=os

**Comment by subash-krishnappa** [comment]
i did refer to the link provided, and have included the instructions to install chrome, this is my updated docker file:

FROM golang as builder

ARG goproxy="https://proxy.golang.org,direct"
ENV GO111MODULE=on
ENV CGO_ENABLED 0
USER root
WORKDIR /app
COPY go.* ./
ADD . .
RUN apt-get update
RUN apt-get install ca-certificates

RUN go test . -c -o ./rod-test



FROM debian:bullseye-slim

RUN apt-get -y update --allow-unauthenticated -qq -o Acquire::https::Verify-Peer=false -o Acquire::Check-Valid-Until=false
RUN apt-get install -y wget
RUN apt-get update && apt-get install -y \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
#    libgtk-4-1 \
    libnspr4 \
    libnss3 \
    libwayland-client0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxkbcommon0 \
    libxrandr2 \
    xdg-utils \
    libu2f-udev \
    libvulkan1 
 RUN wget --no-check-certificate https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 RUN apt-get install -y ./google-chrome-stable_current_amd64.deb

WORKDIR /app
COPY --from=builder /app .

RUN chmod +x rod-test

ENTRYPOINT [ "./rod-test"]

docker image is built using the command: 
docker buildx build --platform linux/amd64 --tag rod-test:latest . -f ./Dockerfile

But still facing the same error: 
<img width="1404" alt="image" src="https://github.com/go-rod/rod/assets/116137464/4cc700ae-1246-4930-96de-e8e489dc82fa">

Same has been updated in the sample project: 
https://github.com/subash-krishnappa/goRodSample

System ChipSet: Apple M1 PRO

**Comment by ysmood** [comment]
```go
func main() {
    path, _ := launcher.LookPath()
    u := launcher.New().Bin(path).MustLaunch()
    rod.New().ControlURL(u).MustConnect().MustPage("https://example.com")
}
```

**Comment by subash-krishnappa** [comment]
Update the code to look for existing chrome path :
```
package sample

import (
	"context"
	"log"
	"testing"
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/proto"
)

func TestSampleRodSetup(t *testing.T) {

	path, err := launcher.LookPath()
	if err != false {
		log.Println(err)
	}
	debugUrl := launcher.New().
		Bin(path).
		Devtools(false).
		Headless(true).
		Leakless(false).
		NoSandbox(true).
		MustLaunch()
	log.Println(debugUrl)

	browser := rod.New().ControlURL(debugUrl).MustConnect().Context(context.Background())
	browser.SlowMotion(time.Second * 1)
	browser.Trace(true)

	page, pageErr := browser.Page(proto.TargetCreateTarget{URL: "https://www.wikipedia.org/"})
	if pageErr != nil {
		log.Println(pageErr)
	}
	page = page.Timeout(time.Second * 60)
	pageNavErr := rod.Try(func() {
		wait := page.MustWaitNavigation()
		pageInst := page.MustNavigate("https://www.wikipedia.org/")
		log.Println(pageInst)
		if pageInst != nil {
			return
		} else {
			wait()
		}
	})
	if pageNavErr != nil {
		log.Println(pageNavErr)
	}

	page.MustElement("#searchInput").MustInput("earth")
	page.MustElement("#search-form > fieldset > button").MustClick()

	time.Sleep(time.Second * 3)
	page.Close()
	browser.Close()
}
```

Locally it works fine here is the console output
<img width="731" alt="image" src="https://github.com/go-rod/rod/assets/116137464/3331475b-5af2-4571-9fb1-c281af7f79a2">

Docker file contents remains the same:
```
FROM golang as builder

ARG goproxy="https://proxy.golang.org,direct"
ENV GO111MODULE=on
ENV CGO_ENABLED 0
USER root
WORKDIR /app
COPY go.* ./
ADD . .
RUN apt-get update
RUN apt-get install ca-certificates

RUN go test . -c -o ./rod-test

FROM debian:bullseye-slim

RUN apt-get -y update --allow-unauthenticated -qq -o Acquire::https::Verify-Peer=false -o Acquire::Check-Valid-Until=false
RUN apt-get install -y wget
RUN apt-get update && apt-get install -y \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libwayland-client0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxkbcommon0 \
    libxrandr2 \
    xdg-utils \
    libu2f-udev \
    libvulkan1 
 RUN wget --no-check-certificate https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 RUN apt-get install -y ./google-chrome-stable_current_amd64.deb

WORKDIR /app
COPY --from=builder /app .

RUN chmod +x rod-test

ENTRYPOINT [ "./rod-test"]
```

but it still fails in container with the error below:

<img width="1083" alt="image" src="https://github.com/go-rod/rod/assets/116137464/ef5c675e-e966-475c-9ca0-6a5784fcd65f">

**Comment by ysmood** [comment]
Why not just run the chromium on your docker without rod? I think it doesn't matter you use rod or not.

**Comment by subash-krishnappa** [comment]
Does it mean, instead of installing a google-chrome stable, just install chromium & chromium-browser in docker container?
Coz i would still need rod to perform web automation, Please confirm?

**Comment by ysmood** [comment]
It means you have to make sure the chrome work on your OS, not rod.

**Comment by subash-krishnappa** [comment]
This issue stands resolved, Thanks @ysmood for your inputs..
Final code changes:

```
FROM golang as builder

ARG goproxy="https://proxy.golang.org,direct"
ENV GO111MODULE=on
ENV CGO_ENABLED 0
USER root
WORKDIR /app
COPY go.* ./
ADD . .
RUN apt-get update
RUN apt-get install ca-certificates

RUN go test . -c -o ./rod-test

FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y wget 

RUN wget --no-check-certificate https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb --fix-missing; apt-get -fy install
RUN apt-get -y install chromium

WORKDIR /app
COPY --from=builder /app .

RUN chmod +x rod-test

ENTRYPOINT [ "./rod-test"]
```

```package sample

import (
	"log"
	"testing"
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
)

func TestSampleRodSetup(t *testing.T) {

	path, _ := launcher.LookPath()
	log.Println(path)
	debugUrl := launcher.New().
		Bin(path).
		Devtools(false).
		Headless(true).
		Leakless(true).
		NoSandbox(true).
		RemoteDebuggingPort(9222).
		Proxy(""). //provide your org proxy address here
		MustLaunch()
	log.Println(debugUrl)

	browser := rod.New().ControlURL(debugUrl)
	browser.SlowMotion(time.Second * 1)
	browser.Trace(true)

	page := browser.MustConnect().MustIgnoreCertErrors(true).MustPage("https://www.wikipedia.org/")

	page.MustElement("#searchInput").MustInput("earth")
	page.MustElement("#search-form > fieldset > button").MustClick()

	time.Sleep(time.Second * 3)
	page.Close()
	browser.Close()
}
```
