### ISSUE TITLE
DATA RACE in WaitStable

### ISSUE THREAD

**Issue by jvegaseg** [go-rod/rod#913]
Rod Version: v0.114.1

From time to time, there is a data race warning within internal rod code:

`WARNING: DATA RACE
Write at 0x00c000b3ef18 by goroutine 170984:
  github.com/go-rod/rod.(*Page).getJSCtxID()
      /root/go/pkg/mod/github.com/go-rod/rod@v0.114.1/page_eval.go:339 +0x797
  github.com/go-rod/rod.(*Page).ensureJSHelper()
      /root/go/pkg/mod/github.com/go-rod/rod@v0.114.1/page_eval.go:248 +0x52
  github.com/go-rod/rod.(*Page).formatArgs()
      /root/go/pkg/mod/github.com/go-rod/rod@v0.114.1/page_eval.go:233 +0x338
  github.com/go-rod/rod.(*Page).evaluate()
      /root/go/pkg/mod/github.com/go-rod/rod@v0.114.1/page_eval.go:149 +0x5a
  github.com/go-rod/rod.(*Page).Evaluate()
      /root/go/pkg/mod/github.com/go-rod/rod@v0.114.1/page_eval.go:128 +0x57
  github.com/go-rod/rod.(*Page).WaitLoad()
      /root/go/pkg/mod/github.com/go-rod/rod@v0.114.1/page.go:731 +0x244
  github.com/go-rod/rod.(*Page).WaitStable.func1()
      /root/go/pkg/mod/github.com/go-rod/rod@v0.114.1/page.go:698 +0x46
  github.com/go-rod/rod/lib/utils.All.func1()
      /root/go/pkg/mod/github.com/go-rod/rod@v0.114.1/lib/utils/utils.go:164 +0x72
  github.com/go-rod/rod/lib/utils.All.func2()
      /root/go/pkg/mod/github.com/go-rod/rod@v0.114.1/lib/utils/utils.go:168 +0x47

Previous read at 0x00c000b3ef18 by goroutine 170985:
  github.com/go-rod/rod.(*Page).Context()
      /root/go/pkg/mod/github.com/go-rod/rod@v0.114.1/context.go:58 +0x7a
  github.com/go-rod/rod.(*Page).WithCancel()
      /root/go/pkg/mod/github.com/go-rod/rod@v0.114.1/context.go:84 +0x10f
  github.com/go-rod/rod.(*Page).WaitRequestIdle()
      /root/go/pkg/mod/github.com/go-rod/rod@v0.114.1/page.go:604 +0x37a
  github.com/go-rod/rod.(*Page).WaitStable.func2()
      /root/go/pkg/mod/github.com/go-rod/rod@v0.114.1/page.go:703 +0x5c
  github.com/go-rod/rod/lib/utils.All.func1()
      /root/go/pkg/mod/github.com/go-rod/rod@v0.114.1/lib/utils/utils.go:164 +0x72
  github.com/go-rod/rod/lib/utils.All.func2()
      /root/go/pkg/mod/github.com/go-rod/rod@v0.114.1/lib/utils/utils.go:168 +0x47`

My code which generates this warning is this (after navigating to a web page):

`err := rod.Try(func() {
		b.Page.Timeout(options.Timeout).WaitStable(1 * time.Second) // Estable durante 1 segundos
	})`

This issue seems to be related only to internal code of rod.

**Comment by ysmood** [comment]
Could you provide full code to reproduce it?

**Comment by ysmood** [comment]
Could you try the latest version, see if it was fixed?
