### ISSUE TITLE
Rod lose connection with pages after wake up from a few seconds sleeping of Macbook Ari

### ISSUE THREAD

**Issue by Databingo** [go-rod/rod#921]
Rod Version: v0.114.2

First of all, wonderful work of rod! 

## The question

I have a problem that when I close my MacBook Air laptop for a while sleeping even a few seconds, then Rod will lose connection with opened Chromium pages.

## The code to demonstrate your question

I have created a binary tool called [Aih](https://github.com/Databingo/aih) that heavily depends on Rod. Aih can communicate with  AI models from the terminal. 

The code is too long so I cannot reduce it, maybe you can try a bit of the released binary.

## What you got

write tcp 127.0.0.1:46438->127.0.0.1:36667: use of closed network connection

## What you expected to see

Work as well as normal after wake up from laptop sleeping.

Thank you very much!

**Comment by Databingo** [comment]
Thanks a lot!

 I understand, and  I have another question: 
After reconnection, could I use the new instance of the browser to execute browser.Pages() to get the previously opened pages

**Comment by ysmood** [comment]
Sure, you can

**Comment by Databingo** [comment]
Thanks! 
I could re-get the page by print the URL out, but cannot operate(Navigate or Activate no reaction) the page.
```
pages := browser.MustPages()
	for _, p := range pages {
		url := p.MustInfo().URL
		if strings.HasPrefix(url, "https://google") {
		fmt.Println(url)
		page_bard = p
		page_bard.MustNavigate("https://baidu.com")}
}
```

Is there anything I missed?

**Comment by Databingo** [comment]
I find the answer in this [issue](https://github.com/go-rod/rod/issues/415#issuecomment-837105438):

_... all the ids will be unusable... people will just restart the whole process again._

That's the very explanation, thanks!
