### ISSUE TITLE
HijackRouter 注释说明有冲突

### ISSUE THREAD

**Issue by xujinzheng** [go-rod/rod#926]
> 见字体加粗部分

https://github.com/go-rod/rod/blob/main/hijack.go#L114
// You **can add** new handler even after the "Run" is called.
func (r *HijackRouter) Add(pattern string, resourceType proto.NetworkResourceType, handler func(*Hijack)) error {}

https://github.com/go-rod/rod/blob/main/hijack.go#L184
// Run the router, after you call it, **you shouldn't add new handler** to it.
func (r *HijackRouter) Run() {
     r.run()
}

**Comment by ysmood** [comment]
多谢指正，能帮忙建个 PR 修正这个问题吗？应该删除 `You can add new handler even after the "Run" is called.`
