### ISSUE TITLE
go get rod /leakless/@v/v0.8.0.zip: 403 Forbidden issue

### ISSUE THREAD

**Issue by raintime3** [go-rod/rod#928]
go get -u  github.com/go-rod/rod
go: downloading github.com/ysmood/leakless v0.8.0
github.com/go-rod/rod imports
        github.com/go-rod/rod/lib/launcher imports
        github.com/ysmood/leakless: github.com/ysmood/leakless@v0.8.0: reading https://proxy.golang.org/github.com/ysmood/leakless/@v/v0.8.0.zip: 403 Forbidden
go: upgraded github.com/ysmood/leakless v0.7.0 => v0.8.0: error finding sum for github.com/ysmood/leakless@v0.8.0: github.com/ysmood/leakless@v0.8.0: reading https://proxy.golang.org/github.com/ysmood/leakless/@v/v0.8.0.zip: 403 Forbidden

**Comment by raintime3** [comment]
> Please add a valid `Rod Version: v0.0.0` to your issue. Current version is v0.114.3
> 
> _generated by [check-issue](https://github.com/go-rod/rod/actions/runs/5997490949)_

I attached the version , but the same thing happens

**Comment by ysmood** [comment]
Github CI works fine, it will also download the same leakless, please check your network.

**Comment by raintime3** [comment]
It seems that the company security team is blocking only this library

**Comment by raintime3** [comment]
> Github CI works fine, it will also download the same leakless, please check your network.
> 
> https://github.com/go-rod/rod/actions/runs/5995947131

I don't know why, but it seems that only this library is being blocked by the company's security team. thank you

**Comment by ysmood** [comment]
check the readme of leakless, you can use your own leakless.
