### ISSUE TITLE
如何在劫持中设置请求头？

### ISSUE THREAD

**Issue by OneSeven** [go-rod/rod#929]
Rod Version: v0.114.3

## The code to demonstrate your question

1. Clone Rod to your local and cd to the repository:

   ```bash
   git clone https://github.com/go-rod/rod
   cd rod
   ```

1. Use your code to replace the content of function `TestRod` in file `rod_test.go`.

1. Test your code with: `go test -run TestRod`, make sure it fails as expected.

1. Replace ALL THE CONTENT under "The code to demonstrate your question" with your `TestRod` function, like below:

```go
func TestRod(t *testing.T) {
    g := setup(t)
    g.Eq(1, 2) // the test should fail, here 1 doesn't equal 2
}
```

## What you got

```go
router:= subPage.HijackRequests()
router.MustAdd("*", func(ctx *rod.Hijack) {
	ctx.Request.Req().Header.Add("Referer", "url")
	ctx.ContinueRequest(&proto.FetchContinueRequest{})
})
```

## What you expected to see

上述代码无效

## What have you tried to solve the question

Such as after modifying some source code of Rod you are able to get rid of the problem.

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/issues/322

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/0af5471d5b16a38276cdc6a81c2efc39658f8dbe/hijack_test.go#L46C40-L46C40

https://github.com/go-rod/rod/blob/0af5471d5b16a38276cdc6a81c2efc39658f8dbe/hijack_test.go#L66-L67
