### ISSUE TITLE
Is rod thread-safe?

### ISSUE THREAD

**Issue by diegobernardes** [go-rod/rod#93]
**Rod Version:** 7954ba514ca38088ccd6c0042cfffffc4635c382

## To Reproduce
`go test -race ./...`

I really like rod and want to change from chromedp to it, but the race conditions are a deal-breaker for me. All my tests are failing because of it.

**Comment by ysmood** [comment]
When I use chromedp, I also face race condition problems, maybe you just don't know the best practice to prevent race condition when using rod. Can you show me some samples?

Here's an issue on chromedp, the author said it it's not thread safe: https://github.com/chromedp/chromedp/issues/541

**Comment by ysmood** [comment]
Due to the nature of chrome (it hold tons of internal private states), I feel it's impossible to make a driver thread-safe, even the official maintained puppeteer.js doesn't support thread-safe.

**Comment by ysmood** [comment]
The only part we guarantee thread-safe is here: https://github.com/go-rod/rod/tree/master/lib/cdp

**Comment by ysmood** [comment]
BTW, it's very easy to let rod's `test -race` work without a problem. Just let each test use its own page. Now we are sharing a single page for all tests. The reason for that is because github CI doesn't have infinite memory for free users, especially the Windows CI will crash if we abuse it too much 😂 , hope you can understand.

**Comment by diegobernardes** [comment]
Thanks for the clarification. About the example, at the first moment, I thought that the problem was with my code but I took extra care to avoid any kind of shared state and if you take a small snippet from the rod repository and turn on the race detection without any kind of concurrency on the user side it's still possible to see the race condition happening.

```
➜  sample go run -trimpath main.go
Git is the most widely used version control system.
➜  sample go run -trimpath -race main.go
==================
WARNING: DATA RACE
Write at 0x00c0003e00d0 by main goroutine:
  runtime.closechan()
      runtime/chan.go:335 +0x0
  github.com/go-rod/rod/lib/launcher.(*Launcher).getURL.func1()
      github.com/go-rod/rod@v0.43.1/lib/launcher/launcher.go:347 +0x50
  github.com/go-rod/rod/lib/launcher.(*Launcher).getURL()
      github.com/go-rod/rod@v0.43.1/lib/launcher/launcher.go:367 +0x408
  github.com/go-rod/rod/lib/launcher.(*Launcher).LaunchE()
      github.com/go-rod/rod@v0.43.1/lib/launcher/launcher.go:304 +0x4f9
  github.com/go-rod/rod.(*Browser).ConnectE()
      github.com/go-rod/rod@v0.43.1/browser.go:109 +0x406
  github.com/go-rod/rod.(*Browser).Connect()
      github.com/go-rod/rod@v0.43.1/sugar.go:18 +0x3c
  main.main()
      command-line-arguments/main.go:13 +0x49

Previous read at 0x00c0003e00d0 by goroutine 11:
  runtime.chansend()
      runtime/chan.go:142 +0x0
  github.com/go-rod/rod/lib/launcher.(*Launcher).read.func1()
      github.com/go-rod/rod@v0.43.1/lib/launcher/launcher.go:337 +0x7a
  github.com/ysmood/kit/pkg/utils.Try()
      github.com/ysmood/kit@v0.24.4/pkg/utils/utils.go:140 +0x70
  github.com/go-rod/rod/lib/launcher.(*Launcher).read()
      github.com/go-rod/rod@v0.43.1/lib/launcher/launcher.go:336 +0x81

Goroutine 11 (running) created at:
  github.com/go-rod/rod/lib/launcher.(*Launcher).LaunchE()
      github.com/go-rod/rod@v0.43.1/lib/launcher/launcher.go:297 +0x4b6
  github.com/go-rod/rod.(*Browser).ConnectE()
      github.com/go-rod/rod@v0.43.1/browser.go:109 +0x406
  github.com/go-rod/rod.(*Browser).Connect()
      github.com/go-rod/rod@v0.43.1/sugar.go:18 +0x3c
  main.main()
      command-line-arguments/main.go:13 +0x49
==================
Git is the most widely used version control system.
Found 1 data race(s)
exit status 66
```

```go
package main

import (
	"fmt"
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/input"
)

func main() {
	// Launch a new browser with default options, and connect to it.
	browser := rod.New().Connect()

	// Even you forget to close, rod will close it after main process ends.
	defer browser.Close()

	// Timeout will be passed to all chained function calls.
	// The code will panic out if any chained call is used after the timeout.
	page := browser.Timeout(time.Minute).Page("https://github.com")

	// Resize the window make sure window size is always consistent.
	page.Window(0, 0, 1200, 600)

	// We use css selector to get the search input element and input "git"
	page.Element("input").Input("git").Press(input.Enter)

	// Wait until css selector get the element then get the text content of it.
	text := page.Element(".codesearch-results p").Text()

	fmt.Println(text)

	// Output: Git is the most widely used version control system.
}
```

**Comment by ysmood** [comment]
Seems like a problem of `launcher`, it's the lib we use to launch chrome, it's not the core part of the rod. I will look into it and see how fix it.

**Comment by ysmood** [comment]
Now when I run the translator example with `-race`, no issue anymore:

```bash
$ go run -race ./lib/examples/translator 世界
World
```

**Comment by ysmood** [comment]
Now you can run all tests with `-race`. It's enforced by the CI now:

https://github.com/go-rod/rod/blob/a255b999be7c243c560844d9fe163bf2f36ee3dd/.github/workflows/test.yml#L55
