### ISSUE TITLE
通过ctrl+click打开新页面，原页面waitOpen卡住，通过Pages拿到新页面WaitLoad方法不生效

### ISSUE THREAD

**Issue by OneSeven** [go-rod/rod#930]
Rod Version: v0.114.3

## The code to demonstrate your question

1. Clone Rod to your local and cd to the repository:

   ```bash
   git clone https://github.com/go-rod/rod
   cd rod
   ```

1. Use your code to replace the content of function `TestRod` in file `rod_test.go`.

1. Test your code with: `go test -run TestRod`, make sure it fails as expected.

1. Replace ALL THE CONTENT under "The code to demonstrate your question" with your `TestRod` function, like below:

```go
func TestRod(t *testing.T) {
    g := setup(t)
    g.Eq(1, 2) // the test should fail, here 1 doesn't equal 2
}
```

## What you got

```go
wait := page.MustWaitOpen()
err = page.Keyboard.Press(input.ControlLeft)
if err != nil {
	log.Println(err)
	return
}
el.MustClick()
err = page.Keyboard.Release(input.ControlLeft)
if err != nil {
	log.Println(err)
	return
}
s := wait() //卡住
//pages := browser.Browser().MustPages()
//s=pages[0]
s.MustWaitLoad()  //不适用WaitOpen，调用WatiLoad不生效
log.Println(s.MustInfo().URL, s.MustInfo().Title) //无法获取到信息
```

## What you expected to see

Such as what you want to do.

## What have you tried to solve the question

Such as after modifying some source code of Rod you are able to get rid of the problem.

**Comment by ysmood** [comment]
#322

**Comment by ysmood** [comment]
ctrl+click 是浏览器 UI 层定义的快捷方式，cdp 不支持的。cdp 控制的非 UI 层的自动化。你可以找 chromium 团队问这个问题，这和 rod 无关。
