### ISSUE TITLE
panic: Get "http://127.0.0.1:9222/json/version": dial tcp 127.0.0.1:9222: connect: connection refused

### ISSUE THREAD

**Issue by hrqmonteiro** [go-rod/rod#936]
Code: 

```
package main

import (
	"fmt"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
)

func main() {
	u := launcher.MustResolveURL("")

	browser := rod.New().ControlURL(u).MustConnect()

	fmt.Println(
		browser.MustPage("https://mdn.dev/").MustEval("() => document.title"),
	)
}
```

Error:

```
panic: Get "http://127.0.0.1:9222/json/version": dial tcp 127.0.0.1:9222: connect: connection refused

goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0x7ba080?, 0xc0000a54d0?})
        /home/hrq/.asdf/installs/golang/1.21.0/packages/pkg/mod/github.com/go-rod/rod@v0.114.3/lib/utils/utils.go:68 +0x1d
github.com/go-rod/rod/lib/utils.E(...)
        /home/hrq/.asdf/installs/golang/1.21.0/packages/pkg/mod/github.com/go-rod/rod@v0.114.3/lib/utils/utils.go:74
github.com/go-rod/rod/lib/launcher.MustResolveURL({0x0?, 0x40ea25?})
        /home/hrq/.asdf/installs/golang/1.21.0/packages/pkg/mod/github.com/go-rod/rod@v0.114.3/lib/launcher/url_parser.go:90 +0x66
main.main()
        /home/hrq/go-browser-automation/cmd/main.go:21 +0x26
exit status 2
```

**Comment by ysmood** [comment]
Your code doesn't launch a browser:

https://github.com/go-rod/rod/blob/dfdc6a8cb16b7f22df8e9d1fe3f26807be1c7580/lib/examples/custom-launch/main.go#L11-L22

**Comment by hrqmonteiro** [comment]
> Your code doesn't launch a browser, you should code like this:
> 
> https://github.com/go-rod/rod/blob/dfdc6a8cb16b7f22df8e9d1fe3f26807be1c7580/lib/examples/custom-launch/main.go#L11-L22

Writing exactly like yours, but with `.Headless(false)`:

![image](https://github.com/go-rod/rod/assets/17055027/b6d8afb4-8c1b-42c4-bf9c-4eda629f588d)

**Comment by hrqmonteiro** [comment]
> > Your code doesn't launch a browser, you should code like this:
> > https://github.com/go-rod/rod/blob/dfdc6a8cb16b7f22df8e9d1fe3f26807be1c7580/lib/examples/custom-launch/main.go#L11-L22
> 
> Writing exactly like yours, but with `.Headless(false)`:
> 
> ![image](https://user-images.githubusercontent.com/17055027/265276968-b6d8afb4-8c1b-42c4-bf9c-4eda629f588d.png)

![image](https://github.com/go-rod/rod/assets/17055027/036e23ce-ad01-4168-80fa-dcbac0367850)

**Comment by ysmood** [comment]
Works fine to me, I think you'd better check your network.

**Comment by hrqmonteiro** [comment]
> Works fine to me, I think you'd better check your network.

What do you mean? My network is fine, if it weren't i wasn't able to post here.

It is giving me the error, will someone help me?

**Comment by hrqmonteiro** [comment]
https://github.com/go-rod/rod/assets/17055027/5b9ffd50-0dc1-4acd-9650-75d92253fd8b

It opens the browser then suddenly closes with this error

**Comment by ysmood** [comment]
The output says `navigation failed: net::ERR_ABORTED`, it means network error.
