### ISSUE TITLE
多个rod.Browser可以共用一个launcher嘛

### ISSUE THREAD

**Issue by Nyx2022** [go-rod/rod#937]
Rod Version: v0.114.3

我需要启动多个rod来进行操作，想共用同一个launcher（因为启动太多的chromium，会导致我的电脑很卡，但是单线程运行又感觉太慢），但是当其中一个rod.Browser调用close()之后，新的rod.Browser在使用ControlURL()连接之前的launcher会报以下错误

![image](https://github.com/go-rod/rod/assets/51039208/430ba193-938f-4c05-939e-659a1b11a1ba)

所以想请教一下，rod.Browser能共用同一个launcher吗？

**Comment by ysmood** [comment]
chromium 不支持，这个和 rod 无关
