### ISSUE TITLE
确认下KeepUserDataDir()是否必须紧跟在Set("--user-data-dir", "X")后面

### ISSUE THREAD

**Issue by lakevilladom** [go-rod/rod#938]
Rod Version: v0.0.0

```golang
// 1、
Set("--disk-cache-dir", filepath.Join(path, dir, `Cache`)).
Set("--user-data-dir", filepath.Join(path, dir, `UserData`)).KeepUserDataDir()

//2、

Set("--user-data-dir", filepath.Join(path, dir, `UserData`)).
Set("--disk-cache-dir", filepath.Join(path, dir, `Cache`)).KeepUserDataDir()
```
>确认下,如上 1的情况下KeepUserDataDir()会生效(保存cookie,下次不需登录)，2的情况下不生效
目前我测试情况好像是这样,还是我用法有误,求解答

**Comment by ysmood** [comment]
好像不影响。你读下 KeepUserDataDir 的源代码就懂了，只有几行而已。

https://github.com/go-rod/rod/blob/4527f6d1fc989cbfd6653d5eb9ca31b224a04f9c/lib/launcher/manager.go#L64-L67

**Comment by lakevilladom** [comment]
那就奇怪了，我真实测试的效果就是有影响
没有跟在Set("--user-data-dir", "X")的代码，打开某个网站每次都要登录，但是跟在Set("--user-data-dir", "X")后面就不需要每次登录了

**Comment by ysmood** [comment]
那可能是 chromium 的设计问题，rod 在这块没有任何隐藏操作。

**Comment by lakevilladom** [comment]
是我搞错了，好像代码最后要显式调用 Browser.Close()还是page.Close()才会保存
