### ISSUE TITLE
Bypass headless chrome detection

### ISSUE THREAD

**Issue by Leezj9671** [go-rod/rod#94]
Any code examples? Make it as a built-in function would be great!

Detection page: https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html

**Comment by ysmood** [comment]
Useful link: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-addScriptToEvaluateOnNewDocument

You can use this example to hook every newly opened page, such as solving this [comment](https://github.com/chromedp/chromedp/issues/557#issuecomment-575959455):

https://github.com/go-rod/rod/blob/acfcf7256448c762b6204d436ef2a9afc93a3ebc/examples_test.go#L282-L295

**Comment by ysmood** [comment]
@NormalPunch you are better than me on this, please help to doc.

**Comment by ysmood** [comment]
This is the example, we will close this ticket. If you still have problems, please let us know.

https://github.com/go-rod/rod/blob/master/lib/examples/bypass-detection/main.go

**Comment by 0xhiroki** [comment]
> This is the example, we will close this ticket. If you still have problems, please let us know.
> 
> https://github.com/go-rod/rod/blob/master/lib/examples/bypass-detection/main.go

Looks like this link is invalid. Do we have a new link for this?

**Comment by ysmood** [comment]
> > This is the example, we will close this ticket. If you still have problems, please let us know.
> > https://github.com/go-rod/rod/blob/master/lib/examples/bypass-detection/main.go
> 
> Looks like this link is invalid. Do we have a new link for this?

https://go-rod.github.io/#/emulation?id=prevent-bot-detection

**Comment by 0xhiroki** [comment]
> > > This is the example, we will close this ticket. If you still have problems, please let us know.
> > > https://github.com/go-rod/rod/blob/master/lib/examples/bypass-detection/main.go
> > 
> > 
> > Looks like this link is invalid. Do we have a new link for this?
> 
> https://go-rod.github.io/#/emulation?id=prevent-bot-detection

Thanks!
