### ISSUE TITLE
设置资源超时时间

### ISSUE THREAD

**Issue by GuoYiJi** [go-rod/rod#940]
Rod Version: v0.113.3

你好，请问我办法针对资源请求做一个类似最大超时的挟持吗，类似这段代码
![image](https://github.com/go-rod/rod/assets/13943322/e87653fc-5b03-48b8-88c1-ad4fd542af38)
因为总是会有一些资源的加载比较耗时，超时时间比较依赖浏览器自身
![image](https://github.com/go-rod/rod/assets/13943322/0bf4189b-c3f2-4877-8c49-44ae2fd55639)

**Comment by GuoYiJi** [comment]
好的，谢谢，我尝试看看

**Comment by GuoYiJi** [comment]
> 可以自己设置 http.Client(客户端)，请搜索相关关键字

不好意思啊，我这样设置了并不能生效，而且我搜索了 http.Client 好像没有暴露相关的参数设置
![image](https://github.com/go-rod/rod/assets/13943322/03135065-d50b-409f-bcb9-fa9b5c59a369)

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/50aa3741ce9fd8d9fc201876a4254f961e56c7e8/hijack.go#L224

**Comment by GuoYiJi** [comment]
> `*http.Client`
> 
> https://github.com/go-rod/rod/blob/50aa3741ce9fd8d9fc201876a4254f961e56c7e8/hijack.go#L224

是的，我也尝试过使用这个，但是执行结果依旧没改变，请求依旧不能够超时，或许是我的使用方式不对
![image](https://github.com/go-rod/rod/assets/13943322/00968e19-0f7d-4a85-bf20-7a604d2970c3)

**Comment by ysmood** [comment]
是的，用法不对，请多 google
