### ISSUE TITLE
导出 cdp 的客户端

### ISSUE THREAD

**Issue by ctaoist** [go-rod/rod#945]
想禁用浏览器的缓存，没有这个选项，就想自己设置 cdp 的 [Network.setCacheDisabled](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setCacheDisabled)，看了下源码，cdp client 好像没有导出

作者考虑下导出这个api啊

Rod Version: v0.114.3

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/4527f6d1fc989cbfd6653d5eb9ca31b224a04f9c/examples_test.go#L395-L417
