### ISSUE TITLE
网站无法渲染内容，不知道原因出在什么地方

### ISSUE THREAD

**Issue by herozzm** [go-rod/rod#946]
Rod Version: v0.114.3

这个网站，无法渲染出真实内容：https://ygp.gdzwfw.gov.cn/#/44/new/jygg/v2/D?nodeId=333197075032559616&noticeId=8a7e59498a0c3ab8018a173416f660bb&projectCode=YFHN2023034&bizCode=2831&siteCode=445300&publishDate=20230911150318&source=%E4%BA%91%E6%B5%AE%E5%B8%82%E5%85%AC%E5%85%B1%E8%B5%84%E6%BA%90%E4%BA%A4%E6%98%93%E4%BF%A1%E6%81%AF%E5%8C%96%E5%B9%B3%E5%8F%B0&titleDetails=%E6%94%BF%E5%BA%9C%E9%87%87%E8%B4%AD

里面有个id="noticeArea"的div内容，无法渲染出来，只能得到ajax渲染前面的html内容

**Comment by ysmood** [comment]
WaitStable 也不行吗？

**Comment by herozzm** [comment]
> WaitStable 也不行吗？

不行，我直接time.Sleep 20s都不行

**Comment by ysmood** [comment]
请学些 shadow dom

https://github.com/go-rod/rod/blob/4527f6d1fc989cbfd6653d5eb9ca31b224a04f9c/element.go#L435C25-L435C25

**Comment by herozzm** [comment]
> 请学些 shadow dom
> 
> https://github.com/go-rod/rod/blob/4527f6d1fc989cbfd6653d5eb9ca31b224a04f9c/element.go#L435C25-L435C25

非常感谢
