### ISSUE TITLE
页面池 PagePool 如何对每个单独的Page设置代理？

### ISSUE THREAD

**Issue by wAnFen1017** [go-rod/rod#957]
Rod Version: v0.114.4

1. 我正在利用多页面池 PagePool 做大量url的渲染爬虫。我希望在每个子线程创建Page时使用一个单独的代理IP。我该如何实现？
2. 如果我改成使用浏览器池，BrowserPool是否可以实现每个Browser使用一个代理？ 
3. BrowserPool的性能和PagePool 性能差距大吗？我应该使用哪一个？

**Comment by wAnFen1017** [comment]
> 目前 chromium 不支持

谢谢您的回复！请问对于这种大量url的渲染，如果在不考虑代理的情况下，推荐使用BrowserPool还是PagePool 呀

**Comment by ysmood** [comment]
就看 localStorage， cookie 会不会相互之间干扰，各有优劣。PagePool 可以享受 cache 共享，但页面共享的东西也会相互干扰，比如 cookie。

**Comment by wAnFen1017** [comment]
> 就看 localStorage， cookie 会不会相互之间干扰，各有优劣。PagePool 可以享受 cache 共享，但页面共享的东西也会相互干扰，比如 cookie。

那性能方面呢，差距大吗

**Comment by ysmood** [comment]
那要看具体情况，就好比你问有没有 cache 性能差别大不大一样。

**Comment by wAnFen1017** [comment]
> 那要看具体情况，就好比你问有没有 cache 性能差别大不大一样。

就只是单纯的打开页面渲染返回html然后就结束了。

**Comment by ysmood** [comment]
你可以写个简单的 benchmark 跑一下，我觉得应该差别不大。

**Comment by wAnFen1017** [comment]
> 你可以写个简单的 benchmark 跑一下，我觉得应该差别不大。

PagePool 确实性能非常好，但是对于BrowserPool的实现文档中的例子似乎并不容易理解，我是go的初学者，作者大大能提供更详尽易懂的BrowserPool实现的示例吗

**Comment by ysmood** [comment]
可以的，但请另开一个 issue，你现在的提问已经和标题无关了，这样会误导其他人。
