### ISSUE TITLE
Expanding elements (click) appears to hang the browser?

### ISSUE THREAD

**Issue by jscott-rawnet** [go-rod/rod#967]
Rod Version: v0.114.4

## The code to demonstrate your question

```golang
u := launcher.New().Delete("--headless").Bin(utils.FindChromePath()).MustLaunch()

browser := rod.New().ControlURL(u).MustConnect()
defer browser.MustClose()
browser.DefaultDevice(devices.Clear)

page := browser.MustPage("https://getbootstrap.com/docs/4.3/components/collapse/").MustWaitStable()

toExpand, _ := page.Elements("button[aria-expanded=\"false\"], a[aria-expanded=\"false\"]")
for _, ele := range toExpand {
  err := ele.MustClick()
  if err != nil {
    log.Println(err)
  }
}
```

## What you got

The page will open as expected, it will click the bootstrap version menu at the top of the page and then hang forever. If you resize the browser to make it very narrow, it will suddenly spring back into action, expand everything and close the browser as expected.

## What you expected to see

It click all expanded false elements including scrolling down the page.

## What have you tried to solve the question

Have tried switching to Tap(), different selectors, with and without providing my own browser path via .Bin etc.

**Comment by ysmood** [comment]
Please read the doc of `Click` first:

https://github.com/go-rod/rod/blob/eff7c9785ce2ae78231d5fdce51c32a4e76af2b4/element.go#L102-L105

It say it will wait until the element is interactable, but some of the elements you select are never visible until your window size is changed to mobile width, how can we click a invisible element with your mouse cusor?

The code below should work:

```go
package main

import (
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/defaults"
)

func main() {
	defaults.Show = true
	defaults.Slow = 300 * time.Millisecond
	defaults.Trace = true

	browser := rod.New().MustConnect().NoDefaultDevice()

	page := browser.MustPage("https://getbootstrap.com/docs/4.3/components/collapse/").MustWaitStable()

	toExpand := page.MustElements("button[aria-expanded=\"false\"], a[aria-expanded=\"false\"]")
	for _, ele := range toExpand {
		if !ele.MustVisible() {
			continue
		}

		ele.MustWaitStable().MustClick()
	}
}
```
