### ISSUE TITLE
能否添加一个打开页面后强制等待的方法

### ISSUE THREAD

**Issue by wAnFen1017** [go-rod/rod#969]
Rod Version: v0.0.0

在页面未完全加载完成时这个方法尤为重要，可以避免定位到空值。
类似于playwright中的page.wait_for_timeout()
我尝试了Sleeper，但是并没有像我预期中等待。我现在直接使用time.Sleep()，我不确定在线程中是否安全。

**Comment by ysmood** [comment]
MustWaitStable

**Comment by wAnFen1017** [comment]
> MustWaitStable

我试了使用WaitStable，但是会抛出异常 panic: non-positive interval for NewTicker

**Comment by wAnFen1017** [comment]
非常感谢！
