### ISSUE TITLE
MustClick can't click the element but javascript can

### ISSUE THREAD

**Issue by Greyh4t** [go-rod/rod#970]
Rod Version: v0.114.4

## The code to demonstrate your question

```go
func TestRod(t *testing.T) {
	dir, _ := os.MkdirTemp(os.TempDir(), "userdata*")

	err := rod.Try(func() {
		l := launcher.New().UserDataDir(dir).Leakless(false).Headless(false).Devtools(false)
		defer l.Cleanup()

		u := l.MustLaunch()
		browser := rod.New().ControlURL(u).Timeout(time.Second * 30)

		browser.MustConnect()
		defer browser.MustClose()

		page := browser.MustPage("https://web.vip.miui.com/page/info/mio/mio/checkIn?skipLocal=true&fromPathname=mioGrowth").MustWaitStable()
		defer page.Close()

		ele := page.MustElement(`span[class*="Privacy_btnRight"]`)
		fmt.Println("click start")
		ele.MustClick()
		// if use Eval(), it works
		// page.Eval(`()=>{a=document.querySelector('span[class*="Privacy_btnRight"]');console.log(a);a.click()}`)
		fmt.Println("click end")
		time.Sleep(time.Second * 5)
	})
	if errors.Is(err, context.DeadlineExceeded) {
		t.Error(err)
	}
}
```

## What you got

MustClick() function will hang forever.

```go
ele := page.MustElement(`span[class*="Privacy_btnRight"]`)
ele.MustClick()
```

## What you expected to see

MustClick() should works well

## What have you tried to solve the question

If use javascript, It's works well

```go
page.Eval(`()=>{a=document.querySelector('span[class*="Privacy_btnRight"]');console.log(a);a.click()}`)
```

**Comment by ysmood** [comment]
Check the doc:

https://github.com/go-rod/rod/blob/eff7c9785ce2ae78231d5fdce51c32a4e76af2b4/element.go#L102-L105

Such as if a button is covered by a popup, mouse can never click on it.

**Comment by Greyh4t** [comment]
> Check the doc:
> 
> https://github.com/go-rod/rod/blob/eff7c9785ce2ae78231d5fdce51c32a4e76af2b4/element.go#L102-L105
> 
> Such as if a button is covered by a popup, mouse can never click on it.

But I think the button I want to click is not covered, is there any way to find out what it is covered by?

<img width="938" alt="0" src="https://github.com/go-rod/rod/assets/8017380/77efdc7f-e9d7-4828-a79a-17cf13a59993">

**Comment by ysmood** [comment]
If you run js `document.querySelectorAll('span[class*="Privacy_btnRight"]')` on the page, you will get 2 elements, the first one is invisible, the second one is the one you want to click.

**Comment by Greyh4t** [comment]
> If you run js `document.querySelectorAll('span[class*="Privacy_btnRight"]')` on the page, you will get 2 elements, the first one is invisible, the second one is the one you want to click.

Oh, my fault, I understand, thank you
