### ISSUE TITLE
MustWaitDownload() is not working when element a's target is set to _blank

### ISSUE THREAD

**Issue by Longdexin** [go-rod/rod#971]
Rod Version: v0.114.4

## The code to demonstrate your question

```go
package main

import (
	"log"
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	u := launcher.
		New().
		UserDataDir("user-data-dir").
		Set("disable-blink-features", "AutomationControlled").
		Set("no-first-run").
		Set("disable-default-apps").
		Headless(false).
		MustLaunch()
	browser := rod.New().ControlURL(u).Timeout(time.Hour).Trace(true).MustConnect().NoDefaultDevice()
	defer browser.MustClose()

	page := browser.MustPage("https://file-examples.com/index.php/sample-documents-download/sample-pdf-download/")
	el := page.MustElementR("a", "DOWNLOAD SAMPLE PDF FILE")
	// _, err := el.Eval("(k,v) => this.setAttribute(k,v)", "target", "_self")
	_, err := el.Eval("(k,v) => this.setAttribute(k,v)", "target", "_blank")
	if err != nil {
		log.Fatal(err)
	}
	wait := page.Browser().MustWaitDownload()
	el.MustClick()
	_ = utils.OutputFile("t.pdf", wait())
}
```

## What you got

The code will still wait even after the file has been successfully downloaded by the browser.

## What you expected to see

Why does it happen? How to fix the code in a better way?

## What have you tried to solve the question

1. I met a similar situation this afternoon when I wanted to download a PDF file from some website.
2. I found that, the element a's target was set to _blank. When it was clicked, a new blank page was opened next to the origin one. Then, the file was seen to be downloaded by the browser, but the code waited forever, there was no file in my destination folder.
3. After some searching, I figured out a way to work around this problem by setting the target to _self (look at the commented code above), so that no new page would be opened when the a was clicked.

**Comment by ysmood** [comment]
You are right, seems like a bug of cdp, there's no `page.DownloadWillBegin` event if we use `_blank`, I don't have a clue yet.

You can debug it with `go run main.go -rod=cdp` to view all the events.

**Comment by Longdexin** [comment]
Thanks a lot, I will try the debug later.
