### ISSUE TITLE
Calling docker contaoner chrome from another docker container

### ISSUE THREAD

**Issue by Tomichi** [go-rod/rod#972]
Rod Version:  v0.114.3

Hi, I want report some tricky behavior.

I have two docker containers scrape and chrome,
when I want to connect to chrome container in scrape container via

```go
connectURL := launcher.MustResolveURL("ws://chrome:9222")
browser := rod.New().ControlURL(connectURL).MustConnect()
page := browser.MustPage("https://google.com")
```

I get error dial tcp. When i replace chrome in `launcher.MustResolveURL("ws://chrome:9222")` into IP of docker container
it works.

But I dont want to do DNS lookup request for translate chrome.

Minimal example of broken code is here https://github.com/Tomichi/scrape
When I install ping into scrape repo and run command ping chrome i get correct IP.

 
Thank you for your help.

**Comment by ysmood** [comment]
The fix is in v0.114.5
