### ISSUE TITLE
How to spawn browser singleton for reusable PagePool?

### ISSUE THREAD

**Issue by lukeed** [go-rod/rod#975]
Rod Version: v0.114.4

```go
package main

import (
	"fmt"
	"sync"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/ysmood/gson"
)

var bb *rod.Browser
var once sync.Once

// Setup a Browser singleton.
// Just need to juggle Pages (or PagePool)
func browser() *rod.Browser {
	once.Do(func() {
		l := launcher.New().Headless(true).Set("max-old-space-size", "128")
		if path, exists := launcher.LookPath(); exists {
			fmt.Println("~> found local browser")
			l.Bin(path)
		}

		defer l.Cleanup()
		fmt.Println("attempting...")
		bb = rod.New().ControlURL(l.MustLaunch()).MustConnect()
		fmt.Println("connected!")
	})

	// never leaves once.Do
	fmt.Println("never runs")

	return bb
}

// Each call to eval should ensure that it has its own Page
func eval(js string, args ...interface{}) gson.JSON {
	b := browser()
	page := b.MustPage()
	defer page.Close()

	return page.MustEval(js, args...)
}

func main() {
	for v := range []int{1, 2, 3} {
		eval("function(x) { console.log('~>', x) }", v)
	}
}
```

## What you got

Program never leaves the singleton stage; eg `browser()`.

## What you expected to see

Would like to reuse a `Browser` instance via utility helpers. 

## What have you tried to solve the question

Code is working fine when all methods (eg, `eval()`) setup and destroyed their own `Browser` and `Page` structs. However, I'd like to extract this part into some shared utility, but as soon as a `Browser` is created, the program blocks indefinitely.

I've also tried using a `BrowserPool`, but that also blocked every time a new `Browser` was created... I can only seem to get rod to work if I inline all the code into the same function; eg:

```go
package main

import (
	"fmt"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
)

func main() {
	l := launcher.New().Headless(true).Set("max-old-space-size", "128")
	if path, exists := launcher.LookPath(); exists {
		fmt.Println("~> found local browser")
		l.Bin(path)
	}

	defer l.Cleanup()
	fmt.Println("attempting...")

	b := rod.New().ControlURL(l.MustLaunch()).MustConnect()
	defer b.Close()

	page := b.MustPage()
	defer page.Close()

	for v := range []int{1, 2, 3} {
		page.MustEval("function(x) { console.log('~>', x) }", v)
	}
}
```

**Comment by ysmood** [comment]
Have tried this?

https://github.com/go-rod/rod/blob/46baf3aad803ed5cd8671aa325cbae4e297a89a4/examples_test.go#L533-L574

**Comment by lukeed** [comment]
Yea tried both. They both work because the pool/browser is created in the same function lifetime. I’m trying to have a singleton that multiple top level functions refer to over time

**Comment by ysmood** [comment]
> have a singleton that multiple top level functions refer to over time

I'm not sure I understand what you mean.

**Comment by lukeed** [comment]
I got it working now, thank you :) It just came down to using `l.Cleanup()`, which I should be calling manually elsewhere.
