### ISSUE TITLE
How can I use $$ or $ helpers in the page.MustElementByJS() method?

### ISSUE THREAD

**Issue by chandleeeee** [go-rod/rod#976]
Rod Version: v0.114.5

## The code to demonstrate your question

1. Clone Rod to your local and cd to the repository:

   ```bash
   git clone https://github.com/go-rod/rod
   cd rod
   ```

1. Use your code to replace the content of function `TestRod` in file `rod_test.go`.

1. Test your code with: `go test -run TestRod`, make sure it fails as expected.

1. Replace ALL THE CONTENT under "The code to demonstrate your question" with your `TestRod` function, like below:

```go
package rod_test

import (
	"testing"
)

// This is the template to demonstrate how to test Rod.
func TestRod(t *testing.T) {
	g := setup(t)
	g.cancelTimeout() // Cancel timeout protection

	// You can use the pre-launched g.browser or g.page for testing
	browser, page := g.browser, g.page

	// You can also use the g.html to serve static html content
	page.MustNavigate(g.html(doc)).MustWaitLoad()
	text := page.MustElementByJS(`() => $("h2")[1]`).MustText()
	//text := page.MustElementByJS(`() => document.getElementsByTagName("h2")[1]`).MustText()

	g.Eq(browser.MustVersion().ProtocolVersion, "1.3")
	g.Has(text, "world")
}

const doc = `
<html>
  <body>
    <h2>hello</h2>
    <h2>world</h2>
  </body>
</html>

`

```

## What you got

panic: eval js error: ReferenceError: $ is not defined

## What you expected to see

PASS: TestRod

## What have you tried to solve the question

text := page.MustElementByJS(`() => document.getElementsByTagName("h2")[1]`).MustText()

**Comment by ysmood** [comment]
It's the same as #393. Look at the `IncludeCommandLineAPI`.
