### ISSUE TITLE
WebAudio.disable cannot work

### ISSUE THREAD

**Issue by zhangguanzhang** [go-rod/rod#98]
I follow the code flow to add the following method cannot close the sound of the page
```
// WebAudioDisableE doc is similar to the method WebAudioDisable
func (p *Page) WebAudioDisableE() error {
	err := proto.WebAudioDisable{}.Call(p)
	if err != nil {
		return err
	}
	return nil
}
```

**Comment by ysmood** [comment]
http://www.catb.org/~esr/faqs/smart-questions.html

## Describe the goal, not the step
> If you are trying to find out how to do something (as opposed to reporting a bug), begin by describing the goal. Only then describe the particular step towards it that you are blocked on.
> 
> Often, people who need technical help have a high-level goal in mind and get stuck on what they think is one particular path towards the goal. They come for help with the step, but don't realize that the path is wrong. It can take substantial effort to get past this.
> 
> Stupid:
> How do I get the color-picker on the FooDraw program to take a hexadecimal RGB value?
> 
> Smart:
> I'm trying to replace the color table on an image with values of my choosing. Right now the only way I can see to do this is by editing each table slot, but I can't get FooDraw's color picker to take a hexadecimal RGB value.
> 
> The second version of the question is smart. It allows an answer that suggests a tool better suited to the task.

## Don't rush to claim that you have found a bug
> When you are having problems with a piece of software, don't claim you have found a bug unless you are very, very sure of your ground. Hint: unless you can provide a source-code patch that fixes the problem, or a regression test against a previous version that demonstrates incorrect behavior, you are probably not sure enough. This applies to webpages and documentation, too; if you have found a documentation “bug”, you should supply replacement text and which pages it should go on.
> 
> Remember, there are many other users that are not experiencing your problem. Otherwise you would have learned about it while reading the documentation and searching the Web (you did do that before complaining, didn't you?). This means that very probably it is you who are doing something wrong, not the software.
> 
> The people who wrote the software work very hard to make it work as well as possible. If you claim you have found a bug, you'll be impugning their competence, which may offend some of them even if you are correct. It's especially undiplomatic to yell “bug” in the Subject line.
> 
> When asking your question, it is best to write as though you assume you are doing something wrong, even if you are privately pretty sure you have found an actual bug. If there really is a bug, you will hear about it in the answer. Play it so the maintainers will want to apologize to you if the bug is real, rather than so that you will owe them an apology if you have messed up.

**Comment by ysmood** [comment]
If check the doc "WebAudioDisable" says `Disables the WebAudio domain.`, look at the `domain`, you sure you understand what does it mean?

**Comment by zhangguanzhang** [comment]
sorry

**Comment by ysmood** [comment]
You can find the flag on the page the example mentioned:

https://github.com/go-rod/rod/blob/5ab8d94f91447876cef2112a2fd5b710b6454c87/examples_test.go#L200-L212

Something like disable-audio-output may be what you want.

**Comment by ysmood** [comment]
I updated your title, hope you can learn something from it.

**Comment by zhangguanzhang** [comment]
```
launcher.New().
		Headless(false).
		Set("disable-audio-output", "true")
```

**Comment by ysmood** [comment]
```
launcher.New().
		Headless(false).
		Set("disable-audio-output")
```

If you look at their doc, it doesn't require something like `--disable-audio-output=true`
