### ISSUE TITLE
Intercept DevTools disconnection

### ISSUE THREAD

**Issue by Kies8** [go-rod/rod#989]
Rod Version: v0.114.5

## The problem
After a while of scraping my browser crashes and I don't understand how to resume execution.
The only way I can replicate the error is apparently to open another page (of the same domain) and change the local storage. I don't think this is exactly what triggers the crash since it happens even when I don't do this procedure.

## How I want to solve this problem
I am trying to intercept when this problem occurs so that I can clear the cache and restart the page but I don't understand how to do it. Or I am open to new solutions

The only thing I'm doing is to run this code:
```golang
func handleTab(tab *rod.Page, search params.Search) {
	for {
		tab.MustWaitDOMStable()
		tab.Eval(`monitor(` + utils.FromStructToJson(search) + `)`)
		time.Sleep(time.Second * 10)
		tab.Eval("localStorage.clear();")
		tab.Reload()
	}
}
```

the `monitor()` function executes an injected function and cycles infinitely every second until it reloads. 

![image](https://github.com/go-rod/rod/assets/52181901/d53ae712-7186-409c-b16c-314bf9f97c8e)
![image](https://github.com/go-rod/rod/assets/52181901/c2d72a8f-eda3-4256-807f-d706976f16c9)

**Comment by ysmood** [comment]
Is there a way to reproduce it?

**Comment by Kies8** [comment]
No and I did not understand the problem, I switched to another solution
