### ISSUE TITLE
chromium can't login gmail account

### ISSUE THREAD

**Issue by twolao** [go-rod/rod#995]
Rod Version: v0.114.5

```go
package main

import (
    "github.com/go-rod/rod"
    "github.com/go-rod/rod/lib/launcher"
    "os"
    "log"
    "fmt"
    "time"
    "os/signal"
    "syscall"
)

var err error
func main() {
    l := launcher.New().
    Headless(false). 
    Devtools(false).
    Env(append(os.Environ(), "TZ=Asia/Tokyo")...).
    Leakless(true)
        
    url, err := l.Launch()
    if err != nil {
        fmt.Println("Error launching browser:", err)
        return
    }
    defer l.Cleanup()
        
    browser := rod.New().ControlURL(url).NoDefaultDevice()
    if err = browser.Connect(); err != nil {
        fmt.Println("Error connecting to browser:", err)
        return
    }
    defer browser.MustClose()
    page := browser.MustPage() 
	page.Navigate("https://gmail.com")

    ticker := time.NewTicker(30 * time.Second)
    quit := make(chan struct{})
    go func() {
        for {
            select {
            case <-ticker.C:
                log.Println("some code")
            case <-quit:
                ticker.Stop()
                return
            }
        }
    }()

    sigs := make(chan os.Signal, 1)
    signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)

    <-sigs
    close(quit)
    fmt.Println("browser closed")
}

```

## What you got

![gmail](https://github.com/go-rod/rod/assets/10527571/2aff8cda-bf00-4a47-be50-c05df1babbba)

## What you expect to see

can log in normally and use gmail

**Comment by oceanchang** [comment]
Is it possible to use firefox or thunderbird browser, how to set up to use non-chromium browser

**Comment by ysmood** [comment]
Please check related issues

**Comment by oceanchang** [comment]
> Please check related issues

find this [https://github.com/go-rod/rod/issues/375](https://github.com/go-rod/rod/issues/375) , The test mentioned that gmail can be used normally, but the time at that time was 2021. I don’t know if Google’s policy has changed recently.

**Comment by oceanchang** [comment]
> Please check related issues

[https://forum.puppylinux.com/viewtopic.php?t=5135](https://forum.puppylinux.com/viewtopic.php?t=5135)  find this post mentioning that Chromium no longer supports gmail login

**Comment by ysmood** [comment]
Yes, might be an upstream issue.

**Comment by oceanchang** [comment]
> Is it possible to use firefox or thunderbird browser, how to set up

Is it possible to use firefox or thunderbird browser, how to configure，can you give some hint

**Comment by ysmood** [comment]
You can check their ticket

**Comment by twolao** [comment]
> You can check their ticket
> 
> BTW, you can use chrome with rod, works fine to me

I found that a multilogin product also uses the Chromium browser and can use Gmail normally, but the browser version is obviously different. go-rod generates 114.0.5720.0 (developer build), that is  chromium 120.0.6099.130 (official version)

Can go-rod also automatically download and use the official version of chromium?

**Comment by ysmood** [comment]
yes, rod exposes all its low level methods, check https://github.com/go-rod/rod/blob/main/lib/launcher/browser.go

**Comment by ysmood** [comment]
> why does go-rod not use chrome directly but choose to use chromium?

Because you can easily switch to chrome with rod, and the License of Chrome make it hard to choose it.

**Comment by twolao** [comment]
> > why does go-rod not use chrome directly but choose to use chromium?
> 
> Because you can easily switch to chrome with rod, and the License of Chrome make it hard to choose it.

thx

**Comment by arjendevos** [comment]
What was the solution? Got the same problem, switching to chrome didn't work for me.
